### ISSUE TITLE
Cannot install CRDs (schema issue?)

### ISSUE THREAD

**Issue by sneko** [open-telemetry/opentelemetry-operator#10]
Hi @jpkrohling,

When trying to install the first YAML file containing CRD definitions I get this error:
`The CustomResourceDefinition "opentelemetrycollectors.opentelemetry.io" is invalid: spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{ID:"", Schema:"", Ref:(*string)(nil), Descripti...`

It says at the end `must only have "properties", "required" or "description" at the root if the status subresource is enabled`.

I'm running Kubernetes 1.11.10

Thank you,

EDIT: Seems a known compatibility issue with Kub' 1.11 😭

**Comment by jpkrohling** [comment]
You can probably just remove the `validation` node from the CRD, but you might end up facing other compatibility problems down the road.

**Comment by sneko** [comment]
I decided to upgrade my cluster 👍 

Thank you for the answer :)
