### ISSUE TITLE
Is it possible to use opentelemtry-operator in kubernetes version v1.16.15 ?

### ISSUE THREAD

**Issue by sathishsoundharajan** [open-telemetry/opentelemetry-operator#1017]
1. If i can use it, what version of operator can be used ?
2. If i cannot use it, what is best deployment mode i can use to deploy to kubernetes ? ( Sidecar, Daemonset, Deployment )

**Comment by pavolloffay** [comment]
We don't guarantee compatibility with k8s 1.16 see https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager

> If i cannot use it, what is best deployment mode i can use to deploy to kubernetes 

Create deployment manifest by hand or try helm chart https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
