### ISSUE TITLE
Option for Service Internal Traffic Policy for Collector Service

### ISSUE THREAD

**Issue by m1o1** [open-telemetry/opentelemetry-operator#1018]
It would be nice if the OpenTelemetryCollector CRD supported setting [topology keys](https://kubernetes.io/docs/concepts/services-networking/service-topology/) for the service that gets created.

I'd like to have the collector deployed twice, once as a DaemonSet (agents) which forward to the second deployment as a Deployment (gateway). However, I'd like to set a topology key for the agents Service so that calls will route to the instance on the same node. I'd prefer not to use host network / NodePort services.

Happy to submit a PR for this.

**Comment by pavolloffay** [comment]
> I'd like to have the collector deployed twice, once as a DaemonSet (agents) which forward to the second deployment as a Deployment (gateway).

Could you please describe your use for this topology? 

Could node selector solve your use-case https://github.com/open-telemetry/opentelemetry-operator/blob/42a6d6044efaefd568ceeaec2003dbe35ac3d44d/apis/v1alpha1/opentelemetrycollector_types.go#L30? 

Note that https://kubernetes.io/docs/concepts/services-networking/service-topology/ is deprecated in v1.21. https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/ should be used instead. 

Did you try to use topology aware hints? It uses `EndpointSlice` for configuration that you might be able to create externally (not via the operator).

**Comment by m1o1** [comment]
Ah I didn't realize it got deprecated. That's unfortunate.

> Could you please describe your use for this topology?

The two deployments mirror the [options listed here](https://opentelemetry.io/docs/collector/deployment/). The agents serve the purpose of collecting host metrics, as well as aggregating telemetry data on the node before compressing and sending to the gateway. The gateway is configured with the external exporters (ex: honeycomb) and I plan to use it for things like tail-based sampling.

> Could node selector solve your use-case

We'd like the agent deployed to all nodes, particularly for metrics, but also so all our services send to an agent local to the node they're running on. All services we deploy would send their telemetry to the instance local to the node it's running on, then that agent would compress and batch them before sending to the gateway instance(s).

The topology-aware hints seem to be specific to zones and handled automatically, so not sure how to say "try routing to instances on the same node". I am not sure how to manually manage EndpointSlices since I think I'd like the Service operator to manage that resource and update as new nodes are created/removed.

We can't use host networking (linkerd won't inject proxies in that case, which is necessary for linkerd proxies to send their telemetry data since they enforce mtls between the proxies and the collector).

However, I'll close this since now this is more of a question than a request.

**Comment by m1o1** [comment]
I'd like to reopen this since I was pointed to the proper solution on Slack using [Service Internal Traffic Policy](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/).

Basically I'd like to force pods to send their spans to the collector agent on the same node. This collector agent would then forward to the collector gateway, [as described here](https://opentelemetry.io/docs/collector/deployment/).

**Comment by jaronoff97** [comment]
we now do this automatically for daemonsets #1517
