### ISSUE TITLE
Emit metrics from the target allocator

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#1029]
Currently, no metrics are emitted by the target allocator which makes it difficult to understand the state of it. Ideally, the TA would emit some metrics about it's success and performance in assigning targets as well as resets to its available collector pool. 

The only open question I have is how we would like to instrument the TA. The operator is already instrumented using prometheus which is the default for the golang operator-sdk. I was hoping to instrument the TA using otel, however, using prometheus may be easier given it's already configured. Are there any thoughts / opinions about this issue?

**Comment by jaronoff97** [comment]
note: I am planning on working on this effort to close this issue.

**Comment by Aneurysm9** [comment]
The target allocator is a separate deployable, so it shouldn't need to be tied to the choices the operator has made.  That said, consistency has value and the OTel Go metrics SDK is still in alpha.  I think if we were having this discussion in three months I'd advocate more strongly for using the OTel SDK, but that this time Prometheus is a reasonable choice.  If the implementation can be done in a way that makes it painless to replace Prometheus with OTel that's even better.

**Comment by jaronoff97** [comment]
That makes sense to me. I'll try to keep my implementation very minimal to make migration in the future seamless. I will also make a follow up issue after the release so we don't forget.
