### ISSUE TITLE
godoc for packages

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#104]
Context: https://github.com/open-telemetry/opentelemetry-operator/pull/102#discussion_r514140707

This ticket is to convert the doc in written as part of that PR into godoc, changing the CONTRIBUTING.md to point users to a webpage with the doc (like: https://godoc.org/github.com/open-telemetry/opentelemetry-operator)

**Comment by IanvsPoplicola** [comment]
Hi there! I've made a commit for this issue; please let me know if there's anything that needs to be updated, e.g. the style/content/wording 🙂

**Comment by jpkrohling** [comment]
This has been done as part of #109
