### ISSUE TITLE
[target-allocator] Apply relabel configs to targets prior to allocation

### ISSUE THREAD

**Issue by kelseyma** [open-telemetry/opentelemetry-operator#1064]
Can the target allocator apply the relabel configs prior to allocation so we can drop any unnecessary targets? This would also help reduce load on the collectors and ensure that the allocation is more evenly distributed.
For example in the test setup I have, the `/metrics` endpoint says the TA is allocating 36 targets, but only 3 of those targets are actually valid based on the relabel configs I set.

**Comment by jaronoff97** [comment]
Hey Kelsey! Thank you for submitting this issue, definitely something I've been thinking about too. I can take a look at implementing this behavior. Not sure when we'll get to it, I may have some time next week.

**Comment by alclark704** [comment]
Hi, I've found this from https://github.com/open-telemetry/opentelemetry-operator/issues/1038 as I think I'm finding the same issue and these seems to imply it resolved it. I just wanted to check my understanding as it seems like this just has the target allocator run through the relabel config and drop any targets resulting from that. But the problem relabel config that adds the prometheus port to the target address doesn't actually drop anything. So it seems like I'm still getting multiple targets found for all ports on an annotated pod, which then get distributed to different collectors and then relabelled to the intended prometheus port. So I get 3 separate collectors monitoring the same pod metrics. 

Should this have fixed that or was there additional changes required? I'm seeing if I can add one extra relabel config to drop targets where the port isn't the specified prometheus port but thought I'd check here as well.
