### ISSUE TITLE
Allow image repository configuration in Collector CRD

### ISSUE THREAD

**Issue by Yamakaky** [open-telemetry/opentelemetry-operator#1093]
The Helm chart allow the separate configuration of the Collector tag and repository, which allow the use of `otel/opentelemetry-collector-contrib` but reuse the image version from the chart. It would be nice to be able to do the same thing in the CRD.

[Values schema](https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator?modal=values-schema&path=manager.collectorImage)
[Default values](https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator?modal=values)

I'm not sure what would be the best option. Maybe add a field `spec.imageRepository` in the CRD, then the collector image would be in order:

1. `image` 
2. `imageRepository:{collectorImage.tag}`
3. `{collectorImage.repository}:{collectorImage.tag}`

An `imageTag` could also be added, though it seems less useful to me.

**Comment by pavolloffay** [comment]
Full collector image can be specified in the CR - https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/opentelemetrycollector_types.go#L63. if no image is specified then the default one is used. The default image can be specified as flag https://github.com/open-telemetry/opentelemetry-operator/blob/main/main.go#L93

The operator image can be specified in the operator deployment file.

**Comment by Yamakaky** [comment]
I don't think that's what I'm talking about. These flags need the complete image including the version/tag, right?

**Comment by pavolloffay** [comment]
Yes, the `spec.image` field gets full image with repo, image name and version tag e.g. `owner/repo:version`. 

I don't see what it should be split. Maybe you can describe your use-case why you need to provide those values separately.

**Comment by Yamakaky** [comment]
I want to use opentelemetry-collector-contrib without having to specify the version (aka use the version from the operator helm chart), which is what you get when you stick to opentelemetry-collector.

**Comment by Yamakaky** [comment]
When I do a helm install for the operator,  I use this override value file:

```
manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
```

If you don't specify `manager.collectorImage.tag`, it will use the default value [here](https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator?modal=values). I'd like to be able to do the same thing in the CRD.

**Comment by Yamakaky** [comment]
I understand this is not a PR you would be willing to accept?

**Comment by pavolloffay** [comment]
There is already an image field in the CR. I would prefer to avoid adding another config for it.

**Comment by yuriolisa** [comment]
@pavolloffay, I think this issue can be closed, right?

**Comment by pavolloffay** [comment]
yes, closing
