### ISSUE TITLE
Error level dpanic invalid key "v2beta2","stacktrace

### ISSUE THREAD

**Issue by frpataciertocom** [open-telemetry/opentelemetry-operator#1098]
Hi,

I have deployed OTEL without issues, then I removed the installation to perform some tests, and after when I redeployed OTEL now I get the error below.

1) I have installed like this: https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/installation
2) Then applied this to try to get traces in X-Ray: https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/config-xray

I got nothing in X-ray and when I checked the logs and I found this "dpanic" invalid key":"v2beta2.

Any ideas?, thank you.
```
"level":"info","ts":1663256456.4467094,"logger":"instrumentation-upgrade","msg":"no instances to upgrade"}
{"level":"info","ts":1663256456.4467492,"logger":"collector-upgrade","msg":"no instances to upgrade"}
{"level":"dpanic","ts":1663256456.548566,"logger":"config","msg":"non-string key argument passed to logging, ignoring all later arguments","invalid key":"v2beta2","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/config.(*Config).StartAutoDetect\n\t/workspace/internal/config/main.go:93\nmain.addDependencies.func1\n\t/workspace/main.go:244\nsigs.k8s.io/controller-runtime/pkg/manager.RunnableFunc.Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:307\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/runnable_group.go:219"}
{"level":"info","ts":1663256456.5485582,"logger":"config","msg":"In Autodetect, Set HPA version to ["}
{"level":"info","ts":1663256456.8421454,"msg":"Starting workers","controller":"opentelemetrycollector","controllerGroup":"opentelemetry.io","controllerKind":"OpenTelemetryCollector","worker count":1}
{"level":"dpanic","ts":1663256461.561525,"logger":"config","msg":"non-string key argument passed to logging, ignoring all later arguments","invalid key":"v2beta2","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/config.(*Config).periodicAutoDetect\n\t/workspace/internal/config/main.go:103"}
{"level":"info","ts":1663256461.5615194,"logger":"config","msg":"In Autodetect, Set HPA version to ["}
{"level":"dpanic","ts":1663256466.5549068,"logger":"config","msg":"non-string key argument passed to logging, ignoring all later arguments","invalid key":"v2beta2","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/config.(*Config).periodicAutoDetect\n\t/workspace/internal/config/main.go:103"}
{"level":"info","ts":1663256466.5548995,"logger":"config","msg":"In Autodetect, Set HPA version to ["}
{"level":"dpanic","ts":1663256471.5632463,"logger":"config","msg":"non-string key argument passed to logging, ignoring all later arguments","invalid key":"v2beta2","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/config.(*Config).periodicAutoDetect\n\t/workspace/internal/config/main.go:103"}
{"level":"info","ts":1663256471.5632415,"logger":"config","msg":"In Autodetect, Set HPA version to ["}
{"level":"dpanic","ts":1663256476.5548413,"logger":"config","msg":"non-string key argument passed to logging, ignoring all later arguments","invalid key":"v2beta2","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/config.(*Config).periodicAutoDetect\n\t/workspace/internal/config/main.go:103"}

```

**Comment by pavolloffay** [comment]
@kevinearls was this fixed in https://github.com/open-telemetry/opentelemetry-operator/commit/19c186df1b89a3898169a16f91bd13fab5a6931f ?

**Comment by pavolloffay** [comment]
@frpataciertocom please tell us what version of OTEL operator are you running.

**Comment by kevinearls** [comment]
@pavolloffay @frpataciertocom Yes, this has been fixed.

**Comment by frpataciertocom** [comment]
Hi @pavolloffay 

Hope that you are doing fine.

I wonder if this is the OTEL version?, when I decided to install this, I have used the steps from this website https://aws-otel.github.io/docs/getting-started/xxxxxx, so I didn't have any chance to pick a version, I just did "kubectl apply -f" (of course change region and so for) on what was present in the yaml files available.

Thank you.


```applied
aws eks describe-addon --addon-name adot --cluster-name XXXX 
{
    "addon": {
        "addonName": "adot",
        "clusterName": "XXXX",
        "status": "ACTIVE",
        "addonVersion": "v0.58.0-eksbuild.1",
        "health": {
            "issues": []
        },
        "addonArn": "arn:aws:eks:xx-xxxx-x:xxxxxxxxxxxx:addon/zzzzzzzzzzz/adot/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "createdAt": "2022-09-15T12:06:05.710000+02:00",
        "modifiedAt": "2022-09-15T12:06:47.662000+02:00",
        "tags": {}
    }
}
```

**Comment by frpataciertocom** [comment]
Hi,

I just wanted to let you know that I have deployed OTEL in a different cluster and I got right the same issue.

Please let me know if you need some more details to understand this, thank you.

**Comment by pavolloffay** [comment]
0.59.0 upward should have the fix. 

Could you please upgrade and let us know/close the issue if it works?

**Comment by pavolloffay** [comment]
Note that this is an upstream community project, not AWS. 

Probably @Aneurysm9 could help you.

**Comment by frpataciertocom** [comment]
@pavolloffay Honestly I have no idea where to from here, Thank you.

**Comment by xxfroxx** [comment]
Hi @Aneurysm9 , Any chance you can advise on this one?, cheers.

**Comment by alex88** [comment]
@frpataciertocom @xxfroxx you'd have to wait for aws to update to 0.59.0 and make that version available

**Comment by Aneurysm9** [comment]
The next ADOT collector release is in progress and a release of the EKS managed add-on using v0.61.0 of the Operator will follow.  I can't give a firm date at this time, and it is dependent on #1131 landing and the release happening, but would anticipate sometime next week.

**Comment by pavolloffay** [comment]
I am closing this as the issue was fixed, please open ticket against AWS repo to track their release with the fix.

**Comment by frpataciertocom** [comment]
> I am closing this as the issue was fixed, please open ticket against AWS repo to track their release with the fix.

Fine to me Brother, thank you.
