### ISSUE TITLE
set resource requests/limits for target-allocator

### ISSUE THREAD

**Issue by seankhliao** [open-telemetry/opentelemetry-operator#1103]
Our k8s clusters run with `ResourceQuota`s, but the deployments created by for the target allocator don't have any set, so they're blocked from creation (at the ReplicaSet level which isn't reported back upwards)

**Comment by seankhliao** [comment]
I ran the target allocator on a larger cluster (200+ servicemonitors).
Without being able to set resource reservations, it was frequently getting OOMKilled (~10 cpu, ~18Gi memory) as it had the lowest resource requests (0).

**Comment by pavolloffay** [comment]
@seankhliao would you like to fix it?

**Comment by seankhliao** [comment]
tbh I'm not sure how I would fix it in the current structure of the CRD.
In attempting to get it to run on one of our larger clusters, I eventually had to use the rest of the PodSpec to schedule it properly (I ran it as an independent deployment without the operator).

ref: https://cloud-native.slack.com/archives/C033BJ8BASU/p1666986594165909

**Comment by yuriolisa** [comment]
@seankhliao, can I work on it?

**Comment by seankhliao** [comment]
sure

**Comment by ilia-medvedev-codefresh** [comment]
@yuriolisa are you or anyone else working on it?
