### ISSUE TITLE
Allow the specification of allocation strategy configuration in collector CRD

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#1105]
The target allocator now has two methods of allocation (least-weighted, and consistent-hashing) the next strategy will be a composite strategy that will only assign targets post relabeling. All of these strategies have some amount of configuration to them, we should allow users of the TA to specify them in the CRD.

This also will allow us to have strategies as typed and not just strings in the CRD. The change will involve passing the spec containing the TA config down to each allocation strategy rather than just a logger as it stands right now. 

[Original discussion here](https://github.com/open-telemetry/opentelemetry-operator/pull/1087#discussion_r972105153)

**Comment by swiatekm-sumo** [comment]
@jaronoff97 this can be closed, right?

**Comment by jaronoff97** [comment]
yep 👍
