### ISSUE TITLE
instrumentation sends too much request to APM backend.

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-operator#1108]
Dear all,

We've deployed the opentelemetry-operator to our k8s cluster and use java instrumentation inject. The result looks great. Just one question, the instrument sends a lot of heart beats or health check request to the backend.
It makes us cannot calculate the actual user request. Is there any way to filter those kinds of request and only keep the request created by the user?

Thanks
Chen

**Comment by rogerogers** [comment]
seems not supported yet.

#https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060

**Comment by pavolloffay** [comment]
Please comment on the issue above. This is not operator related issue.
