### ISSUE TITLE
Update NodeSDK to 0.33 and add resource detectors

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-operator#1113]
The NodeSDK now allows to have additional resource detectors being loaded on startup: 

https://github.com/open-telemetry/opentelemetry-js/releases/tag/experimental%2Fv0.33.0
&
https://deploy-preview-1767--opentelemetry.netlify.app/docs/instrumentation/js/resources/ (WIP)

The auto instrumentation of the operator could make use of that and auto-detect container resources (and [more](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/detectors/node) if running in a cloud environment)

What needs to be done:
* Update dependencies in [package.json](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/package.json) to 0.33 & add additional dependencies
* Update [autoinstrumentation.ts](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/src/autoinstrumentation.ts) to use additional resource detectors:

```js
const sdk = new NodeSDK({
    autoDetectResources: true,
    instrumentations: [getNodeAutoInstrumentations()],
    traceExporter: new OTLPTraceExporter(),
    resourceDetectors: [envDetector, processDetector, dockerCGroupV1Detector, ...],
});
```

cc: @abhee11, @osherv

**Comment by pavankrish123** [comment]
@kabhanus007

**Comment by kabhanus007** [comment]
@pavankrish123  Sure I can take a look into this. thanks

**Comment by svrnm** [comment]
@pavolloffay can you assign this to @kabhanus007 ?

**Comment by sairam866** [comment]
@svrnm - I am working on this. 
```
Will be adding a meta package like @opentelemetry/auto-instrumentations-node for resource detection that would allow something like resourceDetectors: getNodeResourceDetectors()
```
cc: @pavankrish123

**Comment by sairamnat** [comment]
@svrnm - I am working on this. 
```
Will be adding a meta package like @opentelemetry/auto-instrumentations-node for resource detection 
that would allow something like resourceDetectors: getNodeResourceDetectors()
```
cc: @pavankrish123

**Comment by pavolloffay** [comment]
@svrnm sorry I missed the comment. Usually it's enough to just put a comment when somebody is working on something.

**Comment by svrnm** [comment]
> @svrnm sorry I missed the comment. Usually it's enough to just put a comment when somebody is working on something.

no worries!

> Will be adding a meta package like @opentelemetry/auto-instrumentations-node for resource detection 
that would allow something like resourceDetectors: getNodeResourceDetectors()

This is something that belongs to the opentelemetry-js project, I would say it's a great idea, but should not block this feature here.
