### ISSUE TITLE
Move MaxReplicas and MinReplicas to AutoscalerSpec in collector CRD

### ISSUE THREAD

**Issue by moh-osman3** [open-telemetry/opentelemetry-operator#1115]
In https://github.com/open-telemetry/opentelemetry-operator/pull/1077, an Autoscaler field and object was added to the collector CRD.  `MaxReplicas` and `MinReplicas` are fields specific to autoscaling so that should be moved to the AutoscalerSpec, and the HPA source code should be refactored to reflect this.

**Comment by pavolloffay** [comment]
cc) @kevinearls

**Comment by pavolloffay** [comment]
Also note that we can't remove fields from a published CRD. If we want to move things around we would have to do deprecation and support the deprecated options as well.
