### ISSUE TITLE
Update linting to match other open-telemetry repo configs

### ISSUE THREAD

**Issue by kristinapathak** [open-telemetry/opentelemetry-operator#1122]
The golangci.yaml doesn't match other configurations in open-telemetry. A few other golanci configurations:

https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/29a46c89ab69347be7d6f2c7f4f94135cb4d0d4f/.golangci.yml
https://github.com/open-telemetry/opentelemetry-collector/blob/b1329c94b3b31b9ffa4091ab5066d6f091d71f41/.golangci.yml
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d2490af3003387cc4b1baa5b55f7d748303d7a4b/.golangci.yml

I would like to align the operator's lint configuration with the rest of these - making settings match and enabling the same linters (and fixing any lint issues found).  The only additional linter needed here is `goheader`, for license checking.

**Comment by yuriolisa** [comment]
@pavolloffay, @jaronoff97, I believe this issue can be closed. WDYT?

**Comment by pavolloffay** [comment]
thanks @yuriolisa
