### ISSUE TITLE
How to add the inject annotations to the namespace?

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-operator#1125]
Would you mind kindly let me know how to create the instrument inject annotations to a namespace so that all the pod in the namespace could be monitored?
Please provide the k8s yaml example. Thanks so much

**Comment by pavolloffay** [comment]
Please read this section https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-auto-instrumentation-injection it has instruction how the auto-instrumentation works. 

Feel free to re-open if you have any specific questions.
