### ISSUE TITLE
K8S otel-operator latency is too high and the auto-instrumentation number of traces are not accurate.

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-operator#1129]
![Screenshot 2022-09-28 at 03 13 01](https://user-images.githubusercontent.com/90817719/192615816-6034a81d-7e40-4210-9a67-87c261a4109a.png)
You can see one traffic takes such a long time.
And I actually triggered 5 times traffic and only 1 displayed on APM.

**Comment by pavolloffay** [comment]
> K8S otel-operator latency is too high

Could you be please more specific? Are you saying that the OTEL operator is slow (e.g. to inject auto-instrumentation and therefore blocking pod creation) or are you saying that workload is slow to handle requests with the auto-instrumentation? 

If it is the second case then please open the issue against the auto-instrumentation repository. The operator only injects the auto-instrumentations.

**Comment by sweetxiaodai** [comment]
Closed due to the traffic high traffic latency were caused by the hosting k8s cluster

**Comment by sweetxiaodai** [comment]
@pavolloffay The otel itself is not slow. But the service call that which has start with the java-instrumentation-agent has high latencies occasionally. We compared the latency of the service when the application deployed different apm agent. The commercial software didnt' have this issue.
