### ISSUE TITLE
Is there a way to add java-agent extension to the instrumentation?

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-operator#1135]
The instrumentation annotation will inject a -javaagent option to the java execution command line during the pod initialization, if I am correct. Is there a way to modify this command line by adding some jvm options? like the following codes?
```bash
java -javaagent:path/to/opentelemetry-javaagent.jar \
    -Dotel.javaagent.extensions=opentelemetry-contrib-samplers-1.8.0-SNAPSHOT.jar
    -jar myapp.jar
```

**Comment by pavolloffay** [comment]
The injection code configures `JAVA_TOOL_OPTIONS` with `-javaagent:/otel-auto-instrumentation/javaagent.jar` it does not allow any other configuration for the JVM. 


Could you please describe your use-case what are you trying to achieve?

**Comment by sweetxiaodai** [comment]
I just want to add javaagent extensions to filter some URLS. Is it possible?

**Comment by sweetxiaodai** [comment]
The main purpose are the Orel agent will capture health and liveness check of Nacos, it generated massive useless traffics, we needed to filtered it via a ETL process, just want to filter it before the agent send it to APM
@pavolloffay

**Comment by sweetxiaodai** [comment]
Thanks

**Comment by pavolloffay** [comment]
@sweetxiaodai were you able to resolve your use-case? 

If so could you please share how? Maybe it will be useful for other folks.
