### ISSUE TITLE
Wrong image repo path in published manifests

### ISSUE THREAD

**Issue by ekarlso** [open-telemetry/opentelemetry-operator#114]
latest v0.14.0 is published with
```
        image: quay.io/opentelemetry/opentelemetry-operator/opentelemetry-operator:0.14.0
```

This is wrong and leads to failure.

**Comment by jpkrohling** [comment]
That does look wrong in the latest version. The previous version was still correct:

        image: quay.io/opentelemetry/opentelemetry-operator:0.13.0

I think it might be related to this PR: https://github.com/open-telemetry/opentelemetry-operator/pull/105

Would you like to try to fix it?

**Comment by airhorns** [comment]
Would just like to note that I ran into this too -- not at all familiar with this repo's build scripts but I can take a stab at a fix! Editing the published manifest back to `quay.io/opentelemetry/opentelemetry-operator:0.14.0` fixed the container pull issue for me.

**Comment by jpkrohling** [comment]
I'm out this week, so, I can't look into this until probably a couple of weeks. Your help would be highly appreciated, @airhorns!
