### ISSUE TITLE
ImagePullSecret not available 

### ISSUE THREAD

**Issue by Ripurwar80** [open-telemetry/opentelemetry-operator#1153]
**Describe the bug**
unknown field "imagePullSecrets" in io.opentelemetry.v1alpha1.OpenTelemetryCollector.spec

**Steps to reproduce**
Pulling Private image using credentials

**Comment by pavolloffay** [comment]
`ImagePullSecret` can be configured in the service account in the collector CR https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/opentelemetrycollector_types.go#L66. 

Please reopen if this does not solve your use-case.
