### ISSUE TITLE
Do not enable .NET instrumentation if OTEL_DOTNET_AUTO_HOME is already set

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-operator#1156]
I think that we should additionally validate that the `dotNetOTelAutoHomePath` env var was not set in the original container. Otherwise, we cannot auto-instrument the .NET app. If someone set it then it would mean that somebody has already set the .NET AutoInstrumentation in the container.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-operator/pull/1141#discussion_r991019109_

**Comment by avadhut123pisal** [comment]
@pavolloffay Can you please assign this issue on my name. I will raise a PR soon.
