### ISSUE TITLE
Support multiple instrumentations for a container

### ISSUE THREAD

**Issue by avadhut123pisal** [open-telemetry/opentelemetry-operator#1158]
The current implementation of the Auto-instrumentation supports multiple instrumentation at pod level  (e.g. one container java and other python etc.).
But, as single container can have a multiple processes, so there should be support for the enabling the injection of multiple instrumentations in the single container.

_Originally posted by_ _@pellared in_ https://github.com/open-telemetry/opentelemetry-operator/pull/1141#discussion_r991529641

**Comment by mat-rumian** [comment]
Hey @avadhut123pisal,
we are working on it https://github.com/open-telemetry/opentelemetry-operator/issues/1717

**Comment by jaronoff97** [comment]
Closed by #1901, please let me know if that solution is not sufficient!
