### ISSUE TITLE
Refresh go proxy module information on release

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#116]
When releasing the opentelemetry-operator, we might want to make an HTTP request to the Go module proxy, so that it knows about the new version. This should then cause the pkg.go.dev website to refresh the Godoc for this operator.

This is the URL that we should call for new releases: https://proxy.golang.org/github.com/open-telemetry/opentelemetry-operator/@v/v0.14.0.info , replacing `0.14.0` with the released version.

More info: https://go.dev/about

**Comment by KKelvinLo** [comment]
Hey I'd like to pick this up

**Comment by jpkrohling** [comment]
Here's our release script: https://github.com/open-telemetry/opentelemetry-operator/blob/main/.github/workflows/release.yaml

That script could just make a curl call to the URL mentioned earlier, based on the tag information. Check the GitHub Actions documentation to see which env var contains the tag, and use that when building the URL.

**Comment by VineethReddy02** [comment]
I can take this up! :)

**Comment by owais** [comment]
Should we call the URL directly or just run `go get/install` with the newly released version? I think the later is a bit more "future proof"?

**Comment by jpkrohling** [comment]
These are the options:

![image](https://user-images.githubusercontent.com/13387/123131221-c9e91c80-d44d-11eb-8529-4e1299624ec8.png)

I would be fine with the `go get` approach :-)

**Comment by owais** [comment]
Ah, so making request to the specific URL is officially supported. I suggested `go get` just in case the underlying URL scheme changes in future but if it is officially supported then either way should be fine.
