### ISSUE TITLE
Use python OTLP/proto metrics exporter once available

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-operator#1168]
Blocked by https://github.com/open-telemetry/opentelemetry-python/issues/2447

Right now I have set the `OTEL_METRICS_EXPORTER` to none to fix https://github.com/open-telemetry/opentelemetry-operator/issues/1148: https://github.com/open-telemetry/opentelemetry-operator/blob/992b681dd1bb8445b2744fb4f602f0faa0128ac9/pkg/instrumentation/python.go#L69-L72

Once https://github.com/open-telemetry/opentelemetry-python/issues/2447 is done, the operator's default should be updated to use the HTTP/proto exporter.

**Comment by vainikkaj** [comment]
Also by this https://github.com/open-telemetry/opentelemetry-python/pull/3027
Both are merged but new release is needed.
