### ISSUE TITLE
Upgrade e2e test is flaky

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#1173]
The upgrade test added in #1126 seems to be flaky https://github.com/open-telemetry/opentelemetry-operator/actions/runs/3247772222/jobs/5328173445#step:5:1363

@pureklkl could you please look at it?

**Comment by mat-rumian** [comment]
@pavolloffay usually multicontainers e2e tests are failing randomly. I think this could be related to the resources on the github actions machine. I will prepare a PR which sets resources limits/requests for all e2e tests. You can assign issue to me :)

**Comment by jaronoff97** [comment]
fixed by #1175
