### ISSUE TITLE
Release the operator to use collector v0.62.1

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-operator#1176]

**Comment by frzifus** [comment]
Oh and isn it `v0.62.0` instead of `v0.62.1`?

**Comment by pavolloffay** [comment]
we can probably go directly with 0.63.1

**Comment by frzifus** [comment]
ok, but isnt then 0.63.0? 

https://github.com/open-telemetry/opentelemetry-collector-contrib/releases

**Comment by Aneurysm9** [comment]
> we can probably go directly with 0.63.1

I don't think this is appropriate as long as our guidance is that there is a 1:1 correspondence between operator and collector versions.

**Comment by pavolloffay** [comment]
@Aneurysm9 could you please open a ticket to discuss and clarify this? 

I totally agree on

> 1:1 correspondence between operator and collector versions.

but I had a different view if the operator has to be released for all collector versions.

**Comment by frzifus** [comment]
There was also a comment from @vasireddy99 on that https://github.com/open-telemetry/opentelemetry-operator/pull/1215#issuecomment-1299638135.

> Team, I think this PR shouldn't close https://github.com/open-telemetry/opentelemetry-operator/issues/1176 and we still need a release for v0.62.1 right?

What would you recommend? Creating another branch to release `v0.62.1` with a65ec2235e638e07955c5b7be107594685fee53f as a base?

**Comment by Aneurysm9** [comment]
> @Aneurysm9 could you please open a ticket to discuss and clarify this?
> 
> I totally agree on
> 
> > 1:1 correspondence between operator and collector versions.
> 
> but I had a different view if the operator has to be released for all collector versions.

I think this issue works as well as any other.  We should decide here whether we need to release `v0.62.1` or not.

My view is that if there is a 1:1 correspondence between collector and operator versions then the operator must have a release that corresponds to every (non-retracted) collector release.  If the collector retracts a release before a corresponding operator release is made, that's fine, we should move on to whatever the next release is.  But here we have simply not released `v0.62.1` before the collector released `v0.63.0`.  In that case I believe we need to release the operator for both `v0.62.1` and `v0.63.0`.

**Comment by frzifus** [comment]
@open-telemetry/operator-maintainers could you create a release branch based on https://github.com/open-telemetry/opentelemetry-operator/commit/a65ec2235e638e07955c5b7be107594685fee53f? I will then prepare the release of `v0.62.1`.

**Comment by Aneurysm9** [comment]
> @open-telemetry/operator-maintainers could you create a release branch based on [a65ec22](https://github.com/open-telemetry/opentelemetry-operator/commit/a65ec2235e638e07955c5b7be107594685fee53f)? I will then prepare the release of `v0.62.1`.

I have created [`release/v0.62.x`](https://github.com/open-telemetry/opentelemetry-operator/tree/release/v0.62.x).
