### ISSUE TITLE
Support `metrics-level/port/prefix` parameters to the collector

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-operator#12]
The collector has [three metrics related parameters](https://github.com/open-telemetry/opentelemetry-collector/blob/master/service/telemetry.go#L36-L38) that need to be configurable via the CR.

For example, the deployment should be able to pass the metrics level as detailed:
```
--config=/conf/collector.yaml
--metrics-level=DETAILED
```

**Comment by VineethReddy02** [comment]
I can work on this. Is it still relevant? I do not think the link mentioned above points to the intended content anymore. 

@objectiser could you share more info on this?

**Comment by jpkrohling** [comment]
The flag still exists:

```
$ go run ./cmd/otelcol/ --help | grep metrics-level
      --metrics-level Level         Output level of telemetry metrics (none, basic, normal, detailed) (default basic)
```

There could be a new property in the CR named `MetricsLevel`, which then becomes a command line argument for the generated containers.

**Comment by VineethReddy02** [comment]
I will work on this! :)

**Comment by jpkrohling** [comment]
Great catch. We discussed this a few times in the past, on whether it's better to have a generic "args" property or a more typed approach. I think I prefer the generic (current) solution. We'd then just need to document how to get the metrics-level set for the container.

**Comment by VineethReddy02** [comment]
Any specific location you want me to add this as a point to note? Btw I didn't find any dedicated docs other than the `README.md`

**Comment by jpkrohling** [comment]
A great source of documentation is the e2e test suite, which serves as an example repository. Add one generic test using `args`, perhaps setting the metrics and the log levels. You can add a new doc or new section in the readme for the CR configuration and mention this. Even better would be if you could figure out a way to generate good user docs out of our godocs. People have asked before about a doc explaining all the CR options, and this would fit there.
