### ISSUE TITLE
Implementation of a "Kubernetes Operator" not work on .net project

### ISSUE THREAD

**Issue by sr185436** [open-telemetry/opentelemetry-operator#1200]
I appreciate if someone can share example that works on .net

**Comment by pavolloffay** [comment]
There is no demo application right now. 

The only information is in readme https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-auto-instrumentation-injection or you can take a look at dotnet e2e test but you will need to learn kuttl https://github.com/open-telemetry/opentelemetry-operator/tree/main/tests/e2e/instrumentation-dotnet.


I am closing the ticket as it is "too generic".
