### ISSUE TITLE
Nominate @frzifus to approver

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#1207]
I would like to nominate @frzifus to join @open-telemetry/operator-approvers. He has been contributing to the operator for several months. His biggest accomplishment is ingress support https://github.com/open-telemetry/opentelemetry-operator/pull/1128. 

Facts:
* 39 PR reviews https://github.com/open-telemetry/opentelemetry-operator/pulls?q=is%3Apr+reviewed-by%3Afrzifus
* 5 merged PRs https://github.com/open-telemetry/opentelemetry-operator/pulls?q=is%3Apr+author%3Afrzifus+

He meets approver requirements https://github.com/open-telemetry/community/blob/main/community-membership.md#approver 

@frzifus is as well an active maintainer of Jaeger and Tempo operators which proves his domain knowledge in building Kubernetes operators.

cc) @open-telemetry/operator-approvers @open-telemetry/operator-maintainers

**Comment by jpkrohling** [comment]
I support

**Comment by VineethReddy02** [comment]
+1 in having @frzifus as the operator-approver.

**Comment by pavolloffay** [comment]
Voting done, all maintainers agree. 

@frzifus please add yourself to the readme. I have added @frzifus to the @open-telemetry/operator-approvers

**Comment by frzifus** [comment]
Thank you, i do :)
