### ISSUE TITLE
Improve installation docs 

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-operator#1208]
Ref https://github.com/open-telemetry/opentelemetry-operator/pull/1205#pullrequestreview-1156201922

I'm thinking maybe we can add a short guide how to install / upgrade operator using helm, but also leave the current `kubectl apply -f ` approach.

I'm not sure what are other ways to install the operator?

Any thoughts around this? 

FYI: I can find some time to work on this :)

**Comment by jaronoff97** [comment]
closed by #1205
