### ISSUE TITLE
Release the operator to use collector v0.63.0

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-operator#1210]

**Comment by codeboten** [comment]
Please hold off on this until v0.63.1 is released. A patch is required to address https://github.com/open-telemetry/opentelemetry-collector/issues/6433

**Comment by codeboten** [comment]
v0.63.1 is out https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.63.1

**Comment by frzifus** [comment]
Should we go with a `v0.62.0` first? What do you think?

cc @pavolloffay
