### ISSUE TITLE
Add default cipher suites configuration for webhook server

### ISSUE THREAD

**Issue by kangsheng89** [open-telemetry/opentelemetry-operator#1238]
Currently the webhook server default cipher suite from crypto/tls package.
There are 2 cipher is vulnerable on SWEET32 attack
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA

Since webhook server is default to TLSv1.2, we can add configure to default disable cipher suite of the above, and allow the strong cipher suite.

![image](https://user-images.githubusercontent.com/12370490/200990262-35a9f9db-55fc-466d-9fca-73dd6a48011f.png)
The one in yellow is medium strength cipher suite
https://www.openssl.org/blog/blog/2016/08/24/sweet32/

**Comment by kangsheng89** [comment]
Currently the #1244 only fix operator on port 9443, port 8443 need further investigation

**Comment by kangsheng89** [comment]
@pavolloffay  as i understand port 8443 is metrics-server, do u mind to point me where is the entrypoint for setting the server?

**Comment by pavolloffay** [comment]
what is using 8443? Is it for metrics `8443`?

Are you looking to configure rbac proxy https://github.com/brancz/kube-rbac-proxy? The requests from the proxy are proxied to 8080 on the operator.

**Comment by kangsheng89** [comment]
> what is using 8443? Is it for metrics `8443`?
> 
> Are you looking to configure rbac proxy https://github.com/brancz/kube-rbac-proxy? The requests from the proxy are proxied to 8080 on the operator.
I have created this to fix it from helm-chart
https://github.com/open-telemetry/opentelemetry-helm-charts/pull/501
