### ISSUE TITLE
Release the operator to use collector v0.64.0

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#1239]
https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.64.0

**Comment by pavolloffay** [comment]
@yuriolisa I would propose to close this ticket and release only 0.64.1 as part of https://github.com/open-telemetry/opentelemetry-operator/issues/1241

cc) @Aneurysm9

**Comment by yuriolisa** [comment]
look fine to me. I'll close, though.
