### ISSUE TITLE
[Feature request] Ability to use `hostPorts` to expose the collectors ports locally to the instance

### ISSUE THREAD

**Issue by bonclay7** [open-telemetry/opentelemetry-operator#1243]
I would like to be able to declare a list of ports that other pods on the same host can access using `localhost`. Right now `hostNetwork: true` seems to do the trick but it opens up to other security implications

**Comment by jaronoff97** [comment]
closed by https://github.com/open-telemetry/opentelemetry-operator/pull/2763
