### ISSUE TITLE
Warning about PodSecurity when applying some manifests from the E2E tests in OpenShift 4.11

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#1262]
When applying some of the manifest from the E2E tests, this error is shown:
```sh
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "myapp" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "myapp" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "myapp" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "myapp" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

The files with this problem are:
```
tests/e2e/instrumentation-dotnet-multicontainer/01-install-app.yaml
tests/e2e/instrumentation-dotnet-multicontainer/02-install-app.yaml
tests/e2e/instrumentation-dotnet/01-install-app.yaml
tests/e2e/instrumentation-java-multicontainer/01-install-app.yaml
tests/e2e/instrumentation-java-multicontainer/02-install-app.yaml
tests/e2e/instrumentation-java-other-ns/01-install-app.yaml
tests/e2e/instrumentation-java/01-install-app.yaml
tests/e2e/instrumentation-nodejs-multicontainer/01-install-app.yaml
tests/e2e/instrumentation-nodejs-multicontainer/02-install-app.yaml
tests/e2e/instrumentation-nodejs/01-install-app.yaml
tests/e2e/instrumentation-python-multicontainer/01-install-app.yaml
tests/e2e/instrumentation-python-multicontainer/02-install-app.yaml
tests/e2e/instrumentation-python/01-install-app.yaml
tests/e2e/instrumentation-sdk/01-install-app.yaml
```

**Comment by jaronoff97** [comment]
@iblancasa is this still an issue?

**Comment by iblancasa** [comment]
AFAIK, yes.

**Comment by iblancasa** [comment]
@IshwarKanse with the changes done to the new test framework, are those warnings still there?

**Comment by IshwarKanse** [comment]
@iblancasa I'll check and update the issue.

**Comment by IshwarKanse** [comment]
@iblancasa There are no PodSecurity warnings anymore, I checked in OpenShift 4.15. However the instrumentation tests needs to be updated as the asserts are wrong. I was manually running the tests one-by-one and noticed that the tests pass however for many tests the pods run into Error and CrashLoops which is not detected by the current assert. I'm working on a PR to fix this. Will complete it in the next week.

**Comment by IshwarKanse** [comment]
@iblancasa @jaronoff97 We can close this issue as we are not running into the PodSecurity warnings anymore. Also I have resolved issues with asserts, security contexts in this PR, pending merge. https://github.com/open-telemetry/opentelemetry-operator/pull/2702
