### ISSUE TITLE
Understanding how Python Auto-Instrumentation works.

### ISSUE THREAD

**Issue by dominthomas** [open-telemetry/opentelemetry-operator#1267]
Hi, can someone give guidance on these:

1. What's the best way to understand how the python auto instrumentation init container works - do we have any docs for this?
2. Do we have any resources/documentation on how to debug auto instrumentation issues, i.e. no traces, debug logging etc.?

If we don't have documentation on the above, I'm willing to contribute some docs with my experience.

Regards!

**Comment by pavolloffay** [comment]
> Do we have any resources/documentation on how to debug auto instrumentation issues, i.e. no traces, debug logging etc.?

you could perhaps check the python repository if they have some docs. The operator just injects the auto-instrumentation.

> What's the best way to understand how the python auto instrumentation init container works - do we have any docs for this?

Here are some docs https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/python/Dockerfile

**Comment by mat-rumian** [comment]
The best place to check for OpenTelemetry instrumentation is official documentation or specific for instrumentation repository.

@dominthomas please see:
* https://opentelemetry.io/docs/instrumentation/python/ - official OpenTelemetry documentation
* https://github.com/open-telemetry/opentelemetry-python - official OpenTelemetry Python SDK repository
* https://github.com/open-telemetry/opentelemetry-python-contrib - official OpenTelemetry Python Contrib (instrumentation libs) repository
* in case of debug logging you could try to set traces exporter to logging/console and see if instrumentation was correctly initialized and generate spans/traces

**Comment by jaronoff97** [comment]
We've since updated our docs and public otel docs, do let me know if you have more questions. thank you!
