### ISSUE TITLE
Sync list of receivers

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#128]
The operator knows about a few receivers, but I'm not sure this list is up to date:
https://github.com/open-telemetry/opentelemetry-operator/tree/master/pkg/collector/parser

This ticket is to sync this list.

Current delta:

- [ ] awscontainermetrics
- [ ] awsxray
- [ ] dockerstats
- [ ] jmx
- [ ] k8scluster
- [ ] kubeletstats
- [ ] memcached
- [ ] nginx
- [ ] prometheusexec
- [ ] recever
- [ ] redis
- [ ] simpleprometheus
- [ ] splunk
- [ ] stanza

**Comment by gramidt** [comment]
I'll take this @jpkrohling

**Comment by gramidt** [comment]
## The current deltas:

### collector

Currently update to date. May need to compare settings to make sure everything is still following convention.

### collector-contrib

- awscontainermetrics
- awsxray
- dockerstats
- jmx
- k8scluster
- kubeletstats
- memcached
- nginx
- prometheusexec
- recever
- redis
- simpleprometheus
- splunk
- stanza

**Comment by gramidt** [comment]
@jpkrohling - What are your thoughts about the "collector-contrib" receivers? Was your plan to rely on `receiver_generic.go` for deltas?

**Comment by jpkrohling** [comment]
No, the generic is just an implementation detail, as most receivers can be managed in the same way. Basically, if the receiver has an `endpoint` property that accepts a `host:port` value, it can make use of the generic adapter.

**Comment by jpkrohling** [comment]
Perhaps it was implicit in the comment above, but for now, all we care about is the `endpoint` property for the receiver, as we'll use this to automatically add the needed ports to the `Service`. So, there's no need to sync the other properties in each receiver.

**Comment by gramidt** [comment]
Perfect! That's exactly what I was thinking. I'll start tackling the deltas 1-by-1 with individual PRs for each. Should we also split this into multiple issues, @jpkrohling?

**Comment by jpkrohling** [comment]
This issue here has the list of receivers already, if we reference this issue in all individual PRs, it should be fine.

**Comment by gramidt** [comment]
@jpkrohling - Could you add me as an assignee, so I can more easily track this work?

**Comment by jpkrohling** [comment]
Done

**Comment by gramidt** [comment]
Thank you!

**Comment by gramidt** [comment]
@jpkrohling and community - Quick update: I'm planning to start this work either later this week or early next week. My current OSS queue includes finishing the Loki exporter ( https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1894 ), adding a small feature to the F5 Cloud exporter, then circling back to this.

**Comment by VineethReddy02** [comment]
I can take this up! :)

**Comment by jpkrohling** [comment]
It's yours, @VineethReddy02!

**Comment by VineethReddy02** [comment]
This is the [list of receivers](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver) from contrib repo

**Below receivers already exist in the operator**
```
carbon
collectd
sapm
signalfx
wavefront
```

**Delta receivers that aren't scrapers**
```
awsxray
fluentforward
influxdb
jmx
receivercreator
splunkhec
statsd
syslog
tcplog
udplog
```

**Scrapers (which should be ignored as we do not expose any ports for scrapers)**
```
awscontainerinsight
awsecscontainermetrics
dockerstats
dotnetdiagnostics
filelog
googlecloudpubsub
k8scluster
kafkametrics
kubeletstats
memcached
nginx
prometheusexec
redis
simpleprometheus
zookeeper
windowsperfcounters
```

**Comment by yuriolisa** [comment]
@jpkrohling, is that issue done, or should we implement the following receivers?

```
kafka
receivercreator
syslog
```

**Comment by yuriolisa** [comment]
@pavolloffay, how should we proceed with that issue?

**Comment by pavolloffay** [comment]
I would propose to close this and add components per request.
