### ISSUE TITLE
[bug] starting container process caused "chdir to cwd/home/nonroot" in config.json failed: permission denied: unknown

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-operator#1286]
Hi, 

I use [opentelemetry-operator](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/README.md) helm chart deploy in Kubernetes v1.17.2.  but it works in Kubernetes v1.24.0

the operator could not start up normally with the following errors:

```bash
kube-rbac-proxy: failed to start container "Bc560852f99e6567a21763ee7fbde55644649c7d55721525d185a8ebc6110d31":
Error response from daemon OC runtime create failed: container_linux.go: 346:: starting container process caused "chdir to cwd/home/nonroot" in config.json failed: permission denied: unknown
```

anything suggestions about how to solve this problem? thx~

**Comment by JaredTan95** [comment]
solved by set `securityContext` to nil :
```yaml
securityContext: {}
  #runAsGroup: 65534
  #runAsNonRoot: true
  #runAsUser: 65534
  #fsGroup: 65534
```

**Comment by pavolloffay** [comment]
@JaredTan95 is this an operator issue or a helm chart?

**Comment by JaredTan95** [comment]
> @JaredTan95 is this an operator issue or a helm chart?

it's helm

**Comment by JaredTan95** [comment]
> Therefore, it works fine with the following configuration
securityContext:
runAsGroup: 65532
runAsNonRoot: true
runAsUser: 65532
fsGroup: 65532

@ethan256 I noticed you changed `65534` to `65532`, what's the difference? or other reasons?

**Comment by Allex1** [comment]
discussed on https://github.com/open-telemetry/opentelemetry-helm-charts/issues/547 fix is in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/548
I think we can close this issue.
