### ISSUE TITLE
TestSmartCollectorReassignment is flaky

### ISSUE THREAD

**Issue by kevinearls** [open-telemetry/opentelemetry-operator#1291]
TestSmartCollectorReassignment in cmd/otel-allocator/allocation/least_weighted_test.go fails frequently.   I will add a t.skip() to prevent it from breaking CI

**Comment by secustor** [comment]
Fore reference, the PR which introduced the skip: https://github.com/open-telemetry/opentelemetry-operator/pull/1233

**Comment by frzifus** [comment]
Same here: 

https://github.com/open-telemetry/opentelemetry-operator/actions/runs/3584847719/jobs/6032050844#step:6:1174
https://github.com/open-telemetry/opentelemetry-operator/actions/runs/3585751516/jobs/6034118083#step:6:1172

**Comment by swiatekm-sumo** [comment]
This test was flaky because the behaviour it was checking wasn't what the strategy actually does. The least-weighted strategy is not stable - it's not guaranteed that if you allocate using the same sets of Collectors and Targets, you'll always get the same allocation.
