### ISSUE TITLE
statsd reciever port not opening

### ISSUE THREAD

**Issue by krvajal** [open-telemetry/opentelemetry-operator#1295]
When adding a statsd receiver, the port is not being added to the container.
See https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/collector/parser/receiver_statsd.go

**Comment by yuriolisa** [comment]
@krvajal, could you please share your collector config, to help us reproduce the issue?

**Comment by krvajal** [comment]
I found a workaround and I don't have the initial config around anymore. Closing this issue
