### ISSUE TITLE
Otel operator image is not support ARM processors

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-operator#1297]
The docker image cannot be executed in the K8S which is using ARM processors

**Comment by kevinearls** [comment]
@sweetxiaodai Can you give some more details on what you are seeing?  I have been able to build and run the operator on my M1 MacBook Pro.

**Comment by pavolloffay** [comment]
The operator image is published in arch architecture https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fopentelemetry-operator

**Comment by enorasec** [comment]
I'm receiving the same issue when trying to install otel operator. I receive a CrashLoopBackoff after the container is pulled from the repository.  The only log message provided by the manager container is `exec  /manager: exec format error`

otel operator version: v.68.0.
k8s version: v1.25.4+k3s1
Worker nodes are Raspberry Pi 3B+.

Let me know what information is needed to help look into this

**Comment by frzifus** [comment]
@enorasec are you running your os in 32 or 64bit mode?

Using `docker image inspect ...` you should be able to verify if the given image is supported.

**Comment by yuriolisa** [comment]
@sweetxiaodai, did you have the opportunity to check it?

**Comment by jaronoff97** [comment]
we now deploy the operator in many various architectures. Please reach out if one is not supported for you.
