### ISSUE TITLE
Target Allocator versioning

### ISSUE THREAD

**Issue by kristinapathak** [open-telemetry/opentelemetry-operator#1298]
Currently, the target allocator go module has no version/releases:
https://pkg.go.dev/github.com/open-telemetry/opentelemetry-operator/cmd/otel-allocator?tab=versions

The image version is `v0.66.0`, which matches the operator version, but @jaronoff97 pointed out that a new image is built with any merge to `main` (so `v0.66.0` has already been rebuilt [many times](https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Ftarget-allocator/versions)).  This means someone can start using an image with changes not documented in the changelog for that version.

The [Changelog](https://github.com/open-telemetry/opentelemetry-operator/blob/main/CHANGELOG.md) is also kind of confusing, since it's unclear what changes are for the operator vs target allocator.

Is there an easier way to manage builds and versions for the target allocator? Does it make sense for it to have its own changelog?

**Comment by kristinapathak** [comment]
This came up as a result of this discussion:
https://github.com/open-telemetry/opentelemetry-operator/pull/1293#discussion_r1038281091

As we add features for the target allocator that allow for consumers to create their own implementations of something (like target allocation strategies), the go package APIs need to be documented well enough for consumers to know about breaking changes.

**Comment by jaronoff97** [comment]
From the operator SIG meeting, the plan here is to do the following: include a go mod for the target allocator to be bumped with the release of a new target allocator. Separately, we also need to change the build process of the target allocator to _only_ be built & pushed when a release for the operator happens. Does that sound correct @kristinapathak?

**Comment by kristinapathak** [comment]
Changelog changes are covered under https://github.com/open-telemetry/opentelemetry-operator/issues/1317.
