### ISSUE TITLE
auto-instrumentations-node: Allow configuration of custom sampler

### ISSUE THREAD

**Issue by adecchi-2inno** [open-telemetry/opentelemetry-operator#1332]
I am using [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator) and [NodeJS Auto Instrumentation](https://github.com/open-telemetry/opentelemetry-operator/tree/main/autoinstrumentation/nodejs), and I would like to create custom sampler, for example to ignoring certain url-patterns like:

- /info
- /health
-  /swagger-ui
- etc
- etc

I could not find a way to resolve it, is a way to create custom sampler ?

kind regards,

**Comment by pavolloffay** [comment]
The operator only installs and configures the instrumentation. If you want to use a custom sampler you will have to build a custom auto-instrumentation image https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/Dockerfile#L1 and then specify it in the CR.


I would suggest you to look into the Jaeger remote sampler. It allows more fine-grained sampling configuration. Though I am not sure if the nodejs SDK supports it.
