### ISSUE TITLE
[target-allocator] Use json-iter to marshal json

### ISSUE THREAD

**Issue by kristinapathak** [open-telemetry/opentelemetry-operator#1336]
In server handling, we currently have two use cases:
1. marshaling into yaml and then converting yaml to json.
2. marshaling straight to json using the standard library.

There are json libraries more performant than the `json` standard library package and provide configuration on the build tag, allowing us to not have to effectively marshal twice for the yaml -> json conversion.  I looked into `json-iterator`, which is imported in other open-telemetry repos and showed good [benchmarks](https://pkg.go.dev/github.com/json-iterator/go#section-readme).  To see if it was the right fit for us, I wrote benchmarks for our server handling functions to see how json-iterator compares to the standard library package:

https://github.com/open-telemetry/opentelemetry-operator/pull/1323
[benchmarks.txt](https://github.com/open-telemetry/opentelemetry-operator/files/10273573/benchmarks.txt)

In terms of both memory and cpu, json-iterator performed better in all of my tests, especially as objects grew larger.

I'm interested in hearing others' thoughts on this - is this a change people are open to making?

**Comment by jaronoff97** [comment]
Given those benchmarks, I am _very_ interested in this change going through!

**Comment by kristinapathak** [comment]
These changes had to be reverted: https://github.com/open-telemetry/opentelemetry-operator/pull/1351

The prometheus structs have special `MarshalYAML()` functions that a json marshaler won't find and use.  Specifically the Regex [struct](https://pkg.go.dev/github.com/grafana/regexp#Regexp) has no exported fields, so all data is lost there.
