### ISSUE TITLE
Support update the ImagePullSecrets

### ISSUE THREAD

**Issue by saltbo** [open-telemetry/opentelemetry-operator#1340]
I use a privateRegistry for the collector, so must set the ImagePullSecrets. But I found the CR OpenTelemetryCollector not supported. 

Can we add this support?

**Comment by pavolloffay** [comment]
The pull secret can be specified in the service account that can be configured in the CR.

**Comment by saltbo** [comment]
Thanks for your reply

**Comment by saltbo** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/#ServiceAccount
