### ISSUE TITLE
How to add instrumentation of Redis & RabbitMQ 

### ISSUE THREAD

**Issue by sr185436** [open-telemetry/opentelemetry-operator#1342]
How to add instrumentation of Redis & RabbitMQ  by using opentelemetry-operator?
Operator v0.66.0 or v0.61.0 
.NET version 6
-
Redis - [StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis)
RabbitMQ - RabbitMQ.Client 4.0.30319

**Comment by Kielek** [comment]
I suppose that the question is related to .NET (based on #1343).

What do you mean by adding Redis and RabbitMQ instrumentations?
Both of them should be enabled by default in the latest version operator.

It will be great if you can share
- operator version
- .NET version of instrumented applications
- logs from the OpenTelemetry .NET Automatic Istrumentation. Typically stored by operator under `/var/log/opentelemetry/dotnet`

from the solution where you expect Redis/RabbitMQ instrumentation and there is no spans for it.

**Comment by sr185436** [comment]
No it's not related please help how to add Redis & RabbitMQ instrumentation to the opentelemetry-operator?

**Comment by sr185436** [comment]
How to add instrumentation of Redis & RabbitMQ ?

**Comment by sr185436** [comment]
v0.66.0 operator version
.NET version 6

**Comment by pellared** [comment]
What client libraries (together with versions) are you using for Redis & RabbitMQ?

Maybe they are not supported? Check https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.5.0/docs/config.md#traces-instrumentations

**Comment by sr185436** [comment]
Redis - [StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis)
RabbitMQ - RabbitMQ.Client 4.0.30319

**Comment by pellared** [comment]
`StackExchange.Redis` should be instrumented for `≥2.0.405`. The lack of instrumentation might be a bug. Please consisder checking https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation and reporting a bug with repro steps in that reprository.

`RabbitMQ.Client` is not supported.

**Comment by Kielek** [comment]
Ref link for RabbitMQ https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/776

**Comment by sr185436** [comment]
I try to avoid to write code, all idea is to config the operator to trace automatically all same behavior like sqlClient...
Please help and send me some doc/guide that related to the operator.

**Comment by Kielek** [comment]
Operator is using [OpenTelemetry .NET Automatic Instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) under the hood. I suppose that is it not related to operator if any instrumentation is working for you.

For now, we are not able to propose you any solution for RabbitMQ. It has to be implemented on the RabbitMQ side or we will have to add bytecode instrumentation for this library in Automatic Instrumentation project.
We are open for the contribution in Automatic Instrumentation project. I suppose that RabbitMQ community will be also happy to accept changes. 

`StackExchange.Redis ≥ 2.0.405` instrumentation is enabled by default. Once again, if it is not working for you we need reproduction steps. Separate repository/zip file following https://stackoverflow.com/help/minimal-reproducible-example will be really helpful. Without this it will be hard/impossible to help you.

**Comment by pavolloffay** [comment]
I am closing this request is not related to the operator codebase. Please open a ticket against https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation to support additional instrumentations.
