### ISSUE TITLE
Improve CRD Status for OpenTelemetryCollector

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#1355]
Currently, the operator returns minimal information for the status of a collector:
```
⫸ k get opentelemetrycollector/kube-otel-stack-metrics
NAME                      MODE          VERSION   AGE
kube-otel-stack-metrics   statefulset   0.60.0    54d
```

This means that when someone deploying a collector wants to observe the rollout status, there could be a potential race condition when running something like 
```
k rollout status sts/kube-otel-stack-metrics-collector
```
The race exists because the operator may not have applied the changes before someone runs this rollout command.

Ideally, someone would be able to see the rollout status like:
```
k rollout status opentelemetrycollector/kube-otel-stack-metrics
```

Or we could include more information in the status for a collector (an example, not exactly what we would want)
```
⫸ k get opentelemetrycollector/kube-otel-stack-metrics
NAME                      MODE          VERSION        READY   AGE
kube-otel-stack-metrics   statefulset   0.60.0          3/4    54d
```

How do people currently watch the rollout status of their collectors? Are there other fields in here that would be useful to add to the collector's status?

**Comment by yuriolisa** [comment]
@jaronoff97, WDYT to identify also if the collector is using a collector image or a contrib ones?

**Comment by jaronoff97** [comment]
I think that could be helpful as well! That plus desired vs current replicas too
