### ISSUE TITLE
Host python test image source code in this repository 

### ISSUE THREAD

**Issue by ecourreges-orange** [open-telemetry/opentelemetry-operator#1361]
@anuraaga : I cannot find the source of the image `ghcr.io/anuraaga/flask-hello-world:latest`  

# Problem
I have a colleague testing the opentelemetry-operator in python, which works with your image, properly exports spans, but not with the assumed original image `digitalocean/flask-helloworld`.
So what is the difference between the two?

My test setup outside of kubernetes to decompose the problem, is to build the python image in autoinstrumentation, docker cp the autoinstrumentation folder outside of it, then create the file python.env:
```bash
OTEL_EXPORTER_OTLP_CERTIFICATE=/etc/ssl/certs/ca-certificates.crt
OTEL_SERVICE_NAME=otelcol-validator
OTEL_BSP_EXPORT_TIMEOUT=1000
OTEL_TRACES_EXPORTER=otlp,console
OTEL_TRACES_SAMPLER_ARG=1.0
OTEL_EXPORTER_OTLP_ENDPOINT=https://myendpoint
OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
OTEL_METRICS_EXPORTER=none
PYTHONPATH=/autoinstrumentation/opentelemetry/instrumentation/auto_instrumentation:/autoinstrumentation
```

Then run this one generates span in logs and on endpoint
`docker run --env-file python.env -v /home/ecourreges/workspace/opentelemetry-operator/autoinstrumentation/python/autoinstrumentation:/autoinstrumentation -v /etc/ssl/certs/:/etc/ssl/certs/ --rm -p 5000:5000 ghcr.io/anuraaga/flask-hello-world:latest`

Then running this one does not generate any spans: 
`docker run --env-file python.env -v /home/ecourreges/workspace/opentelemetry-operator/autoinstrumentation/python/autoinstrumentation:/autoinstrumentation -v /etc/ssl/certs/:/etc/ssl/certs/ --rm -p 5000:5000 digitalocean/flask-helloworld`

# How to fix
I think that the test image `ghcr.io/anuraaga/flask-hello-world:latest` should be somewhere on this repository, or it makes this repo non reproducible.

Thank you.

**Comment by anuraaga** [comment]
Indeed the image should have been moved over here but unfortunately forgot about that. And I guess I must have pushed that image manually without pushing any source repo. So whatever source I had used is lost :(

I don't recall it being digitalocean, I suspect it was this one but not sure

https://github.com/mehmandarov/docker-flask-helloworld

**Comment by ecourreges-orange** [comment]
Alright, I found the culprit, it seems that Flask `app.run` with `debug=True` deactivates otel auto instrumentation, and probably the same for Django. Is this a known problem?

You can see here my commit that probably corresponds to your image which now works: https://github.com/mehmandarov/docker-flask-helloworld/compare/master...ecourreges-orange:docker-flask-helloworld:master

Now we need a way to document/link the image, and perhaps document the interactions of debug modes with the auto-instrumentation (if not done already, didn't check).

**Comment by anuraaga** [comment]
Ah yeah that's been an issue for a while

https://github.com/open-telemetry/opentelemetry-python-contrib/issues/546

**Comment by pavolloffay** [comment]
@ecourreges-orange would you like to submit a PR to add the source code with image publishing to this repo?

**Comment by jaronoff97** [comment]
closed by 2095
