### ISSUE TITLE
Operator release v0.68.0: generate OLM bundle

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/opentelemetry-operator#1390]
As part of release v0.68.0- require execution of step 9 of [release.md](https://github.com/open-telemetry/opentelemetry-operator/blob/main/RELEASE.md).

Reference Issue: #1362.

**Comment by iblancasa** [comment]
I'm on it

**Comment by iblancasa** [comment]
https://github.com/open-telemetry/opentelemetry-operator/pull/1384#issuecomment-1401569631

**Comment by iblancasa** [comment]
@PaurushGarg we can close this issue now.
