### ISSUE TITLE
Span Status not being set as ERROR for HTTP Client spans even if the HTTP status code is 4xx.

### ISSUE THREAD

**Issue by biswajit-nanda** [open-telemetry/opentelemetry-operator#1394]
I have a very simple node.js application that receives a HTTP request and then makes a HTTP get call to http://httpstat.us:80/410 which returns a 410 status code.

Please see the attached **app.js**.

I have auto-instrumented the application with OpenTelemetry Operator using the latest version of node.js auto-instrumentation library available. The instrumentation resource config looks like below:

Please see the attached **instrumentation.yaml**.

The application gets auto-instrumented successfully, but the Span Status of the Client Span making the HTTP call to http://httpstat.us:80/410 is returned as UNSET even if the HTTP Status Code is coming as 410.

Please see the below SPAN snippet in my Otel Collector logs attached: **otelcol-span-snippet.log**

As per OpenTelemetry Specs (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status), for HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT.

[reproduction.zip](https://github.com/open-telemetry/opentelemetry-operator/files/10492764/reproduction.zip)

**Comment by oppegard** [comment]
Your issue seems specific to the implementation of the node.js auto-instrumentation, rather than the OTel Operator (which packages the instrumentation and deploys it).

I would raise your issue in the repo that maintains the auto-instrumentation: https://github.com/open-telemetry/opentelemetry-js.
