### ISSUE TITLE
I have an issue with exporter

### ISSUE THREAD

**Issue by akalita-conga** [open-telemetry/opentelemetry-operator#1398]
I have configured a controller and deployed as deployment in a EKS cluster(A) in the same AWS account.
Deployed OTEL agent in another EKS cluster(B) as Demonset and trying to send logs & traces data to the central collector in the other EKS cluster(A).
Deployed Ingress nginx in the collector side EKS cluster for HTTP and GRPC,
updated Route53 and created a domain and CNAME as collector.something.app

OTEL agent config
config:
  exporters:
    otlphttp:
      endpoint: https://collector.something.app

I am facing the following error

info    exporterhelper/queued_retry.go:426      Exporting failed. Will retry the request after interval.      {"kind": "exporter", "data_type": "logs", "name": "otlphttp", "error": "failed to make an HTTP request: Post \"https://collector.something.app/v1/logs\": x509: certificate signed by unknown authority", "interval": "33.255795251s"}

If somebody can help it will be great .

The certificate I am using in the EKS cluster (A) is valid and working for other Ingress rules .

**Comment by pavolloffay** [comment]
@akalita-conga could you please share full otelcol CR?

@Aneurysm9 could you please take a look?

**Comment by Aneurysm9** [comment]
In addition to the configuration, logs from the collector at the debug level may be helpful.  Are you using a private CA?

**Comment by akalita-conga** [comment]
@Aneurysm9 Yes, I am using private CA.
@pavolloffay 

`# Default values for opentelemetry-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Valid values are "daemonset", "deployment", and "statefulset".
mode: "deployment"

# Handles basic configuration of components that
# also require k8s modifications to work correctly.
# .Values.config can be used to modify/add to a preset
# component configuration, but CANNOT be used to remove
# preset configuration. If you require removal of any
# sections of a preset configuration, you cannot use
# the preset. Instead, configure the component manually in
# .Values.config and use the other fields supplied in the
# values.yaml to configure k8s as necessary.
presets:
  # Configures the collector to collect logs.
  # Adds the filelog receiver to the logs pipeline
  # and adds the necessary volumes and volume mounts.
  # Best used with mode = daemonset.
  logsCollection:
    enabled: true
    includeCollectorLogs: true
  # Configures the collector to collect host metrics.
  # Adds the hostmetrics receiver to the metrics pipeline
  # and adds the necessary volumes and volume mounts.
  # Best used with mode = daemonset.
  hostMetrics:
    enabled: false
  # Configures the Kubernetes Processor to add Kubernetes metadata.
  # Adds the k8sattributes processor to all the pipelines
  # and adds the necessary rules to ClusteRole.
  # Best used with mode = daemonset.
  kubernetesAttributes:
    enabled: false
  # Configures the Kubernetes Cluster Receiver to collect cluster-level metrics.
  # Adds the k8s_cluster receiver to the metrics pipeline
  # and adds the necessary rules to ClusteRole.
  # Best used with mode = deployment or statefulset.
  clusterMetrics:
    enabled: false
  # Configures the collector to collect Kubelet metrics.
  # Adds the kubeletstats receiver to the metrics pipeline
  # and adds the necessary rules to ClusteRole.
  # Best used with mode = daemonset.
  kubeletMetrics:
    enabled: false

configMap:
  # Specifies whether a configMap should be created (true by default)
  create: true

# Base collector configuration.
# Supports templating. To escape existing instances of {{ }}, use {{` <original content> `}}.
# For example, {{ REDACTED_EMAIL }} becomes {{` {{ REDACTED_EMAIL }} `}}.
config:
  exporters:
    otlphttp:
      endpoint: http://tempo-distributor:4318

    logging:
      logLevel: info #debug
    loki:
      endpoint: http://loki-loki-distributed-gateway:80/loki/api/v1/push


  extensions:
    health_check: {}
    memory_ballast: {}
  processors:
    batch:
      timeout: 10s
    k8sattributes:
      extract:
        labels:
        - key: deployment.environment
          tag_name: deployment.environment
        - key: app
        - key: release
        metadata:
        - k8s.pod.name
        - k8s.node.name
        - k8s.namespace.name
        - k8s.deployment.name
        - k8s.pod.start_time
      filter:
        node_from_env_var: KUBE_NODE_NAME
    k8sattributes/pod_uid:
      extract:
        labels:
        - key: deployment.environment
          tag_name: deployment.environment
        - key: app
        - key: release
        metadata:
        - k8s.pod.name
        - k8s.node.name
        - k8s.namespace.name
        - k8s.deployment.name
        - k8s.pod.start_time
      filter:
        node_from_env_var: KUBE_NODE_NAME
      pod_association:
      - from: resource_attribute
        name: k8s.pod.uid
    memory_limiter:
      check_interval: 5s
      limit_mib: 1638
      limit_percentage: 80
      spike_limit_mib: 512
      spike_limit_percentage: 25
    resource:
      attributes:

        from_attribute: k8s.pod.labels.app
        key: service.name
    resource/kubeletstats:
      attributes:
      - action: upsert
        from_attribute: k8s.container.name
        key: service.name
    resource/prometheus:
      attributes:
      - action: delete
        key: host.name
    # If set to null, will be overridden with values based on k8s resource limits
  receivers:
    otlp:
      protocols:
        grpc:
          keepalive:
            server_parameters:
              max_connection_age: 1h 
              max_connection_age_grace: 10m
        http:
          cors:
            allowed_origins:
             - "*"
    filelog:
      include:
      - /var/log/pods/*/*/*.log
      include_file_name: false
      include_file_path: true
    kubeletstats:
      auth_type: serviceAccount
      collection_interval: 10s
      endpoint: ${KUBE_NODE_IP}:10250
      insecure_skip_verify: true
      metric_groups:
      - node
      - container
      - pod
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
        thrift_compact:
          endpoint: 0.0.0.0:6831
    #otlp:
    #   protocols:
    #   grpc:
    #     endpoint: 0.0.0.0:4317
    #    http:
    #      endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${MY_POD_IP}:8888
          - job_name: apps
            kubernetes_sd_configs:
            - role: pod
              selectors:
              - field: spec.nodeName=$KUBE_NODE_NAME
                role: pod
            relabel_configs:
            - action: keep
              regex: "true"
              source_labels:
              - __meta_kubernetes_pod_ready
            scrape_interval: 10s
    zipkin:
      endpoint: 0.0.0.0:9411
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs:
        exporters:
          - loki
        processors:
          - memory_limiter
          - batch
        receivers:
          - filelog
          - otlp
      metrics:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - otlphttp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp

image:
  # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  #"0.47.0"
imagePullSecrets: []

# OpenTelemetry Collector executable
command:
  name: otelcol-contrib
  extraArgs: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

clusterRole:
  # Specifies whether a clusterRole should be created
  create: true
  # Annotations to add to the clusterRole
  annotations: {}
  # The name of the clusterRole to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # A set of rules as documented here : https://kubernetes.io/docs/reference/access-authn-authz/rbac/
  rules:
   - apiGroups:
     - ''
     resources:
     - 'pods'
     - 'nodes'
     verbs:
     - 'get'
     - 'list'
     - 'watch'

  clusterRoleBinding:
    # Annotations to add to the clusterRoleBinding
    annotations: {}
    # The name of the clusterRoleBinding to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}

# Allows for pod scheduler prioritisation
priorityClassName: ""

extraEnvs: []
extraVolumes: []
extraVolumeMounts: []

# Configuration for ports
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-compact:
    enabled: true
    containerPort: 6831
    servicePort: 6831
    hostPort: 6831
    protocol: UDP
  jaeger-thrift:
    enabled: true
    containerPort: 14268
    servicePort: 14268
    hostPort: 14268
    protocol: TCP
  jaeger-grpc:
    enabled: true
    containerPort: 14250
    servicePort: 14250
    hostPort: 14250
    protocol: TCP
  zipkin:
    enabled: true
    containerPort: 9411
    servicePort: 9411
    hostPort: 9411
    protocol: TCP
  metrics:
    # The metrics port is disabled by default. However you need to enable the port
    # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

# Resource limits & requests. Update according to your own use case as these values might be too low for a typical deployment.
resources:
  limits:
    cpu: 256m
    memory: 512Mi

podAnnotations: {}

podLabels: {}

# Host networking requested for this pod. Use the host's network namespace.
hostNetwork: false

# Pod DNS policy ClusterFirst, ClusterFirstWithHostNet, None, Default, None
dnsPolicy: ""

# only used with deployment mode
replicaCount: 1

annotations: {}

# List of init container specs, e.g. for copying a binary to be executed as a lifecycle hook.
initContainers: []
# initContainers:
#   - name: test
#     command:
#       - cp
#     args:
#       - /bin/sleep
#       - /test/sleep
#     image: busybox:latest
#     volumeMounts:
#       - name: test
#         mountPath: /test

# Pod lifecycle policies.
lifecycleHooks: {}
# lifecycleHooks:
#   preStop:
#     exec:
#       command:
#       - /test/sleep
#       - "5"

service:
  type: ClusterIP
  annotations: {}

ingress:
  enabled: false
  # annotations: {}
  # ingressClassName: nginx
  # hosts:
  #   - host: collector.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  #         port: 4318
  # tls:
  #   - secretName: collector-tls
  #     hosts:
  #       - collector.example.com

  # Additional ingresses - only created if ingress.enabled is true
  # Useful for when differently annotated ingress services are required
  # Each additional ingress needs key "name" set to something unique
  additionalIngresses: []
  # - name: cloudwatch
  #   ingressClassName: nginx
  #   annotations: {}
  #   hosts:
  #     - host: collector.example.com
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #           port: 4318
  #   tls:
  #     - secretName: collector-tls
  #       hosts:
  #         - collector.example.com

podMonitor:
  # The pod monitor by default scrapes the metrics port.
  # The metrics port needs to be enabled as well.
  enabled: false
  metricsEndpoints:
  - port: metrics
    # interval: 15s

  # additional labels for the PodMonitor
  extraLabels: {}
  #   release: kube-prometheus-stack

serviceMonitor:
  # The service monitor by default scrapes the metrics port.
  # The metrics port needs to be enabled as well.
  enabled: false
  metricsEndpoints:
  - port: metrics
    # interval: 15s

  # additional labels for the ServiceMonitor
  extraLabels: {}
  #  release: kube-prometheus-stack

# PodDisruptionBudget is used only if deployment enabled
podDisruptionBudget:
  enabled: false
#   minAvailable: 2
#   maxUnavailable: 1

# autoscaling is used only if deployment enabled
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

rollout:
  rollingUpdate: {}
    # When 'mode: daemonset', maxSurge cannot be used when hostPort is set for any of the ports
    # maxSurge: 25%
    # maxUnavailable: 0
  strategy: RollingUpdate

prometheusRule:
  enabled: false
  groups: []
  # Create default rules for monitoring the collector
  defaultRules:
    enabled: false

  # additional labels for the PrometheusRule
  extraLabels: {}

statefulset:
  # volumeClaimTemplates for a statefulset
  volumeClaimTemplates: []
  podManagementPolicy: "Parallel"
`

**Comment by akalita-conga** [comment]
@pavolloffay 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/111333290/215009051-a0beeaec-df51-4ccc-9e1c-928c22d3de08.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/111333290/215009164-467291d5-2eba-41cd-8c08-c491c7070b4c.png">
<img width="242" alt="image" src="https://user-images.githubusercontent.com/111333290/215009244-dc32dad0-7e4a-4881-b247-df877d0fa9ec.png">

**Comment by Aneurysm9** [comment]
> @Aneurysm9 Yes, I am using private CA.

The private CA certs aren't going to be in the system chain.  You'll need to [configure](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/configtls) the exporter with the correct cert chain.

**Comment by akalita-conga** [comment]
> > @Aneurysm9 Yes, I am using private CA.
> 
> The private CA certs aren't going to be in the system chain. You'll need to [configure](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/configtls) the exporter with the correct cert chain.

Hi that worked for me. Though some error in Agent collector.
Thank you so Much @Aneurysm9 @pavolloffay for your help.

**Comment by frzifus** [comment]
I will close the issue then. Feel free to re-open :)
