### ISSUE TITLE
target allocator concurrent map read write

### ISSUE THREAD

**Issue by seankhliao** [open-telemetry/opentelemetry-operator#1405]
running on commit 6814271a01588fac2df297bcd00b9c555fab252f

I've seen the allocator crash on concurrent map read/writes

log (and unrelated patch) in gist: https://gist.github.com/seankhliao/f34fdcba460fdf20272b12af4adee4a2

**Comment by pavolloffay** [comment]
@seankhliao would you like to submit a patch with a test :)

**Comment by matej-g** [comment]
Hey @seankhliao this looks like a duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/1359, soon enough there should be a fix I'm working on (related PR and discussion: https://github.com/open-telemetry/opentelemetry-operator/pull/1360)

**Comment by seankhliao** [comment]
oh yep, looks like it
not sure why I didn't see that
