### ISSUE TITLE
[target-allocator] With `prometheusCR` enabled, removal of service- or podmonitors is not correctly reflected in the scrape configs handler

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-operator#1415]
When a service- or podmonitor is deleted, this is not being picked up by the target allocator, resulting in an outdated list of job in the `/scrape_configs` handler. The correct list of jobs is present only if target allocator is restarted. Presumably, the reason for this is we are not actually removing entries from the relevant [map](https://github.com/open-telemetry/opentelemetry-operator/blob/6814271a01588fac2df297bcd00b9c555fab252f/cmd/otel-allocator/target/discovery.go#L72) tracking the jobs.

The expectation would be that the jobs corresponding to deleted pod-/servicemonitors are also removed from the scrape configs jobs.

Related discussion: https://cloud-native.slack.com/archives/C033BJ8BASU/p1675110418158939

**Comment by swiatekm-sumo** [comment]
Fixed in #1620
