### ISSUE TITLE
Make sure only a single HPA version is used for a given Kubernetes version

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#1416]
Created from https://github.com/open-telemetry/opentelemetry-operator/pull/1365#pullrequestreview-1277105842 

It seems like the operator can use multiple HPA versions on a single Kubernetes cluster. This  was not intended and it seems nondeterministic. The behavior should be changed to use only a single HPA version on a given Kubernetes cluster.

https://github.com/open-telemetry/opentelemetry-operator/blob/f7aafc50fe0916b359d3070cd3c662002328e24a/tests/e2e/autoscale/00-assert.yaml#L8

cc) @iblancasa

**Comment by iblancasa** [comment]
I just tried and the situation cannot be reproduced anymore. @pavolloffay, could you close the issue?

**Comment by yuriolisa** [comment]
As mentioned by @iblancasa, this issue is no longer reproducible.
