### ISSUE TITLE
[Bug]: otelcol can't get cpu limit and may cause performance issues

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#1456]
### What happened?

See
- https://github.com/open-telemetry/opentelemetry-collector/issues/4459

### Steps to reproduce

Details are in the collector issue

### Expected behavior

detecting the correct amount of cpus

**Comment by yuriolisa** [comment]
@frzifus, can I work on this? Setting the GOMAXPROCS=1 and implementing the round-up rule proposed by @jpkrohling?

**Comment by frzifus** [comment]
@yuriolisa are you still interested in in it? Otherwise i would give it a try. ^^

**Comment by yuriolisa** [comment]
Hi @frzifus, are you working on it? Or can I still get it?

**Comment by jaronoff97** [comment]
@yuriolisa @frzifus would one of you be able to work on this?
