### ISSUE TITLE
statsd-receiver defaults to TCP protocol instead of UDP

### ISSUE THREAD

**Issue by PeterSzegedi** [open-telemetry/opentelemetry-operator#1476]
The statsd-receiver is defaulting to TCP instead of UDP, so the service points on a port which is listening in the pod.
The fix is in progress: https://github.com/open-telemetry/opentelemetry-operator/pull/1433

**Comment by pavolloffay** [comment]
Done in https://github.com/open-telemetry/opentelemetry-operator/pull/1433
