### ISSUE TITLE
Update Kubernetes Registry References

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-operator#1481]
Heya gang - per https://github.com/kubernetes/k8s.io/issues/4780, k8s is migrating its registry. Per [this tracking issue](https://github.com/kubernetes/k8s.io/issues/4780), this repository is impacted.

To remediate this, we need to:
- Update references from [k8s.gcr.io](http://k8s.gcr.io/) to [registry.k8s.io](http://registry.k8s.io/) by April 3rd to remain current.

Once that's done, would probably be good to comment on the tracking issue that it's taken care of. Thanks!

**Comment by pavolloffay** [comment]
Done
