### ISSUE TITLE
Nodejs version mismatch in `versions.txt`. 

### ISSUE THREAD

**Issue by bryan-aguilar** [open-telemetry/opentelemetry-operator#1511]
The nodejs [version](https://github.com/open-telemetry/opentelemetry-operator/blob/aadfac81140556f97e90c1e0e41bbd0d56d7ea32/versions.txt#L22) listed here does not match the current version in [package.json](https://github.com/open-telemetry/opentelemetry-operator/blob/aadfac81140556f97e90c1e0e41bbd0d56d7ea32/autoinstrumentation/nodejs/package.json#L18)

Should this be updated? Should there be a check to ensure that this always matches in the publishing step?

**Comment by bryan-aguilar** [comment]
Based on the auto instrumentation workflows I think the only mismatch we could have is python and nodejs. Since these versions values are derived from dependency versions within their package managers. Should some type of operator prelease check be added so that they match? Step 2 of the release instructions https://github.com/open-telemetry/opentelemetry-operator/blob/main/RELEASE.md is to update the file. This seems like it could be prone to human error.

**Comment by bryan-aguilar** [comment]
I'd be willing to contribute some of these checks if the community thinks they would be helpful/useful/needed.

**Comment by pavolloffay** [comment]
obsolete
