### ISSUE TITLE
Allow overriding image repository in the operator

### ISSUE THREAD

**Issue by juan-ramirez-sp** [open-telemetry/opentelemetry-operator#1554]
Today the operator assumes the repository for the default images is "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector".

I suggest we change the code here, 

https://github.com/open-telemetry/opentelemetry-operator/blob/73d023b37a73c88fca91d2cf7dd65f3ba0e061b7/main.go#L104

We should add a flag to override the repository

	pflag.StringVar(&imageRepo, "image-repo", "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector", "The default OpenTelemetry collector image repo.")
	
Then we can use this variable for all image references

**Comment by jaronoff97** [comment]
I'm not sure i understand the use case here. You are able to override the image for use [here](https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/opentelemetrycollector_types.go#L117-L119) you are able to override the image run for everything by the operator. Let me know if this doesn't solve your use case.

**Comment by jaronoff97** [comment]
I think my hesitation is that this would probably involve changing how we set all of the images for the operator by having them extend from a base repo which would then break anyone who is using multiple repos. i.e.

```
xxx/otel-collector:tag
xxx/otel-operator:tag
yyy/opamp-bridge:tag
...
```

I'm not sure the convenience of allowing to set `xxx` is worth the toil this may potentially cause to those who have multiple base repos. Am I understanding the issue correctly?

**Comment by jaronoff97** [comment]
I'm going to close this for now, please let me know if you'd like to re-open this issue.
