### ISSUE TITLE
No errors logged when failing to reconcile with webhooks disabled

### ISSUE THREAD

**Issue by andrewdinunzio** [open-telemetry/opentelemetry-operator#1569]
We've temporarily disabled webhooks due to #1514 and noticed that if we don't fully specify the OpenTelemetryCollector, then it doesn't create/update the collector `Deployment`. At the same time, the opentelemetry operator doesn't log any errors.

I assume this is because there's some defaulting webhook that isn't being run, and there's some validation failing as a result when it gets reconciled. But it's failing silently. Or maybe it isn't failing but there's some "switch"-like statement that causes it to do nothing because the field isn't set? I haven't had a chance to dig into the code. I guess it's not typical to run without webhooks enabled, but if that's a supported configuration, it would help find problems faster with a bit more logging here.

As soon as I re-enabled the webhooks, it worked fine again. It would be nice to log any errors in the operator that would normally cause a validation failure with the admission webhooks enabled (if it would cause Reconcile to fail).

We disabled the webhooks by setting this in the helm chart:
```yaml
admissionWebhooks:
  create: false
manager:
  env:
    ENABLE_WEBHOOKS: "false"
```

**Comment by pavolloffay** [comment]
Running the operator without webhooks is not supported. 


That said we should definitely add a warning log if the webhook is disabled.

**Comment by pavolloffay** [comment]
See https://github.com/open-telemetry/opentelemetry-operator/pull/1570

**Comment by andrewdinunzio** [comment]
Thank you
