### ISSUE TITLE
Configure pod/service port based on exporter endpoint - for Prometheus exporter

### ISSUE THREAD

**Issue by jangaraj** [open-telemetry/opentelemetry-operator#1609]
Port configuration based on receiver configuration works well. I would expect that port configuration will be based also on exporter configuration. I would like to use pull based approach, instead of push based, so I configured `prometheus` exporter, which is exposed on the endpoint:
```
exporters:
  prometheus:
    endpoint: 0.0.0.0:9999
```
Problem is that operator doesn't include this exporter port into pod/service port configuration automatically. My workaround was to create service manually, but it will be nice to have it in the automatic configuration (as it works for receivers).

Thanks

**Comment by pavolloffay** [comment]
I have changed the title to be more Prometheus specific - I am not sure if the exporter service is a common use case. Correct me if I am wrong.

**Comment by pavolloffay** [comment]
Also did you consider using pod monitors?
