### ISSUE TITLE
Add support for `lifecycle` hooks and `terminationGracePeriodSeconds`

### ISSUE THREAD

**Issue by kristinapathak** [open-telemetry/opentelemetry-operator#1618]
I want to be able to add a `preStop` container lifecycle hook and modify the `terminationGracePeriodSeconds` from its default 30s for my collector pods.  Is this currently possible with the Collector spec? Are people open to me adding this support?

**Comment by kristinapathak** [comment]
Further context:
We want to have a more graceful deployment process by decoupling the shutdown signal sent to the pod and its IP removal from the service.  Ideally, we would like to remove the IP while the pod is still running, wait some time, and then shut down the pod. We are caching the DNS information for a set amount of time, so want to wait for it to expire before shutting down any pods.

This can be done using a `preStop` condition that sleeps for a desired amount of time, but adding sleep time requires a longer grace period, which is why `terminationGracePeriodSeconds` is also needed.

**Comment by avadhut123pisal** [comment]
@pavolloffay / @jaronoff97 I can work on this, if it is still pending.

**Comment by jaronoff97** [comment]
@avadhut123pisal sounds good! Feel free to get started whenever.
