### ISSUE TITLE
Add operator/auto-instrumentation versions as a default resource attribute

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-operator#1621]
Today users can see the instrumentation version that is generating the telemetry for their services, but not necessarily how that instrumentation was put into place. If the owner of a service is not also the manager for the operator, they may not be aware of when the operator managers make changes.  It is possible that a change to the operator may affect their auto-insturmentation injection and therefore their telemetry.

Similar to how SDKs report their name and version, I think it would be useful if the operator included in the auto-instrumentation it injects some information about the operator.  This would allow users to better understand all the components that are involved with the generation of their telemetry.  If there are changes to the operator/instrumentation resource it would be great for those changes to be reflected in the telemetry produced.

I was imaging we could take advantage of the `OTEL_RESOURCE_ATTRIBUTES` env var and inject some extra attributes for the operator version, instrumentation image versions, etc.

**Comment by jaronoff97** [comment]
closed by #1736 i believe!
