### ISSUE TITLE
High and medium severity vulnerabilities detected in opentelemetry-operator image

### ISSUE THREAD

**Issue by szeyit** [open-telemetry/opentelemetry-operator#1636]
I wanted to bring to your attention that a vulnerability scan has detected some high and medium severity vulnerabilities in the opentelemetry-operator image:

**High severity:**
Vulnerability: GHSA-232p-vwff-86mp
Package: github.com/docker/docker
Installed version / Fixed version: 0:v20.10.14+incompatible / 23.0.3

**Medium severity:**
Vulnerability: IN1-GOLANG-GITHUBCOMPROMETHEUSPROMETHEUSWEBUI-174127
Package: github.com/prometheus/prometheus
Installed version / Fixed version: 0:v1.8.2-0.20210621150501-ff58416a0b02 / 2.7.1

Please consider updating the dependencies in the opentelemetry-operator image to address these vulnerabilities. Thank you for your attention to this matter.

**Comment by jaronoff97** [comment]
This issue has already been resolved, we're just waiting on a latest release with #1631, #1630. We're already on a higher version than 2.7.1 ([this](https://github.com/prometheus/prometheus/commit/ff58416a0b02) is our current actual version) Prometheus's versioning system has been messed up many times, which creates false positives like this.
