### ISSUE TITLE
OTEL Collector dynamic pv and pvc provisioning not working to scale statefulset Collector with Custom storage class

### ISSUE THREAD

**Issue by raz08** [open-telemetry/opentelemetry-operator#1639]
Deploying OTEL collector with mode set to "Statefuleset". 

I have kubernetes cluster which does not have "default" storage class. So, I created storage class and provided these details in volumeclaimtemplate section as shown below. But if we have want to scale this it won't work as it try to claim from same pv mentioned. 
``apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  mode: {{ .Values.mode }}
  serviceAccount: {{ include "opentelemetry-collector.serviceAccountName" . }}
  {{- if (eq .Values.mode "statefulset") }}
  volumeMounts:
    - mountPath: "/usr/share/test-volume"
      name: otel-volume
  volumeClaimTemplates:
  - metadata:
      name: otel-volume
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "standard"
      volumeName: pv8
      resources:
        requests:
          storage: 1Gi
  {{- end }}
  resources: {{- .Values.resources | toYaml | nindent 4 }}  
  ports: {{ include "opentelemetry-collector.deploymentPortsConfig" . | nindent 4 }}
  config: |
{{- .Values.config | toYaml | nindent 4}}``

So, in this case if i increase replica to 2 then it will try to use same pv and it get fails because of pv can't claim twice.

Is it something need to be looked at operator side?. To support dynamic provisioning of pv and pvc?

**Comment by jaronoff97** [comment]
I'm not sure what the problem is with the details provided, please open a new issue following our bug template if this is still happening. Thank you!
