### ISSUE TITLE
[feature request] support scale subresource for mode: daemonset

### ISSUE THREAD

**Issue by nazarewk** [open-telemetry/opentelemetry-operator#1667]
Looks like Vertical Pod Autoscaler works only with deployment and statufulset modes, because the operator implements only those two:
https://github.com/open-telemetry/opentelemetry-operator/blob/2d18b7b0d1bae84185471ff15d0d35cfacbfce9f/pkg/collector/reconcile/opentelemetry.go#L58-L70

It would be useful to have the same working for daemonset mode.

Is there any particular reason why it was omitted from #785 ?

field similar to replicas is present in `DaemonSet.status` https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetStatus

resources:
- original implementation #785 
- [slack thread on #sig-autoscaling](https://kubernetes.slack.com/archives/C09R1LV8S/p1681828219669879)

**Comment by yuriolisa** [comment]
I have no objections to implementing it. @jaronoff97, @TylerHelmuth, @pavolloffay WDYT?

**Comment by jaronoff97** [comment]
yeah this would be great to have, not sure why we didn't have it already.

**Comment by TylerHelmuth** [comment]
Let's do it

**Comment by pavolloffay** [comment]
No objections, how does the scaling work with daemonset? Will it schedule additional pods on the missing nodes?

**Comment by KitSutliff** [comment]
Seems like a good idea.  Would be glad to have a go at it.

Just to clarify, we want to set a selector on the daemon set so that the vertical pod autoscaler can scale the collector, correct?  

We could probably handle sidecar with similar logic.  Should we set selectors for that too while we're at it?
