### ISSUE TITLE
Detect and inject the service.version resource attribute

### ISSUE THREAD

**Issue by sermojohn** [open-telemetry/opentelemetry-operator#1670]
The Open Telemetry specification for resource attributes ([link](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service)) contains a set of attributes, such as `service.version` marked as experimental.

This attribute is very useful in debugging and monitoring using telemetry data, because it reveals when deployments of new artifacts are performed and the version of each service is attached to its telemetry data, so comparisons can be performed. This attribute could be manually set for manual instrumentation

Are there any plans for injecting the `service.version` from the operator, for manually or auto-instrumented services?

Side-question: is the operator aware of the service using manual-instrumentation, because I am also interested for this functionality on services of artifacts implemented in go.

**Comment by TylerHelmuth** [comment]
I am surprised the injected instrumentations aren't handling that themselves. But yes, either the instrumentation itself (preferred) or the operator should be supplying that information. 

Tangentially related to https://github.com/open-telemetry/opentelemetry-operator/issues/1621

**Comment by TylerHelmuth** [comment]
The operator can't mess with manual instrumentation, but it can play nicely with it. I believe you can mess with the SDK env vars with the operator tho. 

For Go, see https://github.com/open-telemetry/opentelemetry-operator/pull/1555

**Comment by sermojohn** [comment]
What I would need is to detect the service version from deployment/statefulset `container.image` and inject into the `OTEL_RESOURCE_ATTRIBUTES`. The end result is that each telemetry data (log,trace,metric) will be attached with the version of the container that produced the data.

It seems this might be possible using the [k8sattributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor) when running the collector in agent mode. So, wondering if using this operator and a collector using that processor can support this feature.

**Comment by TylerHelmuth** [comment]
Sorry, I was thinking of the version of the instrumentation. 

For the you application i agree that the k8s processor may be an option. If it is then the operator isn't even needed (unless you want to manage the colllector with the operator). 

Either way, I think it sounds like an interesting feature for the operator.

**Comment by jaronoff97** [comment]
To confirm my understanding of the request: you would like the operator to inject the service.version attribute from the version on the `container.image`? I believe this could be done using the existing instrumentation resource, either via auto-instrumentation or for apps using the `instrumentation.opentelemetry.io/inject-sdk: "true"`. Would the expected behavior be the following?

```
image:v1.2.3 			--> service.version=v1.2.3
image:latest 			--> service.version=latest
image:v0.0.4 			--> service.version=v0.0.4
image:12498yhjfasnkujtoah2n 	--> service.version=12498yhjfasnkujtoah2n
image 				--> ''
```

**Comment by sermojohn** [comment]
@jaronoff97, yes this is the exact behaviour. Thanks a lot, sounds great that its possible and matches the operator scope.

So, in a hypothetical scenario of a Deployment annotated by:
`instrumentation.opentelemetry.io/inject-sdk: "true"`
`instrumentation.opentelemetry.io/container-names: "containerA,containerB"`

the operator would inject OTEL_RESOURCE_ATTRIBUTES=`service.version=...` to each container using the corresponding image tag. 
```
e.g.
containerA -> containerA.image.tag
containerB -> containerB.iamge.tag
```

**Comment by KitSutliff** [comment]
Hello!  

This looks like a fun issue to tackle.  Mind if I take a crack at it?

**Comment by jaronoff97** [comment]
@KitSutliff sure! Let me know if you need any guidance on how to get started with it.
