### ISSUE TITLE
Sidecar mode integrate with normal instrumentation.

### ISSUE THREAD

**Issue by rafaeltovargarrido** [open-telemetry/opentelemetry-operator#1675]
Hello guys, I have the operator setup as sidecar mode https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator#sidecar-mode, and everything is working ok :), I want to use the optl collector like this https://github.com/open-telemetry/opentelemetry-python/blob/main/docs/getting_started/otlpcollector_example.py in my app in k8s my question is what value do I need to put for endpoint="myCollectorURL:4317" since the sidecar will run with my container application? , I don't want to use the auto instrumentation model, wich I know is available for operator and python.

**Comment by jaronoff97** [comment]
With the sidecar enabled on the collector, you should be able to just use `localhost:4317` as the endpoint for your application. If that doesn't work, you may need to use the downward API to access the pod's ip address and do `${KUBE_POD_IP}:4317` as the value. Let me know if that works, thank you!
