### ISSUE TITLE
Support specifying additional containers for OpenTelemetryCollector podspec

### ISSUE THREAD

**Issue by diurnalist** [open-telemetry/opentelemetry-operator#1684]
The primary motivation for this request is to add additional sidecars to the otel-collector pods that are controlled by the operator.

One use-case is for if you want to tell the collector to export to a sidecar that acts as an authenticated proxy (in case the ability to specify static headers in the otel-collector otlp export config is insufficient.) I'm sure there are other use cases that would apply in the future.

The Prometheus operator [has support for a `containers` field in the spec](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.Prometheus), which allows adding or even overriding base container definitions. I'm not sure we have to go as far as that, but having some sort of `additionalContainers` would be nice. For completeness, `initContainers` support may also be helpful for supporting different flavors of deployment environment.

**Comment by initharrington** [comment]
I came here from https://github.com/open-telemetry/opentelemetry-helm-charts/issues/650

I am trying to use file_storage extension and the operator.

I get a permission issue on start up:

```
2023-05-16T14:30:51.451Z	info	extensions/extensions.go:55	Stopping extensions...
2023-05-16T14:30:51.451Z	info	service/service.go:180	Shutdown complete.
Error: cannot start pipelines: open /var/lib/storage/otc/exporter_sumologic__logs: permission denied
2023/05/16 14:30:51 collector server run finished with error: cannot start pipelines: open /var/lib/storage/otc/exporter_sumologic__logs: permission denied
```

I cannot follow the initContainer workaround using the operator.

**Comment by diurnalist** [comment]
#1870 only adds support for init containers, not additional containers that run alongside the main pod container.
