### ISSUE TITLE
[collector] Specify the collector's configuration with structure yaml instead of a string

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-operator#1707]
Currently the only way to define the collector's config in the `OpentlemetryCollector` resource is via a string in the `Spec.Config` field.  Although it works, it can be frustrating to write, especially for complex collector configurations, since indentation is important.  For operator contributors and maintainers working with the string internally is also challenging.

I believe it would be beneficial to allow the config to be expressed as explicit yaml, mirroring the [collector's internal config structure](https://pkg.go.dev/go.opentelemetry.io/collector@v0.76.1/otelcol#Config).  This will allow users a better configuration experience when managing `OpentlemetryCollector` resources and will allow operator contributors and maintainers and typed struct to manipulate internally.

Since changing `Spec.Config` would be a significant breaking change, I propose the following process:

1.  Update the operator's internals to convert the string to a structured representation of the collector config and use the struct for all operations.  This is a non-breaking change to users and prepares us for the next steps.
2. Introduce a new field such as `ConfigSpec` that is a structured representation of the collector config.  If this field is set, use it it for all the operations.  To avoid the need to coalesce, require exactly one of `Config` and `ConfigSpec` to be set.
3. Following the deprecation process, deprecate `Config`.
4. (Optional) Follow a rename process to rename `ConfigSpec` to `Config`.

**Comment by jaronoff97** [comment]
I am a big fan of this idea! I think the scope of it is great as well.

As we discussed during our last SIG meeting, I would like to keep the config spec such that it cannot be layered or separated from the CRD at this time. A few ideas were proposed to create an OpenTelemetryConfig CRD that a collector could pull in, but this brings up a myriad of concerns around discoverability and understanding that worry me. The main question I imagine is someone asking "what configuration is my collector actually running" at which point we would need to shrug and pull together the various layers in just the right order. I believe the onus of reusable collector configuration blocks is on the cluster manager and not on the operator.

**Comment by swiatekm-sumo** [comment]
Sounds like a good plan to me as well.

For the prospective OpenTelemetryConfig CRD, I don't think we need to add it now, but we should think about it while we're here. The way I imagined it, is that we'd keep the ability to specify the config directly in the Collector CR, but create a Config CR in the background to represent it, and also have an "effective config" computed field on the Collector. This would mostly be transparent for users just wanting the simple case, and would free us to add more complex config resolution logic in the Config CR without disturbing those simpler use cases.

**Comment by jaronoff97** [comment]
@swiatekm-sumo i'd prefer we don't add complex config resolution logic at all – there are already too many ways to configure the collector in kubernetes and I'm not sure i see the value in adding another right now. I'd be happy to be proven / shown wrong though, open to feedback in this area.

**Comment by frzifus** [comment]
I'm not quite sure I understand the outcome of this discussion. But here is my take :snail: 

We can overwrite the [collector's internal config structure](https://pkg.go.dev/go.opentelemetry.io/collector@v0.76.1/otelcol#Config) Unmarshal method and support a native yaml configuration as well as parsing a single string into the same structure. This should be done during the validation process in the webhook.
To avoid rewriting logic on everyplace the current string field is used, we might add a `String()` method that can be used.

The final result should be not noticeable for an end user. But both configs should be valid:
```diff
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
-  config: |
+  config:
    receivers:
      otlp:
        protocols:
          http:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
```

wdyt @TylerHelmuth @swiatekm-sumo @jaronoff97 ?

@iblancasa are you still working on this task? Otherwise, I could submit a PR for it.

**Comment by iblancasa** [comment]
@frzifus I'm working on it.

**Comment by frzifus** [comment]
> I'm not sure about this. Why do we want to convert the struct all the time to string? 

Simply to avoid having to adapt all the functions that are currently based on string representation.
I would recommend doing this in a further step.

> It sounds a little bit like a workaround for me to not fix the unmarshalling/marshalling problem.

What problem do you have in mind?

**Comment by iblancasa** [comment]
> What problem do you have in mind?

Basically what @TylerHelmuth suggested:

> Update the operator's internals to convert the string to a structured representation of the collector config and use the struct for all operations. This is a non-breaking change to users and prepares us for the next steps.

**Comment by frzifus** [comment]
It breaks this step down into two smaller changes.
1. Providing an internal structure that could be used to operate on, but still provides you a string representation if needed. (That way you do not need to touch all the functionality that is build on top. Like the config validation or the mods done for the targetAllocator).
2. Changing it on all the places we benefit from a native yaml representation. (This can result in multiple tasks and way smaller PRs then having all in one)

I have not tested the following lines, but they roughly represent what I was thinking of:
```golang
func MustParseConfigSpec(in string) *ConfigSpec {
	cfg := &ConfigSpec{}
	if err := cfg.UnmarshalJSON([]byte(in)); err != nil {
		panic(fmt.Sprintf("could not parse collector config: %s", err))
	}
	return cfg
}

func ParseConfigSpec(in string) (*ConfigSpec, error) {
	cfg := &ConfigSpec{}
	if err := cfg.UnmarshalJSON([]byte(in)); err != nil {
		return nil, fmt.Errorf("could not parse collector config: %s", err)
	}
	return cfg, nil
}

type ConfigSpec struct {
	original string `json:"-"`
	*otelcol.Config
}

func (c *ConfigSpec) String() string {
	return c.original
}

func (c *ConfigSpec) UnmarshalJSON(data []byte) error {
	c.original = string(data)
	var rawConf map[string]any
	if err := yaml.Unmarshal(data, &rawConf); err != nil {
		return err
	}
	cm := confmap.NewFromStringMap(rawConf)
	cfg := otelcol.Config{}
	if err := component.UnmarshalConfig(cm, &cfg); err != nil {
		return err
	}
	c.Config = &cfg
	return nil
}
```

**Comment by iblancasa** [comment]
I'm not a big fan of using something from a package that is not a library. But, anyway, I spent some time trying your approach and we need to use a lot of objects from the collector in order to unmarshal properly the structure.

I think we need a much simpler approach like the one proposed by @TylerHelmuth. I'll continue with his approach since it is easier to implement and maintain.

**Comment by andreasgerstmayr** [comment]
> I'm not a big fan of using something from a package that is not a library. But, anyway, I spent some time trying your approach and we need to use a lot of objects from the collector in order to unmarshal properly the structure.

I think it makes sense to re-use the https://pkg.go.dev/go.opentelemetry.io/collector@v0.76.1/otelcol#Config data type, otherwise this struct and all nested structs need to be duplicated (and kept in sync) in the operator?

And this way you could run `Validate()` (https://pkg.go.dev/go.opentelemetry.io/collector@v0.76.1/otelcol#Config.Validate) in the webhook.

**Comment by pavolloffay** [comment]
On the last SIG meeting there was agreement to bump CRD API version and in the new version drop the string config and expose only the typed config.

**Comment by frzifus** [comment]
Linking this here: https://github.com/open-telemetry/opentelemetry-operator/pull/2182#pullrequestreview-1651697972

**Comment by jaronoff97** [comment]
This will be a breaking change and will be the primary driver of our milestone

**Comment by justurbo** [comment]
@pavolloffay When will OpenTelemetryCollector be available with opentelemetry.io/v1alpha12?

Using Terraform kubernetes_manifest, operator [official setup](https://opentelemetry.io/docs/kubernetes/operator/automatic/), the kubernetes yaml file fails because spec.config is string.

```
resource "helm_release" "open_telemetry" {
  create_namespace = true
  namespace        = "opentelemetry"
  repository       = "https://open-telemetry.github.io/opentelemetry-helm-charts"
  chart            = "opentelemetry-operator"
  version          = "0.78.2"
  name             = "opentelemetry-operator"
  set {
    name  = "manager.collectorImage.repository"
    value = "otel/opentelemetry-collector-k8s"
  }
  set {
    name  = "admissionWebhooks.certManager.enabled"
    value = false
  }
  set {
    name  = "admissionWebhooks.autoGenerateCert.enabled"
    value = true
  }
}


resource "kubernetes_manifest" "collector" {
  manifest = {
    apiVersion = "opentelemetry.io/v1alpha1"
    kind       = "OpenTelemetryCollector"
    metadata = {
      name      = "custom"
      namespace = helm_release.open_telemetry.namespace
    }
    spec = {
      config = yamldecode(file("${path.module}/configs/open-telemetry-collector.yaml"))
    }
  }
}
```


`configs/open-telemetry-collector.yaml`
```
|
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
```
