### ISSUE TITLE
Switch to official scorecard-test-kuttl image

### ISSUE THREAD

**Issue by andreasgerstmayr** [open-telemetry/opentelemetry-operator#1721]
Switch to `quay.io/operator-framework/scorecard-test-kuttl` image in `config/scorecard/patches/kuttl.config.yaml` and `bundle/tests/scorecard/config.yaml` once https://github.com/operator-framework/operator-sdk/pull/6401 is merged.

Related: #1335

**Comment by jaronoff97** [comment]
I think this was completed by #1498
