### ISSUE TITLE
[instrumentation] Is there any way to capture HTTP request headers when using auto-instrumentation for Node.js?

### ISSUE THREAD

**Issue by xwgao** [open-telemetry/opentelemetry-operator#1760]
Is the environment variables for [capturing HTTP request and response headers](https://opentelemetry.io/docs/instrumentation/python/automatic/example/#capture-http-request-and-response-headers) workable in auto-instrumentation for Node.js? I used nodejs.image: [ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.37.0](http://ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.37.0)  in my instrumentation and added the env var OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST=x-tenant-id, but I can not find the attribute `http.request.header.x-tenant-id`  in my spans.
If these environment variables for [capturing HTTP request and response headers](https://opentelemetry.io/docs/instrumentation/python/automatic/example/#capture-http-request-and-response-headers) is not supported by auto-instrumentation for Node.js, is there any way to capture HTTP request headers when using auto-instrumentation for Node.js? Thanks.

**Comment by xwgao** [comment]
@TylerHelmuth  Yes, I saw OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST in the env vars of the container after instrumentation is injected. Is this env var only applicable to the below technologies in Python?

- Django
- Falcon
- FastAPI
- Pyramid
- Starlette
- Tornado
- WSGI

**Comment by TylerHelmuth** [comment]
Oh I completely missed that the link you provided went to the Python section.  `OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST` is not a OpenTelemetry-Specification-required environment variable, so I believe the OTel Python community decided to add it themselves.  I would not expect it to work with OTel Node.js, but you can open an issue in https://github.com/open-telemetry/opentelemetry-js asking for it.  It looks like OTel Java supports it as well.
