### ISSUE TITLE
No trace generated for DotNet 6 Web API app, while same way NodeJS working fine

### ISSUE THREAD

**Issue by ajmal-yazdani** [open-telemetry/opentelemetry-operator#1772]
I have installed the operator and I played with NodeJs Web API app and everything works perfectly.

Now same I am trying to do for my DotNet 6 Web API application with below instrumentation and deployment configuration and nothing is working, I don't see any trace.

I tried with both port 4317 & 4318. No luck. 

Anyone having some sample or how to make it work. Please help.

I am using 
**ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.77.0**

**instrumentation.yml**

apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
  namespace: application
spec:
  exporter:
    **endpoint: http://otel-collector-collector.opentelemetry.svc.cluster.local:4318**
  propagators:
    - jaeger
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"

**deployment.yml**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-aks
  namespace: application
  labels:
    app: application
    component: hello-aks
spec:
  selector:
    matchLabels:
      app: application
      component: hello-aks
  replicas: 1
  template:
    metadata:
      annotations:
        **instrumentation.opentelemetry.io/inject-dotnet: "true"**
      labels:
        app: application
        component: hello-aks
    spec:
      containers:
        - name: hello-aks
          ports:
            - containerPort: 80
          image: ajmaly/dotnetapp:v3
          resources:
            limits:
              memory: 128Mi
              cpu: 500m

**Note: I can see the dotnet initContainer in deployment along with the injected environment variables like below:**

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/1866370/0ef5daa1-8512-4835-a0e1-1751c0103379)

CORECLR_ENABLE_PROFILING : 1
CORECLR_PROFILER : {918728DD-259F-4A6A-AC2B-B85E1B658318}
CORECLR_PROFILER_PATH : /otel-auto-instrumentation/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so
DOTNET_ADDITIONAL_DEPS : /otel-auto-instrumentation/AdditionalDeps
DOTNET_SHARED_STORE : /otel-auto-instrumentation/store
DOTNET_STARTUP_HOOKS : /otel-auto-instrumentation/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll
OTEL_DOTNET_AUTO_HOME : /otel-auto-instrumentation
**OTEL_EXPORTER_OTLP_ENDPOINT : http://otel-collector-collector.opentelemetry.svc.cluster.local:4318**
OTEL_PROPAGATORS : jaeger,b3
OTEL_RESOURCE_ATTRIBUTES : k8s.container.name=hello-aks,k8s.deployment.name=hello-aks,k8s.namespace.name=application,k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),k8s.replicaset.name=hello-aks-69d9d9b6c9
OTEL_RESOURCE_ATTRIBUTES_NODE_NAME : fieldRef(v1:spec.nodeName)
OTEL_RESOURCE_ATTRIBUTES_POD_NAME : fieldRef(v1:metadata.name)
OTEL_SERVICE_NAME : hello-aks
OTEL_TRACES_SAMPLER : parentbased_traceidratio
OTEL_TRACES_SAMPLER_ARG : 1

**Operator logs suggestion something missing port number:**

2023-05-31T16:21:22.300282030Z {"level":"info","ts":"2023-05-31T16:21:22.300176629Z","logger":"instrumentation-resource","msg":"validate update","name":"dotnet-instrumentation"}
2023-05-31T16:21:22.316794866Z {"level":"info","ts":"2023-05-31T16:21:22.316598264Z","logger":"controllers.OpenTelemetryCollector","msg":"truncating container port name","opentelemetrycollector":"opentelemetry/otel-collector","port.name.prev":"otlp-http-legacy","port.name.new":"otlp-http-legac"}
2023-05-31T16:21:22.316811566Z {"level":"info","ts":"2023-05-31T16:21:22.316635465Z","logger":"controllers.OpenTelemetryCollector","msg":"couldn't determine metrics port from configuration, using 8888 default value","opentelemetrycollector":"opentelemetry/otel-collector","error":"missing port in address"}

**Comment by ajmal-yazdani** [comment]
@TylerHelmuth,

Thanks for your response. I tried my best to put all the information, I am using **opentelemetry-operator:0.77.0**.

Exact same settings works for NodeJS app where I am using port (**4317**) for otel endpoint: http://otel-collector-collector.opentelemetry.svc.cluster.local:4317.

But for DotNet 6 apps neither with port 4317 works nor 4318 (as suggested in documentation ).

I don't see any sample anywhere as well. Could you please help here?

**Comment by TylerHelmuth** [comment]
This documentation is good: https://opentelemetry.io/docs/k8s-operator/automatic/#net.

Does your application log any errors?  Can you add the loggingexporter to the collector and ensure data is not reaching the collector?

@open-telemetry/dotnet-instrumentation-approvers I believe the operator is injecting the dotnet instrumentation correctly.  Do you see anything wrong with the resulting environment variables?

**Comment by pellared** [comment]
> https://github.com/orgs/open-telemetry/teams/dotnet-instrumentation-approvers I believe the operator is injecting the dotnet instrumentation correctly. Do you see anything wrong with the resulting environment variables?

.NET auto-instrumentation does not support `jeager` value for `OTEL_PROPAGATOR`.
See: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.6.0/docs/config.md#propagators
For `0.6.0` version it crashes the application (fail-fast): https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.6.0/src/OpenTelemetry.AutoInstrumentation/Configurations/SdkSettings.cs#L55

Side-note: For `0.7.0` it would not crash, but log instead: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.7.0/src/OpenTelemetry.AutoInstrumentation/Configurations/SdkSettings.cs#L68

**Comment by pellared** [comment]
It may be another issue. It is possible that `ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.77.0` already uses `0.7.0` of .NET auto-instrumentation. See: https://github.com/open-telemetry/opentelemetry-operator/blob/main/CHANGELOG.md#0761

**Comment by ajmal-yazdani** [comment]
> .NET auto-instrumentation does not support `jeager` value for `OTEL_PROPAGATOR`

@pellared : then what's the solution for .NET 6 apps. I have Elastic option as well to push app metrices, what  `OTEL_PROPAGATOR` I should use?

**Comment by TylerHelmuth** [comment]
@ajmal-yazdani the jaeger propagator is only needed if you app would receive communications for another app that is creating jaeger traces.  For our troubleshooting, let's not set any propagators:

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
  namespace: application
spec:
  exporter:
    endpoint: http://otel-collector-collector.opentelemetry.svc.cluster.local:4318/
```

**Comment by ajmal-yazdani** [comment]
**@TylerHelmuth. Thanks, I tried this, but same, no trace.

One thing I noticed with NodeJs app, it's continuously capturing all the trace info for the `otel-collector` like below:**

2023-06-02T02:58:10.015878987Z 2023-06-02T02:58:10.015Z info    jaegerexporter@v0.77.0/exporter.go:184  State of the connection with the Jaeger Collector backend      {"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "READY"}
2023-06-02T03:02:31.165501561Z 2023-06-02T03:02:31.165Z info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "logging", "resource spans": 1, "spans": 512}
2023-06-02T03:02:36.177899251Z 2023-06-02T03:02:36.177Z info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "logging", "resource spans": 1, "spans": 222}
2023-06-02T03:03:46.939707524Z 2023-06-02T03:03:46.939Z info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "logging", "resource spans": 1, "spans": 7}

**but for .Net 6, it's always is ready state and nothing logging:**

2023-06-02T03:10:16.994395995Z 2023-06-02T03:10:16.994Z info    jaegerexporter@v0.77.0/exporter.go:184  State of the connection with the Jaeger Collector backend      {"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "READY"}

**Comment by TylerHelmuth** [comment]
@ajmal-yazdani to rule out the operator as the cause, can you manually add the dotnet autoisntrumentation to your pod following these docs: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/v0.7.0/docs

**Comment by ajmal-yazdani** [comment]
> @ajmal-yazdani to rule out the operator as the cause, can you manually add the dotnet autoisntrumentation to your pod following these docs: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/v0.7.0/docs

@TylerHelmuth : this works :)

I made below change in docker file:

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/1866370/cff6a088-d5f6-46fd-8894-e0dc8a0bf356)

and inject environment variable in deployment like this:

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/1866370/f6f7b69e-8da2-491b-b615-fb79a0b81149)

Then something wrong with `auto-Instrumentation` only:
![image](https://github.com/open-telemetry/opentelemetry-operator/assets/1866370/3be1362e-4fc9-49c1-8e81-c04275578bc8)
