### ISSUE TITLE
How to resolve conflicts between Boto3 in opentelemetry auto-instrument and Kubernetes applications?

### ISSUE THREAD

**Issue by luongdangvp2000** [open-telemetry/opentelemetry-operator#1774]
**Sumary**
- I installed OpenTelemetry Operator and OpenTelemetry Collector by helm to implement auto-instrument application which deployed on Kubernetes. But after upgrade, the status of application pod is "crashloopback".

**Describe your environment** 
- Version of OpenTelemetry Operator helm chart: 0.76.1
- Version of OpenTelemetry Collector helm chart: 0.77.0
- The requirement.txt file of application which deployed on Kubernetes

```
fastapi[all]==0.88.0 
aiofiles==22.1.0
loguru==0.6.0
tritonclient[all]==2.28.0
python-decouple==3.6
pymongo==4.3.3
opencv-python==4.6.0.66
Pillow==9.3.0
pandas==1.5.2
pyarrow==10.0.1
dask==2022.12.1
boto3==1.26.49
typeguard==2.13.3
scikit-image==0.19.3
s3fs==0.4.2
rocketry==2.5.1
requests==2.25.1
```

**Steps to reproduce**
- Install OpenTelemetry Operator helm chart
- Install OpenTelemetry Collector helm chart
- Create and apply instrument file:

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  resource:
    addK8sUIDAttributes: true
  exporter:
    endpoint: http://opentelemetry-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    env:
      - name: OTEL_LOG_LEVEL
        value: "debug"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://opentelemetry-collector:4318
```
- Add annotations in application yaml file and upgrade:

```
annotations:
  instrumentation.opentelemetry.io/inject-python: "instrumentation"
```

**What happen?**
But after upgraded application, the status is "CrashLoopBack". I logged that application:
```
Instrumenting of boto3 failed
Traceback (most recent call last):
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py", line 84, in _load_instrumentors
    distro.load_instrumentor(entry_point, skip_dep_check=True)
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/distro.py", line 62, in load_instrumentor
    instrumentor: BaseInstrumentor = entry_point.load()
  File "/otel-auto-instrumentation/pkg_resources/__init__.py", line 2517, in load
    return self.resolve()
  File "/otel-auto-instrumentation/pkg_resources/__init__.py", line 2523, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/otel-auto-instrumentation/opentelemetry/instrumentation/boto3sqs/__init__.py", line 34, in <module>
    import boto3
  File "/usr/local/lib/python3.8/dist-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.8/dist-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.8/dist-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/usr/local/lib/python3.8/dist-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/local/lib/python3.8/dist-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/local/lib/python3.8/dist-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/usr/local/lib/python3.8/dist-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/local/lib/python3.8/dist-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/local/lib/python3.8/dist-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/local/lib/python3.8/dist-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.8/dist-packages/botocore/httpsession.py", line 22, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/otel-auto-instrumentation/urllib3/util/ssl_.py)
Failed to auto initialize opentelemetry
```

**Additional context**
After consider problems, I see boto3 in opentelemetry auto-instrument conflicts to boto3 in my applications. How to fix it??

**Comment by TylerHelmuth** [comment]
I am curious if https://github.com/open-telemetry/opentelemetry-operator/pull/1763 is gonna fix your issue in the next release, but also it is strange that you are experiencing this issue between `0.76.1` and `0.77.0` as none of the python dependencies changed between those operator releases.

Have you recently changed your `boto3` version or did only the operator version change?  Does instrumentation work as expected if you roll back to `0.76.1`?

**Comment by luongdangvp2000** [comment]
I haven't changed my boto3 version because I just received the project recently. `Does instrumentation work as expected if you roll back to 0.76.1?` You mean change version of opentelemetry collector chart from 0.77.0 to 0.76.1, right?
Actually, I checked version of boto3 which auto-instrument using is `boto3 ~= 1.0`. That means my project using version `1.26.49` is ok. But when I saw logging: `Instrumenting of boto3 failed`, I just thought it was conflict version of boto3.

**Comment by luongdangvp2000** [comment]
Is OpenTelemetry Collector chart difference from Collector CRD? I read some blogs but they all use Collector CRD. This make me think about OpenTelemetry Collector's function on Kubernetes.

**Comment by luongdangvp2000** [comment]
Sorry for replying late.
Thank u so much, informations you provided help me understand more about this bug. I think I should try Collector CRD.

**Comment by luongdangvp2000** [comment]
Ah, I have deployed Collector CRD instead of OpenTelemetry Collector helm chart. I have deployed 2 Collector CRD: Collector agent (mode: sidecar) and Collector gateway (mode: deployment). Then I have added annotations to application yaml file and upgrade: 
```
annotations:
  instrumentation.opentelemetry.io/inject-python: "instrumentation"
  sidecar.opentelemetry.io/inject: 'otel-sidecar'
```
Surprisingly, the "otel-sidecar" is running. But the "instrumentation" still "crashLoopBack" like above. So I decide to just use the "otel-sidecar". 
This is the blog I have followed: https://www.aspecto.io/blog/opentelemetry-operator/

**Comment by luongdangvp2000** [comment]
Is it possible if I manual-instrument my application, containerize and deploy it on k8s?

**Comment by TylerHelmuth** [comment]
You could do the work that the operator does to inject auto-instrumentation and provide auto-instrumentation "manually" by adding the appropriate initContainers and env vars.  You could also go the next step and manually instrument your code using the Python.

With Operator 0.78.0 released I am curious if the new python image solves this problem.  Can you re-test with the 0.78.0 version of the OTel Operator?

**Comment by luongdangvp2000** [comment]
I re-test with the 0.78.0 and still see that auto-instrument bug. I think I should use manual-instrument in this case.

**Comment by TylerHelmuth** [comment]
@srikanthccv any ideas?

**Comment by srikanthccv** [comment]
I think this is an issue with the conflict dependencies but not really related to k8s/operator. Did you try using auto-instrumentation in dev or outside k8s env? `urllib3` 2.0.0 removed the `DEFAULT_CIPHERS` and several other symbols. However, the installed `boto3=1.26.49` requires a lower version.  @luongdangvp2000 You could also try pinning the urllib3<2.

**Comment by luongdangvp2000** [comment]
I see the problems. I didn't try using auto-instrumentation this app outside k8s env. I will try it on our server.
In my k8s env, I add `pip install 'urllib3<2'` in _args_ of yaml file and upgrade my pod:
```
containers:
  ...
  args: ["cd /vss-controller && pip install 'urllib3<2' && python3 vss_controller/main.py"]
```
After upgrade, I logs my app:
```
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/otel-auto-instrumentation/urllib3/util/ssl_.py)
WARNING: Ignoring invalid distribution -sspec (/usr/local/lib/python3.8/dist-packages)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f196e315640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/urllib3/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f196e3158e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/urllib3/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f196e300670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/urllib3/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f196e300c40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/urllib3/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f196e300a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/urllib3/
ERROR: Could not find a version that satisfies the requirement urllib3<2 (from versions: none)
ERROR: No matching distribution found for urllib3<2
WARNING: Ignoring invalid distribution -sspec (/usr/local/lib/python3.8/dist-packages)
WARNING: There was an error checking the latest version of pip.
ERROR: Failed to export batch code: 404, reason: 404 page not found
```

**Comment by luongdangvp2000** [comment]
This root cause is my app using `boto3=1.26.49`, so I think I can see the same issue with manual-instrument? Can I use another library to instrument? Should I re-implement my app with new version of boto3?

**Comment by srikanthccv** [comment]
>This root cause is my app using boto3=1.26.49, so I think I can see the same issue with manual-instrument?

Yes, you will still run into issues regardless of the env you run.

>Can I use another library to instrument?

I don't think there is another library as such.

>Should I re-implement my app with new version of boto3?

I think if you get your dependencies sorted out you should be able to make it work in any environment.

**Comment by luongdangvp2000** [comment]
After re-implment and update version of boto3, botocore in my app: `boto3==1.26.142`, `botocore==1.29.142`. This bug has been solved.

**Comment by pl4nty** [comment]
I'm seeing this issue on a third-party application with `0.39b0` and can resolve it by rolling back to an older instrumentation image. Can this be done with pod-level annotations, rather than creating a separate `Instrumentation`?
