### ISSUE TITLE
Example CRD leads to error in collector pod: "unknown processors type 'queued_retry'"

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-operator#18]
I ran the default CRD as shown in the main readme:

```
$ kubectl apply -f - <<EOF
> apiVersion: opentelemetry.io/v1alpha1
> kind: OpenTelemetryCollector
> metadata:
>   name: simplest
> spec:
>   config: |
>     receivers:
>       jaeger:
> 
>     processors:
>       queued_retry:
> 
>     exporters:
>       logging:
> 
>     service:
>       pipelines:
>         traces:
>           receivers: [jaeger]
>           processors: [queued_retry]
>           exporters: [logging]
> EOF
opentelemetrycollector.opentelemetry.io/simplest created
```

and once the pod was available it entered a CrashloopBackoff state, with the following logs:

```
$ kubectl logs pod/simplest-collector-c7d4768f7-np882
{"level":"info","ts":1586977441.512723,"caller":"service/service.go:265","msg":"Starting...","NumCPU":4}
{"level":"info","ts":1586977441.512775,"caller":"service/service.go:104","msg":"Setting up own telemetry..."}
{"level":"info","ts":1586977441.512987,"caller":"service/telemetry.go:93","msg":"Serving Prometheus metrics","port":8888}
{"level":"info","ts":1586977441.513012,"caller":"service/service.go:137","msg":"Loading configuration..."}
2020/04/15 19:04:01 Cannot load configuration: unknown processor type "queued_retry"
```

I tried removing the processor from the config (because they are optional according to the [collector docs](https://opentelemetry.io/docs/collector/configuration/), which then led to this error:

```
$ kubectl logs pod/simplest-collector-c7d4768f7-np882
{"level":"info","ts":1586977563.5065687,"caller":"service/service.go:265","msg":"Starting...","NumCPU":4}
{"level":"info","ts":1586977563.5066233,"caller":"service/service.go:104","msg":"Setting up own telemetry..."}
{"level":"info","ts":1586977563.5068412,"caller":"service/telemetry.go:93","msg":"Serving Prometheus metrics","port":8888}
{"level":"info","ts":1586977563.5068662,"caller":"service/service.go:137","msg":"Loading configuration..."}
2020/04/15 19:06:03 Cannot load configuration: must have at least one pipeline
```

Which is odd because there is a pipeline configured:

```
$ kubectl get -o yaml otelcols/simplest
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"opentelemetry.io/v1alpha1","kind":"OpenTelemetryCollector","metadata":{"annotations":{},"name":"simplest","namespace":"otel-collector"},"spec":{"config":"receivers:\n  jaeger:\n\nprocessors:\n  queued_retry:\n\nexporters:\n  logging:\n\nservice:\n  pipelines:\n    traces:\n      receivers: [jaeger]\n      processors: [queued_retry]\n      exporters: [logging]\n"}}
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-04-15T19:03:10Z"
  generation: 2
  name: simplest
  namespace: otel-collector
  resourceVersion: "29709"
  selfLink: /apis/opentelemetry.io/v1alpha1/namespaces/otel-collector/opentelemetrycollectors/simplest
  uid: fc1d64fa-8ee0-40e9-a687-7e83272fb409
spec:
  config: |
    receivers:
      jaeger:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [queued_retry]
          exporters: [logging]
status:
  replicas: 0
  version: 0.0.2
```

Version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-alpha.1.527+5668dbdc6e60f5", GitCommit:"5668dbdc6e60f54d45f2022fddf8a92359cdcac5", GitTreeState:"clean", BuildDate:"2020-04-13T18:28:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-rc.1", GitCommit:"4d0922f", GitTreeState:"clean", BuildDate:"2020-04-13T22:15:34Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by damemi** [comment]
Update: I removed the `queued_retry` processor from the otelcol spec, but still see the "must have at least one pipeline" error

**Comment by damemi** [comment]
Update2: I fixed this by setting `image: quay.io/opentelemetry/opentelemetry-collector:v0.2.0` in the `otelcols/simplest` CRD.

Would it be reasonable to update the default image version the operator uses to `v0.2.0`, or add this `image` field to the example CRD?

**Comment by bhiravabhatla** [comment]
I see this still happening, latest tag failing with same error.

```
2021-02-28T11:53:38.201Z	info	service/service.go:292	Loading configuration...
Error: cannot load configuration: unknown processors type "queued_retry" for queued_retry
2021/02/28 11:53:38 application run finished with error: cannot load configuration: unknown processors type "queued_retry" for queued_retry
```

**Comment by jpkrohling** [comment]
@bhiravabhatla would you like to submit a PR? This processor has been removed, the solution is to just remove this processor from the examples.

**Comment by bhiravabhatla** [comment]
Will do @jpkrohling. I also found couple more small issues. 

1) If we apply the manifest for CR in the documentation(https://github.com/open-telemetry/opentelemetry-operator#deployment-modes) - Controller is not creating a deployment by default. I had to mention, `spec.mode=Deployment`

I see code also has check for the same while creating deployment -
```
if params.Instance.Spec.Mode == "deployment" {
		desired = append(desired, collector.Deployment(params.Config, params.Log, params.Instance))
	}
```

Is this expected?


2) The CRDs created by controller-gen have apiVersion set to `apiextensions.k8s.io/v1beta1` which give out deprecated warnings when deployed.

`Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

We could configure CRD_OPTIONS to generate v1 apiVersion instead (https://book.kubebuilder.io/reference/controller-gen.html#generators)


```
CRD_OPTIONS ?= "crd:trivialVersions=true,preserveUnknownFields=false,crdVersions={v1}"

```

Let me know, if you want to raise separate issues for these

**Comment by jpkrohling** [comment]
> Controller is not creating a deployment by default. I had to mention, spec.mode=Deployment

Is this during the development, or when the controller is installed following the instructions? The default value is set via a webhook: https://github.com/open-telemetry/opentelemetry-operator/blob/ea579e0d1f8fd2308d7af6d6d04615ea77be1f05/api/v1alpha1/opentelemetrycollector_webhook.go#L37-L51

> The CRDs created by controller-gen have apiVersion set to apiextensions.k8s.io/v1beta1 which give out deprecated warnings when deployed.

I think there's another issue recorded for this, feel free to send a PR for that as well!

**Comment by bhiravabhatla** [comment]
>Is this during the development, or when the controller is installed following the instructions? The default value is set via a webhook:
@jpkrohling  That makes sense. It was during local development. Does it makes sense to add some kind of documentation to clarify this. 

Also in kubebuilder we can add default values using kubebuilder tags (https://book.kubebuilder.io/reference/markers/crd-validation.html#crd-validation), not sure if its possible using operator-sdk. If its possible, is not it cleaner to use it instead of webhook dependency?

**Comment by jpkrohling** [comment]
> Does it makes sense to add some kind of documentation to clarify this.

Sure, it should be part of the contributing guidelines.

> Also in kubebuilder we can add default values using kubebuilder tags (https://book.kubebuilder.io/reference/markers/crd-validation.html#crd-validation), not sure if its possible using operator-sdk. If its possible, is not it cleaner to use it instead of webhook dependency?

Is this new? I would also prefer to use a default there instead of the webhook. The webhook is still useful for other use cases that we might not have implemented yet. Like: when option X is set, the default value for Y should be Z, otherwise, it should be W.

**Comment by bhiravabhatla** [comment]
>Is this new? I would also prefer to use a default there instead of the webhook. 

I think so. Reference - https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting

controller-tools reference -
https://github.com/kubernetes-sigs/controller-tools/issues/250

**Comment by jpkrohling** [comment]
I believe this one has been fixed already.
