### ISSUE TITLE
Please follow the opentelemetry community rules for approvers and maintainers

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-operator#181]
1. Please provide the list of maintainers and approvers in the README.md
2. Consider to remove anyone who is not a member of the opentelemetry org from the maintainers and approvers (https://github.com/objectiser). Alternative apply for org member status.
3. Ask a TC member to create approver/maintainers teams and set the right permissions. Right now 3 people individually have admin rights

/cc @open-telemetry/technical-committee for visibility. I think this is an urgent issue to be resolved.

**Comment by jpkrohling** [comment]
I just removed @objectiser and @pavolloffay. 

@open-telemetry/technical-committee, would one of you please create the following roles?

- approver (@ open-telemetry/collector-approvers)
- maintainer (@jpkrohling, @ open-telemetry/collector-maintainers)

For context: when I suggested this repository, I suggested a SIG Kubernetes to be created to manage this here. While some people thought it would be a good idea, there were no volunteers besides me, and a SIG of one person didn't sound that smart at the time. Given that both @objectiser and @pavolloffay (at the time) were both active in other operators, such as Jaeger's, it sounded like a good idea to have them as backup maintainers, able to merge stuff when I'm not available.

That said, I then propose to add the whole set of collector maintainers as maintainers of this one here too. Hopefully someone will  jump in when I'm not available.

**Comment by arminru** [comment]
@jpkrohling @open-telemetry/technical-committee I added both groups:
https://github.com/orgs/open-telemetry/teams/operator-approvers
https://github.com/orgs/open-telemetry/teams/operator-maintainers

Currently they're set up as:

* collector-approvers
  * collector-maintainers <- Juraci
* collector-triagers
  * collector-approvers
    * collector-maintainers

I don't think we can just put them in a parent/child relationship with the collector teams as suggested, however. This would produce an odd hierarchy:

* collector-triagers
  * operator-approvers
    * collector-approvers
      * operator-maintainers <- Juraci
        * collector-maintainers

By adding someone as an operator-maintainer, we would also make them a collector-approver and operator-approvers also collector-triagers.
I think we'll have to maintain both operator teams manually to keep them in sync with the collector teams, or do you have any better idea?

**Comment by jpkrohling** [comment]
>  I think we'll have to maintain both operator teams manually to keep them in sync with the collector teams, or do you have any better idea?

Sounds good, ideally the lists would evolve independently.

**Comment by bogdandrutu** [comment]
@jpkrohling I made a mistake because the repo was not setup correctly to require PRs, and I created a commit directly on the webpage and default was to merge it directly in the master not to create PR (because branch was not requiring PRs, I fixed that), I am so sorry (my fault).

Can you double check that the last commit is ok, and send a fix or revert if that is not the case.

**Comment by jpkrohling** [comment]
Looks fine, don't worry. Thanks for adding the codeowners!
