### ISSUE TITLE
Skip SSL verification for endpoint using instrumentation CRD

### ISSUE THREAD

**Issue by mabombo** [open-telemetry/opentelemetry-operator#1818]
There is a way to skip ssl verification for an endpoint in Instrumentation crd or directly in java agent configuration?
I have an apm server with self sign certificate and I don't want mount ca cert on all pods.

**Comment by pavolloffay** [comment]
The option is not supported by SDK configuration https://opentelemetry.io/docs/specs/otel/protocol/exporter/. 

please open first the issue in the spec to add a configuration for it, then we can add it to the operator
