### ISSUE TITLE
Allow the collector CRD to specify a list of configmaps to mount

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#1819]
Right now to mount a configmap, a user needs to specify the volumes they want and mount them manually, it would be great if we could just specify a list of configmaps and maybe a desired fs path to mount them. Prometheus operator supplies it like [this](https://github.com/prometheus-operator/prometheus-operator/blob/e13cdad9305110b3a257ed58369cc8e468280528/pkg/apis/monitoring/v1/prometheus_types.go#L218-L222)

**Comment by pavolloffay** [comment]
Is the intention to specify the collector config in the configmap?

**Comment by jaronoff97** [comment]
nope this is more for cert mounting, configurable endpoints, etc. Times when you need to create a volume mount from a configmap or secret

**Comment by yuriolisa** [comment]
Can I take this one?
