### ISSUE TITLE
Apache httpd auto-instrumentation FailedCreate if app probes are configured

### ISSUE THREAD

**Issue by pl4nty** [open-telemetry/opentelemetry-operator#1820]
An initContainer clone of the app container is created, inheriting probes if they exist.
https://github.com/open-telemetry/opentelemetry-operator/blob/846046ccccf3d2bde63be9cb7f75537af5332638/pkg/instrumentation/apachehttpd.go#L52-L58

Probes are invalid on initContainers and are rejected with `FailedCreate`: 

```
Pod "***" is invalid: [
  spec.initContainers[0].livenessProbe:Forbidden: may not be set for init containers,
  spec.initContainers[0].readinessProbe: Forbidden: may not be set for init containers,
  spec.initContainers[0].startupProbe: Forbidden: may not be set for init containers
]
```

**Comment by chrlic** [comment]
Pls assign to me
