### ISSUE TITLE
QUESTION. Traces. OpenTelemetry fault tolerance in deployment mode.

### ISSUE THREAD

**Issue by andreivaloshyn** [open-telemetry/opentelemetry-operator#1824]
Hello
I use OTel operator for K8S in `deployment` mode just for traces.
I mentioned that during the collector redeployment, I can see that some traces can't be pushed by my application to OTel which is a cause of losing them.
Error from the app:
```
Caused by: java.net.SocketException: Socket closed
```

Is there a way how to avoid this?
Will `statefulset` mode solve this problem or there are some other 'stable' ways how to avoid this?

**Comment by jaronoff97** [comment]
This should be handled by retries in your SDK you may want to configure the SDK to be more tolerant to disconnects. Let me know if you are seeing this consistently still
