### ISSUE TITLE
TargetAllocator for daemonset

### ISSUE THREAD

**Issue by tcolgate** [open-telemetry/opentelemetry-operator#1828]
Ideally, when deployed as a daemonset, collectors would scrape the pods running on the node
local to the daemonset instance. It's not obvious from the docs or configs as to if that is achievable
with the current targetAllocator strategies.

Am I missing something? Would you accept a PR that implements this?

**Comment by m1rp** [comment]
We're also interested in this.
we've been reading through the docs and tried a few things but couldn't get this to work.

**Comment by swiatekm-sumo** [comment]
I'm curious if your use cases includes Prometheus Custom Resources as well. Do you want each Otel Pod to scrape Pods on the same Node, as defined by a ServiceMonitor or PodMonitor? Or just all Pods on the Node with the right annotation? I believe you can achieve the latter with plain Prometheus configuration by using selectors for a `pod` role.

**Comment by tcolgate** [comment]
Yeah, we are using ServiceMonitor as it seems to be fairly common for third party charts. Most things I've seen still end up with the older style scrape labels, so I could maybe just use those. I'll have a look around.

**Comment by jaronoff97** [comment]
yeah this is a good idea, we would ultimately implement this as a new strategy that can only be used when target allocator's mode is daemonset. We would first implement the strategy and then expose it under the new target allocator CRD as part of our v2 milestone.

**Comment by swiatekm-sumo** [comment]
@jaronoff97 do we need to tie this to v2? It's not a breaking change and doesn't have any dependencies.

**Comment by jaronoff97** [comment]
Its something I would love to get done in the TA prior to the v2 so that when we make the target allocator CRD it can start with a mode which right now it doesn't have.

**Comment by jaronoff97** [comment]
@matej-g is going to take this on! Thank you :bow:
