### ISSUE TITLE
[target allocator] Support the `Probe` and `ScrapeConfig` Prometheus Operator CRDs

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-operator#1842]
Off the back of the suggestion in https://github.com/open-telemetry/opentelemetry-operator/pull/1710#discussion_r1226753826

In the Prometheus Operator CRDs, there are couple more CRDs that it would be nice to support:
- [`Probe`](https://prometheus-operator.dev/docs/operator/design/#probe)
- [`ScrapeConfig`](https://github.com/prometheus-operator/prometheus-operator/pull/5279)

Actions to take:
- Evaluate if we want to support both
- Implement

**Comment by jaronoff97** [comment]
I'm definitely in support of this, it also should be much easier to do now that we use the upstream prom-operator methods. @yuriolisa was interested in testing this out.
