### ISSUE TITLE
[target allocator] Refactor Prometheus CR watcher methods for loading service / pod monitors

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-operator#1843]
Off the back of the discussion in https://github.com/open-telemetry/opentelemetry-operator/pull/1710#discussion_r1185058848.

After some recent refactoring in the Prometheus Operator, we should be able to use exported methods to load and validate service and pod monitors, instead of having to do this our selves in the `LoadConfig` method. 

- for service monitors: https://github.com/prometheus-operator/prometheus-operator/blob/06b5c4189f3f72737766d86103d049115c3aff48/pkg/prometheus/resource_selector.go#L73
- for pod monitors: https://github.com/prometheus-operator/prometheus-operator/blob/06b5c4189f3f72737766d86103d049115c3aff48/pkg/prometheus/resource_selector.go#L314

**Comment by jaronoff97** [comment]
@rashmichandrashekar this is related to the work we've been discussing.

**Comment by swiatekm-sumo** [comment]
This looks like it was fixed in #2328, can we close this issue?

**Comment by jaronoff97** [comment]
yes, closing.
