### ISSUE TITLE
Unable to auto instrument go services

### ISSUE THREAD

**Issue by dhanvsagar** [open-telemetry/opentelemetry-operator#1846]
Hi,
I am have a demo app (https://github.com/GoogleCloudPlatform/microservices-demo) deployed in a k8s cluster.
The services are in Java, NodeJS, .Net and Go.

I have the open telemetry operator installed in my cluster with ```featureGates: "operator.autoinstrumentation.go"``` to enable support for Go.

The app YAML files contains annotations as follows 
```
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/src/server"
```

But the containers for the services in Go are throwing the error ``` CreateContainerConfigError``` are not getting created.
I can see an init container with the image ```ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.2.1-alpha``` is added to the pod, but it's not getting started.

The pod events shows that  ```runAsUser breaks non-root policy```.
```
  Normal   Pulled     <invalid> (x5 over <invalid>)  kubelet            Container image "ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.2.1-alpha" already present on machine
  Warning  Failed     <invalid> (x5 over <invalid>)  kubelet            Error: container's runAsUser breaks non-root policy (pod: "shippingservice-55c45cc98d-microsrv-demo(1c1e9a09-ae3b-40ce-870d-776695744d72)", container: opentelemetry-auto-instrumentation)
```

The (injected) instrumentation container manifest is with the following security context.

```
     securityContext:
       capabilities:
         add:
         - SYS_PTRACE
       privileged: true
       runAsUser: 0
```

For the other languages its configured as non root user as follows and they are working fine.

```
51   securityContext:
152     fsGroup: 1000
153     runAsGroup: 1000
154     runAsNonRoot: true
155     runAsUser: 1000
```

Could you please help to resolve the issue.

(Please let me know if this should be an issue for the otel go repos)

**Comment by TylerHelmuth** [comment]
It is true that the Go autoinstrumentation agent is setting privileged permission.  It is specifically hard-coded here: 

https://github.com/open-telemetry/opentelemetry-operator/blob/b6f310f0f343b7fb3b0b7e5b2fa1eef7561b34ba/pkg/instrumentation/golang.go#L52-L58

The Go Instrumentation repo also uses this in their example:

https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/a1cff3243bf2c6719a5e2b0ee21a483b32a2c9af/docs/getting-started/emojivoto-instrumented.yaml#L51-L56

@open-telemetry/go-instrumentation-approvers can you confirm that those permissions are necessary.  If so, we can update the operator's documentation to explicitly call out that requirement.

**Comment by pellared** [comment]
> https://github.com/orgs/open-telemetry/teams/go-instrumentation-approvers can you confirm that those permissions are necessary. If so, we can update the operator's documentation to explicitly call out that requirement.

At this moment it is necessary and I suggest to document it. I created https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/204 to document it also in OTel Go Auto repository.

**Comment by TylerHelmuth** [comment]
I'll update our README and also get a section added to https://opentelemetry.io/docs/k8s-operator/automatic/ for Go.

**Comment by MikeGoldsmith** [comment]
As an update, yes - the go instrumentation agent does indeed need elevated permissions to deploy and use eBPF probes. This is because they interact with the kernel and processes do not have the required permissions by default.

@pellared has crated the ticket to document our current requirements and we will also review the permission set as it might be possible to reduce the scope or be more specific.

**Comment by droger88** [comment]
just recently tried the go auto instrument with crds, i am using `otel/autoinstrumentation-go:v0.3.0-alpha`, the pod starts up successfully. But i don't see anything sent to the collector.

below is the go sidecar log, and i have set the log level to debug by adding environment variable to the main container `OTEL_LOG_LEVEL=debug`, is there a way that we can get more insights? (I guess since the go instrument uses sidecar we wont be able to control the `OTEL_SERVICE_NAME` or `OTEL_LOG_LEVEL` via env from the main container?)

```
{"level":"info","ts":1696093999.089724,"caller":"cli/main.go:37","msg":"starting Go OpenTelemetry Agent ..."}{"level":"info","ts":1696093999.0897815,"caller":"opentelemetry/controller.go:119","msg":"Establishing connection to OTLP receiver ..."}{"level":"info","ts":1696094001.0913267,"caller":"process/discover.go:55","msg":"found process","pid":7}{"level":"info","ts":1696094001.091681,"caller":"ptrace/ptrace_linux.go:121","msg":"attach successfully","tid":13}{"level":"info","ts":1696094001.0917468,"caller":"ptrace/ptrace_linux.go:121","msg":"attach successfully","tid":14}{"level":"info","ts":1696094001.091781,"caller":"ptrace/ptrace_linux.go:121","msg":"attach successfully","tid":15}{"level":"info","ts":1696094001.0918076,"caller":"ptrace/ptrace_linux.go:121","msg":"attach successfully","tid":16}{"level":"info","ts":1696094001.0918384,"caller":"ptrace/ptrace_linux.go:121","msg":"attach successfully","tid":7}{"level":"info","ts":1696094001.0967298,"caller":"process/analyze.go:94","msg":"Detaching from process","pid":7}{"level":"info","ts":1696094001.0967762,"caller":"process/analyze.go:139","msg":"mmaped remote memory","start_addr":"7F8707B4C000","end_addr":"7F870934C000"}{"level":"info","ts":1696094001.1067166,"caller":"process/analyze.go:168","msg":"found relevant function for instrumentation","function":"net/http.HandlerFunc.ServeHTTP","start":2764640,"returns":[2764686]}{"level":"info","ts":1696094001.1073456,"caller":"cli/main.go:79","msg":"target process analysis completed","pid":7,"go_version":"1.21.0","dependencies":{"github.com/99designs/gqlgen":"v0.17.36","github.com/agnivade/levenshtein":"v1.1.1","github.com/fsnotify/fsnotify":"v1.6.0","github.com/gorilla/websocket":"v1.5.0","github.com/hashicorp/golang-lru/v2":"v2.0.3","github.com/hashicorp/hcl":"v1.0.0","github.com/magiconair/properties":"v1.8.7","github.com/mitchellh/mapstructure":"v1.5.0","github.com/pelletier/go-toml/v2":"v2.0.8","github.com/rueian/rueidis":"v0.0.100","github.com/spf13/afero":"v1.9.5","github.com/spf13/cast":"v1.5.1","github.com/spf13/jwalterweatherman":"v1.1.0","github.com/spf13/pflag":"v1.0.5","github.com/spf13/viper":"v1.16.0","github.com/subosito/gotenv":"v1.4.2","github.com/vektah/gqlparser/v2":"v2.5.8","gitlab.int.bell.ca/household-technology/go-repo/model/mdm":"v0.0.0","gitlab.int.bell.ca/household-technology/go-repo/model/model":"v0.0.0","gitlab.int.bell.ca/household-technology/go-repo/pkg/config":"v0.0.0","gitlab.int.bell.ca/household-technology/go-repo/pkg/redis":"v0.0.0","gitlab.int.bell.ca/household-technology/go-repo/pkg/utils":"v0.0.0","gitlab.int.bell.ca/household-technology/go-repo/services/catalog-api":"(devel)","golang.org/x/sys":"v0.8.0","golang.org/x/text":"v0.9.0","gopkg.in/ini.v1":"v1.67.0","gopkg.in/yaml.v3":"v3.0.1"},"total_functions_found":1}{"level":"info","ts":1696094001.10742,"caller":"cli/main.go:85","msg":"invoking instrumentors"}{"level":"info","ts":1696094001.107739,"logger":"allocator","caller":"allocator/allocator_linux.go:39","msg":"Loading allocator","start_addr":140217926598656,"end_addr":140217951764480}{"level":"info","ts":1696094001.1195958,"caller":"instrumentors/runner.go:85","msg":"loading instrumentor","name":"net/http"}{"level":"info","ts":1696094001.1206892,"caller":"inject/injector.go:102","msg":"Injecting variables","vars":{"ctx_ptr_pos":232,"headers_ptr_pos":56,"is_registers_abi":true,"method_ptr_pos":0,"path_ptr_pos":56,"url_ptr_pos":16}}{"level":"info","ts":1696094001.1708648,"caller":"instrumentors/runner.go:94","msg":"loaded instrumentors to memory","total_instrumentors":1}
```

**Comment by pavolloffay** [comment]
> (I guess since the go instrument uses sidecar we wont be able to control the OTEL_SERVICE_NAME or OTEL_LOG_LEVEL via env from the main container?)

These env variables can be specified in the instrumentation CR

**Comment by jaronoff97** [comment]
Closing this because we have improved documentation for this.
