### ISSUE TITLE
[.NET auto-instrumentation] Add support for alpine-based images

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-operator#1849]
Reference: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2658

For now, opentelemetry-operator is able to inject auto-instrumentation only for glibc based linux images.
Alpine is using musl library so it cannot be supported.

.NET auto-instrumentation is supporting Alpine. There is a need to inject different set of libraries.

**Comment by Kielek** [comment]
Lets start with comparing
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v0.7.0/opentelemetry-dotnet-instrumentation-linux-glibc.zip
and
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v0.7.0/opentelemetry-dotnet-instrumentation-linux-musl.zip

The only significant difference is file `OpenTelemetry.AutoInstrumentation.Native.so`. It has two important things
1. Location `linux-musl-x64` instead of `inux-x64`
2. It is compiled for musl instead of glibc.

I suppose that we could have one image created by
1. Downloading and unpacking https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v0.7.0/opentelemetry-dotnet-instrumentation-linux-glibc.zip
2. Downloading only https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v0.7.0/opentelemetry-dotnet-instrumentation-linux-musl.zip and unpack only  `OpenTelemetry.AutoInstrumentation.Native.so` to `linux-musl-x64`.

While injecting instrumentation we need to detect which system is used.
One of possibilities can be found in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/e560d9ef50db9a46afde973fe004c4d49daf5296/instrument.sh#L5-L20

The second option is to create fully independent images, but we still need to distinguish which version to inject.

**Comment by TylerHelmuth** [comment]
>While injecting instrumentation we need to detect which system is used and correctly set CORECLR_PROFILER_PATH

That might be tricky.  We set a default value for `CORECLR_PROFILER_PATH` based on our default image.  Maybe it would be best to maintain 2 dotnet images, one for each architecture. 

I'll bring this up at the next SIG.

**Comment by TylerHelmuth** [comment]
@Kielek we discussed this in the SIG meeting today.

Is there any chance the dotnet instrumentation SIG has plans to merge the linux distributions and have the auto-instrumentation detect the libraries the users are using or is this a limitation of dotnet auto-instrumentation?

**Comment by swiatekm-sumo** [comment]
> .NET AutoInstrumentation SIG meeting: In the future you can expect more architectures, like arm64. Please consider this while making decision about the way how to do this.

This is an OCI container spec feature, and will work out of the box if you publish multi-arch images on your end. 

The libc vs musl problem is relatively more difficult, as there's no standard metadata for it. In the operator, we don't have any good way of checking if a particular application image is based on musl or glibc.

**Comment by Kielek** [comment]
> @Kielek we discussed this in the SIG meeting today.
> 
> Is there any chance the dotnet instrumentation SIG has plans to merge the linux distributions and have the auto-instrumentation detect the libraries the users are using or is this a limitation of dotnet auto-instrumentation?

I do not think that it is even possible.
The library is kind of an entry point for auto-instrumentation. As it is written in C++ it requires reference to standard library.
Lets treat it as limitation (as I know similar limitations are implemented in proprietary solutions).
Decision which version inject has to be done before process start.

Once again, how we handle it in shell script: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/e560d9ef50db9a46afde973fe004c4d49daf5296/instrument.sh#L5-L20

**Comment by swiatekm-sumo** [comment]
I've looked into this a bit, but I'm far from an expert on dotnet, so please correct me if I'm wrong about any of it @Kielek.

It looks like this comes down to picking the right binary out of two options, based on the libc implementation. That is what your script does - once we know, we just set an environment variable to the location of the correct binary, and start the application proper.

If we need to solve this in the operator, the best way I can think of doing it is to inject a custom entrypoint script into the application container, and do the detection there. It's going to be messy from what I've seen of similar solutions, but the alternative of trying to detect this statically in the operator based on inspecting the docker image can work as a heuristic at  best. In principle, I don't think there's a good way of figuring out which libc a container has without actually running stuff in it.

**Comment by Kielek** [comment]
@swiatekm-sumo. I can confirm that everything what we can do it to detect library version before process execution. You description sound resonable.

**Comment by TylerHelmuth** [comment]
We discussed this topic during the SIG meeting today and we've landed on a approach:

We will update the docker image we supply to include all necessary versions of the dotnet instrumentation distribution.  We'll introduce a new annotation for users to use to explicitly state which version of the dotnet instrumentation to use.  The operator will use this annotation to correctly setup the initContainer and all the env vars.  So that it isn't a breaking change, the Operator can assume that the lack of the new annotation means use the glibc version.

**Comment by Kielek** [comment]
@TylerHelmuth, could you please describe how annotations should looks like. If possible please document what you have agreed on SIG meeting.

Current supported ways to inject dotnet-auto

```
instrumentation.opentelemetry.io/inject-dotnet: "true"
instrumentation.opentelemetry.io/inject-dotnet: "my-instrumentation"
instrumentation.opentelemetry.io/inject-dotnet: "my-other-namespace/my-instrumentation"
```

Potential additional annotation:
```
instrumentation.opentelemetry.io/dotnet-runtime: "linux-glibc" - default?
instrumentation.opentelemetry.io/dotnet-runtime: "linux-musl"
```

or as required by MS nuget packages for different runtimes

```
instrumentation.opentelemetry.io/dotnet-runtime: "linux-glibc-x64" - default?
instrumentation.opentelemetry.io/dotnet-runtime: "linux-musl-x64"
```

**Comment by swiatekm-sumo** [comment]
I don't think we have a naming convention for instrumentation-specific annotations. `instrumentation.opentelemetry.io/dotnet-runtime` sounds fine to me, and it would generalize to `instrumentation.opentelemetry.io/<name>-<setting>`.

The values shouldn't include the architecture, as the container image itself will encode that information.
