### ISSUE TITLE
[target_allocator] Only admit configurations where targets can exist

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#1859]
Target Allocator gets configuration from two sources:

* scrape configs defined in prometheus receiver configuration in the Collector config
* Prometheus CRs

Right now, you can pass it a configuration that contains neither of these, and it will happily accept it and serve no targets.

During a recent SIG discussion, we've decided that while the Target Allocator itself should accept a configuration like this, we should reject Collector CRDs which would result in this kind of state.

**Comment by KitSutliff** [comment]
Dibs if no other takers!

**Comment by swiatekm-sumo** [comment]
Sorry Kit, there's already a PR of mine fixing this. @jaronoff97 can you assign this to me to prevent further confusion?
