### ISSUE TITLE
Add support for tolerations?

### ISSUE THREAD

**Issue by markfink-splunk** [open-telemetry/opentelemetry-operator#186]
In daemonset mode, it installs to worker nodes only, not master, which is normal and we can usually workaround with a toleration.  But I can't figure out how to apply a toleration to this operator and support for it may need to be added.  The use-case is for the kubelet metrics receiver that is available with otel-collector-contrib.  I'd like to get kubelet metrics on the master node.  I'm creating a separate deployment just for the master now.  It would be convenient to roll support for this into the operator.

**Comment by jpkrohling** [comment]
Sounds like a valid use case. Would you like to send a PR adding support to the operator?
