### ISSUE TITLE
Add a managementState field to the Collector CRD to disable the reconciliation

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#1881]
The idea of this task is to add a new field in the CRD called `managementState`. It would be placed under `.spec.managementState` for the OpenTelemetry Collector instances.

Possible values:
* `Managed` _(default value)_: the reconciliation works currently does
* `Unmanaged`: disables the reconciliation

Disabling the reconciliation can be useful in different use cases:
- Debugging
- Edit the objects created by the operator without losing the changes (because of the reconciliation)
- Keep instances without upgrading (if, for whatever reason we need to upgrade the operator and all the instances except some of them)

This feature is something we implemented for the [Tempo Operator](https://github.com/grafana/tempo-operator/blob/main/docs/operator/api.md#tempostackspec--tempo-grafana-com-v1alpha1-tempostackspec-) and it is also implemented in the  [Loki Operator](https://github.com/grafana/loki/blob/main/operator/docs/operator/api.md#lokistackspec--loki-grafana-com-v1-lokistackspec-).

**Comment by avadhut123pisal** [comment]
I can work on this, if it is not already in progress.
