### ISSUE TITLE
Operator python autoinstrumentation overrides `PYTHONPATH` defined in the app docker image

### ISSUE THREAD

**Issue by pl4nty** [open-telemetry/opentelemetry-operator#1884]
The python autoinstrumentation overrides the target container's [`PYTHONPATH`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) environment variable, which can break python module loading for some applications.

https://github.com/open-telemetry/opentelemetry-operator/blob/a12d944b92074bf81c70a78ba9dbd2668f247519/pkg/instrumentation/podmutator_test.go#L699-L700

If `PYTHONPATH` is present in the target container definition, the OTel values could be appended (or prepended) instead. I'm not sure whether path order affects the order/priority of module loading though. If so, it's worth considering whether OTel modules should override app modules if there's a conflict.

In my case, `PYTHONPATH` was included in the image so the above solution wouldn't work automatically. But as an operator, I would be able to manually set `PYTHONPATH` in the container definition and recover. This scenario could be documented.

**Comment by pavolloffay** [comment]
The `PYTHONPATH` is not overridden if it is defined in the container - https://github.com/open-telemetry/opentelemetry-operator/blob/4de0d208a50394fe166dada924cdb4994c7e81b4/pkg/instrumentation/python.go#L59

The operator does not have ability to inspect app docker image if some variables are hardcoded there. 

However we could at least document that `PYTHONPATH` (and JAVA_OPTS, and others) should not be hardcoded on the docker images.
