### ISSUE TITLE
Run the upgrade as part of the reconciliation for instances that will be switched from unmanaged to managed after the upgrade

### ISSUE THREAD

**Issue by avadhut123pisal** [open-telemetry/opentelemetry-operator#1890]
Run the upgrade as part of the reconciliation for instances that will be switched from unmanaged to managed after the upgrade.

_Originally posted by @pavolloffay in https://github.com/open-telemetry/opentelemetry-operator/pull/1888#discussion_r1251607491_

**Comment by GenPage** [comment]
I can take a crack at this. Running into this with collectors set to `Upgrade Strategy:  none` since we use an in-house collector image. We don't set spec.managementState and the operator is throwing: 

```
{"level":"info","ts":"2023-08-17T16:23:13Z","logger":"controllers.OpenTelemetryCollector","msg":"Skipping reconciliation for unmanaged OpenTelemetryCollector resource","opentelemetrycollector":{"name":"otel-gateway","namespace":"opentelemetry-operator-system"},"name":"opentelemetry-operator-system/otel-gateway"}
```

**Comment by GenPage** [comment]
@avadhut123pisal @pavolloffay After looking deeper into the issue, there seems to be some overlap and a need for clarification on the differences between `UpgradeStrategy` and `ManagementState.` They both try to achieve similar goals.

I propose a solution where `UpgradeStrategy` is either completely removed or changed to handle which parts of the spec you want to be managed. (image, config, etc). Thoughts?

**Comment by GenPage** [comment]
The more I think about it, it should really just be a merge strategy, where in this case we want the upgrade function to add in new values that haven't existed in the past but not override existing ones overridden by cluster-admins (in my case, spec.image)

- UpgradeStrategy: Override, Merge (New Default), None

**Comment by iblancasa** [comment]
> @avadhut123pisal @pavolloffay After looking deeper into the issue, there seems to be some overlap and a need for clarification on the differences between `UpgradeStrategy` and `ManagementState.` They both try to achieve similar goals.

The `UpgradeStrategy` is used to enable or disable the mechanism to upgrade the instance when a new instance of the operator is deployed.
`ManagementState` is used to enable or disable the reconciliation. It can be used, for instance, for debugging the operator.

They should not be merged.
