### ISSUE TITLE
Unable to configure servicemonitorselector under prometheusCR under targetallocator section

### ISSUE THREAD

**Issue by krimeshshah** [open-telemetry/opentelemetry-operator#1907]
### Component(s)

receiver/prometheus

### Describe the issue you're reporting

Since scraping prometheus CR servicemonitor endpoints without any selection consume too much memory and drops the data , we decide to only scrape selected servicemonitor using serviceMonitorSelector option provided by opentelemtry crd from opentelemetry operator which we are using here in kueb-otel-stack - https://github.com/lightstep/otel-collector-charts/blob/main/charts/kube-otel-stack/values.yaml#L146

I read and found out that we can specify the and limit the number of servicemonitor that we want to scrape for metrics using "serviceMonitorSelector" (https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml#L2039) which can reduce the memory consumption i believe as it will reduce the no of scraping endpoints.
As described in opentelemetrycollector crd, this is parameter is of type string but at the same time it is written that it is key value pair. And as per the kube-prometheus-stack i should configue like - https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2975
But when the same way when i try to configure multiple servicemonitor with matchLabel and its key value pair it kube-otel-stack deployment fails.
Hence i tried to configure as below ## Default collector for metrics (includes infrastructure metrics) metricsCollector: name: metrics clusterName: dev image: otel/opentelemetry-collector-contrib:0.73.0 enabled: true mode: statefulset replicas: 6 targetallocator: enabled: true allocationStrategy: "consistent-hashing" filterStrategy: relabel-config replicas: 2 image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:0.73.0 prometheusCR: enabled: true serviceMonitorSelector: matchLabels: "lightstep-metrics-collector"

But the things is , i can only specify one servicemonitor this way, how can i configure multiple servicemonitor?

**Comment by jaronoff97** [comment]
Yep, this is an oversight on my part – my initial implementation was a stop gap solution for someone at the time, im not sure why i didn't go with [what prometheus does](https://github.com/prometheus-operator/prometheus-operator/blob/45a45f9737ae33b5d0eb4dddfbb6ee5444c3dfbd/pkg/apis/monitoring/v1/prometheus_types.go#L76). This is a good first issue for anyone who wants to take it... We can support both implementations, deprecating the old one and eventually removing it.

**Comment by jaronoff97** [comment]
This will result in a breaking change and is this included in our v2 milestone.

**Comment by Toaddyan** [comment]
has this been completed in the v2 version? anywhere that I can pick up from?

**Comment by jaronoff97** [comment]
@Toaddyan not yet, but i think @yuriolisa is working on this?

**Comment by Toaddyan** [comment]
sounds good. lmk!

**Comment by yuriolisa** [comment]
@Toaddyan, actually this issue has been resolved by @swiatekm-sumo  on #2564.
