### ISSUE TITLE
Please publish new version of autoinstrumentation-java

### ISSUE THREAD

**Issue by echatman-ias** [open-telemetry/opentelemetry-operator#1916]
The latest java agent version is [1.28.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases) but the latest autoinstrumentation-java image available is [1.26.0](https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fautoinstrumentation-java). Can you please publish an autoinstrumentation-java v1.28.0?

**Comment by TylerHelmuth** [comment]
Related issue, our CI action to update the java version on new releases is broken: https://github.com/open-telemetry/opentelemetry-operator/actions/runs/5526776918/jobs/10081861894

**Comment by TylerHelmuth** [comment]
Created https://github.com/open-telemetry/opentelemetry-operator/issues/1917 to track the broken CI

**Comment by pavolloffay** [comment]
Done https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fautoinstrumentation-java
