### ISSUE TITLE
add service.instance.id into resource env

### ISSUE THREAD

**Issue by Duncan-dsf** [open-telemetry/opentelemetry-operator#1921]
Why not add service.instance.id into resources? Is there any consideration?

https://github.com/open-telemetry/opentelemetry-operator/blob/02b4d30b5786dc1f0ec03ccf63a91013c229d515/pkg/instrumentation/sdk.go#L324

<img width="1162" alt="image" src="https://github.com/open-telemetry/opentelemetry-operator/assets/29371215/d51cd42d-7b92-44a5-84b7-4a8af66f5fc2">

**Comment by TylerHelmuth** [comment]
We could.  Is that something you'd like to contribute.

**Comment by yuriolisa** [comment]
I can take this on, ok?
