### ISSUE TITLE
TargetAllocator hash computation returning false negative

### ISSUE THREAD

**Issue by rashmichandrashekar** [open-telemetry/opentelemetry-operator#1926]
I am seeing hash computation issue for regex field where it returns a false negative, when there is only change in the regex field here - https://github.com/open-telemetry/opentelemetry-operator/blob/56f5de94dd3f1f83ac7dbdba3b8b4a6379317b48/cmd/otel-allocator/target/discovery.go#L85

For example, when there are 2 scrape configs with just the regex field changed between the 2, the hash returned is the same.

    scrape_configs:
      - job_name: kube-proxy
        scrape_interval: 30s
        label_limit: 63
        label_name_length_limit: 511
        label_value_length_limit: 1023
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: keep
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_name
          separator: "/"
          regex: kube-system/kube-proxy.+
        - source_labels:
          - __address__
          action: replace
          target_label: __address__
          regex: "regex1"
          replacement: "$$1:10249"

    scrape_configs:
      - job_name: kube-proxy
        scrape_interval: 30s
        label_limit: 63
        label_name_length_limit: 511
        label_value_length_limit: 1023
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: keep
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_name
          separator: "/"
          regex: kube-system/kube-proxy.+
        - source_labels:
          - __address__
          action: replace
          target_label: __address__
          regex: "regex2"
          replacement: "$$1:10249"

These 2 configs return the same hash

**Comment by rashmichandrashekar** [comment]
Similar to issue - #1358

**Comment by swiatekm-sumo** [comment]
Fixed by #2171

**Comment by rashmichandrashekar** [comment]
@swiatekm-sumo - Sorry for the delay in responding to this issue as there seems to be a fix made with this - #2171 
But, the fix is only partial because, if the same fix isn't made to the otel collector's prometheusreceiver, even though the hash computation here fixes the relabeling for targets, the collector fails to get the updated config and will not work e2e as expected for metric relabeling. The same fix needs to be made [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1d886eacd7806128d2528bda512e3915a1fa6a25/receiver/prometheusreceiver/metrics_receiver.go#L142C85-L142C85)
Are there any plans to make this change in the otel collector repo?

**Comment by swiatekm-sumo** [comment]
@rashmichandrashekar you should open an issue in the contrib repo and reference this one. Looks like a simple enough fix in the receiver - thanks for pointing this out!

**Comment by rashmichandrashekar** [comment]
> @rashmichandrashekar you should open an issue in the contrib repo and reference this one. Looks like a simple enough fix in the receiver - thanks for pointing this out!

Thanks @swiatekm-sumo - I have created an issue here - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29313
