### ISSUE TITLE
Put reconciliation errors in CRD events

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#1972]
A user shouldn't need to look at operator logs for CRD reconciliation problems. We should add them proactively on the CRD's events to make clear why something couldn't be reconciled. This will be easier with the completion of https://github.com/open-telemetry/opentelemetry-operator/issues/1876

**Comment by pavolloffay** [comment]
+1

**Comment by iblancasa** [comment]
I would like to work on this. Could you assign this task to me? Thanks!

**Comment by jaronoff97** [comment]
@iblancasa i want to complete #1876 first which will make setting status much easier hopefully... but happy to assign you!
