### ISSUE TITLE
Support specifying additional containers 

### ISSUE THREAD

**Issue by nikore** [open-telemetry/opentelemetry-operator#1987]
It would be useful to be able to specify additional containers that run inside the otel collector pod. 

Possible use cases:

- Running cloud agents that will consume Prometheus exporter from otel collector
- Running logging sidecars 
- Running auth proxies
- Running other sidecars that do not support injection

Some examples in other operators:

[KOperator](https://github.com/banzaicloud/koperator/blob/master/api/v1beta1/kafkacluster_types.go#L244)
[Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/apis/monitoring/v1/prometheus_types.go#L337)
[Grafana Operator](https://github.com/grafana-operator/grafana-operator/blob/master/api/v1beta1/grafana_types.go#L67C14-L67C27) Note they just take a whole deployment spec 

There are more that I can probably find but those where the ones that came to mind right away.

**Comment by diurnalist** [comment]
FYI I had filed https://github.com/open-telemetry/opentelemetry-operator/issues/1684 earlier. It was closed when a patch that added initContainer support was merged, but the intent of the issue was to capture initContainers and sidecars.

**Comment by pavolloffay** [comment]
done
