### ISSUE TITLE
Operand image version not being referenced from the version file

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-operator#20]
When reproducing issue #18 found that the operand image version referenced was v0.0.2 - according to the version file it should have been using 0.2.0.

**Comment by jpkrohling** [comment]
This might be fixed in the current master. Using the Operator 0.2.0 brings the operand 0.2.0.

**Comment by jpkrohling** [comment]
Sorry, misunderstood the issue. This is probably indeed happening.

**Comment by jpkrohling** [comment]
Master is indeed fixed: I just tried changing the versions.txt to 0.8.0 as part of testing #42 and it did attempt to bring the otel-col 0.8.0.
