### ISSUE TITLE
Publishing the bundle image failed for 0.82.0

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#2001]
See: https://github.com/open-telemetry/opentelemetry-operator/actions/runs/5807500252/job/15742453581

```
ERROR: failed to solve: failed to push otel/opentelemetry-operator-bundle:0.82.0: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

It looks like we're using the same credentials as for other images, so I'd assume this is a problem with permissions in Dockerhub. 

Pinging @iblancasa as the author of #1880.

**Comment by iblancasa** [comment]
Who has permissions in the DockerHub organization?

**Comment by swiatekm-sumo** [comment]
I see @pavolloffay already opened a maintenance request in the community repo: https://github.com/open-telemetry/community/issues/1635

**Comment by pavolloffay** [comment]
Also the publish for 0.83.0 failed

**Comment by pavolloffay** [comment]
Publishing to dockerhub seems to be fixed, but the same issue is with the GHCR

**Comment by pavolloffay** [comment]
The publishing is still failing

**Comment by swiatekm-sumo** [comment]
I tried this on a fork and it worked (albeit after getting rid of publishing to Docker): https://github.com/swiatekm-sumo/opentelemetry-operator/actions/runs/6260451251/job/16998511279. So the failure most likely has something to do with our repo settings themselves.

**Comment by pavolloffay** [comment]
The publishing of the bundle image is still failing. I have created https://github.com/docker/build-push-action/issues/981

What is interesting is that the e2e test images were published https://github.com/orgs/open-telemetry/packages?repo_name=opentelemetry-operator
However sometimes the first image publish fails on a similar error - https://github.com/open-telemetry/opentelemetry-operator/actions/runs/6394622279/job/17356427547
```
ERROR: failed to solve: failed to push ghcr.io/open-telemetry/opentelemetry-operator/e2e-test-app-apache-httpd:main: failed commit on ref "manifest-sha256:c33c301c43c5636fc91147e12740f65f2b2339e606f8710b3bbc6210e87fcc0e": unexpected status from PUT request to https://ghcr.io/v2/open-telemetry/opentelemetry-operator/e2e-test-app-apache-httpd/manifests/sha256:c33c301c43c5636fc91147e12740f65f2b2339e606f8710b3bbc6210e87fcc0e: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/open-telemetry/opentelemetry-operator/e2e-test-app-apache-httpd:main: failed commit on ref "manifest-sha256:c33c301c43c5636fc91147e12740f65f2b2339e606f8710b3bbc6210e87fcc0e": unexpected status from PUT request to https://ghcr.io/v2/open-telemetry/opentelemetry-operator/e2e-test-app-apache-httpd/manifests/sha256:c33c301c43c5636fc91147e12740f65f2b2339e606f8710b3bbc6210e87fcc0e: 403 Forbidden
```

**Comment by pavolloffay** [comment]
Done

**Comment by swiatekm-sumo** [comment]
I would really like to know why changing the name fixed this problem. Was the previous name tainted in some way?

**Comment by pavolloffay** [comment]
Not sure, maybe it was too long?
