### ISSUE TITLE
Make it possible to have multiple instrumentation CRD per namespace

### ISSUE THREAD

**Issue by angelopoerio** [open-telemetry/opentelemetry-operator#2036]
A common scenario is having different deployments per namespace, for example a web backend, some workers etc. 
So it would be very flexible to specify different instrumentation CRD to have different behaviours per deployments in the same namespace (maybe using  different sample rates for a different deployments in the same namespace).
At the moment this is impossible (https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/instrumentation/podmutator.go#L219).
Is it something interesting to be implemented in the operator?

**Comment by jaronoff97** [comment]
Would this solve your issue? https://github.com/open-telemetry/opentelemetry-operator/pull/1901

**Comment by angelopoerio** [comment]
@jaronoff97 yes, it's exactly what I was looking for. Thanks. Should we close this issue?

**Comment by jaronoff97** [comment]
Yep, closing :)
