### ISSUE TITLE
Volume "opentelemetry-auto-instrumentation" of type emptyDir of init container does not have sizeLimit

### ISSUE THREAD

**Issue by KaiKaisen** [open-telemetry/opentelemetry-operator#2044]
Hi all,
When using _instrumentation.opentelemetry.io/inject-java: "true"_ in Kubernetes deployment yaml the used volume has no sizeLimit:
```
volumes:
...
  - emptyDir: {}
    name: opentelemetry-auto-instrumentation
...
```
A common kyverno rule (require-emptydir-requests-and-limits) checks for a sizeLimit for emptyDir volumes and therefore this kyverno rule reports a policy violation.
Would it make sense to add sizeLimit to this volume. 
Thanks in advance,
Kai

**Comment by pavolloffay** [comment]
It makes sense to set the limit size.
