### ISSUE TITLE
Use business applications hosted in this repository for the instrumentation E2E tests

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2073]
Currently, we use some applications to test the autoinstrumentation injection. Those applications are hosted by others.

When we find a problem in those applications or their images, we depend on a third one to fix the image and make the test pass.

Also, some images are really big. Doing this can do the CI a little bit faster.

Finally, it would be awesome if we could move the instrumentation E2E tests to their own folder. It makes sense from the logical organization of the E2E tests and can help to speedup the CI since the run will be done in parallel.

**Comment by TylerHelmuth** [comment]
I would also support using the otel-demo components for our tests instead of building our own test images.

**Comment by iblancasa** [comment]
> I would also support using the otel-demo components for our tests instead of building our own test images.

Good idea. I'll try and, if not, use something custom.
Thanks for the suggestion!

**Comment by pavolloffay** [comment]
> I would also support using the otel-demo components for our tests instead of building our own test images.

LGTM, if the image size is not large. 

The goal here is to improve maintenance and as well speed up CI (e.g. image size).

Internally we will also start testing on different architectures and we will need the test apps to run on those archs as well.
