### ISSUE TITLE
Environment Variables in Instrumentation Spec should not need OTEL or SPLUNK prefix.

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-operator#2098]
You can pass in environment variables thru the `instrumentation.spec.env` field, but they're checked for OTEL or SPLUNK prefixes. However, if you wish to do something like set the exporter endpoint to the Node IP (for daemonset deployments), you need to get the IP in somehow, and an env var is convenient. Since the instrumentation is running in the init container, the env var needs to be there. 

While you certainly can just prefix it with OTEL, it seems like the check is unneeded to begin with and might discourage users from sending in env vars.

My suggestion would be to either make NODE_IP available by default, or remove the required prefixing.

**Comment by TylerHelmuth** [comment]
I vote for removing any required prefixing

**Comment by prashant-shahi** [comment]
> My suggestion would be to either make NODE_IP available by default, or remove the required prefixing.

To me, the latter seems like better way to go about.

I had encountered something similar when trying to pass set `HOST_IP` env.
When it said only `OTEL_` prefixed environments were allowed, my first perception was only the environments from OpenTelemetry Specifications were allowed.

**Comment by jvoravong** [comment]
- Posting an [example](https://github.com/signalfx/splunk-otel-collector-chart/blob/0a8211ce9c255a2eaf7fa102c446cad70e2a5c0b/examples/enable-operator-and-auto-instrumentation/rendered_manifests/operator/instrumentation.yaml#L22) of how Splunk uses the host IP with a collector daemonset we deploy. Not sure how reusable this example solution is for this particular case.
- I find using OTEL_ (and occasionally Splunk_) prefixes helpful in distinguishing environment variables for instrumentation from those for user applications. However, I'm open to flexibility on this matter.

**Comment by yuriolisa** [comment]
I would suggest keeping the OTEL_ prefixes to distinguish environment variables set by the instrumentation but removing the requirement to accept only this prefix.

**Comment by jriguera** [comment]
+1 for removing the prefix validation. The SDK already enforces the prefix, this is an "operator", so I think the validation is not needed. I am having a similar issue (but to define a tenant header) and having to add the prefix to variables which do not have anything to do with the SDK sounds not correct.
