### ISSUE TITLE
Support configuring updateStrategy in collector workloads

### ISSUE THREAD

**Issue by sfc-gh-rscott** [open-telemetry/opentelemetry-operator#2107]
Currently it's not possible to configure the `updateStrategy` for collector workloads. This has the effect of setting `maxUnavailable` to 1 for `DaemonSet` workloads, which causes rollouts to take a long time in clusters with many nodes. It would be great to be able to set [.spec.updateStrategy.rollingUpdate.maxUnavailable](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec) to something other than 1.

**Comment by yuriolisa** [comment]
@frzifus, are you working on it or can I take this one?

**Comment by frzifus** [comment]
Nope, please go ahead :smile:
