### ISSUE TITLE
Migrate OpenShift route reconciliation to use manifests

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#2108]
Currently, reconciliation for routes is handled in a bit of an odd way, we should centralize this to be done via manifest / only once https://github.com/open-telemetry/opentelemetry-operator/blob/main/controllers/opentelemetrycollector_controller.go#L72-L92

**Comment by jaronoff97** [comment]
@pavolloffay @frzifus

**Comment by frzifus** [comment]
Somehow I have in mind that we discussed to put this behind a feature flag. wdyt?

**Comment by jaronoff97** [comment]
from our last SIG call, i think the decision we came to was instead of checking for the status of OPA routes on an interval we just do it once on startup and that sets a flag

**Comment by pavolloffay** [comment]
LGTM for doing the Route API discovery at startup
