### ISSUE TITLE
Otel-Collector mode as deployment/daemonset when run with Target Allocator

### ISSUE THREAD

**Issue by sfc-gh-akrishnan** [open-telemetry/opentelemetry-operator#2140]
While using Otel-collectors with Target Allocator, only mode that is allowed seems to be "statefulset"

While this is fine, I'd like to understand if there are particular limitations that is preventing the usage of modes such as "daemonset" and "deployment"?

Is there any future plans to support this or is it out of question?

If there is some docs that dwells into the design choices, I'd be super interested as well. 

Thank you for the time and consideration in reviewing the request

**Comment by jaronoff97** [comment]
This goes back to the [original design](https://docs.google.com/document/d/1GdpCqdkz72291l_8S-jio7EhVltminobvqshsFih6vA/edit#heading=h.bxbqjd6pjflh), but the reasoning is still accurate – we rely on consistent and stable ids of collectors to assign target to prevent dual scrapes / bad assignments during a rollout. At this time, there wouldn't be a great way to support this with a high availability mode.

**Comment by sfc-gh-akrishnan** [comment]
Thank you for the quick response! Much appreciate it :) 

When you say, `high availability mode`, do you mean multiple replicas of Target Allocator? 

The API docs read: 
```
Replicas is the number of pod instances for the underlying TargetAllocator. This should only be set to a value other than 1 if a strategy that allows for high availability is chosen.
```

Does the strategy here refer to `allocationStrategy`? If so, is `consistent-hashing` the meant strategy? Must anything else be kept in mind or be aware of while setting replicas > 1?

**Comment by jaronoff97** [comment]
Yep HA mode is done with the consistent hashing strategy and you can use as many replicas as you want.
