### ISSUE TITLE
Autoinstrumentation dotnet throws error

### ISSUE THREAD

**Issue by rassmate** [open-telemetry/opentelemetry-operator#2143]
I have a dotnet application running in a docker container based on mcr.microsoft.com/dotnet/sdk:7.0

The container is deployed in a kuberenetes cluster where the open telemetry operator is deployed.
The autoinstrumentation kicks in but I get errors when during the setup process.

There is some file copying going on during the setup that fails with similar errors as this:

https://stackoverflow.com/questions/75938559/opentelemetry-operator-not-able-to-inject-auto-instrumentation-libraries

Any ideas?

**Comment by TylerHelmuth** [comment]
@rassmate that looks like a permission issue, but I've not seen it before. Are you doing this in OpenShift or Kubernetes?

**Comment by rassmate** [comment]
Openshift.

Java applications in same env works.

The dotnet applications gets env variables and files are copied but i don’t
get any metrics out from dotnet application.

Dotnet application sneda data to sidecar



tors 21 sep. 2023 kl. 17:05 skrev Tyler Helmuth ***@***.***>:

**Comment by Kielek** [comment]
@TylerHelmuth, there were a report similar to this some time ago, please check #1013

@rassmate, based on linked issue, please let is know if the files are finally copied to your pod. It should be available under folder `/otel-auto-instrumentation/`.

The next step is to check if you can find any logs under `/var/log/opentelemetry/dotnet/`. Especially from the start time. If they are available it will be great to share.
If possible before executing your container please set `OTEL_LOG_LEVEL`  to `debug` - https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/17ec6ae54aa1fec5f7c8bf9a48c0976ae9996ad4/docs/config.md#L61

**Comment by rassmate** [comment]
Yes, the files are copied and is not owned by root but by another User
10500…something

No logs found in application container under /var/log/opentelemetry/dotnet

When starting the application, nothing happens regarding metrics/traces.


It is a small dotnet 7 project.
I do have package references in my project to the otel packages but i
shouldn’t need them right?

Can their presence even cause conflicts perhaps?
I guess they are the same libraries downloaded in the init container.


fre 22 sep. 2023 kl. 07:14 skrev Piotr Kiełkowicz ***@***.***

**Comment by Kielek** [comment]
You do not need any references to OTel SDK.

It will be great if you can provide [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)
including
1. Exact version of your system and Kuberentes/OpenShift
2. All yaml/configuration/manifets files used to deploy opentelemetry-operator
3. Minimal docker application with Dockerfile and deployment manifest

**Comment by rassmate** [comment]
I Restarted with debug log set.
The application is just silent. No extra logs in application. And no logfile in /var/log/opentelemetry/dotnet in the application container.

If i set the project up with the libraries and manually configuring it in the .cs file i can get it to work and the metrics are send through otlp exporter to my Sidecar.

But using the fully automatic instrumentation doesn't seem to work.

I Will try to gather more data om monday

**Comment by rassmate** [comment]
Any custom System.Diagnostics Metrics

**Comment by Kielek** [comment]
You have to explicitly enableit. Plaese check documention about OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_SOURCES under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md

**Comment by rassmate** [comment]
Thanks a lot @Kielek!
I Will try this out Monday.
Have a great weekend.

I Will close this issue now
