### ISSUE TITLE
Not able to deploy Daemonset Collector in kind cluster

### ISSUE THREAD

**Issue by khossain-clgx** [open-telemetry/opentelemetry-operator#2155]
I have followed the below documentation to deploy Kind cluster and helm
https://opentelemetry.io/docs/kubernetes/getting-started/

1. kind create cluster
2. helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
3. helm install otel-collector open-telemetry/opentelemetry-collector --values <path where you saved the chart>
[values.zip](https://github.com/open-telemetry/opentelemetry-operator/files/12713548/values.zip)

getting the below issue
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  39s               default-scheduler  Successfully assigned default/otel-collector-opentelemetry-collector-agent-rgmb9 to kind-control-plane
  Warning  Failed     24s               kubelet            Failed to pull image "otel/opentelemetry-collector-contrib:0.85.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/otel/opentelemetry-collector-contrib:0.85.0": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/80/8051649435451f81e29a45ce50f48c11320e9142d3e74365e2377279d6b94088/data?verify=1695633563-U2A1arAET4IZyAo2NvGsD81p6mQ%3D": tls: failed to verify certificate: x509: certificate signed by unknown authority
  Warning  Failed     24s               kubelet            Error: ErrImagePull
  Normal   BackOff    23s               kubelet            Back-off pulling image "otel/opentelemetry-collector-contrib:0.85.0"
  Warning  Failed     23s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    7s (x2 over 38s)  kubelet            Pulling image "otel/opentelemetry-collector-contrib:0.85.0"

**Comment by TylerHelmuth** [comment]
@khossain-clgx it looks like you don't have permission to pull images from dockerhub.  Do you normally use a private image registry?

**Comment by khossain-clgx** [comment]
no this is the first time I am exploring opentelemetry for  Kubernetes.I have deployed kind cluster as suggested. Can you help how I can resolve this issue.

**Comment by pavolloffay** [comment]
The issue does not seem to be related to the operator `Back-off pulling image "otel/opentelemetry-collector-contrib:0.85.0"`. 

Please re-open if there is anything we can do.
