### ISSUE TITLE
Conflict between instrumentation.opentelemetry.io/inject-java: true and sidecar.istio.io/inject: "true" labels

### ISSUE THREAD

**Issue by lusains** [open-telemetry/opentelemetry-operator#2158]
When enabling both the instrumentation.opentelemetry.io/inject-java: true and sidecar.istio.io/inject: "true" labels on a pod, a conflict arises due to the ordering of the containers. Specifically, the istio-proxy container takes precedence in the container index, pushing the business container to a subsequent position.

This ordering conflict results in environment variables, such as otel-endpoint, intended for the business container being set on the istio-proxy container instead. Consequently, the business container cannot access the otel-endpoint environment variable.
and the same results after added "instrumentation.opentelemetry.io/container-names" annotation.

**Comment by pavolloffay** [comment]
thanks for reporting @lusains. Would you like to submit a PR to fix it?

**Comment by lusains** [comment]
> thanks for reporting @lusains. Would you like to submit a PR to fix it?
Thank you for the opportunity. I'm willing to address this and will work on fixing it.

**Comment by lusains** [comment]
In higher versions, the above problem has been solved through this annotation instrumentation.opentelemetry.io/container-names
