### ISSUE TITLE
imagePullSecrets in OpenTelemetryCollector.spec

### ISSUE THREAD

**Issue by sfc-gh-akrishnan** [open-telemetry/opentelemetry-operator#2161]
The OpenTelemetryCollector.spec today does not have method for set imagePullSecrets. Is there any way to accomplish the same or any workable solutions?

**Comment by jaronoff97** [comment]
The way we do this now is to give the service account created by the operator the necessary permissions to pull [this data](https://github.com/open-telemetry/opentelemetry-operator/pull/1928#issuecomment-1638232600). We should document this to make it more present. You can read more on how to do [this here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account).
