### ISSUE TITLE
Can't remove Instrumentations as a CRD

### ISSUE THREAD

**Issue by changliu-wk** [open-telemetry/opentelemetry-operator#2164]
We just use custom resource OpenTelemetryCollector as a Prometheus scraper to some pods, we disabled webhook in opentelemetry-operator helm chart, in our use case, we don't need to deploy and maintain this unused CRD Instrumentation. But after making some investigation, it seems we are not allowed to do this. 

Opentelemetry-operator will automatically look for Instrumentation, and give this error: 
`{"level":"error","ts":"2023-09-25T18:34:00Z","logger":"setup","msg":"problem running manager","error":"failed to list: no matches for kind \"Instrumentation\" in version \"opentelemetry.io/v1alpha1\"","stacktrace":"main.main\n\t/workspace/main.go:286\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}`

**Comment by jaronoff97** [comment]
I'm not positive this is supported, for any operator (not just ours) it will automatically watch the CRDs it owns. If you choose not to use the Instrumentation resource that's supported, however, the operator needs the resource to exist to start in the scenario a user starts using it.

**Comment by pavolloffay** [comment]
+1

I am closing this as won't do.
