### ISSUE TITLE
Tolerations in TargetAllocator

### ISSUE THREAD

**Issue by sfc-gh-akrishnan** [open-telemetry/opentelemetry-operator#2172]
The target allocator needs ability to have "Tolerations" to control scheduling of the pods

**Comment by jaronoff97** [comment]
Agreed, we should probably have this. Definitely a good first issue and a relatively small change. Would you be able to take this on?

**Comment by sfc-gh-akrishnan** [comment]
I'd like to take this up :) 
My exposure with kubernetes is minimal, but I am willing to learn it. If you could point me to a reference PR on how to introduce a knob and the files to make changes to, I can work on this!

**Comment by jaronoff97** [comment]
Here's an example that you should be able to base your [work on](https://github.com/open-telemetry/opentelemetry-operator/commit/e66ef73fc64334a2ff5f82a2d2fcaca597dc679e). A few files have been moved around, but the concepts are the same.
