### ISSUE TITLE
Bump the OpenTelemetry Operator CRD version

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2183]
On the last SIG meeting there was agreement to bump CRD API version and in the new version drop the string config and expose only the typed config.

_Originally posted by @pavolloffay in https://github.com/open-telemetry/opentelemetry-operator/issues/1707#issuecomment-1742595238_
            

26Oct2023. Update [after SIG meeting](https://docs.google.com/document/d/1Unbs2qp_j5kp8FfL_lRH-ld7i5EOQpsq0I4djkOOSL4/edit):
1. Create the CRD types, no manifests or anything
2. Have the operator reconcile it behind a feature flag 
3. After some time, put the reconciliation feature flag in beta
4. Webhook Conversion behind a new feature flag 
5. After some time, move the Webhook Conversion feature flag to beta
6. Move the feature flags to stable
7. Deprecate the old types

**Comment by iblancasa** [comment]
I started working on this.

**Comment by frzifus** [comment]
Should we not first figure out how the new ConfigSpec is implemented? Since thats the main reason to bump the version right now?

**Comment by iblancasa** [comment]
> Should we not first figure out how the new ConfigSpec is implemented? Since thats the main reason to bump the version right now?

Where do you want to implement it? In the old CRD?

**Comment by bryan-aguilar** [comment]
How long will the previous CRD version be supported for?

**Comment by iblancasa** [comment]
@bryan-aguilar as soon as the new one is implemented, we can take a decision about that.

**Comment by iblancasa** [comment]
> Another follow up question, will improvements to the CRD be made to both versions while the previous version is supported? Or will the older version no longer receive updates?

The idea is to use this: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion

So, the instances using the old CRD will be converted to the new one.

**Comment by bryan-aguilar** [comment]
Awesome, thanks for the info!

**Comment by pavolloffay** [comment]
Done in other issues/PRs
