### ISSUE TITLE
Relax requirement of having at least one code review

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#219]
@tigrannajaryan, unfortunately, I don't think we have enough approvers with knowledge on both otelcol and operators in general. 

Would it be OK to change the settings of this repo to not require at least one code review approval? For PRs from other folks, I'll always review before merging, but getting my own PRs merged are a problem right now (see #217).

I will always try to get someone to approve my PRs, even if this comes from non-official approvers, and I'll ask to reinstate the current requirements once we have at least two more approvers for this repository here.

**Comment by tigrannajaryan** [comment]
Otel [policies](https://github.com/open-telemetry/community/blob/b26795f9810f8615a700c16becb980fbe147b68c/docs/how-to-configure-new-repository.md#policies) explicitly require at least 1 approval:
>The default setting for Required approving reviews is 1 approval. Individual repositores may opt-in for bigger number of required reviews.

Two possibilities here:
1. Convince Otel governance to change the policy.
2. Find someone else who is interested in the operator and wants to become an approver. I would argue that this is the right approach. If we can't find another person who is interested then the question arises if the operator needs to be in Otel.

**Comment by jpkrohling** [comment]
>I would argue that this is the right approach

That's what I prefer as well, just not sure how long it's going to take, as I don't currently have contributors with a steady history of contributions yet. If you don't mind, I'll try to get non-official approvals from the community as a whole, and get your "approval by proxy" for my own PRs.
