### ISSUE TITLE
Bug: Target Allocator: Promotes a otel-collector pod in "pending state to 

### ISSUE THREAD

**Issue by sfc-gh-akrishnan** [open-telemetry/opentelemetry-operator#2200]

**Comment by pavolloffay** [comment]
@sfc-gh-akrishnan is this a duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/2201  ?

**Comment by sfc-gh-akrishnan** [comment]
Opened a dup by mistake. Let me close it
