### ISSUE TITLE
Add the ability to assign annotations to service account otel-collector

### ISSUE THREAD

**Issue by paco-sisutech** [open-telemetry/opentelemetry-operator#2227]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

I'm trying to get opentelemetry collector running in GKE to export data to google cloud trace as explained here:

https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kustomize/components/google-cloud-operations#workload-identity

So, I need to annotate the service account generated by the collector (otel-collector) but it gets constantly overwritten. Is it there some way to make it work adding some section in the collector.yaml file so it would persist the annotation?

I'm using the opentelemetry operator and the CR of the collector to generate it

### Describe the solution you'd like

I would like the possibility to add annotations to the service account otel-collector generated by the operator

### Describe alternatives you've considered

Add my own service account which would be used by the collector

**Comment by jaronoff97** [comment]
you should be able to supply your own custom service account for use by the operator. [See this line in our docs](https://github.com/open-telemetry/opentelemetry-operator/blob/3337b9c40419c460542bda8d5ec6f7697c75a2d8/apis/v1alpha1/opentelemetrycollector_types.go#L302-L305). You should be able to create a service account separately from your collector CRD and tell the CRD to use that serviceaccount for its actions. Let me know if this is sufficient. Thank you!

**Comment by paco-sisutech** [comment]
Even though I put the serviceName the otel-collector service account keep getting created
