### ISSUE TITLE
[Instrumentation NodeJS] Bump Node JS dependencies

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2240]
### Component(s)

instrumentation

### Is your feature request related to a problem? Please describe.

Update the NodeJS dependencies to publish a new image and avoid #2236.

### Describe the solution you'd like

.

**Comment by TylerHelmuth** [comment]
When we bump we need to handle https://github.com/open-telemetry/opentelemetry-operator/issues/2237 as well
