### ISSUE TITLE
[target allocator] Avoid disruptions with default PDB

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-operator#2261]
### Component(s)

target allocator

### Is your feature request related to a problem? Please describe.

In order to ensure HA for the target allocator when running with > 1 replicas, the operator should manage a default `PodDisruptionBudget` for the target allocator. Since it is [recommended](https://github.com/open-telemetry/opentelemetry-operator/issues/2159#issuecomment-1739785276) to run the TA with at least 2 replicas to ensure HA, this should be addressed. In case of a node/cluster upgrade, k8s might disrupt all running TA's at the same time, which would result in a non-HA target allocator.
With work being done on #2141, a PDB for the collector has been added already. 

### Describe the solution you'd like

Similar to #2141, a default PDB with `maxUnavailable=1` should be created for the TA by the operator by default.

### Additional context

https://kubernetes.io/docs/tasks/run-application/configure-pdb/

**Comment by JorTurFer** [comment]
It seems that I misunderstood the TA when I supported PDB on the collector, but if it's an HA component, I'm willing to add the PDB to it too

**Comment by jaronoff97** [comment]
@JorTurFer would you be able to work on this?

**Comment by JorTurFer** [comment]
Yes I am, assign it to me and I'll try to do it this weekend

**Comment by jaronoff97** [comment]
yes, but only if the consistent-hashing strategy is set!

**Comment by jaronoff97** [comment]
no problem! I can do that in a follow up. Thank you!

**Comment by cmergenthaler** [comment]
@JorTurFer Thanks for your work! @jaronoff97 the issue can be closed right?

**Comment by jaronoff97** [comment]
yep! Thank you so much @JorTurFer

**Comment by JorTurFer** [comment]
no worries, happy to help :)
