### ISSUE TITLE
[target allocator] Add target allocator affinity configuration

### ISSUE THREAD

**Issue by olehrgf** [open-telemetry/opentelemetry-operator#2263]
### Component(s)

target allocator

### Is your feature request related to a problem? Please describe.

In the HA mode, we want to route target allocator's to the specific nodes.

### Describe the solution you'd like

Add the configuration for the pod affinity as it is specified in the k8s specification.

**Comment by changexd** [comment]
Hi, I am interested in this issue, if the assignment is still available, I would love to contribute to this issue!

**Comment by changexd** [comment]
@jaronoff97 Could you please assign this issue to me if it is still available?

**Comment by swiatekm-sumo** [comment]
Resolved in #2323
