### ISSUE TITLE
Wrong version of nodejs autoinstrumentation pulled due to caching

### ISSUE THREAD

**Issue by FredrikAugust** [open-telemetry/opentelemetry-operator#2271]
### Component(s)

instrumentation

## Description

The wrong version of nodejs autoinstrumentation is pulled leading to our applications having the wrong SDK versions.

## Steps to Reproduce

Unsure, but we've upgraded from v0.40.0 to v0.41.0 (helm).

## Expected Result

As we upgraded to v0.41.0 it should fetch nodejs autoinstrumentation: `0.41.1` which should resolve to `ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs@sha256:177d204e2934264ad25f007e5730b61dc800e1a79811e7df6abf5afa78c115e8`, but it instead resolves to `ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs@sha256:1554492e63472b78b2adfacf2d8ab9d03ee499ecaff540b34c200ca34571fe0b` which I can't find — and which isn't correct.

## Actual Result

It says that

```
Container image "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.41.1" already present on machine
```

Which resolves to the wrong version.

### Kubernetes Version

1.26.5-gke.2100

### Operator version

b6c75a

### Collector version

0.87.0

## Environment

- ArgoCD v2.8.4 for GitOps
- linkerd 2.14 for service mesh

**Comment by jaronoff97** [comment]
I'm honestly very unsure how to confirm this. Were you able to reproduce this?

**Comment by iblancasa** [comment]
I think this should be fixed now.
