### ISSUE TITLE
Upgrade to operator-sdk 0.19.x

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#23]
We are a few versions behind, and one open issue might even get fixed by upgrading (#22).

**Comment by cybervagabond** [comment]
@jpkrohling do you mean to 0.19?

**Comment by jpkrohling** [comment]
I did mean 0.18, and it was done already (#24). Given that I forgot to close this issue, I'll change the title to track the upgrade to 0.19 :-)

**Comment by jpkrohling** [comment]
We are currently blocked by https://github.com/kubernetes-sigs/kubebuilder/issues/1404 (unless I can figure out a workaround).
