### ISSUE TITLE
Monitors for Prometheus exporter in sidecar mode

### ISSUE THREAD

**Issue by lwj** [open-telemetry/opentelemetry-operator#2306]
### Component(s)

operator

### Is your feature request related to a problem? Please describe.

Relates to #1983 

Generating a ServiceMonitor for a collector using  `observability.metrics.enableMetrics: true` works fine using the `deployment` mode, but when generating for the `sidecar` mode, the ServiceMonitor will not scrape metrics from the sidecar.

### Describe the solution you'd like

I don't believe this can be solved using the current implementation with ServiceMonitors, as the operator won't have visibility of the services generated for the injected applications.

Could we use a `PodMonitor` instead in the sidecar case? Perhaps matching on the `sidecar.opentelemetry.io/injected` label. Also won't want to restrict to the namespace the collector is defined in, as it could feasibly be used from any.

**Comment by jaronoff97** [comment]
I think using a podmonitor is a great idea! That should work, and i don't think it's objectionable. Interested in other opinions.

**Comment by yuriolisa** [comment]
Agree with the idea. @jaronoff97 or @lwj  are you willing to send a contribution or can I take this one?

**Comment by jaronoff97** [comment]
I don't have the capacity right now, but happy to assign someone interested!

**Comment by yuriolisa** [comment]
Let me take this one.
