### ISSUE TITLE
Ignore invalid CRDs and pick up valid CRDs with TargetAllocator

### ISSUE THREAD

**Issue by rashmichandrashekar** [open-telemetry/opentelemetry-operator#2309]
### Component(s)

target allocator

## Description
When a podmonitor/svcmonitor CRD has an erraneous field for regex in the relabeling/metric relabeling fields, the crd creation succeeds since it can be a valid string but not a valid regex( ex- .*( ). This causes any subsequent valid CRDs being created from getting picked up.

## Steps to Reproduce
Create a podmonitor/svc monitor CRD with invalid regex (ex - .*()
## Expected Result
[This](https://github.com/open-telemetry/opentelemetry-operator/blob/4b310f5cc94d73d5b29e598a5e2217a7ef62f36f/cmd/otel-allocator/watcher/promOperator.go#L241) only generates the config without actually validating the pod/service monitors selected. It should follow a similar approach to prometheus-operator's [resource selector](https://github.com/prometheus-operator/prometheus-operator/blob/45185c8d5c0e97027f7e99beeb9114c5642aeec3/pkg/prometheus/resource_selector.go#L67) where all the monitors are looped through and validated and the invalid ones are rejected.
## Actual Result
All CRDs fail to be applied when one crd is error prone

### Kubernetes Version

1.25.11

### Operator version

v0.85.0

### Collector version

v0.85.0

### Log output

{"level":"error","ts":"2023-11-04T20:33:52Z","logger":"setup","msg":"Unable to load configuration","error":"error parsing regexp: missing closing ): `^(?:.*()$`","stacktrace":"main.main.func13\n\t/app/main.go:228\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38"}

**Comment by jaronoff97** [comment]
closed by #2328 thank you again @rashmichandrashekar !!
