### ISSUE TITLE
[target allocator] Create ServiceMonitor to monitor target allocator

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-operator#2311]
### Component(s)

target allocator

### Is your feature request related to a problem? Please describe.

With the support for more target allocator specific [metrics](https://github.com/open-telemetry/opentelemetry-operator/pull/2169), it would be nice to have them scraped automatically.

### Describe the solution you'd like

Operator creates ServiceMonitor CR for target allocator, similar to the [one for otel-collectors](https://github.com/open-telemetry/opentelemetry-operator/pull/1874).
Using a config `targetAllocator.observability.metrics.enable` would be helpful to enable/disable exposing and scraping TA metrics.

**Comment by changexd** [comment]
Hi I'm interested in this issue, @jaronoff97 can you please assign this issue to me?
