### ISSUE TITLE
New changes to Dockerfiles requires docker version >= 23.0

### ISSUE THREAD

**Issue by changexd** [open-telemetry/opentelemetry-operator#2321]
### Describe the issue you're reporting

I found changes #2289 in the docker file that uses [Automatic platform ARGs](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope) requires docker version >= v23.0

As I got stuck for a bit to find out that my docker version was older and not supporting this, is it possible to add this to the pre-requisites section in the CONTRIBUTION.md for future contributors also using the older version of docker.

**Comment by swiatekm-sumo** [comment]
You mean for building the images, not running them, right? Yeah, we should make it explicit what version is required in CONTRIBUTING.md

**Comment by pavolloffay** [comment]
@changexd the issue is free to take. You can submit a PR to fix it.
