### ISSUE TITLE
service "opentelemetry-operator-webhook" not found

### ISSUE THREAD

**Issue by IamSatyaonline** [open-telemetry/opentelemetry-operator#2324]
### Component(s)

instrumentation

## Description
Hi 
We are are using cert-manger helm chart cert-manager-v1.13.2 and also deployed the open-telelmetry-operator. When we try to deploy instrumentation object but it's throwing the error below.
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "minstrumentation.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook.optel-demo.svc:443/mutate-opentelemetry-io-v1alpha1-instrumentation?timeout=10s": service "opentelemetry-operator-webhook" not found

## Steps to Reproduce
We are running the command to apply yaml file as below and getting the error.
[root@master-node java]# kubectl -n optel-demo apply -f - <<EOF
> apiVersion: opentelemetry.io/v1alpha1
> kind: Instrumentation
> metadata:
>   name: my-instrumentation
> spec:
>   exporter:
>     endpoint: http://otel-collector:4317
>   propagators:
>     - tracecontext
>     - baggage
>     - b3
>   sampler:
>     type: parentbased_traceidratio
>     argument: "0.25"
>   java:
>     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
>   nodejs:
>     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
>   python:
>     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
>   go:
>     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:latest
> EOF

## Expected Result

We should be able to create instrumentation.
## Actual Result
Failing with error
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "minstrumentation.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook.optel-demo.svc:443/mutate-opentelemetry-io-v1alpha1-instrumentation?timeout=10s": service "opentelemetry-operator-webhook" not found

### Kubernetes Version

v1.27.6

### Operator version

0.88.0

### Collector version

0.88.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
[root@master-node java]# kubectl -n optel-demo apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
  go:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:latest
EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "minstrumentation.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook.optel-demo.svc:443/mutate-opentelemetry-io-v1alpha1-instrumentation?timeout=10s": service "opentelemetry-operator-webhook" not found
[root@master-node java]#
```

### Additional context

Hi ,
Below is the service object which is running with different name
`[root@master-node java]# k get svc -n optel-demo
NAME                                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
cert-manager-webhook                                        ClusterIP   10.111.118.214   <none>        443/TCP    76m
opentelemetry-operator-controller-manager-metrics-service   ClusterIP   10.106.87.110    <none>        8443/TCP   73m
opentelemetry-operator-webhook-service                      ClusterIP   10.108.33.174    <none>        443/TCP    73m

`

**Comment by IamSatyaonline** [comment]
Hi ,
Below is the service object which is running with different name
[root@master-node java]# k get svc -n optel-demo
NAME                                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
cert-manager-webhook                                        ClusterIP   10.111.118.214   <none>        443/TCP    76m
opentelemetry-operator-controller-manager-metrics-service   ClusterIP   10.106.87.110    <none>        8443/TCP   73m
opentelemetry-operator-webhook-service                      ClusterIP   10.108.33.174    <none>        443/TCP    73m

**Comment by IamSatyaonline** [comment]
Hi @TylerHelmuth 
Could you please help us to resolve this issue ?

Thanks,
Satya

**Comment by iblancasa** [comment]
Some questions:
2. Is the operator up and running when you try to create the object?
1. Is it something that just happens with the `Instrumentation` CR or also with `OpenTelemetryCollector`?

**Comment by bryan-aguilar** [comment]
Service name it's looking for `opentelemetry-operator-webhook` and the service name in your namesapce `opentelemetry-operator-webhook-service`. This is most likely because you tried to install the operator with both the helm chart and the kubectl method. 

Uninstall the operator, clean up all dangling resources, and reinstall with only one method.

**Comment by pavolloffay** [comment]
Closing, please reopen @IamSatyaonline if the issue persist or you have more information to share

**Comment by MarahAbu** [comment]
Hi,
I have the same issue, in my case it's looking for `opentelemetry-operator-webhook-service` in `opentelmetry-operator-system` ns and I have opentelemetry-operator-webhook in my namespace
Operator version: v0.86.0
collector version: :0.87.0
k8s version: v1.27.8
I deployed the operator with argocd and used autoGenerateCert

any idea what's the reason for the error?

**Comment by shishir84** [comment]
i cleaned up everything and re-installed using below helm chart. and worked for me.
helm install  -n opentelemetry-operator-system --set admissionWebhooks.certManager.enabled=false --set admissionWebhooks.certManager.autoGenerateCert=true  opentelemetry-operator open-telemetry/opentelemetry-operator

**Comment by sonerdm** [comment]
I faced a similar problem, in my case, I thought I cleared all old otel resources but missed deleting mutating webhook configs. Deleting the hook configs and installing them with helm again solved my problem.

**Comment by holmesb** [comment]
Operator looks for opentelemetry-operator-webhook-service, but helm deploys opentelemetry-operator-webhook. 

Disabling Cert Manager webhook cert creation isn't a fix. Need to relax hard-coded service name either in operator, helm chart or both. Regardless, this issue needs reopening.

**Comment by igorestevanjasinski** [comment]
I'm facing the same issue, any fix ?

**Comment by jdiegosierra** [comment]
Hello, I found how to fix the issue. If you run `kubectl get ValidatingWebhookConfiguration` you will see multiple resources created for the OpenTelemetry operator webhook. In my case:

```bash
k get ValidatingWebhookConfiguration
NAME                                                             WEBHOOKS   AGE
opentelemetry-operator-opentelemetryoperator-validation          4          18d
otel-operator-opentelemetry-operator-validation                  4          49d
```

So you just have to delete the old one.

This happened to me because I deployed the operator with different names, setting the _nameOverride_ value

**Comment by jdiegosierra** [comment]
Hi, I found how to fix the issue. If you run `kubectl get ValidatingWebhookConfiguration` you should see at least two resources related with the OpenTelemetry operator. In my case:
```bash
k get ValidatingWebhookConfiguration
NAME                                                             WEBHOOKS   AGE
opentelemetry-operator-opentelemetryoperator-validation          4          18d
otel-operator-opentelemetry-operator-validation                  4          49d
```
Same for MutatingWebhookConfiguration
```bash
k get MutatingWebhookConfiguration
NAME                                                    WEBHOOKS   AGE
opentelemetry-operator-opentelemetryoperator-mutation   3          19d
otel-operator-opentelemetry-operator-mutation           3          49d
```

So you just have to delete the old ones.

This happened to me because I deployed the operator with different names, setting the _nameOverride_ value.

**Comment by prashant-shahi** [comment]
Even the namespace was stuck in terminating when deleted and unable to patch the finalizers.

After deleting the opentelemetry `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration`, I was able to cleanup and re-install.
