### ISSUE TITLE
Annotating a deployment with inject-sdk is not working

### ISSUE THREAD

**Issue by rassmate** [open-telemetry/opentelemetry-operator#2343]
### Component(s)

instrumentation

## Description
I annotate my deployment with instrumentation.opentelemetry.io/inject-sdk: "true" according to documentation
## Steps to Reproduce
Creating local cluster.
Using operator version  (also tried with 0.87.0)

Annotate deployment with 
 instrumentation.opentelemetry.io/inject-sdk: "true"

## Expected Result
OTEL_RESOURCE_ATTRIBUTES environment variable set

## Actual Result
No OTEL_RESOURCE_ATTRIBUTES environment variable set

### Kubernetes Version

1.27.2

### Operator version

0.88.0

### Collector version

0.87.0

## Environment
OS: Mac m2

**Comment by iblancasa** [comment]
Could you check with the files provided as part of [the `instrumentation-sdk` E2E tests](https://github.com/open-telemetry/opentelemetry-operator/tree/d76cf668d95bf70fff8e473cfb163f35d500b911/tests/e2e-instrumentation/instrumentation-sdk)?

**Comment by rassmate** [comment]
Realized when reading the integration test files I deployed the Instrumentation in a different namespace so I had to do
instrumentation.opentelemetry.io/inject-sdk: "<mynamespace>/<myinstrumentationname>"

Sorry to bother you but it is resolved now.
