### ISSUE TITLE
Use k8s 1.28 native sidecar for OTEL collector sidecar mode

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#2376]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

The k8s 1.28 introduced "native sidecar" mode (init-container with `restartPolicy: Always`) https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/. 

The approach makes sure the sidecar starts/finishes before the application. 

### Describe the solution you'd like

Use the native sidecar for collector sidecar on k8s 1.28 and above.

**Comment by frzifus** [comment]
I would like to give that a try.

**Comment by angelokurtis** [comment]
Hey @frzifus, are you currently working on this task? If not, I'd be interested in contributing to it.

**Comment by im-aIex** [comment]
Any update on getting this support added? Or any known workarounds to get the new `restartPolicy: Always` included in the meantime?

**Comment by jasonious** [comment]
We are running into this while using gcsfuse annotation which creates a native sidecar, and then the pods can't be terminated. Any estimated timelines for when/if the solution will be merged in? It appears to not have any movement on it for a few months.

**Comment by frzifus** [comment]
Hey, I will try to get this ready on the weekend. :)
