### ISSUE TITLE
Service Name

### ISSUE THREAD

**Issue by Garrybac** [open-telemetry/opentelemetry-operator#2380]
### Component(s)

instrumentation

### Describe the issue you're reporting

Dear All,

As I have set annotations:
instrumentation.opentelemetry.io/inject-java: "opensearch/otel-instrumentation"
I see in Jaeger Server got the service name as deployment name. How could I change or set the service name in annotations?

Thanks

**Comment by Garrybac** [comment]
I have found just add env to change the service name.

**Comment by rrhubenov** [comment]
@Garrybac Hi, do you remember what you meant by 'add env'? I'm having the same issue
