### ISSUE TITLE
beyla integration

### ISSUE THREAD

**Issue by wibed** [open-telemetry/opentelemetry-operator#2387]
### Describe the issue you're reporting

https://grafana.com/docs/grafana-cloud/monitor-applications/beyla/configure/export-modes/

the documentation states to export data via scrape method, unlike prometheus does.
is there already an integration for this or has one to be written especially to integrate beyla into the landscape.

i am new to this, if you could excuse my novelty if this question seems redundant, would be greatly appreciated.

**Comment by swiatekm-sumo** [comment]
There's no support for auto instrumentation using Beyla, but if you set up instrumentation manually, you can configure it to send data to an Otel collector provisioned by the operator.
