### ISSUE TITLE
Target Allocator support multiple prometheus receivers

### ISSUE THREAD

**Issue by zh-w** [open-telemetry/opentelemetry-operator#2389]
### Component(s)

operator, target allocator

### Is your feature request related to a problem? Please describe.

When I collect different targets through the service discovery mechanism of prometheus receiver, the metrics of these targets need to be processed through different pipelines, so multiple prometheus receivers are configured, such as prometheus/a, prometheus/b. But only the receiver named prometheus is going to be parsed and generates target allocator‘configuration by operator .

`
  exporters:
    file/no_rotation:
      path: ./data
  extensions:
  processors:
    batch: {}
  receivers:
    prometheus/a:
      config:
        global:
          scrape_interval: 30s
        scrape_configs:
          - job_name: cadvisor
            metrics_path: /metrics/cadvisor
            tls_config:
              insecure_skip_verify: true
            kubernetes_sd_configs:
              - role: node
      target_allocator:
        endpoint: http://otel-targetallocator
        interval: 30s
        collector_id: ${POD_NAME}
    prometheus/b:
      config:
        global:
          scrape_interval: 30s
        scrape_configs:
            - job_name: node-exporter
              scrape_interval: 30s
              kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                  - kube-system
                selectors:
                - role: pod
                  label: app=node-exporter
              relabel_configs:
              - source_labels: 
                - __meta_kubernetes_pod_container_name
                - __meta_kubernetes_pod_container_port_name
                separator: ;
                regex: node-exporter;metrics
                action: keep
      target_allocator:
        endpoint: http://otel-targetallocator
        interval: 30s
        collector_id: ${POD_NAME}
  service:
    extensions:
    pipelines:
      metrics/cadvisor:
        exporters:
          - file/no_rotation
        processors:
          ...
        receivers:
          - prometheus/a
      metrics/node-exporter:
        exporters:
          - file/no_rotation
        processors:
          ...
        receivers:
          - prometheus/b
`

### Describe the solution you'd like

Target allocator support multiple prometheus receiver.

**Comment by swiatekm-sumo** [comment]
Can you explain a bit more about what you're trying to achieve with this? Even if we allow it, you'll have multiple Prometheus receivers scraping the same data, which I don't see the point of.

**Comment by jaronoff97** [comment]
+1 to the above, I would recommend using a single prometheus receiver, and instead relying upon something like the [routing connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/routingconnector) to do processing on different metrics.

**Comment by zh-w** [comment]
> Can you explain a bit more about what you're trying to achieve with this? Even if we allow it, you'll have multiple Prometheus receivers scraping the same data, which I don't see the point of.

let me clarify this，the point is that i need multiple Prometheus receivers scraping the different data. For example，receiver prometheus/node-exporter scraping metrics from node-exporter and another receiver prometheus/ksm scraping metrics from kube-state-metrics. These two types of metrics require different processors，so i can't put them into one prometheus receiver.
Thanks to @jaronoff97's suggestion, I may be able to achieve my purpose through the [routing connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/routingconnector)

**Comment by jaronoff97** [comment]
Great, thank you. I'm curious, what processing changes based on those scrape jobs? From my experiences, those translations tend to be uniform.

**Comment by zh-w** [comment]
> Great, thank you. I'm curious, what processing changes based on those scrape jobs? From my experiences, those translations tend to be uniform.

Not just ksm and node-exporter metrics, from my use case, we need to add some k8s metadata attributes to ksm metrics through the k8sattribute processor, but for metrics from a business pod collected by pod/service monitor, we do not need to do this. Those two kind of metric targets are discovered by target allocator.This is why i need split those two kind of metrics into two pipelines.

**Comment by swiatekm-sumo** [comment]
To be able to have two different Prometheus receivers for these types of metrics would require two separate Target Allocators as well. That's not impossible to do, but it's much more complicated than just using a routing connector.
