### ISSUE TITLE
Add securityContext configuration for TargetAllocator

### ISSUE THREAD

**Issue by frances-barcelos** [open-telemetry/opentelemetry-operator#2397]
### Component(s)

target allocator

### Is your feature request related to a problem? Please describe.

We have enforced OPA policies which means we have to set runAsUser in our deployments. Can we have the option to set the securityContext for the targetallocator?

`admission webhook \"webhook.openpolicyagent.org\" denied the request: runAsUser not specified kind`

### Describe the solution you'd like

 Add securityContext configuration for Target Allocator.
 
`spec:
 mode: statefulset
 targetAllocator:
   enabled: true
   runAsUser: 65532`

**Comment by jaronoff97** [comment]
Thanks for this issue – this is certainly something we should add, and we're actually looking in to splitting out the target allocator in to its own CRD (see [here](https://github.com/open-telemetry/opentelemetry-operator/pull/2320/files) for the beginning of that work). I think this is probably worth doing before then though. Would you be able to work on this? [Here's](https://github.com/open-telemetry/opentelemetry-operator/pull/2323) an example of what to do

**Comment by frances-barcelos** [comment]
Sure! Would you mind assigning this to me please? Thanks
