### ISSUE TITLE
Release script is updating the manifests with a wrong version pattern

### ISSUE THREAD

**Issue by JasonTruter** [open-telemetry/opentelemetry-operator#240]
![image](https://user-images.githubusercontent.com/79902798/113873899-891a2980-97b5-11eb-8415-6538fe046f37.png)

Version 23.0

For some reason when I applied version 23 manifest to the cluster. The pod has an error "Failed to pull image "quay.io/opentelemetry/opentelemetry-operator:0.23.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/opentelemetry/opentelemetry-operator:0.23.0 not found: manifest unknown: manifest unknown"

**Comment by jpkrohling** [comment]
Thanks for the report! For some reason, the release script generated the manifest without the v in the version. It should be `quay.io/opentelemetry/opentelemetry-operator:v0.23.0` instead. I just published a tag following what the released manifest expects, but will keep this open so that we fix it properly for 0.24.0.

**Comment by JasonTruter** [comment]
No problem, I've just hopped on board to get started running a simple collector. 
I'm using the previous version fine for now.

**Comment by chasekiefer** [comment]
Mind if I give this a try? The fix would be to modify the creation of opentelemetry-operator.yaml so it has a version :v0.24.0 instead of :0.24.0, right?

**Comment by jpkrohling** [comment]
Go ahead! Once you find the place to fix it, try to look at the git history for that file, as I think this was fixed and possibly reverted before. I think there's a place (goreleaser?) that needs the version to not have the v prefix, so, fixing this in one place might potentially break something else.

**Comment by chasekiefer** [comment]
Updating the IMG var instead of VERSION should avoid any breaking changes.
