### ISSUE TITLE
[targetallocator] Evaluate relabel rules prior to assignment

### ISSUE THREAD

**Issue by diurnalist** [open-telemetry/opentelemetry-operator#2405]
### Component(s)

target allocator

### Is your feature request related to a problem? Please describe.

Currently we observe that the target allocator performs no pruning of targets via `keep` relabel configurations, and in general it looks like the relabel rules are applied on the opentelemetry collector's prometheusreceivers instead. This can lead to really large target lists being allocated over a few pods in a deployment managed by the operator. The targetallocator is not able to efficiently allocate the targets b/c it doesn't (yet) know which ones should actually be preserved as scrape targets, if it is not applying relabel rules.

### Describe the solution you'd like

I can imagine a solution where the targetallocator applies relabel rules before assigning targets to each pod it is allocating over. The otel collectors could either also apply the relabel rules themselves (a bit weird but theoretically fine), or all the relabel logic could be done in the targetallocator, and then the output of those rules could be passed down to the otel collectors themselves (at which point they wouldn't really have or need __meta labels.)

Forgive me if my understanding of Prometheus and relabel rules is incorrect or incomplete!

### Additional context

We do not utilize the prometheus-operator and so aren't using ServiceMonitors or things like that, perhaps the ergonomics of those are different.

**Comment by jaronoff97** [comment]
no problem! and do let me know if you have any issues with the relabel strategy :)
