### ISSUE TITLE
Make getScrapeConfigHash method exported instead of private  

### ISSUE THREAD

**Issue by rashmichandrashekar** [open-telemetry/opentelemetry-operator#2435]
### Component(s)

target allocator

### Describe the issue you're reporting

Change the visibility of [getScrapeConfigHash](https://github.com/open-telemetry/opentelemetry-operator/blob/0ce68dcfeaab7db172cbcef4c2935cf0d2de547a/cmd/otel-allocator/target/discovery.go#L140C6-L140C25) method in target allocator's target package so that it can be reused in [prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ece9f7ceb1a4111e40f96222412d784ac4dccc2a/receiver/prometheusreceiver/metrics_receiver.go#L143) in the open telemetry collector.
This can use used to fix the [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29313) where regex changes in scrape config for metric relabelling doesn't get picked up when using target allocator.

**Comment by swiatekm-sumo** [comment]
Do we need these methods to be identical? Exporting the method and depending on the target allocator package in Prometheus receiver is a lot of additional coupling, and I'd rather not do it if it's not absolutely necessary. Can't the receiver just implement the hashing its own way?

**Comment by jaronoff97** [comment]
I agree with @swiatekm-sumo, I don't think we should expose this publicly as it will create a cyclic dependency between ourselves and the collector which we should avoid.

**Comment by rashmichandrashekar** [comment]
@swiatekm-sumo -  I was thinking having them identical gives us the benefit of keeping the behavior consistent between the 2 target allocator components. But, if we want to avoid the additional coupling I could just add the same method there too. 

@jaronoff97 - Sounds good. Yes, the cyclic dependency will be a concern. Looks like the cons outweigh the pro here. I can just add the same method in the receiver too.
