### ISSUE TITLE
Service account is created even when one is specified in targetallocator spec

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#2443]
### Component(s)

target allocator

## Description

The operator creates a ServiceAccount for the Target Allocator even if `spec.targetAllocator.serviceAccount` is set. This is basically the same bug as #2372, but for the Target Allocator manifests.

### Kubernetes Version

1.27

### Operator version

0.90.0

### Collector version

0.90.1

**Comment by jaronoff97** [comment]
🤦 @swiatekm-sumo would you be able to get this in prior to #2443

**Comment by swiatekm-sumo** [comment]
Prior to this very issue, @jaronoff97? I am very talented, but not yet a time traveler.

But yeah, I can do it before the next release.

**Comment by jaronoff97** [comment]
🤦 this is what i get for bad typing!! i meant to do #2433 😓 i was 10 off 😆

**Comment by swiatekm-sumo** [comment]
Fixed in #2445
