### ISSUE TITLE
Add support for configuring the K8s resources for injected collectors

### ISSUE THREAD

**Issue by jfiedler** [open-telemetry/opentelemetry-operator#247]
It would be nice if K8s resources of the injected collectors (for sidecar mode) could be configured via the operator CRD. This is an important requirement when using horizontal pod autoscalers later on. Containers in a pod that have no resource requests can cause issues with HPA.

**Comment by jpkrohling** [comment]
Would you like to contribute with a PR? Should be relatively easy to do it: add a `Resources` node here, similar to what `v1.Container` has:

https://github.com/open-telemetry/opentelemetry-operator/blob/33f21cc8292f98c0a0170dde340ef571ff837008/api/v1alpha1/opentelemetrycollector_types.go#L23-L79

Then apply it here:
https://github.com/open-telemetry/opentelemetry-operator/blob/33f21cc8292f98c0a0170dde340ef571ff837008/pkg/collector/container.go#L66-L72

**Comment by jfiedler** [comment]
Sure. I will give it a shot.
