### ISSUE TITLE
Add PodSecurityContext to Target Allocator

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#2495]
Removed in #2492 we need to bring this back :) 

_Originally posted by @jaronoff97 in https://github.com/open-telemetry/opentelemetry-operator/pull/2492#discussion_r1444827579_

**Comment by husnialhamdani** [comment]
Can I work on this @jaronoff97?

**Comment by jaronoff97** [comment]
@husnialhamdani sure! I'll assign you. Thank you :bow:

**Comment by swiatekm-sumo** [comment]
Resolved in #2500
