### ISSUE TITLE
Enable RBAC creation by default

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#2507]
### Is your feature request related to a problem? Please describe.

https://github.com/open-telemetry/opentelemetry-operator/pull/2394 introduced RBAC capabilities in the operator.
The operator has RBAC to create cluster role and bindings. However the creation of the RBAC for given processors is disabled by default. 

### Describe the solution you'd like

The proposal is to enable RBAC creation by default. The operator should check with SAR if it can create it (there is already a package for it).

**Comment by iblancasa** [comment]
> The proposal is to enable RBAC creation by default. The operator should check with SAR if it can create it (there is already a package for it).

Right now, we are giving permissions to the OpenTelemetry Operator Service Account permissions to create the `ClusterRoles` and `ClusterRoleBindings` (as part of the manifest). So, the current package to check if one service account has permission to manage another resource, would return `true` always for `ClusterRoles` and `ClusterRoleBindings`  and the operator service account, right? To make this thing work properly, we would need to remove the permissions in the operator service account and document how to add those permissions or something.

**Comment by pavolloffay** [comment]
This is related to https://github.com/open-telemetry/opentelemetry-operator/issues/2588 

Closing as the RBAC will be just documented
