### ISSUE TITLE
[opentelemetry-operator] - Add support for imagePullSecrets for collectors

### ISSUE THREAD

**Issue by alita1991** [open-telemetry/opentelemetry-operator#2521]
I encounter a scenario where I must retrieve images from a private registry. While I successfully utilized the "imagePullSecrets" feature within the helm chart for the otel-operator, I encountered difficulty in figuring out how to apply the same mechanism to the collectors generated by the otel-operator.

**Comment by TylerHelmuth** [comment]
I believe this could be handled via the OpenTelemetryCollector CR or via the service account the Collector is using.

**Comment by bdschaap** [comment]
The Instrumentation CR needs this functionality as well.  Should a separate issue be opened for that?

**Comment by jaronoff97** [comment]
Yes, our recommendation is to use the service account for the image pull secrets. I think this issue could be migrated to be a docs problem, as we don't make it very clear what needs to happen.

**Comment by yuriolisa** [comment]
@jaronoff97, I will create documentation explaining how to use it.
