### ISSUE TITLE
Is there a way to specify which Otel Collector to use within the Otel Operator?

### ISSUE THREAD

**Issue by stephenhong** [open-telemetry/opentelemetry-operator#254]
Hello team, I'm working on a project leveraging the OpenTelemetry Collector. I created a custom trace exporter and it is not on the OpenTelemetry Collector repo (https://github.com/open-telemetry/opentelemetry-collector) or the OpenTelemetry Collector Contrib repo (https://github.com/open-telemetry/opentelemetry-collector-contrib). Is there a way to configure the Otel Operator so that it uses the Otel Collector on my local machine or on my repository?

**Comment by jpkrohling** [comment]
You can wrap your collector in a container image and publish it in a registry where the operator has access, such as a registry within your Kubernetes cluster. Then, specify the image location  as part of the .Spec.Image property: https://github.com/open-telemetry/opentelemetry-operator/blob/db40230d99040201ba7b85a64700788392e96b62/api/v1alpha1/opentelemetrycollector_types.go#L42

**Comment by stephenhong** [comment]
Thank you so much!
