### ISSUE TITLE
Detection of Python packages during an autoinstrumentation with Operator

### ISSUE THREAD

**Issue by sy-bee** [open-telemetry/opentelemetry-operator#2559]
### Component(s)

operator

### Describe the issue you're reporting

Hello!

The issue I describe here is a documentation issue which causes extra confusion around how Python autoinstrumentation works in regards to "detecting packages" in K8s operator environment.

When using autoinstrumentation without an operator, it is expected at some point to install `opentelemetry-distro` which has a helper script `opentelemetry-bootstrap`. The bootstrap script can then be used to detect and install necessary packages to the Python environment via `opentelemetry-bootstrap -a install`. Then the application can be started with the `opentelemetry-instrument` wrapper script which takes care of monkey patching and instrumenting the app.

Now this seems to be different in case when K8s Operator is used with an init container. From what I see, init container image contains [all of the instrumentation packages](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/python/requirements.txt) and installs them regardless if the libraries are in use by the app or not. It is not clear whether this was a design decision or the `opentelemetry-bootstrap` came to existence at a later stage as an optimisation to the list of packages which are installed, hence the Python Operator image simply doesn't use it yet.

Text on [this](https://opentelemetry.io/docs/kubernetes/operator/automatic/#python-excluding-auto-instrumentation) page implies that we do indeed "detect" Python packages: _By default the Python auto-instrumentation will detect the packages in your Python service and instrument anything it can._ It seems that this applies only to the instrumentation part and not the installation? Or am I missing the bit where operator indeed detects Python packages to install?

Thank you!

For context:
* https://github.com/open-telemetry/opentelemetry-operator/pull/524
* https://github.com/open-telemetry/opentelemetry-operator/issues/455

**Comment by iblancasa** [comment]
I think it was a design decision to make it similar to how other languages do. The problem I can see with using the `opentelemetry-bootstrap` CLI is that the packages will be installed each time you create a pod with auto instrumentation.

**Comment by sy-bee** [comment]
I guess the documentation could be updated to reflect that the init container already has lots of instrumentation libraries preinstalled as opposed to the non operator approach whereby instrumentation packages are installed based on "detected" libraries in the code. I've spent some time trying to find where does the operator "detects" Python modules to install, but apparently this bit is not happening when using the Operator approach (for better or worse).

**Comment by sy-bee** [comment]
Created a PR to address this: https://github.com/open-telemetry/opentelemetry.io/pull/3868

Adjusted the wording to match the description in other languages.
