### ISSUE TITLE
expectedServices function not copying desired spec

### ISSUE THREAD

**Issue by bhiravabhatla** [open-telemetry/opentelemetry-operator#256]
https://github.com/open-telemetry/opentelemetry-operator/blob/db40230d99040201ba7b85a64700788392e96b62/pkg/collector/reconcile/service.go#L182-L199

I guess, we should be copying desired.Spec to updated.Spec if I am not wrong. - 

```go
  updated.Spec = desired.Spec
```
If we dont do that service spec wont be updated if some one adds a new receiver in config or explicit port in Spec.Ports of collector.

**Comment by jpkrohling** [comment]
From what I remember, we can't simply copy the Spec, as the clusterIP has to either be empty or None. The service controller will then change the value to a real IP if it's empty, and an update of this resource will fail if we specify the IP ourselves. So, I prefer to cherry-pick the properties that we want to override.

**Comment by bhiravabhatla** [comment]
As of now we are not cherrypicking Spec.Ports. I think we should then?

**Comment by jpkrohling** [comment]
Could you clarify on "ports added"? Do you mean that users might add ports to a service?

**Comment by bhiravabhatla** [comment]
I meant some one can add a new receiver in opentelemetry collector CR config or a new port in CR spec.ports

**Comment by jpkrohling** [comment]
Right, the new desired ports should override the current list of ports.

**Comment by bhiravabhatla** [comment]
Yep :).

**Comment by thib92** [comment]
Should we only copy the ports? Otherwise, which fields of the Service spec would we wish to copy?

**Comment by jpkrohling** [comment]
Here's the reference docs for the Service object. I think copying the ports should be sufficient, but review it as well and see if you have another suggestion.
