### ISSUE TITLE
Creating custom spans on top of auto-instrumentation 

### ISSUE THREAD

**Issue by NoamBuzaglo** [open-telemetry/opentelemetry-operator#2560]
### Component(s)

instrumentation

### Describe the issue you're reporting

Hey
I would like to add custom spans on Node.Js application which auto instrumented by using `opentelemetry-operator`.
I'm using it by adding `init-container` to deployment inside K8S which inject and execute this [script](https://github.com/open-telemetry/opentelemetry-operator/blob/0821383bfd392366c0e7065041e2c3af4ff57b33/autoinstrumentation/nodejs/src/autoinstrumentation.ts) before the application starts.

Unfortunately since all examples i've seen before, i need the `TraceProvider` to be able adding spans to the "live" trace which created by the `auto instrumented` script.

I couldn't find a way to get this provider inside the application container so each span i've added manually i saw the traceId and spanId as `000000000000`.

NOTE:  I don't want to initialize the SDK in other way which is not by using `init-container`.

Thanks!

**Comment by iblancasa** [comment]
You need to initialize the Trace using the context. Check [for context propagation](https://opentelemetry.io/docs/concepts/context-propagation/).

**Comment by NoamBuzaglo** [comment]
> You need to initialize the Trace using the context. Check [for context propagation](https://opentelemetry.io/docs/concepts/context-propagation/).

Indeed but I don't have access to the context which created by the auto instrumentation.

**Comment by iblancasa** [comment]
@NoamBuzaglo so, the problem is not related to the Kubernetes operator but to the SDK.
You can ask [here](https://cloud-native.slack.com/archives/CJFCJHG4Q).

**Comment by NoamBuzaglo** [comment]
> @NoamBuzaglo so, the problem is not related to the Kubernetes operator but to the SDK. You can ask [here](https://cloud-native.slack.com/archives/CJFCJHG4Q).

Not sure why it related to the SDK
In case of using the SDK without the k8s-operator i can have an access to the `TraceProvider` so that i can get the same tracer with the same context of the auto instrumentation tracer.
