### ISSUE TITLE
Documentation for `observability.metrics.enableMetrics` truncated

### ISSUE THREAD

**Issue by reknih** [open-telemetry/opentelemetry-operator#2561]
### Component(s)

operator, collector

### What happened?

I am currently trying to wrap my head around how to let the OpenTelemetry Collector expose a `ServiceMonitor`. While doing so, I checked the [API docs](https://github.com/open-telemetry/opentelemetry-operator/blob/0821383bfd392366c0e7065041e2c3af4ff57b33/docs/api.md#opentelemetrycollectorspecobservabilitymetrics) for the Collector CRD. In there, it contains the following description of the `enableMetrics` key:

> EnableMetrics specifies if ServiceMonitor or PodMonitor(for sidecar mode) should be created for the service managed by the OpenTelemetry Operator. The operator.observability.

This description is obviously truncated. The issue apparently was introduced in PR #1983. 

It would be great if the full docs entry could be added back as the instruction to enable the `operator.observability.prometheus` feature gate seems pretty vital to make use of this key.

Tangent: I'd really appreciate more thorough docs somewhere on how to set up the OTel Collector with its Prometheus exporter and a Service/PodMonitor!

### Kubernetes Version

1.27.7

### Operator version

v0.92.1

### Collector version

v0.92.0

## Environment
Microsoft AKS

**Comment by iblancasa** [comment]
It seems `crdoc` is the one truncating the description (in the CVS is shown properly).

> Tangent: I'd really appreciate more thorough docs somewhere on how to set up the OTel Collector with its Prometheus exporter and a Service/PodMonitor!

When the feature gate is enabled and `enableMetrics` is `true`, the `ServiceMonitor` is created. You can check the E2E test to see an example configuration:
- https://github.com/open-telemetry/opentelemetry-operator/blob/main/tests/e2e-prometheuscr/create-sm-prometheus-exporters/02-install.yaml
- https://github.com/open-telemetry/opentelemetry-operator/blob/main/tests/e2e-prometheuscr/create-sm-prometheus-exporters/02-assert.yaml

**Comment by iblancasa** [comment]
Actually is this:
```$(KUSTOMIZE) build config/crd -o $$TMP_DIR/crd-output.yaml```
