### ISSUE TITLE
HPA is only added with autoscaler setting, the reverse is ignored

### ISSUE THREAD

**Issue by JustinMason** [open-telemetry/opentelemetry-operator#2568]
## Description
Adding the autoscaler to a collector deploys a HPA crd, but it does not remove the CRD if the autoscaler section is removed.
operator logs show this instead.
`hpa field is unset in Spec, skipping autoscaler creation`

## Steps to Reproduce
Deploy a Collector with the autoscaler in the spec.
Validate HPA is deployed for collector.
Remove autoscaler from spec.
HPA CRD remains.

## Expected Result
HPA CRD for collector to get deleted.

## Actual Result
HPA CRD remains.

### Kubernetes Version

v1.25.15-gke.1115000

### Operator version

v0.92.1

### Collector version

v0.92.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
hpa field is unset in Spec, skipping autoscaler creation
```

**Comment by yuriolisa** [comment]
Hi @JustinMason, 

I have just tested it, and the HPA is not being deleted when we remove it from the OpenTelemetryCollector instance. So, I'll send a fix for that issue.
