### ISSUE TITLE
Service exposes ports for receivers which are not enabled

### ISSUE THREAD

**Issue by bhiravabhatla** [open-telemetry/opentelemetry-operator#257]
If I understand open-telemetry config correctly, a receiver is enabled only if its mentioned in  service section of config

```
Configuring a receiver does not enable it. Receivers are enabled via pipelines within the service section.
```
Reference - https://opentelemetry.io/docs/collector/configuration/

In our current implementation of service reconciliation, while fetching inferred Ports - I do not see this check. 

https://github.com/open-telemetry/opentelemetry-operator/blob/db40230d99040201ba7b85a64700788392e96b62/pkg/collector/adapters/config_to_ports.go#L35

https://github.com/open-telemetry/opentelemetry-operator/blob/db40230d99040201ba7b85a64700788392e96b62/pkg/collector/reconcile/service.go#L78-L82

This would imply that we would  have disabled receiver ports in service spec. Is this expected. Or am I missing something?

**Comment by jpkrohling** [comment]
You are absolutely correct. Our logic should indeed check if the receiver is being used in any pipelines before deciding to open the port.

**Comment by bhiravabhatla** [comment]
I can work on this once I am done with unit test cases

**Comment by bhiravabhatla** [comment]
@jpkrohling  - started working on this. Have a question, as of now in operator we are not umarshalling collector config to a struct. We are unmarshalling it to map[interface]interface{}.

To get the list of enabled receivers  it would be easier to unmarshall the config into a Config struct - rather than recursively parsing through a map[interface]interface{}.  opentelemetry-collector code base already has logic to unmarshall the config. Can we reuse it?

**Comment by jpkrohling** [comment]
I think @pavolloffay, @rubenvp8510, and now you have proposed that. While I think that not having a dependency on the otel-collector API is advantageous, as the interface the collector has with its users is indeed the config as a string (and we are one of such users), I do see the benefits of reusing their config structs.

If both @pavolloffay and @rubenvp8510 are still of this opinion, I'm OK with merging a PR dedicated to introducing this new pattern.

**Comment by yuriolisa** [comment]
@bhiravabhatla are you still working on that issue?
