### ISSUE TITLE
Change instrumentation feature gates into normal command-line flags

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#2582]
### Component(s)

operator

### Describe the issue you're reporting

We currently use operator feature gates to control which instrumentations are enabled. The intent is to keep this configurable forever, so cluster operators can make this decision for the whole operator deployment. Feature gates are a suboptimal choice for this, however, as they assume a strict stage progression from `Alpha` to `Stable`, and eventually are intended to be removed completely.

We should change these into normal command-line flags for the operator while it's still a relatively painless change for our users.

As an aside, we also can't upgrade to newer versions of the otel featuregate package, as some of our gate names contain dashes, which the package now forbids. This is starting to block upgrades of other packages which depend on the featuregate package, for example #2570. In this case, the responsible gates are `operator.autoinstrumentation.apache-httpd` and `operator.autoinstrumentation.multi-instrumentation`, so we should start with those.

Flags migrated:
- [x] `operator.autoinstrumentation.multi-instrumentation`
- [x] #2670
- [x] #2671
- [x] #2672
- [x] #2673
- [x] #2674
- [x] #2675
- [x] #2676

**Comment by changexd** [comment]
Hi @swiatekm-sumo I am interested to helping this out, so far I'm planning to add flags to `config.Config` and put it in `instPodMutator`, however I wonder if we should separate those into different configs?

**Comment by swiatekm-sumo** [comment]
I think it's fine if they're part of the operator's main config struct for now. We can refactor this later if it's unwieldy. Right now we don't have a lot of configuration for any individual instrumentation.

**Comment by swiatekm-sumo** [comment]
I've updated the issue with a checklist for the flags that need to be migrated. I'd like to keep this issue open to track the procedure across all the flags.

**Comment by jaronoff97** [comment]
@swiatekm-sumo i opened up issues for each of these so we don't need to worry about closing the parent issue

**Comment by artem-nefedov** [comment]
Feature gate `operator.autoinstrumentation.multi-instrumentation` was removed but an example in README still uses it

**Comment by swiatekm-sumo** [comment]
With #2834 merged, we are done.
