### ISSUE TITLE
PVC does not increase after initially set

### ISSUE THREAD

**Issue by JustinMason** [open-telemetry/opentelemetry-operator#2587]
## Description

After deploying a collector with a pvc of 5Gi, Increasing it later doesn't not increase the PVC.

## Steps to Reproduce
Deploy Collector and set the volumeClaimTemplates storage to `5Gi`.
Update the CRD and increase to `50Gi`
Check PVCs to validate new size.

## Expected Result

PVCs increase to `50Gi`

## Actual Result
PVSs remain the same, `5Gi`.

### Kubernetes Version

v1.27.7-gke.1121000

### Operator version

v0.92.1

### Collector version

v0.92.0

## Environment
GKE

### Additional context

I have to manually delete the PVC before they get created with the new size.

**Comment by yuriolisa** [comment]
@JustinMason , could you please check it if your StorageClass manifests has this parameter set? 

`allowVolumeExpansion: true`
