### ISSUE TITLE
Replace the create-rbac-permissions flag by just checking if the SA has permissions

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2588]
### Is your feature request related to a problem? Please describe.

After fixing #2525, the `ClusterRole` and `ClusterRoleBinding` are not part of the operator manifest anymore.

### Describe the solution you'd like

During a SIG call, we agreed to document that those permissions need to be added to the operator service account if you want the operator to, automatically, generate the RBAC resources for those processors that need it. Also, instead of having the `create-rbac-permissions`  flag, we can check if the SA has permissions to handle those resources and reconcile them.

**Comment by shashankram** [comment]
> During a SIG call, we agreed to document that those permissions need to be added to the operator service account if you want the operator to, automatically, generate the RBAC resources for those processors that need it.

What was the reason for this?
How does a user know what RBAC perms a component managed by the operator needs? Isn't that the purpose of an operator, to simplify UX?

**Comment by iblancasa** [comment]
> > During a SIG call, we agreed to document that those permissions need to be added to the operator service account if you want the operator to, automatically, generate the RBAC resources for those processors that need it.
> 
> What was the reason for this? How does a user know what RBAC perms a component managed by the operator needs? Isn't that the purpose of an operator, to simplify UX?

The permissions need to be added anyway to the operator (because if the operator has no permissions over one resource, cannot grant permissions over other resources).

**Comment by shashankram** [comment]
> > > During a SIG call, we agreed to document that those permissions need to be added to the operator service account if you want the operator to, automatically, generate the RBAC resources for those processors that need it.
> > 
> > 
> > What was the reason for this? How does a user know what RBAC perms a component managed by the operator needs? Isn't that the purpose of an operator, to simplify UX?
> 
> The permissions need to be added anyway to the operator (because if the operator has no permissions over one resource, cannot grant permissions over other resources).

Are you referring to the operator needing to create RBAC resources for the collector?
