### ISSUE TITLE
WATCH_NAMESPACE doesn't work for a single namespace

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#2589]
### Component(s)

operator

## Description

Setting WATCH_NAMESPACE to a single value has no effect. Multiple values delimited by commas work.

### Kubernetes Version

1.28

### Operator version

0.92.0, most likely present since 0.84.0

### Collector version

0.92.0

### Additional context

Looks like #2046 accidentally removed the second branch of a conditional instruction, and now we do nothing if the value of WATCH_NAMESPACE contains no commas. See: https://github.com/open-telemetry/opentelemetry-operator/blob/1573cd938a81583cf2ffe54353e4f3da536f51bf/main.go#L215

**Comment by davidhaja** [comment]
I would like to work on this one.
My idea is to move the `namespaces` map filling, the `watchNamespace` splitting, and cache.Config{} creation under the `found` condition.
https://github.com/open-telemetry/opentelemetry-operator/blob/1573cd938a81583cf2ffe54353e4f3da536f51bf/main.go#L200-L202

**Comment by jaronoff97** [comment]
closed by #2606
