### ISSUE TITLE
opentelemetry-operator.yaml have wrong image 

### ISSUE THREAD

**Issue by valdemarpavesi** [open-telemetry/opentelemetry-operator#259]
https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
 
 image: quay.io/opentelemetry/opentelemetry-operator:0.24.0
 
 must be:
 
  image: quay.io/opentelemetry/opentelemetry-operator:v0.24.0
  
  from quay.io:
  
  docker pull quay.io/opentelemetry/opentelemetry-operator:v0.24.0

**Comment by valdemarpavesi** [comment]
After fixing the image, now it is up and running:
`
NAMESPACE                       NAME                                                         READY   STATUS    RESTARTS   AGE
opentelemetry-operator-system   opentelemetry-operator-controller-manager-7df489cb85-nwjwl   2/2     Running   0          23s`

![image](https://user-images.githubusercontent.com/10376101/116430923-e3366980-a80c-11eb-8a3d-fc194929c84e.png)

**Comment by jpkrohling** [comment]
This has hit us again... #240 had this but I didn't have the chance to fix it in time for this release. I'll close this in favor of that one, but I appreciate your report!

**Comment by valdemarpavesi** [comment]
thanks @jpkrohling
