### ISSUE TITLE
v1alpha2: make getConfigMapSHA a method of the new CRD

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#2591]
### Component(s)

operator

### Describe the issue you're reporting

https://github.com/open-telemetry/opentelemetry-operator/pull/2532#discussion_r1474770348

**Comment by pavolloffay** [comment]
I would propose to close this ticket as won't do. 

The only `annotations.go` are calculating hash from the collector config object https://github.com/open-telemetry/opentelemetry-operator/blob/08b33a5616880087b480de0ef1359cf4b3d09222/internal/manifests/manifestutils/annotations.go#L91. Therefore it does not warrant to move the  getConfigMapSHA to the public API package.
