### ISSUE TITLE
Wrong java instrumentation version in 0.93.0 operator release notes

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-operator#2600]
### Component(s)

operator

### Describe the issue you're reporting

Hello, the 0.93.0 operator release notes mention version 1.32.0 is being used for java instrumentation, but it looks like it's actually 2.0.0 https://github.com/open-telemetry/opentelemetry-operator/blob/v0.93.0/autoinstrumentation/java/version.txt?

**Comment by jaronoff97** [comment]
we are waiting on changing the default instrumentation for java and dotnet. Please see here for more https://github.com/open-telemetry/opentelemetry-operator/issues/2529
