### ISSUE TITLE
`observability.metrics.DisablePrometheusAnnotations` does not work

### ISSUE THREAD

**Issue by verejoel** [open-telemetry/opentelemetry-operator#2608]
## Description
Setting the new `DisablePrometheusAnnotations` config option to `true` in the latest version of the operator does not work.

## Steps to Reproduce
Operator version: 0.93.0
CRDs have been updated on K8s for this version.

Add the following stanza to an existing `OpenTelemetryCollector` and observe that the deployment is not rolled out, nor are annotations removed.
```yaml
spec:
  observability:
    metrics:
      DisablePrometheusAnnotations: true

```

I also tried redeploying the operator, to no avail.

## Expected Result
The prometheus scrape annotations should not be present on the deployment if this option is enabled.

## Actual Result
Prometheus scrape annotations are present, operator does not perform reconciliation

## Supplemental
Can we also fix the naming of this resource in the OpenAPI spec to not start with a capital letter?

### Kubernetes Version

1.28.3

### Operator version

1.93.0

### Collector version

Custom build

**Comment by verejoel** [comment]
I tested this also with the `--feature-gates=operator.observability.prometheus` flag enabled with the same result

**Comment by jaronoff97** [comment]
Are there any error logs from the operator?

**Comment by pavolloffay** [comment]
The implementation of this feature is very simple https://github.com/open-telemetry/opentelemetry-operator/blob/769c9843728b56af6d2042784716c0a4ebd3c5f2/internal/manifests/collector/annotations.go#L31 

Could you pleae paste collector deployment with `DisablePrometheusAnnotations: true`

**Comment by rivToadd** [comment]
I just ran a validation 
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: statefulset
  replicas: 1
  observability:
    metrics:
      enableMetrics: true
      # DisablePrometheusAnnotations: true
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
    processors:

    exporters:
      debug:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [debug]
        ```
        give it a go with this spec. I was successful with it

**Comment by jaronoff97** [comment]
an aside, I do think we should rename `DisablePrometheusAnnotations` to be lowercased to match all of the other fields we have.

**Comment by NickAnge** [comment]
Hey everyone. 👋  We are facing the issue. 
Defining `DisablePrometheusAnnotations: true`, doesn't seem to remove the annotations. Is there a plan to get this fixed ?

Thanks in advance

**Comment by jaronoff97** [comment]
@NickAnge there's an open PR that's gone stale #2664 (cc @rivToadd) 

For now, you can manually override the annotations iirc by setting it false:

```
prometheus.io/scrape: "false"
```

**Comment by NickAnge** [comment]
Hey @jaronoff97 . Thank you, we will try it

**Comment by Toaddyan** [comment]
This was fixed in the v1alpha1 version of it, but now it seems the change is in the v1beta1 version of it. If you migrate forward to the v1beta1, this feature will work.
