### ISSUE TITLE
Evaluate chainsaw to run e2e tests

### ISSUE THREAD

**Issue by eddycharly** [open-telemetry/opentelemetry-operator#2609]
### Component(s)

operator

### Describe the issue you're reporting

I would like to discuss a possible migration of e2e tests from Kuttl to [chainsaw](https://github.com/kyverno/chainsaw)

This is mostly a seamless migration via script and should supercharge tests with better logs, [assertions trees](https://kyverno.io/blog/2023/12/13/kyverno-chainsaw-exploring-the-power-of-assertion-trees/) and many more things 💪

The KUTTL project has very low activity, no new features and minimum maintenance.

Associated (WIP) PR: https://github.com/open-telemetry/opentelemetry-operator/pull/2607

**Comment by yuriolisa** [comment]
Issue can be closed by #2607
