### ISSUE TITLE
Enable direct reconciliation of the v1beta1 types

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#2620]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

The operator should add the v1alpha2 types to its known schemas

### Describe the solution you'd like

Add it to the scheme

**Comment by pavolloffay** [comment]
I have started looking into this:
* add conversion webhook 
* include v1alpha2 CRD in the bundle and manifests
* add v1alpha2 to reconciliation

**Comment by pavolloffay** [comment]
Note when `v1alpha2` is enabled we run into 

``` k apply -f otelcol-cr.yaml                                                                                                                                                                                                                                                                                                                                1 ↵ ploffay@fedora
The CustomResourceDefinition "opentelemetrycollectors.opentelemetry.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

In the past it was solved with https://github.com/open-telemetry/opentelemetry-operator/pull/1981#discussion_r1294881203 to trim the CRD description.

This happens with `kubectl apply` as it stores the last version in the annotations that has a limited size. The problem does not occur with `kubectl create|replace` commands.

**Comment by pavolloffay** [comment]
The setting description size to `0` fixed the issue.
