### ISSUE TITLE
Add support for autoinstrumenting nginx 1.21.6 + 1.25.0

### ISSUE THREAD

**Issue by djluck** [open-telemetry/opentelemetry-operator#2633]
### Component(s)

instrumentation

### Is your feature request related to a problem? Please describe.

Currently you cannot use autoinstrument to instrument [nginx-ingress](https://github.com/kubernetes/ingress-nginx) pods due to the version of nginx they currently use (1.21.6) and the next version they plan to support (1.25.0).

### Describe the solution you'd like

It would be fantastic if we could get support for these nginx versions- nginx-ingress is commonly used but it's own implementation of OpenTelemetry doesn't work as intended.

**Comment by pavolloffay** [comment]
The operator supports only what is supported by the nginx OTEL instrumentation:

>  Support for nginx version 1.24.0 and 1.25.3.(https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/340) 

https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.93.0 
https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/tag/webserver%2Fv1.0.4


I would suggest opening the ticket in https://github.com/open-telemetry/opentelemetry-cpp-contrib

**Comment by djluck** [comment]
Thanks for the nudge, I'll re-open the ticket in the appropriate project.
