### ISSUE TITLE
Disabling ingress does not remove the created ingress objects

### ISSUE THREAD

**Issue by Starefossen** [open-telemetry/opentelemetry-operator#2651]
### Component(s)

collector

## Description

If you disable a previously enabled ingress for a Collector the ingress resource will not be deleted from the cluster.

## Steps to Reproduce

1. Create a collector with an ingress
2. Remove the ingress and apply the collector to the cluster

## Expected Result

The previously created ingress resource should be removed.

## Actual Result

The previously created ingress is not removed.

### Kubernetes Version

v1.28.3-gke.1286000

### Operator version

0.93.0

### Collector version

n/a

## Environment
Cloud: GKE

**Comment by jaronoff97** [comment]
Thanks for opening this, we are actively working on a fix. CC @yuriolisa this is the bug for #2575

**Comment by yuriolisa** [comment]
Thank you, @jaronoff97, for pointing this out. I'm just waiting for @pavolloffay  to review it.
