### ISSUE TITLE
Provide Access to Pod DNSConfig

### ISSUE THREAD

**Issue by forestsword** [open-telemetry/opentelemetry-operator#2658]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

I need to be able to add the DNSConfig to the collector pods by way of the Operator. Today this is not exposed.

### Describe the solution you'd like

That [`DNSConfig`](https://pkg.go.dev/k8s.io/api@v0.29.2/core/v1#PodDNSConfig) is exposed as a part of the `OpenTelemetryCollector` API.

### Describe alternatives you've considered

I don't know of another way aside from a custom mutating webhook.

**Comment by forestsword** [comment]
As a late follow up, it would be also be helpful to have [`DNSPolicy`](https://pkg.go.dev/k8s.io/api@v0.29.2/core/v1#DNSPolicy) configurable.

**Comment by pavolloffay** [comment]
@forestsword could you please describe the use-case you are trying to solve?

**Comment by forestsword** [comment]
Sure, I'm following some internal best practices for our Kubernetes clusters where we use dnsmasq to cache and prevent overloading coredns.

The policy needs to be set to `None` and a custom dns configuration provided to use a local dnsmasq instead.

**Comment by jaronoff97** [comment]
@forestsword will [this resolve](https://github.com/open-telemetry/opentelemetry-operator/pull/3077/files#diff-34db83fc5c513943d88ada8c831ee83c992c8250ff9e791d57ac985f73623de4) your issue?
