### ISSUE TITLE
Configure zap EncoderConfig for operator

### ISSUE THREAD

**Issue by kaskavalci** [open-telemetry/opentelemetry-operator#268]
Operator uses default configuration for zap encoder configuration. `levelKey` in this config defaults to `level`. This creates an issue in GCP Logging as it expects `severity` for log level. Below is an example of a log level interpreted as error. 

I've noticed operator uses `sigs.k8s.io/controller-runtime/pkg/log/zap` package to bind directly from environment variables. As far as I can see, that function does not support full configuration of `zapcore.EncoderConfig`. But, it seems it is possible to configure zap completely by using the zap package from controller-runtime. 

If such a feature is reasonable, I'm happy to pick it up to contribute.

```json
{
  "insertId": "z96t3fg2d841ax",
  "jsonPayload": {
    "opentelemetry-collector": "0.24.0",
    "go-os": "linux",
    "opentelemetry-operator": "0.24.0",
    "build-date": "2021-04-22T20:20:45Z",
    "go-version": "go1.15.11",
    "ts": 1620630610.4453816,
    "msg": "Starting the OpenTelemetry Operator",
    "go-arch": "amd64",
    "level": "info"
  },
  "timestamp": "2021-05-10T07:10:10.445834703Z",
  "severity": "ERROR",
  "receiveTimestamp": "2021-05-10T07:10:16.030283595Z"
}
```

**Comment by jpkrohling** [comment]
Are you still interested in this one, @kaskavalci?

**Comment by kaskavalci** [comment]
I do but it's been difficult to integrate this work with summer plans. I put a self imposed deadline but that didn't work either :) Is the issue prioritized? I'm happy to leave it to others or pick it up ASAP I find some time on my hands.

**Comment by jpkrohling** [comment]
It's not prioritized, I would love to have you do it whenever you have time for it.

**Comment by kaskavalci** [comment]
@jpkrohling I'm sorry to keep this holding on me. It seems I cannot allocate any time to ship this feature. So, it's open for grabs!

**Comment by yuriolisa** [comment]
@jpkrohling, @kaskavalci. Could you please clarify what the expected results in this issue are?

**Comment by yuriolisa** [comment]
@jpkrohling.

**Comment by crossoverJie** [comment]
Is this the expected outcome of the issue?

Current:
```json
{"level":"info","ts":"2024-03-12T14:39:02+08:00","msg":"test"}
```

Expect:
```json
{"severity":"info","ts":"2024-03-12T14:41:24+08:00","msg":"test"}
```

**Comment by yuriolisa** [comment]
> @yuriolisa Is this the expected outcome of the issue?
> 
> Current:
> 
> ```json
> {"level":"info","ts":"2024-03-12T14:39:02+08:00","msg":"test"}
> ```
> 
> Expect:
> 
> ```json
> {"severity":"info","ts":"2024-03-12T14:41:24+08:00","msg":"test"}
> ```

I would assume the level field shouldn't be replaced with severity, but adding a severity field at another level, like the very first comment of this issue.

**Comment by yuriolisa** [comment]
> @yuriolisa Is this the expected outcome of the issue?
> 
> Current:
> 
> ```json
> {"level":"info","ts":"2024-03-12T14:39:02+08:00","msg":"test"}
> ```
> 
> Expect:
> 
> ```json
> {"severity":"info","ts":"2024-03-12T14:41:24+08:00","msg":"test"}
> ```

I did a misinterpretation about that issue, but you're right. It's exactly what's expected.
