### ISSUE TITLE
Add support for yaml tags in the OpenTelemetryCollectorSpec

### ISSUE THREAD

**Issue by adil-sultan** [open-telemetry/opentelemetry-operator#2696]
### Component(s)

collector, opamp bridge

### Is your feature request related to a problem? Please describe.

We are attempting to import the Collector CRD directly in our OpAMP vendor server code, but for our use case we unmarshal and utilize yaml tags. Currently there are only json tags available.

### Describe the solution you'd like

The OpenTelemetryCollectorSpec (anywhere with json tags really) could also use yaml tags as well

### Describe alternatives you've considered

We manually define the spec locally but this runs the risk of going out of sync with the actual collector spec.

**Comment by jaronoff97** [comment]
We shouldn't need the YAML tags, as the JSON tags should be sufficient. I'm happy to pair on this and we can report back what to do here when we're done. Closing for now.
