### ISSUE TITLE
Clarify which RBAC permissions are needed for different Target Allocator features

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#2734]
### Component(s)

target allocator

### Describe the issue you're reporting

The [target allocator README](https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#rbac) only provides RBAC permissions required to use Prometheus CRs with the target allocator. 

The allocator needs a much smaller set of permissions for static targets. It does need the specified Pod/Endpoint/... permissions if the user wants to use Kubernetes Service Discovery in their scrape config, but this isn't very clear in the documentation.

We should be clear about what is required for each of these use cases.

**Comment by pavolloffay** [comment]
Related to https://github.com/open-telemetry/opentelemetry-operator/issues/424
