### ISSUE TITLE
0.96.0 docker image didn't get created at release

### ISSUE THREAD

**Issue by tico24** [open-telemetry/opentelemetry-operator#2756]
## Description
Can't pull the 0.96.0 docker image for the operator. It seems to have not been released.

## Steps to Reproduce
```
docker pull ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.96.0
```

## Expected Result
The container pulls.

## Actual Result
`Error response from daemon: manifest unknown`

### Kubernetes Version

1.29

### Operator version

0.96.0

### Collector version

n/a

## Environment
OS: Any (i'm running macos locally)
Compiler(if manually compiled): n/a

### Log output

```shell
Error response from daemon: manifest unknown
```

**Comment by jaronoff97** [comment]
hello, thanks for opening this. we're working to get these images published.

**Comment by pavolloffay** [comment]
The OLM repositories need the image as well:
* https://github.com/k8s-operatorhub/community-operators/pull/4000 
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4173

**Comment by pavolloffay** [comment]
Release job https://github.com/open-telemetry/opentelemetry-operator/actions/runs/8234359438

**Comment by pavolloffay** [comment]
The 0.96.0 has been published.

```bash
PLATFORMS=linux/amd64,linux/arm64,linux/s390x,linux/ppc64le

for platform in $(echo $PLATFORMS | tr "," "\n"); do
            arch=${platform#*/}
            echo "Building manager for $arch"
            make manager ARCH=$arch
done

docker buildx build --push --platform=$(PLATFORMS) --tag ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.96.0 --tag  ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.96 --tag  ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.96.0  --tag ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:latest -f Dockerfile .
```

**Comment by Starefossen** [comment]
Bumping the helm chart https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1084
