### ISSUE TITLE
Question/Clarification: Any config changes that can be made to manage collector-contrib with this operator

### ISSUE THREAD

**Issue by karthikinamanamelluri** [open-telemetry/opentelemetry-operator#276]
Hello,

Can someone please let me know if this operator can be used to manage the contrib distribution of collector.
I do see below statement in doc. 
'At this point, it has OpenTelemetry Collector as the only managed component.'
Is parameterizing the image name here as an option would help?
https://github.com/open-telemetry/opentelemetry-operator/blob/main/internal/config/main.go#L70 

Thanks

**Comment by jpkrohling** [comment]
Yes, you can manage different distributions, like the contrib. You can override the default image for all the CRs managed by the operator using the flag you mentioned, or via the `.Spec.Image` property, as seen here: https://github.com/open-telemetry/opentelemetry-operator/issues/77#issuecomment-836340138
