### ISSUE TITLE
Release the operator v0.97.0

### ISSUE THREAD

**Issue by atsu85** [open-telemetry/opentelemetry-operator#2766]
### Component(s)

auto-instrumentation

### Describe the issue you're reporting

# Describe the issue you're reporting

#2745 bumped NodeJS auto-instrumentation.
Need to release the operator to be able take advantage of it using [opentelemetry-operator helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator)

**Comment by pavolloffay** [comment]
Before cutting 0.97.0 we should consider finishing some of the tickets for moving to v1beta1 https://github.com/open-telemetry/opentelemetry-operator/milestone/4

**Comment by jicki** [comment]
When will version v0.97.0 be released?
