### ISSUE TITLE
Plans to auto-instrument dotnet framework via the operator?

### ISSUE THREAD

**Issue by hobbesuk** [open-telemetry/opentelemetry-operator#2791]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

The operator currently doesn't appear to support dotnet framework - it doesn't appear to be called out anywhere, but my init container fails with:

`Failed to pull image "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0": no match for platform in manifest: not found`

### Describe the solution you'd like

dotnet framework containers support auto instrumentation via the operator

**Comment by swiatekm-sumo** [comment]
We do support it, and the image does exist:

```bash
➜  ~ docker pull ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0
1.2.0: Pulling from open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet
a307d6ecc620: Pull complete 
045cb514e412: Pull complete 
4be61df43163: Pull complete 
7eaba9941a66: Pull complete 
380e17bad330: Pull complete 
Digest: sha256:6e087c7e5b0488b45a176350beb128854ec9d4fadbeb6e3eae19e0a284c45319
Status: Downloaded newer image for ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0
ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0
```

At a guess, you have pullSecrets defined on the Pod which log you into ghcr.io, but don't have public repo permissions.

**Comment by hobbesuk** [comment]
Hi, yes, I'm trying this on windows, as far as I'm aware dotnet framework is windows only

**Comment by swiatekm-sumo** [comment]
My apologies, I'm not a dotnet person, and not very up to speed on which parts are supported on Linux nowadays.

In any case, the operator does not support Windows containers in general, nor can it run on Windows Nodes. If you'd like to add your voice to the users requesting this feature, please comment under https://github.com/open-telemetry/opentelemetry-operator/issues/642.

**Comment by swiatekm-sumo** [comment]
@hobbesuk can I close this ticket in favor of #642 for now?

**Comment by hobbesuk** [comment]
Yes, thanks for taking the time to look.

For anyone else who ends up here what I ended up doing in the end was creating a new docker image using my original image as the base, within this container I used the powershell module to instrument IIS.
