### ISSUE TITLE
TargetAllocator returned scrape config crashes otel MetricsReceiver when relabel or metric relabel action has action:keepequal or dropequal 

### ISSUE THREAD

**Issue by rashmichandrashekar** [open-telemetry/opentelemetry-operator#2793]
### Component(s)

target allocator

## Description
TargetAllocator's responce crashes metricsreceiver when relabel or metric relabel action has action:keepequal or dropequal.
When the metricsreceiver calls the TA service to receive config and unmarshal the response, it fails because of the unmarshal implementation. https://github.com/prometheus/prometheus/blob/25a8d576717f4a69290d6f6755b4a90cfaab08ff/model/relabel/relabel.go#L144C3-L144C46
This is related to this issue - https://github.com/prometheus/prometheus/issues/12534

## Steps to Reproduce
Use configmap or pod or service monitor CRD that use action keepequal or dropequal.

## Expected Result
The action should not result in otel metrics receiver crashing

## Actual Result
Prometheus Metrics Receiver crashes after receiving config from TA with the following error - 
"level":"error","ts":1707850745.82048,"caller":"prometheusreceiver/metrics_receiver.go:167","msg":"Failed to retrieve job list","kind":"receiver","name":"prometheus","data_typ
e":"metrics","error":"keepequal action requires only 'source_labels' and `target_label`, and no other fields"

### Kubernetes Version

1.26.12

### Operator version

0.96.0

### Collector version

0.96.0

**Comment by swiatekm-sumo** [comment]
I'd love to solve this in a robust way, where we can be confident we're generating valid config, not just for these specific relabel actions. I think we might be able to imitate what prometheus-operator does, maybe Prometheus itself also has a config serialization mechanism defined that we could reuse.
