### ISSUE TITLE
Remove Target Allocator Rewrite Feature Gate in v0.99.0

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-operator#2796]
### Component(s)

collector, target allocator

### Describe the issue you're reporting

The feature gate has been in beta for a while. We should promote it to Stable, and remove it in a subsequent version.

**Comment by jaronoff97** [comment]
closed by #2797

**Comment by swiatekm-sumo** [comment]
I'd like to use this issue to track removing the flag in 0.99.0.

**Comment by jaronoff97** [comment]
@swiatekm-sumo sounds good, would you mind rewriting the title to match that?
