### ISSUE TITLE
Allow ServiceMonitor/PodMonitor to set custom MatchLabels

### ISSUE THREAD

**Issue by yaron-idan** [open-telemetry/opentelemetry-operator#2838]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

Currently, when the collector is creating podMonitors is using a predefined set of labels configured [here](https://github.com/open-telemetry/opentelemetry-operator/blob/c65629b3b9fcb722e770eb58b73ea4f5cc8bc63f/internal/manifests/manifestutils/labels.go#L77). Since the pods we want to configure have different labels (as they are running a service the collector is only a sidecar of), the labels are not matched and the pods are not monitored.

### Describe the solution you'd like

I'd like to inject a set of custom labels to any pod injected with the opentelemetry collector sidecar, and then match these labels in the podMonitor.

### Describe alternatives you've considered

Creating the podMonitor manually.

**Comment by iblancasa** [comment]
Could it be a solution to add those labels + the ones you define for your OTEL Collector? Those labels could be propagated to the created `PodMonitor` and achieve what you want.

**Comment by yaron-idan** [comment]
That could work but in order for the podMonitor to match arbitrary workloads injected with the sidecar there has to be a flag that allows omission of these labels (since labels like `app.kubernetes.io/instance` which are currently used are very common, and will probably be defined differently for each workload.

If that makes sense I can take a stab of implementing this myself.

**Comment by jaronoff97** [comment]
@yaron-idan were you able to implement this solution? I'm going to close this for now, please re-open if you have more questions/comments.
