### ISSUE TITLE
Docs for enabling multi-instrumentation still point to enabling it via the --feature-gates flag

### ISSUE THREAD

**Issue by suyash-811** [open-telemetry/opentelemetry-operator#2855]
### Component(s)

Docs (README)

### Describe the issue you're reporting

Hi all,

I recently started using the opentelemtry-operator. (Thanks for all the good work 😄)
While reading the README, i noticed that the docs instruct to enable multi-instrumentation using the ```feature-gates```  flag. 

The logs from the opentelemtry-operator pod throw an error, stating that ```operator.autoinstrumentation.multi-instrumentation``` is not one of the available feature flags.

I was however, able to enable multi-instrumentation by adding the ```--enable-multi-instrumentation``` flag to the container arguments.

I feel this change should also be updated in the README, which could help out other new adopters of this operator. I am willing to update the README with the necessary changes

Looking forward for some feedback 😄

**Comment by TylerHelmuth** [comment]
You are correct, as part of https://github.com/open-telemetry/opentelemetry-operator/issues/2582 we need to update the README

**Comment by suyash-811** [comment]
Can i make the changes to the README and submit a PR?

**Comment by TylerHelmuth** [comment]
@suyash-811 Sure!
