### ISSUE TITLE
Ambiguous target allocator deployment mode compatibility

### ISSUE THREAD

**Issue by fredrikgh** [open-telemetry/opentelemetry-operator#2866]
### Component(s)

target allocator

## Description

The [Target allocator docs](https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator) state that it supports modes `deployment`, `daemonset` and `statefulset` but[ the implementation](https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1beta1/collector_webhook.go#L328) suggests that it doesn't support `deployment`.

I'm looking for some clarification on what I should expect, i.e. are the docs or the validations wrong?

### Kubernetes Version

v1.28.3

### Operator version

v0.98.0

### Collector version

v0.98.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jaronoff97** [comment]
that's an issue in our docs, we don't support deployments as of right now and would recommend deploying as a statefulset or a daemonset.

**Comment by fredrikgh** [comment]
@jaronoff97 thanks for confirming, and updating the docs.
