### ISSUE TITLE
Reconfiguration of OpenTelemetryCollector CR mode is not working like expected

### ISSUE THREAD

**Issue by alita1991** [open-telemetry/opentelemetry-operator#2888]
## Description
When the mode of an existing OpenTelemetryCollector CR is changed from deployment to statefulset, the deployment resource is not deleted after the reconfiguration process is done.

## Steps to Reproduce
Create a new collector with mode = deployment
Change the mode to statefulset

## Expected Result
Deployment collector should be deleted after reconfiguration

## Actual Result
Deployment collector is not deleted after reconfiguration

### Kubernetes Version

1.26.0

### Operator version

0.90.0

### Collector version

0.90.1

**Comment by jaronoff97** [comment]
have you tried upgrading to the latest versions? This should be solved.

**Comment by alita1991** [comment]
If the issue was fixed in the latest version, we can close the ticket and create a new one if the problem is still present.
Thank you for help!
