### ISSUE TITLE
Target Allocator multiple Replicas with per-node allocationStrategy

### ISSUE THREAD

**Issue by diezfx** [open-telemetry/opentelemetry-operator#2900]
### **Component(s)**
target allocator

### **Description**
The documentation says:

> Replicas is the number of pod instances for the underlying TargetAllocator. This should only be set to a value other than 1 if a strategy that allows for high availability is chosen. Currently, the only allocation strategy that can be run in a high availability mode is consistent-hashing.

Is there a reason the per-node allocation does not support multiple replicas currently?
In contrast to least-weighted, there should be no problems with contradicting allocations.

**Comment by pavolloffay** [comment]
cc) @open-telemetry/operator-ta-maintainers

**Comment by jaronoff97** [comment]
This should work for multiple replicas as stated, but I haven't tested this yet. cc @matej-g @swiatekm-sumo have you tested this? Or do we have confidence this should _just work_?

**Comment by swiatekm-sumo** [comment]
I've not tested it, but it should work correctly. At the very least, we don't check `Replicas` at admission, so you can really set it to whatever you want. If we wanted to test it, what we should really do is add unit tests for strategies where we randomly rearrange input targets and assert that the allocation is always the same.

**Comment by swiatekm-sumo** [comment]
Yeah, you should be able to set a PDB, and the default PDB should be set for the `per-node` strategy.
