### ISSUE TITLE
Warnings on Java auto-instrumentation for failed log exports when logging is not configured on Collector

### ISSUE THREAD

**Issue by justsomecorporateuser** [open-telemetry/opentelemetry-operator#2905]
### Component(s)

auto-instrumentation

### Describe the issue you're reporting

With Java -auto- instrumentation (2.3.0) , applications are logging this

otel.javaagent 2024-04-28 12:42:46:325 +0300] [OkHttp http://metric-trace-collector.opentelemetry-operator-system:4318/...] WARN io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs. Server respond ed with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found 

My Collector is having only metrics and traces enabled.  Is there a way to get rid of these needless calls?

Collector config:

    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      googlecloud:
        project: my-project
        metric:
        trace:
 
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [googlecloud]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [googlecloud]

**Comment by PandeoF1** [comment]
Hi, i think your problem is that you use `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` variables and not `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` and `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT`.

Because by default if the `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` is set it will send traces,metrics and logs to the endpoint.

See : [otel-exporter-docs](https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/)

**Comment by justsomecorporateuser** [comment]
Tested by changing my instrumentation yaml from..

spec:
  exporter:
    endpoint: http://metric-trace-collector.opentelemetry-operator-system:4318

..to..

spec:
#  exporter:
#    endpoint: http://metric-trace-collector.opentelemetry-operator-system:4318
...
  java:
    env: 
    - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
      value: http://metric-trace-collector.opentelemetry-operator-system:4318
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT 
      value: http://metric-trace-collector.opentelemetry-operator-system:4318

and outcome is now that the correct variables are in place but it does not stop auto-instrumentation from trying to send the logs.  With above changes, its actually trying localhost, as the general variable is missing

ERROR io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4318

**Comment by PandeoF1** [comment]
Maybe try to add this env var : `OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=none` or `OTEL_LOGS_EXPORTER=none` (idk which is the good one)

**Comment by justsomecorporateuser** [comment]
Thanks @PandeoF1,  used the OTEL_LOGS_EXPORTER none  and restored the common endpoint.  This looks like working for non-logging case:

```
spec:
  exporter:
    endpoint: http://metric-trace-collector.opentelemetry-operator-system:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
    #argument: "0.25"
  java:
    env: 
    - name: OTEL_LOGS_EXPORTER
      value: none
```

**Comment by pavolloffay** [comment]
Closing, feel free to re-open if the issue was not solved
