### ISSUE TITLE
publish node autoinstrumentation v1.X

### ISSUE THREAD

**Issue by msvechla** [open-telemetry/opentelemetry-operator#2909]
### Component(s)

auto-instrumentation

### Describe the issue you're reporting

The NodeJS auto instrumentation now also has a v1.X available, see: https://github.com/open-telemetry/opentelemetry-js/releases

This is important because the new major version now follows the semantic conventions, similar to the Java v2 release [here](https://github.com/open-telemetry/opentelemetry-operator/pull/2514).

Can we simply [bump the dependency version here](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/package.json#L18) to trigger a new release for the latest [v1.24.0](https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.24.0)?

**Comment by swiatekm-sumo** [comment]
What kind of difference is there between this version and the one we have currently? Are there any breaking changes?
