### ISSUE TITLE
Error: cannot load configuration: unknown processors type "k8s_tagger" for k8s_tagger

### ISSUE THREAD

**Issue by deepakkhetwal** [open-telemetry/opentelemetry-operator#291]
I am having below issue
rror: cannot load configuration: unknown processors type "k8s_tagger" for k8s_tagger

See below my collector yaml file - 
# Reference - https://github.com/open-telemetry/opentelemetry-operator
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: aks-otlp-collector
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      k8s_tagger:
        passthrough: true
    exporters:
      kafka/1:
        brokers:
          - 10.80.18.89:9092
        topic: otlp.traces
        encoding: jaeger_json
        protocol_version: 2.0.0
      jaeger/1:
        endpoint: simple-streaming-collector.keda-functions.svc.cluster.local:14250
        insecure: true
      zipkin/1:
        endpoint: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
        insecure: true
      

    service:
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [kafka/1]
        traces/2:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [jaeger/1]
        traces/3:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [zipkin/1]

**Comment by timcosta** [comment]
You need to set the image of your collector by setting `spec.image: otel/opentelemetry-collector-contrib:0.27.0`. By default the operator deploys the core collector, and the k8s tagger is part of the contrib collector.

**Comment by deepakkhetwal** [comment]
@timcosta  I added contrib image as shown in yaml file, but strangely, after getting exported using jaeger/kafka/zipkin. No where, I am seeing kubernetes host and pod information got imported. I am using K8_tagger. please advise, How i can add kubernetes host and pod information into exporters. below is my collector yaml
# Reference - https://github.com/open-telemetry/opentelemetry-operator
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: aks-otlp-collector
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib
  config: |
    receivers:
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          memory:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      k8s_tagger:
        passthrough: false
    exporters:
      kafka/1:
        brokers:
          - 10.80.18.89:9092
        topic: otlp.traces
        encoding: jaeger_json
        protocol_version: 2.0.0
      jaeger/1:
        endpoint: simple-streaming-collector.keda-functions.svc.cluster.local:14250
        insecure: true
      zipkin/1:
        endpoint: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
        insecure: true
      

    service:
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [kafka/1]
        traces/2:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [jaeger/1]
        traces/3:
          receivers: [otlp]
          processors: [k8s_tagger]
          exporters: [zipkin/1]

**Comment by timcosta** [comment]
Not sure on that one, I haven't used that tagger before, I just recognized this error from another receiver i was configuring.

**Comment by jpkrohling** [comment]
@deepakkhetwal you should ask this one in the contrib repository, but make sure the pod IP is part of the resources for the data points reaching your collector.
