### ISSUE TITLE
Support the ability to override instrumentation image via annotation

### ISSUE THREAD

**Issue by BenB196** [open-telemetry/opentelemetry-operator#2912]
### Is your feature request related to a problem? Please describe.

There are some cases, where you want to define a specific instrumentation image/version for a specific deployment, where needing to define a completely new `Instrumentation` CRD is a bit overkill. It would be nice to have the ability to define an override at the deployment/pod level for image/version.

### Describe the solution you'd like

Support for defining an annotation that allows overriding image/version for a specific language:

Something like:
```
instrumentation.opentelemetry.io/inject-java-image: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.3.0"
instrumentation.opentelemetry.io/inject-dotnet-image: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.1.0"
```

### Describe alternatives you've considered

I could define multiple `Instrumentation` CRDs, however, when 95% of the file is the same and I just want to change 1 or 2 image versions for a specific deployment/pod, this is a bit overkill.

### Additional context

I have some applications which need to run on some older instrumentation versions, but I'd like my "default" for applications to always target near the latest version.

**Comment by pavolloffay** [comment]
I don't see much value in the proposal, given the use-case can be solved with the existing solution.

**Comment by jaronoff97** [comment]
Closing this for now, as our existing solution allows for this. I also think a proposal like #2744 would cover this case.
