### ISSUE TITLE
Automatically set GOMEMLIMIT for collector, TA, bridge, etc.

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#2919]
### Component(s)

collector, target allocator, opamp

### Is your feature request related to a problem? Please describe.

It would be awesome if we could automatically set the GOMEMLIMIT for the collector (and TA/Bridge too) when a user sets a limit on the k8s deployment.

### Describe the solution you'd like

when we create the deployment/sts/daemon we could read the resource limit and if present set GOMEMLIMIT to 80% of that per the recommendation [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/ballastextension/README.md)

**Comment by pavolloffay** [comment]
+1

**Comment by jaronoff97** [comment]
I will be implementing it for GOMAXPROCS as well ([related](https://github.com/open-telemetry/opentelemetry-collector/issues/4459#issuecomment-1490096473))

**Comment by jaronoff97** [comment]
related: https://github.com/open-telemetry/opentelemetry-operator/issues/1456

**Comment by iblancasa** [comment]
Do we want to do it for the collector or just rely on this new component? https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30289

**Comment by jaronoff97** [comment]
i think it still makes sense for us to set this for users outside of that feature, this is a pretty known pattern
