### ISSUE TITLE
Determine better strategy for handling map merging for various fields

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#2947]
Right now we have to manually clear maps for only the node selector in the mutate.go, but i'm sure there are other places where we shouldn't blindly merge things together.

_Originally posted by @swiatekm-sumo in https://github.com/open-telemetry/opentelemetry-operator/pull/2941#pullrequestreview-2050424029_

**Comment by swiatekm-sumo** [comment]
In reality, I think the logic here should be very simple. We should clear everything except labels and annotations, and even in their case I'm not completely convinced this is a good idea. It's another question whether this is actually straightforward to do with our current tooling.

**Comment by jaronoff97** [comment]
Yeah maybe this is worth doing for everything... if anyone reading this wants to check it out do reach out!

**Comment by davidhaja** [comment]
I would like to work on this.
