### ISSUE TITLE
OpenCensus port is not exposed by the Collector Service

### ISSUE THREAD

**Issue by thib92** [open-telemetry/opentelemetry-operator#295]
Hello,

I am deploying an OpenTelemetry Collector with an OpenCensus receiver.
According to [the comments on the `ports` parameter](https://github.com/open-telemetry/opentelemetry-operator/blob/36d59730af234c2bfc4f909fa2ff8a4659b90c86/api/v1alpha1/opentelemetrycollector_types.go#L72-L78), the operator should be able to detect well-known protocols in the `config` and expose their port. However, after deploying it, the collector initializes the OpenCensus receiver, but the service is not updated to expose the OpenCensus port.

It should be noted that the collector was first declared and deployed with only an `oltp` receiver, and I later updated it to add the OpenCensus collector. Maybe the operator simply didn't update the service.

**Comment by bhiravabhatla** [comment]
Yep - you are right - On update the exposed ports are not getting updated. We have an open issue for the same.

https://github.com/open-telemetry/opentelemetry-operator/issues/256

I was supposed  to fix this, but have been occcupied in some other work. Feel free to raise a PR for this.

**Comment by thib92** [comment]
I'm going to give it a try. It doesn't seem to hard.
