### ISSUE TITLE
Support setting ipFamilies and ipFamilyPolicy on Services

### ISSUE THREAD

**Issue by jutley** [open-telemetry/opentelemetry-operator#2958]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

We are in the process of migrating our clusters from IPv4 to IPv6. Part of this process has required setting the Service `.spec.ipFamilies` field to include `IPv6`, and sometimes setting `ipFamilyPolicy` to `RequireDualStack` if we want to support dualstack.

The opentelemetry-operator project currently doesn't seem to provide any way for us to configure these fields of the generated Service resources.

### Describe the solution you'd like

I'd like these fields to be made available from the OpenTelemetryCollector CRD. 

### Additional context

We also need to update the Helm chart to support configuring these fields on the services the Helm chart deploys, but that is probably better to request in the helm chart repository, not here.

**Comment by swiatekm-sumo** [comment]
Sounds reasonable to me. We can add it to the common fields.

**Comment by yuriolisa** [comment]
> Sounds reasonable to me. We can add it to the common fields.

Thanks. I will work on it.
