### ISSUE TITLE
Auto-instrumentation doesn't work as expected

### ISSUE THREAD

**Issue by Sotatek-GiangPham2** [open-telemetry/opentelemetry-operator#2959]
Hi everyone,

I recently deployed a application nodejs, and setup Opentelemtry-operator  and Jaeger to trace latency of my application. I read carefully docs, so i configurate successfuly init instrumentation into application. But when i check logs of collector and Jaeger UI, i can't see anything metrics (i curl API application before). I feel a bit strange, do I have to write anything else in my code? But i used auto-instrumentation. Hope everyone support!

Thanks
Giang

-------------------------

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/160448551/512f4ae3-0dba-4fe0-be95-dab33ddeb454)
![image](https://github.com/open-telemetry/opentelemetry-operator/assets/160448551/eec0b534-83a9-45c5-a667-287989a1dd95)
Information for my appilication
![image](https://github.com/open-telemetry/opentelemetry-operator/assets/160448551/4fa0f119-cdd9-4ea8-a004-839d8a06ae92)

**Comment by yuriolisa** [comment]
@Sotatek-GiangPham2, could you please confirm if your Jaeger endpoint configured on exporters is correct? Also, note that you configured only traces pipeline, which will send only traces. If you intend to export metrics and logs, please ensure the exporter and pipeline configurations accordingly.

**Comment by Sotatek-GiangPham2** [comment]
@yuriolisa Thanks you so much, i fixed this errors. 

By the way, if you mind if I ask more about python auto-instrumentation. If i deployed a simple application by python( a hello-world api), i can easy insert instrumentation into pod and reach all information need tracing at jaeger. But when i use a complicated application of my project, i can't reach tracing information. 

I know it's a stupid question but I don't understand why it happens to my two projects go and python. Hope you can suggest it help me. Thanks you

Giang

**Comment by jaronoff97** [comment]
@Sotatek-GiangPham2 please reach out in the CNCF slack if you have any trouble with autoinstrumentation for your applications and need some debugging help. Closing this for now.
