### ISSUE TITLE
Unable to exec  into open telemetry collector pod managed by operator with Daemonset mode of deployment

### ISSUE THREAD

**Issue by anushanagireddy0430** [open-telemetry/opentelemetry-operator#2976]
### Component(s)

collector

### What happened?

Deploy open telemetry operator of app version 0.95.0.
My cluster has 4 nodes, I chose Daemonset as mode of collector deployment. 4 otel collector pods created as expected.
I need to enable file_storage extension for logs and traces exporters and wal for prometheusremotewrite exporter for persistence.
For debugging purpose I need to exec into pod but getting "executable file not found in $PATH: unknown" for "sh" and "bash".
Any workaround or solutions for my problem?

### Kubernetes Version

v1.27.6-gke.2500

### Operator version

0.95.0

### Collector version

contrib-0.95.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by pavolloffay** [comment]
The collector images are built at https://github.com/open-telemetry/opentelemetry-collector-releases please open the request there.
