### ISSUE TITLE
Add support PriorityClass for target-allocator Pod

### ISSUE THREAD

**Issue by mdietzer-fn** [open-telemetry/opentelemetry-operator#2980]
### Component(s)

target allocator

### Is your feature request related to a problem? Please describe.

We would like to set a PriorityClass for all of our OpenTelemetry Pods. Most pods objects/configs support this via `priorityClassName`. However, the TargetAllocator spec does not seem to include `priorityClassName` as a possible field.

Setting `priorityClassName` on an `opentelemetry.io/v1beta1:OpenTelemetryCollector` gives the collector itself the priority class, but if the `targetAllocator` is enabled within this object, it does not inherit this priority class, so there is no way to configure it.

### Describe the solution you'd like

Add `priorityClassName` to the target allocator spec such that it can have a priority class configured or inherit priority class from the main `OpenTelemetryCollector` object.

**Comment by jaronoff97** [comment]
closing this in favor of #2422
