### ISSUE TITLE
Bridge should pull from v1beta1 too

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#2985]
### Component(s)

opamp

### Is your feature request related to a problem? Please describe.

The OpAMP Bridge currently only queries for v1alpha1 collectors, we should also check for v1beta1 now too!

### Describe the solution you'd like

Modify the code to query for v1beta1 and v1alpha1

**Comment by yuriolisa** [comment]
@jaronoff97, I can get this.

**Comment by yuriolisa** [comment]
> @yuriolisa my colleague has been working on this and should have a PR soon for it actually :)

Great!! Thanks for the heads-up!

**Comment by jaronoff97** [comment]
@gdfast is working on it :)
