### ISSUE TITLE
Create OpenShift metrics dashboards from the operator

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#2995]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

The OpenShift Console allows the creation of dashboards to display graphs created from metrics. Those are based on [the Grafana JSON Model] for dashboards, more concretely on Grafana 6.x dashboard format.

The creation of the dashboard is done by creating a `ConfigMap` with the label `"console.openshift.io/dashboard"` set to `"true"` in the `"openshift-config-managed"` namespace.

The idea of this issue would be to create one dashboard to visualize the metrics from the OpenTelemetry Collector automatically. Those metrics would be the ones associated to the OpenTelemetry Collector monitoring.

### Describe the solution you'd like

It is not necessary to create this dashboard per collector so, after a talk with @pavolloffay we think it would be nice if we create this dashboard as part of the steps to set up the operator.

We don't need to reconcile this `ConfigMap`.

Also, we can enable/disable the creation of the `ConfigMap` with a CLI flag (set to `false` by default).

### Additional context

![Dashboard example](https://github.com/open-telemetry/opentelemetry-operator/assets/4806311/8f1ee6a2-186c-4190-ba48-3e28952a2a40)

**Comment by jaronoff97** [comment]
IMO this feels like something that should be packaged in the helm chart no?

**Comment by jaronoff97** [comment]
true............ hm...... idk I need some other thoughts here @swiatekm-sumo @pavolloffay. We do already have some OpenShift specific code but a lot of that is for creating openshift related resources, not necessarily creating something for a vendor's backend.

**Comment by swiatekm-sumo** [comment]
Logically, this feels more like something that should be part of the OLM package rather than the operator itself, especially if it's static. I don't see why we need to involve the operator in what is essentially just creating a fixed ConfigMap.

**Comment by pavolloffay** [comment]
@iblancasa could the CM be put into the bundle and be installed by OLM? Meaning the integration would be static without  code change on the operator

**Comment by iblancasa** [comment]
> @iblancasa could the CM be put into the bundle and be installed by OLM? Meaning the integration would be static without code change on the operator

Yes. It should be fine if we just create the CM somewhere. Do you mean to add it to the bundle or how?

**Comment by jaronoff97** [comment]
@iblancasa i do think we should add it to the bundle, yes. feels a lot cleaner :)

**Comment by iblancasa** [comment]
> @iblancasa i do think we should add it to the bundle, yes. feels a lot cleaner :)

Is it ok if we add it to the bundle for regular K8s environments? I don't know if there is a way to enable/disable this somehow... or just we can add it always. Nothing will be done for the K8s clusters (if something fails should be detected during the E2E). WDYT?

**Comment by jaronoff97** [comment]
I was under the impression that the openshift bundle is installed from a single path [here](https://github.com/open-telemetry/opentelemetry-operator/tree/main/bundle/manifests). I think if we just add in the file there it would only be installed for openshift. Though my knowledge of this is very shaky.

**Comment by iblancasa** [comment]
> I was under the impression that the openshift bundle is installed from a single path [here](https://github.com/open-telemetry/opentelemetry-operator/tree/main/bundle/manifests). I think if we just add in the file there it would only be installed for openshift. Though my knowledge of this is very shaky.

That will affect the installation in plain Kubernetes too. @pavolloffay and I were thinking about having a separate bundle for OpenShift. We are doing that for other projects and it goes well.

**Comment by jaronoff97** [comment]
Oh that would work well too. I would support that.

**Comment by pakita** [comment]
Please can you provide link to OpenShift Dashboard JSON file.
And can you direct me to the link where I can find list of all related metrics that are used for Dashboard.
Thank you

**Comment by iblancasa** [comment]
@pakita you can find it here https://github.com/open-telemetry/opentelemetry-operator/pull/2996/files#diff-7204f0648289b9d9fe4aef9f5c1abb1ab7f07dff8a28d8638cf972a68f488464

**Comment by iblancasa** [comment]
> > I was under the impression that the openshift bundle is installed from a single path [here](https://github.com/open-telemetry/opentelemetry-operator/tree/main/bundle/manifests). I think if we just add in the file there it would only be installed for openshift. Though my knowledge of this is very shaky.
> 
> That will affect the installation in plain Kubernetes too. @pavolloffay and I were thinking about having a separate bundle for OpenShift. We are doing that for other projects and it goes well.

This is not an option because OLM will create the `ConfigMap` in the same namespace where the operator is installed.

**Comment by pavolloffay** [comment]
We should still consider creating on OCP specific bundle if there will be functionality we want to enable by default on that platform

**Comment by iblancasa** [comment]
> We should still consider creating on OCP specific bundle if there will be functionality we want to enable by default on that platform

Sure.
