### ISSUE TITLE
Update Collector to v0.102.0

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-operator#3012]
v0.102.0 has been released, it's time for the Operator to upgrade to v0.102.0!

**Comment by pavolloffay** [comment]
@swiatekm-sumo you are next on the list :)

**Comment by jaronoff97** [comment]
@codeboten i got the release going and we are using the released 0.102.1

**Comment by codeboten** [comment]
thanks @jaronoff97!
