### ISSUE TITLE
appArmorProfile is removed from SecurityContext

### ISSUE THREAD

**Issue by jbmolle** [open-telemetry/opentelemetry-operator#3036]
## Description
When creating a Pod or a Deploy with appArmorProfile into securityContext field, the appArmorProfile is removed by the mutating webhook.
Check https://github.com/kubernetes/kubernetes/issues/125069

## Steps to Reproduce
1) Create a pod with a Yaml file containing 
```
securityContext:
  appArmorProfile:
    type: Unconfined
```
The security context is there with kubectl apply -f xxx.yaml -oyaml --dry-run=server
2)Install opentelemetry-operator
3) Run again kubectl apply -f xxx.yaml -oyaml --dry-run=server, the securityContext appArmorProfile is gone

## Expected Result
appArmorProfile should be present in securityContext

## Actual Result
appArmorProfile is not there

### Kubernetes Version

1.30.2

### Operator version

0.102.0

### Collector version

0.102.0

## Environment
OS: Ubuntu 22.04 / Ubuntu 24.04

**Comment by swiatekm-sumo** [comment]
As I mentioned in https://github.com/open-telemetry/opentelemetry-operator/pull/3037#issuecomment-2163479802, this is blocked on #3041, which is blocked by bumping our required Go version to 1.22 (#2757).
