### ISSUE TITLE
Does Target Allocator support standalone deployment?

### ISSUE THREAD

**Issue by elvis-cai** [open-telemetry/opentelemetry-operator#3038]
### Component(s)

target allocator

### Describe the issue you're reporting

We are using the OpenTelemetry Helm chart to install the OpenTelemetry Collector (https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector). Configuring prometheusreceiver or combining receiver_creator and prometheusreceiver is still a challenge to manage. I'm wondering if we could utilize the Target Allocator to help us dynamically discover targets from Prometheus Operator's PodMonitor/ServiceMonitor, or do we need to install the OpenTelemetry Operator first?

**Comment by swiatekm-sumo** [comment]
You can run it standalone, it's very lightly coupled to the otel operator. Just keep in mind that the configuration still sees breaking changes semi-regularly, and pay attention when upgrading.

**Comment by elvis-cai** [comment]
thanks @swiatekm-sumo 🙏  , at least good to know we can run standalone mode now 👍

**Comment by swiatekm-sumo** [comment]
I'm going to close this issue for now, as your question has been answered. If you have further questions, feel free to reopen and ask them here.
