### ISSUE TITLE
operator does not support dotnet 6 applications

### ISSUE THREAD

**Issue by kaushikramakrishna** [open-telemetry/opentelemetry-operator#3052]
Auto instrumentation annotation on dotnet 6 application throws exception 

kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.50.0/opentelemetry-operator.yaml

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793ae60'. The system cannot find the file specified.

Do we have downward compatibility of operator supporting dotnet 6 ?

**Comment by pavolloffay** [comment]
Please open the issue at https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation?tab=readme-ov-file#compatibility 

but it seems like all versions should be supported.

**Comment by rahjesh-vunet** [comment]
This is still exists. I tried to use Opentelemetry Operator version 0.64.1 for instrumenting the .NET 6 application and I got the same error.
