### ISSUE TITLE
How to inject pod's label to resource attribute?

### ISSUE THREAD

**Issue by JhouXerox** [open-telemetry/opentelemetry-operator#3053]
### Component(s)

collector, auto-instrumentation

### Describe the issue you're reporting

I currently using OT Operator to auto instrumentation. under k8s 1.26.1
I found in my OTEL_RESOURCE_ATTRIBUTES there's no label info.

I need to get label named "app" and "version" to aggregate some metrics.

and I fond some information in document here https://opentelemetry.io/docs/specs/semconv/attributes-registry/k8s/

k8s.pod.label.key

how to use it?

I need apply label info from agent to collector

**Comment by pavolloffay** [comment]
I can think of two option how this can be solved. 

1. downward API https://kubernetes.io/docs/concepts/workloads/pods/downward-api to get the label into an env var. Once it is in the env var it can be reused via OTEL_RESOURCE_ATTRIBUTES 
2. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor 


Please re-open if you run into issues

**Comment by JhouXerox** [comment]
> I can think of two option how this can be solved.
> 
> 1. downward API https://kubernetes.io/docs/concepts/workloads/pods/downward-api to get the label into an env var. Once it is in the env var it can be reused via OTEL_RESOURCE_ATTRIBUTES
> 2. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor
> 
> Please re-open if you run into issues

Thank you for reply, here's the question

1. downward API, I get label into env "label_app" . 
I can echo $label_app ,but it not reused via OTEL_RESOURCE_ATTRIBUTES
![image](https://github.com/open-telemetry/opentelemetry-operator/assets/24403596/c230649f-66e6-43d7-99f4-10e954fee576)

2. if option(1) is not available, will collector get label value by k8sattributes processor? 
If my pod and collector in same namespace, It's no need to set k8s RBAC, right? can collector work on deployment mode?
