### ISSUE TITLE
Create a separate bundle for OpenShift

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#3054]
We should still consider creating on OCP specific bundle if there will be functionality we want to enable by default on that platform

_Originally posted by @pavolloffay in https://github.com/open-telemetry/opentelemetry-operator/issues/2995#issuecomment-2158443988_

This issue is to create a separate bundle for OpenShift. With this, we can enable/disable features that we want to enable for this specific platform.

**Comment by jaronoff97** [comment]
closed by #3056
