### ISSUE TITLE
Updating OpenTelemetryCollector CR mode not deleting old pods

### ISSUE THREAD

**Issue by keruitan-wk** [open-telemetry/opentelemetry-operator#3055]
### Component(s)

collector

## Description
Same as https://github.com/open-telemetry/opentelemetry-operator/issues/2888, updating the mode of the collector CR from deployment to statefulset creates the new statefulset pods but does not remove the old deployment pod.

## Steps to Reproduce
Create a new collector in deployment mode
Update the mode to statefulset

## Expected Result
The old deployment mode pod is removed after the mode is updated and the new statefulset pods are created.

## Actual Result
The old deployment mode pod is still running and has not been removed.

### Kubernetes Version

v1.25.16

### Operator version

v0.102.0

### Collector version

0.102.1

**Comment by swiatekm-sumo** [comment]
I think we should make the `mode` field immutable rather than actually clean this up. Realistically, we'll need to delete the old Deployment/StatefulSet/DaemonSet anyway, with all the consequences of such, and I think it's better if the user explicitly does this on their own. WDYT @jaronoff97 @pavolloffay ?

**Comment by jaronoff97** [comment]
yeah i think doing that probably makes more sense and is a better experience, swapping modes on the fly could have some unintended consequences (going from deployment -> daemonset for example)

**Comment by fyuan1316** [comment]
Agreed, making the `mode` field immutable seems like a safer approach.
Consider another scenario where statefulset is changed to another mode. Stateful services should be handled with care, removing them outright could cause other problems.

**Comment by jaronoff97** [comment]
@fyuan1316 would you want to work on this one?

**Comment by fyuan1316** [comment]
Hi @jaronoff97 

Do you have any suggestions for a specific implementation? I'm wondering if webhook validation is enough.

**Comment by fyuan1316** [comment]
I've submitted a PR but I'm not sure if this modification is appropriate. Does this make sense?

**Comment by swiatekm-sumo** [comment]
As far as I'm aware you can't do much better than webhook validation here while also supporting K8s 1.23. In newer K8s versions, you could use CEL for this, but we can't assume the cluster supports it yet.

**Comment by jaronoff97** [comment]
yeah i don't think there's a good way to do this in the controller today other than running some extra queries which would be kinda hacky IMO. I think once we upgrade our min kube version we could revisit this.
