### ISSUE TITLE
Operator takes a long time to reacquire lease after previous leader exits

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/opentelemetry-operator#3058]
### Describe the issue you're reporting

When leader election is enabled for the operator, it takes upwards of two minutes before the new leader acquires the lease. Leader election is enabled by default so this affects even single-replica Deployments.

A proposed fix would be to release the lease on manager exit by enabling `LeaderElectionReleaseOnCancel` https://github.com/kubernetes-sigs/controller-runtime/blob/8290d13680ed6066d9789c0ed59ff604387e20da/pkg/manager/manager.go#L202. This can apparently be unsafe in some circumstances, but we immediately exit on manager exit, so we should be fine.

**Comment by fyuan1316** [comment]
<img width="1623" alt="image" src="https://github.com/open-telemetry/opentelemetry-operator/assets/42265657/97d0ebb8-551a-456e-82fa-8d4b448dfe7d">

I just ran into this as well, deleting the operator pod and rebuilding should reproduce it. It does take a little longer.
