### ISSUE TITLE
Enable "enable-multi-instrumentation" flag by default

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#3090]
### Component(s)

collector, auto-instrumentation

### Is your feature request related to a problem? Please describe.

The features that are enabled by `enable-multi-instrumentation` have been there for a while and it might be a good time to enable them by default.

The only risk I can see is those user workloads using the  `instrumentation.opentelemetry.io/container-names` would not be instrumented when they are restarted or recreated. We can implement a warning as part of the validation webhook + something as part of the upgrade routines in order to replace this annotation with the language-specific ones.

### Describe the solution you'd like

.

**Comment by pavolloffay** [comment]
@swiatekm @jaronoff97 any objections?

**Comment by swiatekm** [comment]
As far as I can see, this would be a breaking change, as the flag actually changes the behaviour, and different annotations must be used for multi-container instrumentation for the same language. Can we not avoid this breaking change, or at least allow the old annotations to work while the multi-instrumentation flag is enabled?

**Comment by pavolloffay** [comment]
@iblancasa can we write an upgrade procedure to migrate already injected agents?

**Comment by iblancasa** [comment]
> . Can we not avoid this breaking change, or at least allow the old annotations to work while the multi-instrumentation flag is enabled?
@swiatekm With a migration procedure should be enough. But I agree that it would be better if we could make the `instrumentation.opentelemetry.io/container-names` annotation work when the flag is enabled. I'll try to send a PR to make it work when the annotation is there (I'm not sure if that would be considered a breaking change too).

> @iblancasa can we write an upgrade procedure to migrate already injected agents?
@pavolloffay It is what I proposed in my first comment:
```
We can implement a warning as part of the validation webhook + something as part of the upgrade routines in order to replace this annotation with the language-specific ones.
```
I'll create a PR to address this.

**Comment by artem-nefedov** [comment]
It seems that recent changes broke something, check https://github.com/open-telemetry/opentelemetry-operator/pull/3213#issuecomment-2383700953

**Comment by iblancasa** [comment]
https://github.com/open-telemetry/opentelemetry-operator/pull/3213#issuecomment-2383700953

@artem-nefedov can you provide more information like:
1. Is it multiinstrumentation enabled in your environment?
2. Any log messages from the operator?
3. Is the `initContainer` created?

**Comment by iblancasa** [comment]
> It seems that recent changes broke something, check [#3213 (comment)](https://github.com/open-telemetry/opentelemetry-operator/pull/3213#issuecomment-2383700953)

#3307
