### ISSUE TITLE
Add support for k8s labels such as app.kubernetes.io/name

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-operator#3112]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

k8s labels such as app.kubernetes.io/name are recommended to set the app name and similar

See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

this should be supported by the otel operator

### Describe the solution you'd like

This mapping should work for the following labels:

- `app.kubernetes.io/name` - `service.name`
- `app.kubernetes.io/instance` - `service.instance.id`
- `app.kubernetes.io/version` - `service.version`
- `app.kubernetes.io/part-of` - `service.namespace`

And for the following annotations:

- `opentelemetry.io/resource.foo` - `foo` (for any key) - note that the [k8sattributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md) can also process those annotations, see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34040

**Comment by jaronoff97** [comment]
@zeitlinger is this different from [this issue](https://github.com/open-telemetry/opentelemetry-operator/issues/2181)? Wondering if i can merge these together.

**Comment by zeitlinger** [comment]
> @zeitlinger is this different from [this issue](https://github.com/open-telemetry/opentelemetry-operator/issues/2181)? Wondering if i can merge these together.

didn't know about it 
looks very similar

- the prefix in my pr is `opentelemetry.io/resource.` instead of `resource.opentelemetry.io/` - I don't have a strong preference
- I also have support for common k8s variables (see description)
- I think I've handled more edge cases in my pr

**Comment by jaronoff97** [comment]
I think i prefer the `resource.opentelemetry.io/`, and agreed, I think your PR handles more. I'm going to close that issue and PR in favor of this one.

**Comment by jaronoff97** [comment]
@zeitlinger i added the discuss-at-sig label as it seems from Tyler's comment on the PR that there's some bigger picture stuff we need to figure out in order to not break users. We have a SIG meeting tomorrow (8/29) at noon EST where we will discuss this.

**Comment by zeitlinger** [comment]
> @zeitlinger i added the discuss-at-sig label as it seems from Tyler's comment on the PR that there's some bigger picture stuff we need to figure out in order to not break users. We have a SIG meeting tomorrow (8/29) at noon EST where we will discuss this.

great - I'll join
