### ISSUE TITLE
CI steps fail publishing images and logging into docker

### ISSUE THREAD

**Issue by gdfast** [open-telemetry/opentelemetry-operator#3113]
### Describe the issue you're reporting

I've been doing the typical contributor flow of making commits to branches on my fork – https://github.com/gdfast/opentelemetry-operator – and then opening pull requests again the main repo. When I updated PR https://github.com/open-telemetry/opentelemetry-operator/pull/3080 today after merging in new upstream changes from the main branch, I got a series of CI failures, including:

* [[gdfast/opentelemetry-operator] Publish operator bundle workflow run](https://github.com/gdfast/opentelemetry-operator/actions/runs/9841910429)
* [[gdfast/opentelemetry-operator] Publish NodeJS Auto-Instrumentation workflow run](https://github.com/gdfast/opentelemetry-operator/actions/runs/9841910430)
* [[gdfast/opentelemetry-operator] Publish operator workflow run](https://github.com/gdfast/opentelemetry-operator/actions/runs/9841910446)
* [[gdfast/opentelemetry-operator] Publish Operator OpAMP Bridge workflow run](https://github.com/gdfast/opentelemetry-operator/actions/runs/9841910433)
* [[gdfast/opentelemetry-operator] Publish target allocator workflow run](https://github.com/gdfast/opentelemetry-operator/actions/runs/9841910443)

All of these workflows fail at the "Log into Docker.io" step with
> Error: Username and password required

A little later, I also got the failure
* [[gdfast/opentelemetry-operator] Publish Test E2E images workflow run](https://github.com/gdfast/opentelemetry-operator/actions/runs/9841910456)

which failed in each workflow's _Build and push_ step with
> Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/open-telemetry/opentelemetry-operator/e2e-test-app-bridge-server:main: unexpected status from POST request to https://ghcr.io/v2/open-telemetry/opentelemetry-operator/e2e-test-app-bridge-server/blobs/uploads/: 403 Forbidden

My fork was sync'ed to this commit: https://github.com/open-telemetry/opentelemetry-operator/commit/1289c63d762f74700d0f288115bb2cde67b9f8ad

I acknowledge the OTel Operator is under active development and I may have missed a new setup step that wasn't previously required.

**Comment by pavolloffay** [comment]
All these workflows are from your fork https://github.com/gdfast/opentelemetry-operator. We don't guarantee that GHA workflows will work in forked repositories.

**Comment by jaronoff97** [comment]
@pavolloffay i wonder if we should either disable workflows on user forks by default _or_ have it use their repo for pushing images. That being said, idk why we do a push at all for this?

**Comment by pavolloffay** [comment]
I would not object if someone wants to use generic org-name/repo-name in https://github.com/open-telemetry/opentelemetry-operator/blob/98006c220c8a5ec51efe52723fa53756ae0a8da8/.github/workflows/publish-autoinstrumentation-java.yaml#L37

but I would treat it as a best effort. It's problematic to test and maintain.
