### ISSUE TITLE
Operator instrumentation duplicating prometheus metrics

### ISSUE THREAD

**Issue by igorestevanjasinski** [open-telemetry/opentelemetry-operator#3114]
### Component(s)

auto-instrumentation

## Description
Hello, I'm trying to use the operator to instrument my java applications with traces, metrics and logs using opentelemetry operator and I'm having problems with the metrics instrumentation which seems to duplicate metrics or fetching metrics from other containers or from the init-container itself. 

![image](https://github.com/open-telemetry/opentelemetry-operator/assets/108187126/9f8e2493-efd3-49c2-94f8-da933d575723)

I also try to configure the init container manually using operator instrumentation image, but same result.
![image](https://github.com/open-telemetry/opentelemetry-operator/assets/108187126/8670cae6-a029-49dc-90b2-ec94ec44fb0b)

## Steps to Reproduce
`apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: amstad-instrumentation-with-prometheus-logs
spec:
  exporter:
    endpoint: xxx
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: xxxs
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: prometheus
      - name: OTEL_EXPORTER_PROMETHEUS_PORT
        value: "9464"
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest

`
## Expected Result
1 promeheus endpoint for each application
## Actual Result
Metrics duplicated

### Kubernetes Version

v1.24.17

### Operator version

0.100.0

### Collector version

na

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by pavolloffay** [comment]
Maybe the issue is that there are two scare jobs.

could you please paste here output for `:9464/metrics` endpoint of the application?

**Comment by igorestevanjasinski** [comment]
> Maybe the issue is that there are two scare jobs.
> 
> could you please paste here output for `:9464/metrics` endpoint of the application?

[metrics.txt](https://github.com/user-attachments/files/16142989/metrics.txt)

**Comment by igorestevanjasinski** [comment]
> Do you see there any duplicated metrics?

Actually no, but at the prometheus targets I'm able to see 2 scrapes. 1 for the actual app and 1 for the init container.
![image](https://github.com/open-telemetry/opentelemetry-operator/assets/108187126/b70ece1f-1056-457a-a2d4-418be638a821)
Any tip how to avoid that?
