### ISSUE TITLE
Use 0.0.0.0 as otlp receiver default address

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-operator#3126]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

The 0.104.0 collector release enables `component.UseLocalHostAsDefaultHost` by default. Since this would be a breaking change for the users, the operator in 0.104.0 reverts this change by updating fields like `:4317` or empty fields to `0.0.0.0:4317`.

### Describe the solution you'd like

Maybe it does make sense to use the collector default `localhost` in sidecar scenarios and the `$POD_IP` for all the other modes. 

---

### Update
Add upgrade routine and default webhook entry for the following components(source https://github.com/open-telemetry/opentelemetry-collector/issues/8510#issuecomment-1735292387):
- [x] [otlp receiver]()
 - [x]    [healtcheck extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/extension/healthcheckextension/factory.go#L19)
---
- [ ] [awsproxy extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/extension/awsproxy/factory.go#L19)
- [ ]     [jmx receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/jmxreceiver/factory.go#L19)
 - [ ]    [loki receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/lokireceiver/factory.go#L23)
 - [ ]    [jaeger receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/jaegerreceiver/factory.go#L33)
 - [ ]    [zipkin receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/zipkinreceiver/factory.go#L20)
 - [ ]    [awsxray receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/awsxrayreceiver/factory.go#L35)
 - [ ]    [influxdb receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/influxdbreceiver/factory.go#L28)
 - [ ]    [awsfirehose receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/awsfirehosereceiver/factory.go#L23)
 - [ ]    [opencensus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/opencensusreceiver/factory.go#L32)
 - [ ]    [skywalking receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39d1e5398ff9f20681adb1c46f667b8f61c74143/receiver/skywalkingreceiver/factory.go#L32)

Next:
- [ ] Double check if we miss some components
- [ ] Add upgrade routine to remove `component.UseLocalHostAsDefaultHost` feature-gate.
- [ ] Remove `component.UseLocalHostAsDefaultHost` from defaulting webhook
---

### Describe alternatives you've considered

Keep it like it is today or disable the `component.UseLocalHostAsDefaultHost` featuregate. (Which will be removed in the future).

### Additional context

https://github.com/open-telemetry/opentelemetry-operator/pull/3119#discussion_r1674716212

**Comment by frzifus** [comment]
cc @jaronoff97 @pavolloffay @swiatekm

**Comment by pavolloffay** [comment]
`$POD_IP` makes more sense than `0:0:0:0` but I don't know if there is a big difference for deployment/SS pods, but maybe it matters more in e.g. daemonset .

**Comment by matthagenbuch** [comment]
For services running in kubernetes, the norm is to bind to the 0 address. Binding to pod_ip may be slightly more secure since it is a smaller surface area, but it could result in unexpected behavior, such as when using `kubectl port-forward`. As a user I would prefer binding to the 0 address by default for convention / convenience.

**Comment by frzifus** [comment]
Something you want to work on @led0nk? :)

**Comment by led0nk** [comment]
Yes, please

**Comment by jaronoff97** [comment]
would this featuregate be enabled by default and eventually removed?

**Comment by frzifus** [comment]
It should be enabled by default once `component.UseLocalHostAsDefaultHost` is removed on the collector side.
