### ISSUE TITLE
Skipping javaagent injection

### ISSUE THREAD

**Issue by mghidotti** [open-telemetry/opentelemetry-operator#3166]
### Component(s)

auto-instrumentation

### Describe the issue you're reporting

While trying to instrument my java application (called "api-rest") using open-telemetry auto instrumentation injection, I discovered that it is not possible to instrument my app.

Looking at my opentelemetry operator logs this is what i got:
`{"level":"INFO","timestamp":"2024-07-25T09:44:27Z","message":"Skipping javaagent injection","reason":"the container defines env var value via ValueFrom, envVar: JAVA_TOOL_OPTIONS","container":"api-rest"}
{"level":"INFO","timestamp":"2024-07-25T09:45:08Z","message":"Skipping javaagent injection","reason":"the container defines env var value via ValueFrom, envVar: JAVA_TOOL_OPTIONS","container":"api-rest"}
{"level":"INFO","timestamp":"2024-07-25T12:42:56Z","message":"Skipping javaagent injection","reason":"the container defines env var value via ValueFrom, envVar: JAVA_TOOL_OPTIONS","container":"api-rest"}
{"level":"INFO","timestamp":"2024-07-25T12:43:38Z","message":"Skipping javaagent injection","reason":"the container defines env var value via ValueFrom, envVar: JAVA_TOOL_OPTIONS","container":"api-rest"}`

My app takes the JAVA_TOOL_OPTIONS env var from a config map and I need the configuration to be done this way to be able to give access to modify only the config map from outside. **I wanted to ask if there was a workaround to this problem.**

Let me know if you need further information, thanks

**Comment by jaronoff97** [comment]
This is a known issue right now and we are waiting an implementation for the fix. https://github.com/open-telemetry/opentelemetry-operator/issues/1814

Please follow up on the initial issue if you can, so we can prioritize a fix accordingly.
