### ISSUE TITLE
Support opentelemetry-operator/autoinstrumentation-java v1.x

### ISSUE THREAD

**Issue by ElfoLiNk** [open-telemetry/opentelemetry-operator#3167]
### Component(s)

opentelemetry-operator/autoinstrumentation-java docker image

### Describe the issue you're reporting

Hi,

I have a mixed Java and Node.js application and I do not want to bump the Java instrumentation to version 2.x due to the breaking changes it introduces ([changelog link](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/CHANGELOG.md#%EF%B8%8F%EF%B8%8F-breaking-changes-%EF%B8%8F%EF%B8%8F)).

Is there a plan or possibility to continue releasing Docker images for Java 1.x instrumentation? The last image for 1.x is 1.31.0 ([link](https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fautoinstrumentation-java)), but the latest version available is 1.33.5 ([link](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases)).

Thank you,

**Comment by jaronoff97** [comment]
Thanks for opening this, I think we'll need to have a conversation to figure out how to support both of these. Right now our CI supports only 2.x, so it will require some changes.

**Comment by pavolloffay** [comment]
We should keep publishing 1.x. Here is PR for 1.33.5 https://github.com/open-telemetry/opentelemetry-operator/pull/3176
