### ISSUE TITLE
Allow to customize collector's name or collector's service name

### ISSUE THREAD

**Issue by jdiegosierra** [open-telemetry/opentelemetry-operator#3177]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

When the collector is deployed, a service is created using metadata.name followed by "-collector", for example:
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: test-collector
 ```
 This will create a service called "test-collector-collector".

### Describe the solution you'd like

I want to be able to customize collector's name or collector's service name without adding the "-collector" sufix

### Additional context

For the collector Deployment there should be a way to overwrite the name here:
https://github.com/open-telemetry/opentelemetry-operator/blob/eab0b6a7bff1d952eb8c67c60ac3481eb8adc9d4/internal/naming/main.go#L70-L72

For the service:
https://github.com/open-telemetry/opentelemetry-operator/blob/eab0b6a7bff1d952eb8c67c60ac3481eb8adc9d4/internal/naming/main.go#L120-L122

**Comment by jdiegosierra** [comment]
I'm not an expert in go, but I don't mind to implement it. Please let me know if you agree with this feature.

**Comment by jdiegosierra** [comment]
@pavolloffay @jaronoff97 what do you think?

**Comment by jaronoff97** [comment]
This could result in a major breaking change as many users potentially rely on the existing naming. I think maintaining two naming conventions would result in a lot of edge cases that we wouldn't want to handle today. I'm not sure there's a clean way to implement this without resulting in either a challenging developer experience or a breaking change for users.

**Comment by jaronoff97** [comment]
Is there something that this is preventing you from doing today, or is this mostly cosmetic?

**Comment by jdiegosierra** [comment]
Is purely cosmetic. If there isn't a clean way then it's not worth it.

Thank you!
