### ISSUE TITLE
Add podLabels to collectors

### ISSUE THREAD

**Issue by melchiormoulin** [open-telemetry/opentelemetry-operator#3186]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

I can't see [here](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector) how to add labels to the pod and the deployment of collector and targetallocator. 

### Describe the solution you'd like

having a podLabels keys for the pod
having a podLabels keys for the targetallocator
having a deploymentLabels keys for the deployment

**Comment by pavolloffay** [comment]
The labels set on the collector CR should get propagated to the deployment. 

Does it solve your use-case?

**Comment by melchiormoulin** [comment]
thanks, i've tested it, it works.
