### ISSUE TITLE
The labels-filter startup parameter, flag is --label, which is inconsistent with the example and variable name.

### ISSUE THREAD

**Issue by chinaran** [open-telemetry/opentelemetry-operator#3201]
### Component(s)

collector

## Description

The labels-filter startup parameter, flag is --label, which is inconsistent with the example and variable name.

## Expected Result

--labels-filter

## Actual Result

--label

### Kubernetes Version

v1.29.2

### Operator version

v0.105.0

### Collector version

v0.104.0

### Additional context

Reference Code: https://github.com/open-telemetry/opentelemetry-operator/blob/v0.105.0/main.go#L173

```go
pflag.StringArrayVar(&labelsFilter,
 "label",
 []string{},
 "Labels to filter away from propagating onto deploys.
  It should be a string array containing patterns,
 which are literal strings optionally containing a * wildcard character.
  Example: --labels-filter=.*filter.out will filter out labels that looks like: label.filter.out: true")
```

**Comment by pavolloffay** [comment]
@chinaran would you like to fix it?
