### ISSUE TITLE
Align label filter flag with attribute filter flag name

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#3218]
Right now the flag we use for label filtering is `--label` rather than `--labels-filter` which aligns with the existing naming for the `--annotations-filter`. To migrate we could introduce the new flag, and automatically move anything from --label to be appended to that. Eventually we deprecate/remove the --label flag.

_Originally posted by @jaronoff97 in https://github.com/open-telemetry/opentelemetry-operator/pull/3203#pullrequestreview-2236123687_

**Comment by davidhaja** [comment]
I would like to work on this one.
