### ISSUE TITLE
Add @VineethReddy02 as approver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#324]
@VineethReddy02 has been making constant quality contributions to this repository. As such, I think it would be beneficial for the community to add them to the @open-telemetry/operator-approvers group.

cc @open-telemetry/operator-maintainers

**Comment by bogdandrutu** [comment]
I am ok with this :) Thanks

**Comment by tigrannajaryan** [comment]
I support.

**Comment by jpkrohling** [comment]
Great! Who can make the changes? Looks like I don't have permissions to change the groups :-)

**Comment by jpkrohling** [comment]
ping @tigrannajaryan, @bogdandrutu

**Comment by tigrannajaryan** [comment]
Added. Welcome as an approver @VineethReddy02 !
