### ISSUE TITLE
TargetAllocator broken after release 0.105 when using custom domains.

### ISSUE THREAD

**Issue by foolusion** [open-telemetry/opentelemetry-operator#3242]
### Component(s)

target allocator

## Description

The code in #3187 hardcodes svc.cluster.local as the domain in TargetAllocator. This breaks for everyone that uses custom domains in kubernetes. 

## Steps to Reproduce

Create a cluster with a custom domain --cluster-domain="foo.cluster.local"
Add OTelOperator and TA

## Expected Result

TA should create configs that use either cluster domain or omit the the svc.cluster.local like it previously did in 0.105.

## Actual Result

TA adds svc.cluster.local to the endpoint and it fails

### Kubernetes Version

1.30

### Operator version

v0.107.0

### Collector version

v0.107.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

Set --cluster-domain="foo.cluster.local"

**Comment by yingsamsung** [comment]
This issue is blocking our deployment. We had to roll back to 0.105. Can you please provide a ETA on when you can get this fixed? Thanks.

**Comment by foolusion** [comment]
I created a rollback commit @jaronoff97 and @pavolloffay PTAL
