### ISSUE TITLE
Prometheus exporter

### ISSUE THREAD

**Issue by ShaunHavelaar91** [open-telemetry/opentelemetry-operator#3251]
### Component(s)

collector

### Describe the issue you're reporting

Hi

I'm struggling to find resources around the Prometheus exporter. Currently, it's in beta so it should be part of the latest release by default, but whenever I try to use it I get the following error

`error decoding 'exporters': unknown type: "prometheus" for id: "prometheus" (valid values: [file loadbalancing otelarrow debug nop otlp otlphttp])
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):`

it's probably something stupid on my end but I've been trying to get this working without any success :) any help would really be appreciated

**helm version:** opentelemetry-operator:0.67.0
**collectorImage:** otel/opentelemetry-collector-k8s:latest

Snipped to the template:

`
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-sidecar
  namespace: default
spec:
  mode: sidecar
  config:

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        metrics:
          exporters:
            - prometheus
          receivers:
            - otlp
`

**Comment by chinaran** [comment]
This should be a case of collector being compiled without the prometheusexporter.
You can switch to the otelcol-contrib version, otel/opentelemetry-collector-contrib, or compile it yourself.
Reference:
- [otelcol-k8s/manifest.yaml](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-k8s)
- [otelcol-contrib/manifest.yaml](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml#L76C79-L76C97)

**Comment by iblancasa** [comment]
The operator uses the core OTEL Collector image:
https://github.com/open-telemetry/opentelemetry-operator/blob/789e2c23b526bc6e0aa8b2c367d1435fbac4ccc0/main.go#L163C20-L163C27

You need to use your own distribution or contrib.
