### ISSUE TITLE
Autoscaler targetCPUUtilization and TargetMemoryUtilization cannot be greater than 99

### ISSUE THREAD

**Issue by davidhaja** [open-telemetry/opentelemetry-operator#3258]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

In some cases users want to configure the HPA to scale out when the average utilization is over the requested resource and close to the configured limits. 
We can put any % value in the HPA autoscaler. For example, you can set a resource request of 100m and set the autoscaler to 500% that will create new pods when the CPU usage is 500m.

The conditions [here](https://github.com/open-telemetry/opentelemetry-operator/blob/629aed56e6352728c1f482d099a35fb9494819b7/apis/v1beta1/collector_webhook.go#L381C2-L386C3) limit the configurable utilization values that we can set to the range of 1-99, which I believe is unnecessary.
I would change this logic to check only if the provided utilization values are positive numbers.

### Describe the solution you'd like

I think it is enough to check whether the TargetCPUUtilization and the TargetMemoryUtilization are positive numbers in [these conditions](https://github.com/open-telemetry/opentelemetry-operator/blob/629aed56e6352728c1f482d099a35fb9494819b7/apis/v1beta1/collector_webhook.go#L381C2-L386C3)

### Additional context

HPA calculates the resource utilization using the resource requests.
From the [HPA Documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/): "if a target utilization value is set, the controller calculates the utilization value as a percentage of the equivalent [resource request](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits) on the containers in each Pod."

Although in some cases users may want to configure the thresholds closer to their configured resource limits [Kubernetes - 72811](https://github.com/kubernetes/kubernetes/issues/72811).
As a workaround they can set the utilization threshold greater than 100%.

**Comment by jaronoff97** [comment]
Hmm I hadn't considered the use case for a >100% hpa usage number. It seems a bit odd to do this, but I don't think we should disallow it. I say go for it, just remove the upper bound and we should be fine.
