### ISSUE TITLE
Allow references to other volumes (eg. PVCs) for instrumention auto-inject

### ISSUE THREAD

**Issue by jnarezo** [open-telemetry/opentelemetry-operator#3267]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

In an environment where you **can't provision an emptyDir above ~150Mi** (the size of the nodejs instrumentation), it's impossible to use auto-instrumentation, since the emptyDir would be too small to transfer the instrumentation from the injected init container to the main container.

### Describe the solution you'd like

Changing the Instrumentation resource spec to replace `Instrumentation.spec.<lang>.volumeSizeLimit` with something more generic like `Instrumentation.spec.<lang>.volume` that references a [Volume](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#volume-v1-core).

This solution should allow a reference to a pre-existing or ephemeral volume help alleviate this issue.

### Describe alternatives you've considered

I've also considered:
- Allow some switch between emptyDir and a reference to a PVC
  - Not as flexible as just allowing the user to specify a k8s **core** spec
- Forcing user to change their environment
  - Operator is responsible for creating the volume to transfer instrumentation, it makes more sense for it to be customizable/solved at this level

**Comment by jnarezo** [comment]
I don't mind tackling this myself + opening a PR, but would like to hear your opinions/suggestions for the overall feature. 🙂

**Comment by iblancasa** [comment]
> Changing the Instrumentation resource spec to replace Instrumentation.spec.<lang>.volumeSizeLimit with something more generic like Instrumentation.spec.<lang>.volume that references a [Volume](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#volume-v1-core).

I think those should be two independent configurations. Not a replacement.

>Forcing user to change their environment
Operator is responsible for creating the volume to transfer instrumentation, it makes more sense for it to be customizable/solved at this level

It is more or less what the operator is currently doing, right? It creates the Volumen to inject the instrumentation.

I don't get the `Forcing user to change their environment`, can you give context?

**Comment by jnarezo** [comment]
> I don't get the Forcing user to change their environment, can you give context?

Sorry, I meant to say that I considered these alternative **workarounds**, however I don't think they're good solutions.

With my second bullet point, a workaround could be "forcing the user to change their environment," which means forcing the user to work with their cluster admins to change policies and increase the emptyDir size limit policy.

However, that's not really a solution so that's why I opened this issue.

---

> I think those should be two independent configurations. Not a replacement.

Yeah! I'm not against it, but I'm not sure about this edge case: When user provides a volume spec with a specific size + `volumeSizeLimit` at the same time.

If both are defined, will this just throw an error? Or should the values somehow be merged?
