### ISSUE TITLE
Remove ComponentUseLocalHostAsDefaultHost()

### ISSUE THREAD

**Issue by diranged** [open-telemetry/opentelemetry-operator#3306]
### Component(s)

collector

## Description

The [`ComponentUseLocalHostAsDefaultHost()`](https://github.com/open-telemetry/opentelemetry-operator/blob/v0.109.0/apis/v1beta1/collector_webhook.go#L446-L464) function should be removed at this point... the operator forces the `component.UseLocalHostAsDefaultHost` flag to be added. The problem is that in the OTEL Collector [0.110.0](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.110.0),  that flag is no longer settable:

```
Error: invalid argument "+processor.resourcedetection.hostCPUSteppingAsString,+exporter.prometheusremotewritexporter.RetryOn429,-component.UseLocalHostAsDefaultHost" for "--feature-gates" flag: feature gate "component.UseLocalHostAsDefaultHost" is stable, can not be disabled
```

### Kubernetes Version

1.30.0

### Operator version

0.109.0

### Collector version

1.111.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jaronoff97** [comment]
this should be part of our next release, cc @frzifus would you be able to do this to close https://github.com/open-telemetry/opentelemetry-operator/issues/3126 as well?

**Comment by frzifus** [comment]
yes!

**Comment by ryanmt** [comment]
Is there any way to prevent this feature flag from being added to the produced resources w/o a new release? I'm trying to overcome an issue similar to this one for the helm chart from the install manifests. https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1339

**Comment by jaronoff97** [comment]
@ryanmt we will need to do a new release as that's how the images get published, though i guess you could use the image from main. We haven't released 0.110.0 yet, so i would recommend not misaligning those versions.

**Comment by henrikrexed** [comment]
Hi,
i'm having the same issue , i forced to use a collector v 0.110 to get the latest functions of the transform processor. 
When would the feature flalg UseLocalHostAsdeFualthost would be removed and when is the next release of the operator planned?

**Comment by jaronoff97** [comment]
@henrikrexed @frzifus is on it right now and will be done hopefully by EOW this week.

**Comment by odubajDT** [comment]
Related issue https://github.com/Dynatrace/dynatrace-otel-collector/issues/311. The feature flag was fully moved to stable in OTel upstream, waiting for a new upstream release to backport the changes to dynatrace-otel-collector.
