### ISSUE TITLE
container names annotations don't work for for sdk, apache, nginx

### ISSUE THREAD

**Issue by Joibel** [open-telemetry/opentelemetry-operator#3313]
### Component(s)

auto-instrumentation

## Description

This is just an issue to cover #3307 as I need an issue for the changelog.

## Steps to Reproduce

Attempt to use the container names annotations for the 3 affected injectors

## Expected Result

They inject into the appropriate containers

## Actual Result

The annotations are ignored

### Kubernetes Version

1.28

### Operator version

v0.109.0

### Collector version

Irrelevent

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jaronoff97** [comment]
closed by #3307

**Comment by jaronoff97** [comment]
thank you for your contribution!
