### ISSUE TITLE
autoinstrumentation nodejs no image found in image index for architecture ppc64le

### ISSUE THREAD

**Issue by massimilianocorsi** [open-telemetry/opentelemetry-operator#3322]
### Is your feature request related to a problem? Please describe.

I would like to request that the OpenTelemetry Nodejs autoinstrumentation image (ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.52.1) be built and made available for the ppc64le architecture (IBM Power).

Currently, the image seems to be available only for other architectures, and we require it for our environment which runs on ppc64le.

### Describe the solution you'd like

I would like to inquire if a multi-architecture image of the OpenTelemetry Nodejs autoinstrumentation is available, specifically with support for the ppc64le architecture.

### Describe alternatives you've considered

I can build it from dockerfile https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/Dockerfile

**Comment by massimilianocorsi** [comment]
I found Dockerfile https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node?activeTab=code

**Comment by pavolloffay** [comment]
See https://github.com/open-telemetry/opentelemetry-operator/pull/3362
