### ISSUE TITLE
Allow customizing role RBAC rules

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-operator#333]
Today the operator creates a role with RBAC rules that make sense for the standard installation of Otel collector. However, some installations might not working with the default rules depending on the components selected and the k8s distribution being used. For example, a receiver might want to collect ClusterResourceQuota metrics from an OpenShift cluster but it needs additional RBAC rules. 

OpenTelemetry Operator allows to specify a custom service account but this requires the users to manually create a role, service account, cluster role bindings and then manage those objects.

It'd be great if users could specify RBAC rules when creating a collector instance and the operator would automatically add those rules to the role it creates.

**Comment by jpkrohling** [comment]
I think there are two aspects to this request, and I have different opinions depending on how we see it.

> a receiver might want to collect ClusterResourceQuota metrics from an OpenShift cluster but it needs additional RBAC rules

In this case, the operator should indeed create a service account with the required permissions. The operator is the right piece of code to hold the knowledge about which receivers need which resources.

> It'd be great if users could specify RBAC rules when creating a collector instance and the operator would automatically add those rules to the role it creates.

In this case, I'm not sure I agree. I think this would belong to the provisioning tool used by the admins. The same way they provision the operator, they can provision a service account with their custom requirements. We have this philosophy elsewhere in other operators, like Jaeger's: we can provision a basic Elasticsearch/Kafka cluster, but anything beyond the basics has to be done by admins outside of the scope of the operator.
