### ISSUE TITLE
RELATED_IMAGE_AUTO_INSTRUMENTATION_NGINX points to httpd-apache image by default

### ISSUE THREAD

**Issue by GerbenWelter** [open-telemetry/opentelemetry-operator#3335]
### Component(s)

auto-instrumentation

### Describe the issue you're reporting

I'm not sure if this was intentional or some copy/paste error but ever since support was added for nginx autoinstrumentation in #2033 the default refers to the httpd-apache image. The versions.txt file also seems to suggest it was a copy/paste error because it mentions 'Apache NGINX'. The more confusion part is that there seems to be no autoinstrumentation-nginx image available.

So my question is if there should be an autoinstrumentation-nginx image or was the httpd-apache always to be used but wasn't made that clear?

**Comment by pavolloffay** [comment]
nginx and apachehttpd images are the same https://github.com/orgs/open-telemetry/packages?repo_name=opentelemetry-operator
