### ISSUE TITLE
Why was the minor version increased despite a breaking change?

### ISSUE THREAD

**Issue by fkaksa** [open-telemetry/opentelemetry-operator#3348]
### Component(s)

collector

### Describe the issue you're reporting

Hi,

I noticed that the v0.100.0 release of the OpenTelemetry component includes a breaking change, yet the version bump was a minor version increase (v0.99.0 -> v.0.100.0). 
According to semantic versioning principles, shouldn't a breaking change trigger a major version update?

Could you clarify the reasoning behind this decision?

Thanks,
Filip

**Comment by jaronoff97** [comment]
Right now the operator follows the collector's versioning scheme so we keep our versioning 1:1 with them. Further going from 0.99.0 to 0.100.0 contained [no breaking changes](https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.100.0) (we did need to hotfix something in our version 0.100.1). It is expected ([per kubernetes guidance](https://kubernetes.io/docs/reference/using-api/#api-versioning)) that v1alpha1 may contain breaking changes between releases, we promoted the collector CRD to v1beta1 for this exact reason – to show that we are minimizing breaking changes to that spec.
