### ISSUE TITLE
Black-box vs. white-box testing

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#34]
The Operator SDK (and most other Go projects I've seen) has a white box testing approach by default. Kubebuilder has, apparently, opinions about it and follows a black box approach, using specific test packages (`foo` vs `foo_test`) so that the API can be validated as well. The problem with this is that it requires the subject to have features that are needed only by the tests at first, and potentially forever. This makes the subject more complex, without a real need.

Context: https://github.com/open-telemetry/opentelemetry-operator/pull/31#discussion_r471398987

It's good to note that both can live alongside, but this issue is to mainly discuss what's our preferred approach, resorting to the other approach only when it's not feasible to use the preferred approach.

**Comment by jpkrohling** [comment]
cc @objectiser, @kevinearls

**Comment by objectiser** [comment]
I think better to stick with white box testing, and only use black box testing approach when that is a specific requirement - to fit in better with go convention, and make it more familiar for contributors.

**Comment by treasurechristain** [comment]
Please, what are we expected to do on this issue?

**Comment by jpkrohling** [comment]
@treasurechristain this is only a discussion on what we should prefer for the future, there's no specific outcome for this yet.

**Comment by treasurechristain** [comment]
@jpkrohling  Yes, I go with the white box testing because the need to test the integral path of the system/app is very necessary. It will give us the insight of how the system works and the interior components of the system, thereby w=you will be able to dictate bugs/error easily.

But adopt black box testing when a specific evaluation is needed.
