### ISSUE TITLE
release v0.112.0

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-operator#3404]
### Component(s)

collector

### Describe the issue you're reporting

https://github.com/open-telemetry/opentelemetry-collector/issues/11516#issue-2606145609

cc @evan-bradley

**Comment by pavolloffay** [comment]
@yuriolisa you are next on the list :)

**Comment by swiatekm** [comment]
@yuriolisa please prepare the PR bumping only the collector version asap, so we can see if we need to address any breakage. The actual release PR you can submit whenever appropriate.

**Comment by pavolloffay** [comment]
@swiatekm is there anything specific that might be breaking in 0.112.0?

**Comment by swiatekm** [comment]
> @swiatekm is there anything specific that might be breaking in 0.112.0?

I was hoping to find that out. :) But if Yuri wants to do a single PR, that's fine as well. I'm mostly concerned with detecting potential breakage asap.
