### ISSUE TITLE
Add support for multiple config files

### ISSUE THREAD

**Issue by wperron** [open-telemetry/opentelemetry-operator#3410]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

I want to define a basic set of configuration in the `config` block, but also allow for arbitrary configurations to be added via an additional configmap. In my case I'm deploying the operator as a Helm subchart and want users of my chart to be able to pass arbitrary blocks of configurations that I can't know ahead of time.

### Describe the solution you'd like

I want to mount a configmap which contains additional configuration to be passed to controller, and then add a `config: /path/to/additional-config.yaml` arg that would be added to the container's args.

Currently this doesn't work because the operator ignores the `config` key from the `args` part of the spec.

**Comment by jaronoff97** [comment]
If you have ideas on how you think the linked issue above should work, would love to hear any ideas. Thank you!
