### ISSUE TITLE
Show a warning in the webhook if the SA for a collector has not the correct RBAC permissions

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-operator#3432]
### Component(s)

collector

### Is your feature request related to a problem? Please describe.

One thing that can happen is that users will not give permission to the operator service account to create RBAC. In that case, users will need to manually create the RBAC for the service account running the collector. If the user is not cautious enough, can create a collector and have failures while running the collector because of the missing permissions.

### Describe the solution you'd like

It would be nice to show a warning on the operator logs when the collector is being created.

**Comment by swiatekm** [comment]
Shouldn't we do this in the webhook instead? That would be much more visible to users. I would also add it to the Collector status before operator logs - these are already quite noisy imo.

**Comment by iblancasa** [comment]
> Shouldn't we do this in the webhook instead? That would be much more visible to users. I would also add it to the Collector status before operator logs - these are already quite noisy imo.

I'm fine with that. Didn't want to do it in the webhook because I was not sure if it was too much "disruptive"

**Comment by swiatekm** [comment]
There's some potential for spurious warnings here, but imo it's outweighed by the gain of informing users what RBAC they need proactively.
