### ISSUE TITLE
Instrument only env vars

### ISSUE THREAD

**Issue by jtyr** [open-telemetry/opentelemetry-operator#3439]
### Component(s)

auto-instrumentation

### Describe the issue you're reporting

The only auto-instrumentation for Go applications is to inject a sidecar that will monitor the Go application from outside via eBPF. I have a manually instrumented Go application (metrics, logs, traces) that I would like to instrument with the env vars from `Instrumentation` resource so the app knows where to send the telemetry data without me having to specify the `OTEL_EXPORTER_OTLP_ENDPOINT` (and other env vars) for every single application. Is this somehow possible to do?

**Comment by iblancasa** [comment]
Yes. That's the purpose of the sdk "injection".
