### ISSUE TITLE
No release for v0.26.0

### ISSUE THREAD

**Issue by jughead** [open-telemetry/opentelemetry-operator#349]
Hello! I wanted to take v0.26.0 of the operator as it's the latest working with Kubernetes 1.18. But I don't see it in the releases, nor in the tags.

**Comment by jpkrohling** [comment]
Looks like we jumped straight from 0.25 to 0.27. Would you be open to try 0.25 out? We need to fix the compat matrix as well.

**Comment by jpkrohling** [comment]
I'm closing this, but feel free to reopen if you need 0.26 specifically, and not 0.25.
