### ISSUE TITLE
OpenTelemetryCollector does not support daemonset

### ISSUE THREAD

**Issue by MB175** [open-telemetry/opentelemetry-operator#3499]
It looks like the kind OpenTelemetryCollector does not support mode daemonset as mentioned in the docs !

` denied the request: the OpenTelemetry Collector mode is set to daemonset, which does not support the target allocation deployment`

[#L6C78-L6C87 ](https://github.com/open-telemetry/opentelemetry-operator/blob/54caa0e762fdf9eb97f1064d489bfbaa22c4c452/cmd/otel-allocator/README.md?plain=1#L6)

**Comment by jaronoff97** [comment]
what version of the operator/ collector are you running? can you please provide some more details?

**Comment by jaronoff97** [comment]
[This was changed over a year ago i believe](https://github.com/open-telemetry/opentelemetry-operator/blob/54caa0e762fdf9eb97f1064d489bfbaa22c4c452/apis/v1beta1/collector_webhook.go#L314-L316)

**Comment by MB175** [comment]
@jaronoff97, thanks for the quick response I think I got an old version of the CRD due to an outdated helm chart 
i will replace the v1alpha1 with the beta and than it should work I guess

**Comment by jaronoff97** [comment]
great, thank you! I'll close this for now, let me know if i need to re-open it.
