### ISSUE TITLE
Tests for reconcilers

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#35]
The reconcilers (`pkg/collector/reconcile`) are currently untested. This issue is to track building the unit tests for them.

**Comment by jpkrohling** [comment]
@treasurechristain, would you like to give this one a try?

**Comment by treasurechristain** [comment]
OK, let me try it out

**Comment by treasurechristain** [comment]
@jpkrohling please what are my expected to do here.

**Comment by jpkrohling** [comment]
We have a package that has no test coverage at all: 

https://github.com/open-telemetry/opentelemetry-operator/blob/master/pkg/collector/reconcile/

This task here is about creating tests for the code in that package. For instance, for `pkg/collector/reconcile/configmap.go`, we'll need to:

1. test that `desiredConfigMap()` returns a config map with a `collector.yaml` entry in it (you can/should also assert that it contains a label with the component's name)
1. test that `expectedConfigMaps()` creates new config maps if they don't exist yet in the cluster
1. test that `expectedConfigMaps()` updates an existing configmap if it exists already in the cluster
1. test the error conditions that can be reached by `expectedConfigMaps`
1. test that `deleteConfigMaps()` deletes configmaps that might have been part of a previous state
1. test one or two of the scenarios above in a bigger context (`ConfigMaps()`)

You can take a look at the tests in `pkg/collector/upgrade/upgrade_test.go` for reference for tests that need to interact with the underlying Kubernetes events (save/delete/update/list).

Let me know if you need further clarification.

**Comment by treasurechristain** [comment]
I'm currently working on it. I will notify you when i'm done

**Comment by gramidt** [comment]
@amadikwajoyn - Any progress on this?

**Comment by bhiravabhatla** [comment]
@jpkrohling I would like to take a stab at this after I am done with reload config PR if it's ok?
