### ISSUE TITLE
Breaking change for influxdb receiver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#350]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4277

We need an upgrade routine for v0.31.0 to handle this change. Basically, if this field exists, it has to be removed. Similar to this: https://github.com/open-telemetry/opentelemetry-operator/blob/7250758d04076b0e011b196d10bdea885b84fe80/pkg/collector/upgrade/v0_19_0.go#L47-L52

**Comment by VineethReddy02** [comment]
I would like to work on this!
