### ISSUE TITLE
Unable to set "additionalLabels"

### ISSUE THREAD

**Issue by diamantn** [open-telemetry/opentelemetry-operator#3508]
### Component(s)

collector

### What happened?

Describe the bug
YAML parse error on opentelemetry-collector/templates/clusterrole.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context

Steps to reproduce
Add:
--set-json 'additionalLabels={"app.kubernetes.io/part-of": "myApp"}'

What version did you use?
0.110.3

### Kubernetes Version

1.27

### Operator version

0.114.0

### Collector version

0.114.0

**Comment by jaronoff97** [comment]
Hello, I think this may be a helm bug. Are you seeing this on the collector CRD or via a helm chart?

**Comment by frzifus** [comment]
I assume its an helm issue. AFAIK the collector and operator do not have a flag named `--set-json`.

**Comment by jaronoff97** [comment]
Agreed. @diamantn if this is still an issue, please open it in the helm repository when you get a chance. Thank you :bow:
