### ISSUE TITLE
Re-Run Release Pipeline

### ISSUE THREAD

**Issue by kevinmartin** [open-telemetry/opentelemetry-operator#3541]
### Component(s)

collector

### Describe the issue you're reporting

The Release pipeline failed yesterday, causing the release assets to not be added to the release.

https://github.com/open-telemetry/opentelemetry-operator/actions/runs/12280059086/job/34265599695

Sharing for visibility. Can we please re-run it? Thank you in advance.

cc @jaronoff97

**Comment by jaronoff97** [comment]
argh, I thought this worked but this is unfortunate... fixing now!

**Comment by jaronoff97** [comment]
@kevinmartin all set, thanks for bringing this up :) Let me know if you have any issues!
