### ISSUE TITLE
Can not autoinstrument go in ollama/ollama:0.4.7

### ISSUE THREAD

**Issue by yaroslavkasatikov** [open-telemetry/opentelemetry-operator#3542]
### Component(s)

auto-instrumentation

### What happened?

I wanted to add autoinstrumentation to ollama/ollama:0.4.7 but got this error:

root@k8s ~ # oc logs my-ollama-5c77d5fff-sm4d8 -c opentelemetry-auto-instrumentation
{"time":"2024-12-12T16:59:06.799298584Z","level":"INFO","source":{"function":"main.main","file":"/app/cli/main.go","line":103},"msg":"building OpenTelemetry Go instrumentation ...","globalImpl":false,"version":{"Release":"v0.17.0-alpha","Revision":"unknown","Go":{"Version":"go1.23.2","OS":"linux","Arch":"amd64"}}}
{"time":"2024-12-12T16:59:08.799810027Z","level":"INFO","source":{"function":"go.opentelemetry.io/auto/internal/pkg/process.(*Analyzer).DiscoverProcessID","file":"/app/internal/pkg/process/discover.go","line":64},"msg":"found process","pid":7}
{"time":"2024-12-12T16:59:08.802800727Z","level":"ERROR","source":{"function":"main.main","file":"/app/cli/main.go","line":121},"msg":"failed to create instrumentation","error":".gosymtab section not found in target binary, make sure this is a Go application"}

Ollama is go application. Also it worked with old version of ollama but has been broken when update (ollama/ollama:0.1.14)

### Kubernetes Version

v1.29.2

### Operator version

opentelemetry-operator-0.74.3  0.113.0    

### Collector version

opentelemetry-collector-contrib:0.115.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by jaronoff97** [comment]
I'm not sure there's much we can do here unfortunately. I would open an issue with either ollama or the [opentelemetry-go-instrumentation](https://github.com/open-telemetry/opentelemetry-go-instrumentation) group.
