### ISSUE TITLE
Update python auto-instrumentation operator to not be 2 full releases behind

### ISSUE THREAD

**Issue by ian-activeloop** [open-telemetry/opentelemetry-operator#3546]
### Component(s)

auto-instrumentation

### Is your feature request related to a problem? Please describe.

I'd like to autoinstrument aiokafka, but the python operator package hasn't been updated as python-contrib has released a couple of times since the last time operator was.

### Describe the solution you'd like

I'd like the python auto-instrumentation operator to support current releases of python-contrib and associated new auto-instrumentations.

### Describe alternatives you've considered

Just not bothering to instrument?

**Comment by swiatekm** [comment]
:+1: We should do it. For new packages, it'd probably be best if we could convince the Python contrib maintainers to own the [requirements file](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/python/requirements.txt). Then we run less risk of missing new packages.

**Comment by jaronoff97** [comment]
will be closed by #3561
