### ISSUE TITLE
Bump gcr.io/kubebuilder/kube-rbac-proxy to latest

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#355]
We are currently using `gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0` in front of our metrics port, to validate the incoming requests. Looks like there's a new version of it that we should be using:

https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy?gcrImageListsize=30

This is likely the only place that needs to be changed:
https://github.com/open-telemetry/opentelemetry-operator/blob/7250758d04076b0e011b196d10bdea885b84fe80/config/default/manager_auth_proxy_patch.yaml#L13

**Comment by lastchiliarch** [comment]
I'd like to take this.

**Comment by jpkrohling** [comment]
It's yours
