### ISSUE TITLE
Create issues whenever a dependency is updated

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#357]
While dependabot can manage some dependencies for us, there are some things it can't. For instance: #356 or #355. 

I [circulated the idea](https://twitter.com/jpkrohling/status/1415584737586995201) of using/building an action that acts on a "release" event of external repositories, creating issues here for things we care: cert-manager, Kubernetes, Operator SDK, RBAC Proxy, and kuttl. Other things can be added later if needed.

For the first implementation, it should be sufficient to just call something like this:

```
 $ gh issue create -R github.com/open-telemetry/opentelemetry-operator \
  --title "New release for ...: vX.Y.Z" \
  --label "good first issue,enhancement,help wanted" \
  --body "Release notes: https://..."
```

The tricky part is getting the event from the external repository.

cc @alolita

**Comment by pavolloffay** [comment]
This should be most likely implemented in the dependency repositories - e.g. collector release. 

Now java auto-instrumentation has GHA job that will create a PR to update the agent version - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5710

**Comment by jpkrohling** [comment]
This wouldn't work on the two examples I have, as they are very popular dependencies. We can't possibly expect them to have a GitHub Action creating an issue in our repos.
