### ISSUE TITLE
Revert kustomization of the manager image

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#359]
In a previous update, a customization of the manager image got committed, causing all CSV and other generated resources to use this instead of newer versions.

https://github.com/open-telemetry/opentelemetry-operator/blob/7250758d04076b0e011b196d10bdea885b84fe80/config/manager/kustomization.yaml#L5-L8

Example of a side-effect: https://github.com/k8s-operatorhub/community-operators/pull/39

**Comment by VineethReddy02** [comment]
closing the issue as its been fixed #369
