### ISSUE TITLE
Align operator version with the tooling around it

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#37]
We currently get the operator's version based on git tags, which brings a `v` prefix to the version. Some of the tooling around the operator/kubebuilder expects numeric versions, so, we should adjust the `Makefile` to use the appropriate notations.

Example:

```console
$ make bundle
...
...
FATA[0000] invalid command options: release/v0.2.0-2-gb203820 is not a valid semantic version: Invalid character(s) found in major number "release/v0" 

```

**Comment by mneverov** [comment]
hi, i'd like to work on this
