### ISSUE TITLE
New default port for OTLP HTTP

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#371]
Context: https://github.com/open-telemetry/opentelemetry-collector/pull/3743

We need to:

1. make sure we create a new -legacy port, for 55681
1. change the default port from 55681 to 4318
1. schedule a ticket to remove the legacy port in two releases

This PR can be used as a reference, which did the same when the gRPC port changed from 55680 to 4317: https://github.com/open-telemetry/opentelemetry-operator/pull/135

**Comment by joaopgrassi** [comment]
I'll take a look at this today/tomorrow and hopefully send a PR :)
