### ISSUE TITLE
Missing labels in ConfigMap and Lease

### ISSUE THREAD

**Issue by Ramilito** [open-telemetry/opentelemetry-operator#394]
There are two resources created by opentelemetry-operator that are missing recommended labels.
I would be satisfied with labels such as:

```
metadata
    labels
        opentelemetrycollectors.opentelemetry.io: v0.6.0-beta.0
```

name: .opentelemtry.io, kind: ConfigMap
![image](https://user-images.githubusercontent.com/8473233/129751160-765a526f-71fa-4be4-bd73-ff693ba72ed5.png)

name: .opentelemtry.io, kind: Lease
![image](https://user-images.githubusercontent.com/8473233/129751477-4741ac9e-1b0e-46cd-944b-57cd7a040883.png)

**Comment by jpkrohling** [comment]
Could you please link to sources stating that this would be a recommended label? It would also help to understand the problems it's causing to you.

**Comment by Ramilito** [comment]
I was thinking about this:

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

A snippet from the above link:
![image](https://user-images.githubusercontent.com/8473233/130037516-a7f43a26-5683-48f4-b0b7-0a8e189f6b83.png)


My suggestion fit more with your existing labels, theirs are more generic.

**Comment by jpkrohling** [comment]
In short, you are requesting the resources we generate to have the `app.kubernetes.io/version` label?

**Comment by Ramilito** [comment]
Yes!
But if you go with their recommended labels I would also be needing app.kubernetes.io/name or app.kubernetes.io/managed-by label.
To make my query unique per app.

**Comment by jpkrohling** [comment]
We can do that for name and version, probably. But the managed-by doesn't make sense, as we don't know who is managing the operator (helm? OLM? you?).
