### ISSUE TITLE
Minimize mutex lock time in target allocator when updating collectors

### ISSUE THREAD

**Issue by alexperez52** [open-telemetry/opentelemetry-operator#414]
### Part of Target Allocator changes
Mutex is locked when collectors are being updated. 
Instead, there could be a local var that stores the list of collectors which will replace `allocator.collectors`. The mutex would then only be locked when the change is ready.

Related PR: https://github.com/open-telemetry/opentelemetry-operator/pull/354

**Comment by jaronoff97** [comment]
We've overhauled how this works and this should be much more efficient now, please let me know if you run into more performance problems here.
