### ISSUE TITLE
Add configuration/flag to override collector image

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#447]
The default collector image is hardcoded https://github.com/open-telemetry/opentelemetry-operator/blob/f7b7b9385c302e5d2f73dfd2700ef3cee6a49506/internal/config/main.go#L74. 

Vendors providing a custom build of the operator (and collector) should be able to change the default image.

**Comment by nevosial** [comment]
Hello I would like to work on this .
Can you help me where to get started as I am a new contributor.

**Comment by jpkrohling** [comment]
@nevosial, take a look at this doc: https://github.com/open-telemetry/opentelemetry-operator/blob/main/CONTRIBUTING.md

**Comment by pavolloffay** [comment]
I have already submitted a PR for this https://github.com/open-telemetry/opentelemetry-operator/pull/449.
