### ISSUE TITLE
Move Operator Hub instructions to its own section

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#456]
The current release process includes submitting pull requests to update the operator on the Operator Hub. However, this is not really required to release the operator proper. We still want this documented there, though. This ticket is about moving that item from the release process into its own section.

**Comment by pavolloffay** [comment]
This is related to https://github.com/open-telemetry/opentelemetry-operator/issues/433

The operator 0.34.0 and 0.35.0 were released without publishing changes to the operatorhub.io. There are users that noticing this and asking to publish the operator see #433 

The operatorhub.io is a central location where users can find released operators. The release process should include publishing to the operatorhub. Splitting the release process makes it easier to release (for maintainers) but it is not great for users and not great from the release perspective (multiple people have to look for the release and do trivial steps to fully finish it).

**Comment by vitorguidi** [comment]
I would like to take ownership of this issue. How can I go about it?

**Comment by pavolloffay** [comment]
Please just submit a PR

**Comment by yuriolisa** [comment]
@pavolloffay, I believe this issue can be closed. Right?
