### ISSUE TITLE
Restart collector on config change

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#460]
At the moment operator does not restart the collector when `spec.config` part of the CR changes (e.g. configure new processor). The operator could restart the collector if the config changes. 

The config update could be implemented on the collector itself, but that seems like a long way to go https://github.com/open-telemetry/opentelemetry-collector/issues/273.

**Comment by BronzeDeer** [comment]
@bhiravabhatla I just encountered the same problem as @pavolloffay with a Deployment not updating. The Annotation needs to go on the pod spec template not the Deployment/Daemonset itself, otherwise kubernetes does not trigger a rolling update

**Comment by bhiravabhatla** [comment]
@BronzeDeer  -> As far as I remember, I used annotations on deployment knowingly, whenever configmap is updated, we are publishing an event.

https://github.com/open-telemetry/opentelemetry-operator/blob/dd248a328fd020dc387df79ffba4ddde3a90598c/pkg/collector/reconcile/configmap.go#L178-L180

And deployment reconciller listens for configMap events - 

https://github.com/open-telemetry/opentelemetry-operator/blob/dd248a328fd020dc387df79ffba4ddde3a90598c/controllers/opentelemetrycollector_controller.go#L172

Reconciller should be triggered whenever there is a new event for configmap. Let me debug what is happening. Will update if i find something.

**Comment by bhiravabhatla** [comment]
But I see your point even if deployment annotation is change, new replicaset wont be rolledout unless pod spec is not updated. May be that is the issue, not sure how missed this. Thanks for pointing it out.

**Comment by bhiravabhatla** [comment]
Yep - this was miss. would make required changes and raise another PR. Apologies for the same. I guess we should add an e2e test for this as well. 

 @jpkrohling  and @pavolloffay  had a question, I see that we are adding prometheus scrape annotations to deployment.metadata.annotations.

https://github.com/open-telemetry/opentelemetry-operator/blob/dd248a328fd020dc387df79ffba4ddde3a90598c/pkg/collector/annotations.go#L29-L32

 Shouldn't they be in deployment.spec.template.metadata.annotations as well? If I am not wrong prometheus kuberenetes-pod job (default config) looks for annotations on pods not deployments.
 
 https://github.com/prometheus-community/helm-charts/blob/936d4712cda5ab28da304516cd7894c74067b63b/charts/prometheus/values.yaml#L1673-L1681

**Comment by BronzeDeer** [comment]
@bhiravabhatla Is there a reason that we want to manually trigger a new rollout via the event? Just updating the pod template is fine and quite a bit more light weight. If we are calculating the cm hash to update the deployment anyway we can just always do that on the pod template and get the rolling update for free, no?

**Comment by bhiravabhatla** [comment]
@BronzeDeer - One reason I could think of was - if some one directly updates configmap ( I know this should not be done, but no one is stopping anyone with access to do so), reconciler should get triggered and sync it back. Or else the config in opentelemetry CR and the actual configmap would be different.

**Comment by BronzeDeer** [comment]
@bhiravabhatla fair point

**Comment by bhiravabhatla** [comment]
@jpkrohling @pavolloffay, if you could confirm on my above question about prometheus annotations, I can raise a PR fixing both

**Comment by jpkrohling** [comment]
To be honest, I do not know the answer to the Prometheus annotation question. Can you find a place on their documentation about it? In any case, it would be a different PR, not related to this issue here.

**Comment by bhiravabhatla** [comment]
As far as I understand the kubernetes_sd_config in prometheus, we have  roles for discovering pods, services, endpoints, nodes and ingress only. I dont think we have role for deployment. More on this here - 

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config

Sure I can raise another issue for this. I was asking because the change for config reload fix is in the same place as this :)

**Comment by lionelvillard** [comment]
I ran into the issue as well. I hope this will get fixed.
