### ISSUE TITLE
CRD from this repository break kubernetes 1.22 cluster

### ISSUE THREAD

**Issue by paulfantom** [open-telemetry/opentelemetry-operator#473]
Applying just the CRD from this repository prevents kubernetes controller-manager GC from kicking in and removing child objects (kubernetes issue: https://github.com/kubernetes/kubernetes/issues/101078).

Steps to reproduce:
1. Start kubernetes 1.22 cluster
2. `kubectl apply -f https://raw.githubusercontent.com/open-telemetry/opentelemetry-operator/main/bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml`
3. `kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/controllers/nginx-deployment.yaml `
4. Wait for pods to finish starting up
5. `kubectl delete deployment nginx-deployment`
6. Verify status of Deployment, ReplicaSet, Pods:
  - `kubectl get deployment`
  - `kubectl get replicaset`
  - `kubectl get pods`

I would expect to have no pods, no replicasets, and no deployments. However only deployment is removed and kubernetes controller-manager starts crashing.

**Comment by rkukura** [comment]
I can work on this now if nobody else is. I'm convinced its the same issue causing https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/402 to fail CI on OpenShift 4.9, which is based on kubernetes 1.22.

**Comment by rkukura** [comment]
We should be able to close this now.

**Comment by jpkrohling** [comment]
@paulfantom, would you please confirm the CRD we have in the main branch fixes the problem?

**Comment by rkukura** [comment]
Both the OpenShift and Kubernetes operator hubs have now been updated to 0.38.0 with the fixed CRD from https://github.com/open-telemetry/opentelemetry-operator/pull/521 included.

**Comment by paulfantom** [comment]
I confirm that #521 fixes the issue. Thank you all for the fix! :+1:
