### ISSUE TITLE
Update Kubernetes images for kuttl

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#478]
There are new Kubernetes patch versions for the matrix we use for testing. We need to update our kuttl files to use them. For instance, the following file needs to be updated as soon as a new kuttl image is created tracking v1.19.16.

https://github.com/open-telemetry/opentelemetry-operator/blob/f4273b84f9da6f8ec0a296bdf67653e3a8da69d4/kind-1.19.yaml#L1-L5

**Comment by jpkrohling** [comment]
New Kubernetes versions are available:

https://github.com/kubernetes/kubernetes/releases/tag/v1.23.0-beta.0 (new minor!)
https://github.com/kubernetes/kubernetes/releases/tag/v1.22.4
https://github.com/kubernetes/kubernetes/releases/tag/v1.21.7
https://github.com/kubernetes/kubernetes/releases/tag/v1.20.13

**Comment by jpkrohling** [comment]
I believe it's a good opportunity to stop testing 1.19.

**Comment by yuriolisa** [comment]
It looks ok to me, however, I'd like to contact some Kind maintainer to release these new versions on Kind, then we'll be able to remove the 1.19 test.
