### ISSUE TITLE
Convert messages to events

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#486]
We have a facility to record events in the operator, like this:

https://github.com/open-telemetry/opentelemetry-operator/blob/7455eede6ae9347cf86cfc39cb2c90a6648ced0f/pkg/collector/reconcile/configmap.go#L179

But so far, we have been using the messages field in the status object, like this:

https://github.com/open-telemetry/opentelemetry-operator/blob/02dc4901d7ceefa630539374226665969f3191f2/pkg/collector/upgrade/v0_19_0.go#L50

We should change the existing code to record such messages as events.

**Comment by yuriolisa** [comment]
@jpkrohling , @pavolloffay

**Comment by pavolloffay** [comment]
First, what is the motivation to convert `status.messages` to events? When should be events used and when status messages? 

The ticket says messages should be recorded as events, does @jpkrohling mean that status messages should be migrated to events (and e.g. deprecated)? 

My understanding is that events are more standard way of indicating changes on an object. However can all our current status messages be represented as events? 


Event recorder API:

```golang
type EventRecorder interface {
	// Event constructs an event from the given information and puts it in the queue for sending.
	// 'object' is the object this event is about. Event will make a reference-- or you may also
	// pass a reference to the object directly.
	// 'type' of this event, and can be one of Normal, Warning. New types could be added in future
	// 'reason' is the reason this event is generated. 'reason' should be short and unique; it
	// should be in UpperCamelCase format (starting with a capital letter). "reason" will be used
	// to automate handling of events, so imagine people writing switch statements to handle them.
	// You want to make that easy.
	// 'message' is intended to be human readable.
	//
	// The resulting event will be created in the same namespace as the reference object.
	Event(object runtime.Object, eventtype, reason, message string)
```

**Comment by jpkrohling** [comment]
> First, what is the motivation to convert status.messages to events? 

To let users know when something relevant happened during a process they might not be watching. The operator doesn't have a UI, and we rarely want to block something from happening, such as a pod creation, just because something didn't work out (like a sidecar injection).

An upgrade, for instance, might be an unattended event, so we should make sure users know when something happened. Events are better in this sense, as cluster admins should already be watching for those events anyway.

> When should be events used and when status messages?

Status messages should be the current state of the object. We've been misusing this in the past as a way to pass information from the operator to users, but events are a better mechanism for that.

> event reasons: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/events/event.go#L17

Are those the only events that may exist, or are we free to create our own?
