### ISSUE TITLE
Installation fails when using Cert Manager 1.6 or newer.

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-operator#490]
Cert Manager 1.6 removes support for alpha APIs. This commit https://github.com/open-telemetry/opentelemetry-operator/commit/eedf44e1c0f3731f59a1b614c9cec6211c3f3b67 to main resolves the issue but it is not released.

As a work around, I need to use Cert Manager v1.5.4 while using the latest Open Telemetry Operator release.

**Comment by RomeroGaliza** [comment]
Exactly same issue here.

**Comment by jpkrohling** [comment]
We will be having a release soon (#488), but this issue here is also evidence that we need a compatibility matrix in the readme with the cert-manager we tested for each release.

cc @VineethReddy02

**Comment by yuriolisa** [comment]
Hi @jpkrohling , I'll prepare this Matrix tomorrow.
