### ISSUE TITLE
Use GitHub Container Repository instead of Quay

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#492]
Switched to quay. I'd recommend separately considering migrating to GHCR for everything. For an OSS contributor project like OTel I think there is a lot to like about having creds / permissions tied to the repo itself rather than a backchannel

_Originally posted by @anuraaga in https://github.com/open-telemetry/opentelemetry-operator/pull/475#discussion_r740972480_

**Comment by pavolloffay** [comment]
#536 switched operator image to GHCR. 

The only remaining image in quay is the target allocator.
