### ISSUE TITLE
Register java instrumentation image with Quay

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-operator#500]
Currently the java image publish is failing with this

```
#9 pushing layer 7645a384f473 0.2s done
#9 pushing layer a9ca537752fd 0.2s done
#9 ERROR: unauthorized: access to the requested resource is not authorized
------
 > pushing quay.io/opentelemetry/opentelemetry-operator-autoinstrumentation-java:1.7.0 with docker:
------
error: unauthorized: access to the requested resource is not authorized
Error: buildx failed with: error: unauthorized: access to the requested resource is not authorized
```

The login step is there so presumably the image has to be registered in quay.

@jpkrohling Are you able to register the image? Or should I just go with GHCR under the assumption of #492?

**Comment by jpkrohling** [comment]
I tried logging in, but apparently, my account is still tied to my redhat.com address, which I no longer have access. Looks like @pavolloffay's quay.io account, which is also admin to that organization, is also disabled. We both emailed Red Hat's support to regain access to our accounts, and I believe @bogdandrutu and @tigrannajaryan both have admin rights to that organization, so, we can resort to them in the worst case.

I think we can/should migrate to GitHub's container repository soon, but would prefer to keep publishing images to both places in parallel for some time. If we can't regain access to our Quay.io accounts, then we'll have to make a hard switch.

**Comment by jpkrohling** [comment]
I'm assigning this to Pavol, as he might be able to get access to the repository by the same time as I do.

**Comment by pavolloffay** [comment]
if we are planning to migrate I don't see value of publishing the java agent image to quay as it has never been published there.

**Comment by pavolloffay** [comment]
Here is PR to move java image to GHCR only. https://github.com/open-telemetry/opentelemetry-operator/pull/501

**Comment by jpkrohling** [comment]
Agree. Closing this.
