### ISSUE TITLE
Don't checkin autogenerated resources

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-operator#522]
It's quite difficult to develop on this repo since it's basically not possible to have code in a state where it builds locally and CI equally. This is because of version and kustomize manifests which reflects the git state - a local build requires a different value _committed_ to be able to run, but this then causes the CI to not run and needs to be reverted. Most problematic is that `make bundle` does generate some files that do need to be committed for the CI to run, namely the ones reflecting the CRD. So I find myself `make bundle` and finding the files to revert before pushing code.

Is it possible to just run autogeneration as part of a build without having to check them into the repo?

**Comment by pavolloffay** [comment]
I agree with you that it's annoying how it is setup right now. At the same time I like that generated valid CRD is committed to the main branch, but perhaps this can be done only for the release commit. 

nit I run the following before submitting PR
```
VERSION=0.38.0 USER=opentelemetry  make bundle 
```

**Comment by pavolloffay** [comment]
Also, I would prefer to keep check-in in all files to be compliant with the sample project https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v3/memcached-operator.

There are some assuptions that `operator-sdk` uses and we should be compatible with them.

**Comment by anuraaga** [comment]
Any approach that solves the dance would be fine, if it can support the merged autogen code. I think currently, it's in a really bad place when local code and CI code can't build with the same repo state, or may require some opaque flags.

**Comment by jaronoff97** [comment]
resolved by https://github.com/open-telemetry/opentelemetry-operator/pull/2421 and https://github.com/open-telemetry/opentelemetry-operator/pull/2479
