### ISSUE TITLE
Clean up namespaces after unit test run

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-operator#523]
I suspect this affects `make test` too though I'm currently having trouble with that command and have only checked with running tests in GoLand directly, including with debugger. It seems that namespaces get created and not deleted, and then tests cannot be re-ran until I manually delete the namespaces. The tests should have a cleanup hook to delete namespaces, regardless of test success or failure, to allow rerunning easily.

**Comment by jpkrohling** [comment]
Are you talking about integration tests, or e2e (kuttl) tests?

**Comment by anuraaga** [comment]
Integration tests I guess (I thought they are called unit tests ;) ). Normal _test.go files, at least the ones in the instrumentation package seem to have this issue.

**Comment by jpkrohling** [comment]
Right, those are integration tests, even though they look like regular unit tests :-) If you don't have a cluster running, it would just bootstrap an environment of its own and use it. See https://book.kubebuilder.io/reference/envtest.html

**Comment by anuraaga** [comment]
I was using `USE_EXISTING_CLUSTER` as recommended in CONTRIBUTING.md :-) Not using that variable fails with `cannot find etcd` - presumably I could install deps to get it to create a cluster, but I suspect the test feedback loop would generally be faster if able to use an existing cluster and the tests cleaned up after themselves

**Comment by anuraaga** [comment]
Realized that the namespace creation isn't a part of testEnv but just our ad-hoc test code

https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/instrumentation/podmutator_test.go#L402

So, unless creating an internal test framework or something to handle that sort of thing, at the least it's probably good to have a `defer k8sClient.Delete(context.Background(), ns)` when doing that sort of creation in test code.

**Comment by anuraaga** [comment]
By the way I realized one reason for the confusion on unit vs integration is, at least in the pkg/instrumentation package, all tests are "effectively" integration tests - for example, I can't run only `TestInjectNodeJS` without a cluster because `TestMain` gets run for these unit tests as well, setting up the otherwise unused testEnv. Wonder if there is a way to split tests to allow these to be run independently.
