### ISSUE TITLE
Nominate pavolloffay to approver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#538]
I would like to nominate @pavolloffay to the @open-telemetry/operator-approvers group.

Pavol has reviewed about [30 PRs](https://github.com/open-telemetry/opentelemetry-operator/pulls?q=is%3Apr+reviewed-by%3Apavolloffay) and is the author of more than [30 PRs](https://github.com/open-telemetry/opentelemetry-operator/pulls?q=is%3Apr+author%3Apavolloffay+), including the one introducing the auto-instrumentation for Java workloads.

I invite all the current @open-telemetry/operator-approvers and @open-telemetry/operator-maintainers to vote. Community members are also encouraged to provide their feedback.

**Comment by VineethReddy02** [comment]
+1

**Comment by bogdandrutu** [comment]
+1

**Comment by jpkrohling** [comment]
3 maintainer votes out of 4 maintainers, welcome @pavolloffay! 

@bogdandrutu, I don't seem to have permission to change the group. Would you please do the honors?

**Comment by VineethReddy02** [comment]
Closing this issue, as Pavol is now the approver!! :)

**Comment by pavolloffay** [comment]
I still don't have any Github permissions though not being listed in the readme

**Comment by tigrannajaryan** [comment]
@pavolloffay I added you to operator-approvers, you should have the permissions now.
