### ISSUE TITLE
Upgrade not handling TLS changes from 0.36.0 for all components

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#539]
All components that make use of configgrpc are affected by open-telemetry/opentelemetry-collector#4063. This was partially fixed by #465 (tracked by #463), but other exporters are missing, such as Jaeger's. 

cc @rkukura, @VineethReddy02

**Comment by pavolloffay** [comment]
The 0.36.0 is out. Is this issue relevant?

**Comment by jpkrohling** [comment]
I think this is not relevant anymore.
