### ISSUE TITLE
Change calls to Update() to Patch()

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#54]
Instead of doing `Update()` calls for the changes we detect, we should attempt to use `Patch()`, to reduce the number of failures caused by stale objects.

From:
```go
		if err := params.Client.Update(ctx, updated); err != nil {
			return fmt.Errorf("failed to apply changes: %w", err)
		}
```

To:
```go
	// at the beginning of the reconciliation function, store a copy of `params.Instance` as `changed`
	patch := client.MergeFrom(&params.Instance)
	if err := params.Client.Patch(ctx, &changed, patch); err != nil {
		return fmt.Errorf("failed to apply changes: %w", err)
	}
```

**Comment by vigneshashokan** [comment]
Can I take a stab at this issue if it is still open?

**Comment by jpkrohling** [comment]
It is still open, just give me a few hours to another PR in, otherwise you'll likely get merge conflicts :-)

**Comment by jpkrohling** [comment]
The PR is now merged. It's your turn, @vigneshashokan!

**Comment by treasurechristain** [comment]
Hi @jpkrohling 
I'm Amadikwa Joy N, an outreachy applicant

Please is this issue still open?
I would like to work on it.

If I get the instruction very well, you want us to change calls from Update to Patch?

**Comment by jpkrohling** [comment]
It's yours, @treasurechristain. There's an example in the issue description on how to convert those calls. Here's a list of files to be changed:

pkg/collector/reconcile/service.go
pkg/collector/reconcile/deployment.go
pkg/collector/reconcile/daemonset.go
pkg/collector/reconcile/serviceaccount.go
pkg/collector/reconcile/configmap.go

**Comment by treasurechristain** [comment]
@jpkrohling what I'm to do is just to change it 

from. 
if err := params.Client.Update(ctx, updated); err != nil {
			return fmt.Errorf("failed to apply changes: %w", err)
		}

To
patch := client.MergeFrom(&params.Instance)
	if err := params.Client.Patch(ctx, &changed, patch); err != nil {
		return fmt.Errorf("failed to apply changes: %w", err)
	}


Hope I won't add anything else on it?

**Comment by jpkrohling** [comment]
That's pretty much it. You should also test it, to make sure it's actually working. You can either run the instructions from the readme to install a CR and later on update it (which should trigger the code that you are changing), or you can try to add a new test for this case if there isn't one already.

**Comment by treasurechristain** [comment]
Hi @jpkrohling  should I also replace this side of the code that have 'update' as variable ?
![serviceupdate](https://user-images.githubusercontent.com/20610726/96169559-36ecff80-0f1a-11eb-890e-bf9f2f6c0e27.PNG)

**Comment by treasurechristain** [comment]
Could this be the modification you are expecting?
![serviceupdate1](https://user-images.githubusercontent.com/20610726/96170902-1cb42100-0f1c-11eb-9814-56b459c9f715.PNG)

**Comment by treasurechristain** [comment]
@jpkrohling I just did a pull request now, Please check and confirm.

Outreachy Applicant

Thanks, Amadikwa Joy N.

**Comment by jpkrohling** [comment]
>  should I also replace this side of the code that have 'update' as variable ?

No, that part is fine.

> I just did a pull request now, Please check and confirm.

I'm out for a couple of days, but will review it next week. Thanks for the PR!

**Comment by treasurechristain** [comment]
Ok @jpkrohling 

I ran this code 

	patch := client.MergeFrom(&params.Instance)
	if err := params.Client.Patch(ctx, &changed, patch); err != nil {
		return fmt.Errorf("failed to apply changes: %w", err)
	}

but I couldn't pass the unit test because it was saying 'changed; not defined
![unittesterror](https://user-images.githubusercontent.com/20610726/96180098-d5349180-0f29-11eb-93dd-22db183a1716.PNG)

So I replaced it with  this code '&changed' with 'updated' and it successfully passed it
![unittestpass](https://user-images.githubusercontent.com/20610726/96180229-090fb700-0f2a-11eb-841d-8c5d04e2085b.PNG)


Hope I'm still on track?

**Comment by treasurechristain** [comment]
Mentor @jpkrohling Please is there anyother project i will be working on till you come back next week?
