### ISSUE TITLE
Add status object for Instrumentation kind

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#544]
The instrumentation Kind does not expose any status at the moment. There are a couple of useful fields that the status object can expose:

1. sampling configuration
2. exporter config
3. which workloads are instrumented 

I think that showing which workloads are instrumented can be super helpful.

**Comment by frzifus** [comment]
Regarding the workloads, what would you recommend as an indicator? 
I thought it might make sense to split them by type and store the pod names there. 

e.g.:
```yaml
status:
  instrumented:
    java: ["spring-6d569df946-vqxk8"]
    python: ["flask-54996c6f85-zm5lr"]
```

Another thing, what do you think about rejected injections as a status field?
We could save the pod names too. However, it is not quite clear to me when they should be removed. Probably when the pod is deleted or the injection was successful.
As an alternative, it probably makes sense to create an event for failed injections and only expose the number of successful and failed injections as status.

It would then look like this:
```bash
NAME                   AGE   INSTRUMENTED   REJECTED   OTEL-ENDPOINT               SAMPLE-TYPE                SAMPLE-RATE
my-instrumentation-1   62m   1              3          http://abc-collector:4317   parentbased_traceidratio   0.25
```

**Comment by pavolloffay** [comment]
Closing as there is already some status object. Let's improve it case by case.
