### ISSUE TITLE
Deletion of resources shouldn't fail if the webhook server isn't available

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#56]
When the operator isn't up and running, removing resources will fail with:

```
$ kubectl delete otelcol opentelemetrycollector-sample
Error from server (InternalError): Internal error occurred: failed calling webhook "vopentelemetrycollector.kb.io": Post "https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/validate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=30s": dial tcp 10.96.165.160:443: connect: connection refused

$ kubectl get otelcols
NAME                            MODE         VERSION   AGE
opentelemetrycollector-sample   deployment   0.10.0    3h39m
```

**Comment by gramidt** [comment]
@jpkrohling - One potential thought is to split the "validating-webhook-configuration" into two validating webhooks. The second one would be for the "DELETE" and would have `failurePolicy: Ignore`. This would allow deletion of the resource, but would leave the cleanup of the underlying resources to the user (including removing finalizers when applicable). Thoughts?

**Comment by jpkrohling** [comment]
> This would allow deletion of the resource, but would leave the cleanup of the underlying resources to the user, including removing finalizers when applicable

Not sure we do anything at all in our code. When a CR is deleted, all the resources that are owned by this CR are deleted automatically. In our reconciliation function, we'll see the delete event but won't find the CR, in which case we'll just return. So, I think your idea would work nicely.

https://github.com/open-telemetry/opentelemetry-operator/blob/543ff618e40cc035648bf3569a522d3559562034/controllers/opentelemetrycollector_controller.go#L116-L125

**Comment by gramidt** [comment]
Great! This will be straightforward to implement then, @jpkrohling. This is now in my backlog to tackle.

**Comment by VineethReddy02** [comment]
@jpkrohling I can work on this!

**Comment by jpkrohling** [comment]
Go ahead! Can you please double-check the kubebuilder docs to see if they have a recommendation about this? What we have right now is following what was bootstrapped by kubebuilder when I first bootstrapped this operator, and things might have changed since then.
