### ISSUE TITLE
Auto instrumentation Error

### ISSUE THREAD

**Issue by ananda-chintalapati** [open-telemetry/opentelemetry-operator#567]
I am following the deployment steps and the auto instrument step is failing with the below error.

`error: error validating "inst.yaml": error validating data: [ValidationError(Instrumentation.spec): unknown field "nodejs" in io.opentelemetry.v1alpha1.Instrumentation.spec, ValidationError(Instrumentation.spec): unknown field "propagators" in io.opentelemetry.v1alpha1.Instrumentation.spec, ValidationError(Instrumentation.spec): unknown field "python" in io.opentelemetry.v1alpha1.Instrumentation.spec, ValidationError(Instrumentation.spec): unknown field "sampler" in io.opentelemetry.v1alpha1.Instrumentation.spec]; if you choose to ignore these errors, turn validation off with --validate=false`

I am trying with sidecar deployment and the config files looks appropriate. 

Adding more data as per comments. inst.yaml file is the content based on instructions

`apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest`

**Comment by pavolloffay** [comment]
@jpkrohling please do not assign issues ;) 


@anuraaga does this sound familiar? This is from the nodejs part

**Comment by anuraaga** [comment]
Could it be a version issue? There seem to be many newer fields including sampler and propagators in the log. Nothing else comes to mind

**Comment by pavolloffay** [comment]
Version of the OTEL stack? 

I don't know what the `inst.yaml` refers to from the log. It seems like user-defined file. 


@ananda-chintalapati could you please paste here your dependency tree -e.g. package.json (I am not JS guy :-) )?

**Comment by anuraaga** [comment]
The error is operator API validation isn't it? I guess it's an Instrumentation object.

@ananda-chintalapati Can you post your inst.yaml and verify the version of the operator?

**Comment by pavolloffay** [comment]
lol that is correct it is incorrect `Instrumentation` CR. I need to grab Monday morning coffee :)

**Comment by pavolloffay** [comment]
Note that nodejs is not supported in 0.38.0. It will come in the next version.

**Comment by jpkrohling** [comment]
>@jpkrohling please do not assign issues ;)

Aren't you one of the owners of the auto-instrumentation feature?

**Comment by pavolloffay** [comment]
> Aren't you one of the owners of the auto-instrumentation feature?

yes :)) 

In community projects, people are usually self-assing themselves.

**Comment by jpkrohling** [comment]
> In community projects, people are usually self-assing themselves.

That's not true. We do assign items to folks in the OpenTelemetry community ;-)

**Comment by ananda-chintalapati** [comment]
> The error is operator API validation isn't it? I guess it's an Instrumentation object.
> 
> @ananda-chintalapati Can you post your inst.yaml and verify the version of the operator?

HiAnurag, Updated issue with inst.yaml file and I am using latest version of image for opentelemtry collector

**Comment by pavolloffay** [comment]
@ananda-chintalapati please format the `inst.yaml` well, in the correct form it is not readable. 

> using latest version of image for opentelemtry collector

Could you please paste here the full image name with tag?

**Comment by ananda-chintalapati** [comment]
Closing this issue as the issue as support for Python and NodeJS are planned for 0.39.0 version and I was trying for 0.38.0 version of collector
