### ISSUE TITLE
controller-manager failure with new release

### ISSUE THREAD

**Issue by sharathbana** [open-telemetry/opentelemetry-operator#588]
There seems to be references to old  image. I see below failure in controller-manager logs.
Please help to fix this.

`kubectl describe pod opentelemetry-operator-controller-manager-56677949c8-9msqm -n opentelemetry-operator-system
Name:         opentelemetry-operator-controller-manager-56677949c8-9msqm
Namespace:    opentelemetry-operator-system
Priority:     0
Node:         aks-nodepool1-45911280-vmss000000/10.240.0.4
Start Time:   Mon, 29 Nov 2021 18:39:22 +0530
Labels:       control-plane=controller-manager
              pod-template-hash=56677949c8
Annotations:  <none>
Status:       Pending
IP:           10.244.0.203
IPs:
  IP:           10.244.0.203
Controlled By:  ReplicaSet/opentelemetry-operator-controller-manager-56677949c8
Containers:
  manager:
    Container ID:  
    Image:         ghcr.io/open-telemetry/opentelemetry-operator//opentelemetry-operator:v0.39.0
    Image ID:      
    Port:          9443/TCP
    Host Port:     0/TCP
    Args:
      --metrics-addr=127.0.0.1:8080
      --enable-leader-election
    State:          Waiting
      Reason:       InvalidImageName
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  256Mi
    Requests:
      cpu:        100m
      memory:     64Mi
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from opentelemetry-operator-controller-manager-token-gm6xv (ro)
  kube-rbac-proxy:
    Container ID:  containerd://d58d6ca685adbd7526daf1cc457658c9e123a4fa936949595a67866a4f42588d
    Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
    Image ID:      gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --secure-listen-address=0.0.0.0:8443
      --upstream=http://127.0.0.1:8080/
      --logtostderr=true
      --v=10
    State:          Running
      Started:      Mon, 29 Nov 2021 18:39:27 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from opentelemetry-operator-controller-manager-token-gm6xv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  opentelemetry-operator-controller-manager-service-cert
    Optional:    false
  opentelemetry-operator-controller-manager-token-gm6xv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  opentelemetry-operator-controller-manager-token-gm6xv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason         Age                    From               Message
  ----     ------         ----                   ----               -------
  Normal   Scheduled      5m6s                   default-scheduler  Successfully assigned opentelemetry-operator-system/opentelemetry-operator-controller-manager-56677949c8-9msqm to aks-nodepool1-45911280-vmss000000
  Warning  FailedMount    5m5s (x3 over 5m6s)    kubelet            MountVolume.SetUp failed for volume "cert" : secret "opentelemetry-operator-controller-manager-service-cert" not found
  Normal   Pulled         5m2s                   kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" already present on machine
  Normal   Created        5m2s                   kubelet            Created container kube-rbac-proxy
  Normal   Started        5m2s                   kubelet            Started container kube-rbac-proxy
  Warning  Failed         3m43s (x9 over 5m2s)   kubelet            Error: InvalidImageName
  Warning  InspectFailed  3m32s (x10 over 5m2s)  kubelet            Failed to apply default image tag "ghcr.io/open-telemetry/opentelemetry-operator//opentelemetry-operator:v0.39.0": couldn't parse image reference "ghcr.io/open-telemetry/opentelemetry-operator//opentelemetry-operator:v0.39.0": invalid reference format`

**Comment by jpkrohling** [comment]
See #580.
