### ISSUE TITLE
Opt-out of managed instance upgrade

### ISSUE THREAD

**Issue by adriankostrubiak-tomtom** [open-telemetry/opentelemetry-operator#598]
As a cluster admin running the `opentelemetry-operator`, I would like to avoid having the controller automatically upgrade the configuration of `OpenTelemetryCollector`s and would rather manage that process myself.

---

Automatic upgrades can be an undesirable event, and lead to confusing situations. This is especially the case when using a custom `spec.image`. 

The upgrade process assumes using the latest `otel/opentelemetry-collector` as defined by the version of the `opentelemetry-operator`.  As such, it is possible for the controller's upgrade process to upgrade a `OpenTelemetryCollector` resource's configuration to an invalid configuration given the image being run.  I believe the opportunity for this to occur is greater when upgrading over a wider version range (eg 0.24 -> 0.36 vs 0.38 -> 0.40) as the underlying configuration has more opportunity to change across the versions.

Looking into the code a bit, and validated with an experiment, this is currently accomplishable by applying a label to an `OpenTelemetryCollector` of `app.kubernetes.io/managed-by` set to anything other than `"opentelemetry-operator"`:
https://github.com/open-telemetry/opentelemetry-operator/blob/a94a13888165ec688a5f83d4e444e9fbc934fca2/pkg/collector/upgrade/upgrade.go#L35-L39

However, it is unclear if such a configuration will result in unintended consequences.

If this is indeed the appropriate approach, I would like to suggest improving the documentation around the upgrade process.

If not, I believe there should be a configuration such that the controller will not upgrade a given `OpenTelemetryCollector`.

Regardless of the answer, I'd be happy to take a crack at the resulting work :)

**Comment by jpkrohling** [comment]
Using `app.kubernetes.io/managed-by` is not the correct approach. I prefer having an explicit option to disable the automatic upgrade. I'm just not sure if this should be a per-CR config or if it should be a per-operator option. Or both, with the CR one taking precedence over the operator one.
