### ISSUE TITLE
Linter fails if adding a file from another project while preserving copyright

### ISSUE THREAD

**Issue by mmatache** [open-telemetry/opentelemetry-operator#611]
This issue relates to: #596

During the implementation, the `util` functions from Jaeger were used, but since they were small, it was decided to simply copy the files over so as to not add a dependency.

The problem is that we were not able to properly preserve the Jaeger copyright as the `goheader` linter would error out:
```
make lint
golangci-lint run
pkg/naming/dns.go:2:4: Actual: Copyright The Jaeger Authors.
Expected: (goheader)
// Copyright The Jaeger Authors.
   ^
make: *** [Makefile:114: lint] Error 1
```  

As such I am opening this ticket to try and figure out a solution for this, as this situation might arise again.

**Comment by pavolloffay** [comment]
Done in #609
