### ISSUE TITLE
Add Kubernetes 1.23 to the test matrix

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#615]
Similar to #378, Kubernetes 1.23 has just been released and we need to add it to the test and compatibility matrix.

https://github.com/kubernetes/kubernetes/releases/tag/v1.23.0

**Comment by shree007** [comment]
@jpkrohling  i can work on it.

**Comment by VineethReddy02** [comment]
Fixed in #633
