### ISSUE TITLE
Flaky tests -- scorecard

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#626]
The scorecard tests are failing intermittently. Examples:

https://github.com/open-telemetry/opentelemetry-operator/runs/4484687728?check_suite_focus=true
https://github.com/open-telemetry/opentelemetry-operator/actions/runs/1563783393/attempts/2

Following the OpenTelemetry Collector Contrib practices, the test will be disabled soon if it's not made stable.

**Comment by jpkrohling** [comment]
And again: https://github.com/open-telemetry/opentelemetry-operator/runs/4484937054?check_suite_focus=true

**Comment by jpkrohling** [comment]
@pavolloffay, are you able to make this more stable?

**Comment by pavolloffay** [comment]
I can try to increase the timeout

**Comment by jpkrohling** [comment]
Another one: https://github.com/open-telemetry/opentelemetry-operator/runs/4485792715?check_suite_focus=true
