### ISSUE TITLE
Allow set imagePullSecrets

### ISSUE THREAD

**Issue by templarfelix** [open-telemetry/opentelemetry-operator#656]
Today don't have method for set imagePullSecrets.

**Comment by jpkrohling** [comment]
We have support for service accounts, which allows setting image pull secrets. Can't you use that instead?

**Comment by newhero911** [comment]
Hi @jpkrohling ,

I got an error when used service account:
`
error: error validating "otel/instrumentation.yaml": error validating data: ValidationError(Instrumentation.spec): unknown field "serviceAccountName" in io.opentelemetry.v1alpha1.Instrumentation.spec; if you choose to ignore these errors, turn validation off with --validate=false
`

could you take a look ?

**Comment by pavolloffay** [comment]
The instrumentation CR does not have `serviceAccountName` field. 

Note that the auto-instrumentation images are used as init-containers in the application pod. I don't think the operator can change the service account. The `imagePullSecrets` is a list maybe it could add an entry there. 


@templarfelix could you please explain your use-case why do you need to set `imagePullSecrets` in the instrumentation CR?

**Comment by templarfelix** [comment]
Sorry for late comment, service account solve my problems
