### ISSUE TITLE
opentelemetry-operator.yaml not published in 0.42

### ISSUE THREAD

**Issue by langsamu** [open-telemetry/opentelemetry-operator#666]
I think due to [this failed run](https://github.com/open-telemetry/opentelemetry-operator/runs/4805213417?check_suite_focus=true).

This is `404`:
https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.42.0/opentelemetry-operator.yaml

**Comment by pavolloffay** [comment]
now it is available https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.42.0
