### ISSUE TITLE
Change structure of our changelog to align with OTELcol core/contrib

### ISSUE THREAD

**Issue by yuriolisa** [open-telemetry/opentelemetry-operator#701]
Should we use the same changelog scheme of OTEL Core / Contrib?

**Comment by pavolloffay** [comment]
We should as well add links to core and contrib changelogs.

**Comment by pavolloffay** [comment]
@yuriolisa is there any action item on this issue? Could we close this? 

From my side I am happy that we are adding link to the core/contrib changelogs in our changelog. That is enough.

**Comment by jpkrohling** [comment]
While I appreciate the links to the changelogs for the operands, I think this is about the changelog for the operator, following what's common practice for contrib/core, where each PR should include a changelog entry. This way, the changelog is ready by the time the release is made.

**Comment by pavolloffay** [comment]
I am fine with aligning the structure.
