### ISSUE TITLE
Promote @pavolloffay to maintainer of the operator

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#705]
@pavolloffay has been very active in the operator repository and demonstrated a sense of ownership, attention to detail, and care for the overall code quality of the project. Given Pavol has also submitted precious code contributions, I would like to nominate him as maintainer of this repository.

Here's a complete list of PRs Pavol submitted: https://github.com/open-telemetry/opentelemetry-operator/pulls?q=is%3Apr+author%3Apavolloffay

Of special mention, Pavol is the original author of the auto-instrumentation support for the operator: https://github.com/open-telemetry/opentelemetry-operator/pull/464

@open-telemetry/operator-maintainers and @open-telemetry/collector-maintainers: please share your 👍🏽  and 👎🏽.
Community members: please show your support 🚀 to Pavol's nomination.

**Comment by VineethReddy02** [comment]
+100 for @pavolloffay 🚀

**Comment by codeboten** [comment]
+100

**Comment by jpkrohling** [comment]
@bogdandrutu, @tigrannajaryan, looks like I don't have the rights to add @pavolloffay to the @open-telemetry/operator-maintainers group. Would you please do the honors?

**Comment by tigrannajaryan** [comment]
> @bogdandrutu, @tigrannajaryan, looks like I don't have the rights to add @pavolloffay to the @open-telemetry/operator-maintainers group. Would you please do the honors?

Done!

**Comment by jpkrohling** [comment]
Thank you!
