### ISSUE TITLE
inject env begining with prefix "OTEL_"

### ISSUE THREAD

**Issue by elvis-cai** [open-telemetry/opentelemetry-operator#706]
Hi

we are using otel operator to inject splunk otel java library, and from the doc https://docs.splunk.com/observability/gdi/get-data-in/application/java/instrumentation/instrument-java-application.html#deploy-the-java-agent-in-kubernetes, we also need inject env starting with prefix SPLUNK_, and from the code https://github.com/open-telemetry/opentelemetry-operator/blob/main/apis/v1alpha1/instrumentation_webhook.go#L134 it is hardcoded to OTEL,  just wondering is it possible we could inject env other than OTEL_ to make operator more generic? thanks.

**Comment by pavolloffay** [comment]
@elvis-cai would you like to submit a PR to fix this?

**Comment by elvis-cai** [comment]
sure.
