### ISSUE TITLE
Create a tools.go

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#71]
Create a tools.go with the imports for the tools we need to build the project, such as operator-sdk, kustomize, controller-gen, ...

**Comment by ibraimgm** [comment]
Can I try this one? Is there a specific list of tools somewhere or should I do it based on the `Makefile` contents?

**Comment by jpkrohling** [comment]
It's yours! I did give it a try yesterday but went into a dependency hell. If you can crack this one, a PR would be welcome! If you think it's not worth pursuing it, it's fine to just get all the tools to be installed via make targets, like `kustomize` right now.

The main idea behind this task is to install the tools we need before running the tasks that use them.

It's based on the Makefile, but here's a list of things that I can think of: `kustomize`, `kubebuilder`, `operator-sdk`, `ginkgo`, `controller-gen`. There might be others, though.

**Comment by ibraimgm** [comment]
Ok, I did manage to make `ginkgo` and `controller-gen` work on `tools.go`... but nothing else, really. 

`kustomize`, AFAIK is currently **impossible** to add to `tools.go` simply beacause I cannot import  a `main`  package and all other packages of this command are `internal`.

I was unable to build `operator-sdk`. Tried with version `0.19.0` and had a lot of trouble with dependencies. We might have more luck with a newer version.

How about doing something like that to the makefile:

```makefile
tools: ginkgo controller-gen kustomize (... and others)

ginkgo:
# do the shell instalation (kustomize) or a simple go install (gingko, controller-gen)
# also, add the missing ones (e. g. operator-sdk)
```

This way, the user has an option to "just install everything in one go".

Anyway, take a look at #79 to see the changes so far. If you think it is worth it, I can try to add `operator-sdk` installation to makefile (the same way is done with `kustomize`) and add the `tools` target.

BTW, please consider adding the "hacktoberfest" topic to the repository, if you can.

**Comment by jpkrohling** [comment]
I think I'd prefer the `tools` target instead of #79. I can see now why there are no `tools.go` in the scaffolding created by `kubebuilder` :-) My biggest concern is that we'll eventually get inconsistent versions between the `Makefile` and `go.mod`.

> BTW, please consider adding the "hacktoberfest" topic to the repository, if you can.

Any specific reason? We don't have any topics (and we probably should), and this isn't required by Hacktoberfest rules. I typically add labels to issues instead (and just did to this one). Is that enough?

**Comment by ibraimgm** [comment]
Take a look at #91. I added the missing installation for `operator-sdk` (sadly, a simple `go get` is not enought) and the `tools` target, which simply lists the required tools.

About the hacktoberfest thing, [they changed the rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update) to reduce spam. Now you need to either put `hacktoberfest` as a topic on the repo or add the `hacktoberfest-accepted` label on the PR.

**Comment by jpkrohling** [comment]
I just added the label to the PR. Thanks for the info!

**Comment by jpkrohling** [comment]
Closing, as the tools.go isn't the way to go for this.
