### ISSUE TITLE
Metrics Args name convention

### ISSUE THREAD

**Issue by yuriolisa** [open-telemetry/opentelemetry-operator#711]
On the v.0.43.0 we change the `metrics-addr` and `metrics-level` to Spec.Config. However, we're still using the both args into controller manager Deployment: 

https://github.com/open-telemetry/opentelemetry-operator/blob/704ff26e02ffb4874de553ab195f47c90f0fa30c/config/default/manager_auth_proxy_patch.yaml#L32

https://github.com/open-telemetry/opentelemetry-operator/blob/704ff26e02ffb4874de553ab195f47c90f0fa30c/main.go#L82

Then, I'd like to ask if should we keep the same Args name or should we change trying to achieve a kind of name convention?

**Comment by pavolloffay** [comment]
@yuriolisa is there any action item in this ticket? If no could it be closed?
