### ISSUE TITLE
Allow spec fields override in operator configuration

### ISSUE THREAD

**Issue by etiennejournet** [open-telemetry/opentelemetry-operator#718]
Hello Team !

What do you think of making it possible to override fields provided to the `OpentelemetryCollectorConfig` when configuring the operator ?

Example: 
You want to force users to use a specific opentelemetry image. This would be configurable using a variable in the operator, provided by Helm for example.

Thanks :)

**Comment by pavolloffay** [comment]
> You want to force users to use a specific opentelemetry image. This would be configurable using a variable in the operator, provided by Helm for example.

This is already doable by flag https://github.com/open-telemetry/opentelemetry-operator/blob/main/main.go#L87



Could you please be more specific and define exactly what fields you want to configure and what is the use case?

**Comment by etiennejournet** [comment]
Hello,

Thanks for getting back to me, this is exactly what I'm looking for but for
some reason I was unable to find this in the chart config so considered it
wasn't possible.

Regards


Le lun. 21 févr. 2022 à 09:49, Pavol Loffay ***@***.***> a
écrit :

**Comment by pavolloffay** [comment]
>  I was unable to find this in the chart config so considered it
wasn't possible.

Please reach out to the helm chart community to add this. 


@etiennejournet I am closing the issue as there does not seem to be any action item. Feel free to reopen if you think otherwise.
