### ISSUE TITLE
Add support to specify custom propagator in the instrumentation CRD

### ISSUE THREAD

**Issue by bharathiram** [open-telemetry/opentelemetry-operator#721]
We are using Opentelemetry Operator in a combination with Istio Tracing + Zipkin (using B3 Headers)

B3 header propagation works fine. Istio relies on Envoy to support distributed tracing. In addition to `B3 headers`, Envoy expects the `x-request-id` header to be propagated between services. 
[Envoy Tracing Info](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#tracing)

Currently, there is no official propagator which propagates `x-request-id`. We created a `customXRequestIdPropagator` to resolve the issue as part of our instrumentation. It would be really useful to have an option to provide a `customPropagator` as part of the instrumentation CRD

**Comment by jpkrohling** [comment]
cc @pavolloffay , @anuraaga

**Comment by pavolloffay** [comment]
The custom propagator can be specified in `OTEL_PROPAGATORS` as an environment variable - see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration. In the CR it can be specified via `spec.env` https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#instrumentationspec 


If `customXRequestIdPropagator` is not included in official SDK/instrumentation you will have to build your work auto-instrumentation image (https://github.com/open-telemetry/opentelemetry-operator/tree/main/autoinstrumentation) that includes the custom propagator implementation.

**Comment by dacox** [comment]
@bharathiram do you have any resources for creating a custom propagator?

**Comment by Hronom** [comment]
Istio is popular, please create propagator for it and include in OTEL

Here is the doc for all headers: https://istio.io/latest/about/faq/distributed-tracing/#how-to-support-tracing
