### ISSUE TITLE
Nominate @anuraaga to approver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-operator#727]
I would like to nominate @anuraaga to the https://github.com/orgs/open-telemetry/teams/operator-approvers group.

Anuraag has reviewed about [17 PRs](https://github.com/open-telemetry/opentelemetry-operator/pulls?q=is%3Apr+reviewed-by%3Aanuraaga) and is the author of more than [10 PRs](https://github.com/open-telemetry/opentelemetry-operator/pulls?q=is%3Apr+author%3Aanuraaga+), including the one introducing the auto-instrumentation for non-Java workloads.

I invite all the current @open-telemetry/operator-approvers and @open-telemetry/operator-maintainers to vote. Community members are also encouraged to provide their feedback.

Operator maintainers: please share your 👍🏽  and 👎🏽.
Community members: please show your support 🚀 to Anuraag's nomination.

**Comment by jpkrohling** [comment]
@open-telemetry/technical-committee, would one of you please do the honors in adding @anuraaga to @open-telemetry/operator-approvers?

**Comment by tigrannajaryan** [comment]
> @open-telemetry/technical-committee, would one of you please do the honors in adding @anuraaga to @open-telemetry/operator-approvers?

Done.

**Comment by jpkrohling** [comment]
@anuraaga, could you add yourself to the readme?

**Comment by bogdandrutu** [comment]
@jpkrohling usually the maintainers do that :)

**Comment by bogdandrutu** [comment]
Also you are a maintainer of the team now, so you can change things :)
