### ISSUE TITLE
Collector replicas count and HorizontalPodAutoscaler 

### ISSUE THREAD

**Issue by binjip978** [open-telemetry/opentelemetry-operator#729]
Hi, I want to use opentelemetry collector with Horizontal Pod Autoscaler, with help of OpenTelemetry Operator but OpenTelemetryCollectorSpec can have only fixed number of replicas allowed. And obviously both controllers does not work well together.

```bash
kubectl apply -f basic-otel-config.yaml
kubectl autoscale deployment simplest-collector --min=2 --max=3
```

and both opentelemetry collector and HPA controller will update the deployment:
```
simplest-collector-5db4bf447-dsjqx   0/1     Pending   0          0s
simplest-collector-5db4bf447-dsjqx   0/1     Pending   0          0s
simplest-collector-5db4bf447-dsjqx   0/1     ContainerCreating   0          0s
simplest-collector-5db4bf447-dsjqx   1/1     Running             0          1s
simplest-collector-5db4bf447-ds9mk   0/1     Pending             0          0s
simplest-collector-5db4bf447-ds9mk   0/1     Pending             0          0s
simplest-collector-5db4bf447-ds9mk   0/1     ContainerCreating   0          0s
simplest-collector-5db4bf447-ds9mk   0/1     Terminating         0          0s
simplest-collector-5db4bf447-ds9mk   1/1     Terminating         0          1s
simplest-collector-5db4bf447-ds9mk   0/1     Terminating         0          2s
simplest-collector-5db4bf447-ds9mk   0/1     Terminating         0          2s
simplest-collector-5db4bf447-ds9mk   0/1     Terminating         0          2s
simplest-collector-5db4bf447-hv9dg   0/1     Pending             0          0s
simplest-collector-5db4bf447-hv9dg   0/1     Pending             0          0s
simplest-collector-5db4bf447-hv9dg   0/1     ContainerCreating   0          0s
simplest-collector-5db4bf447-hv9dg   0/1     Terminating         0          0s
simplest-collector-5db4bf447-hv9dg   1/1     Terminating         0          1s
```

So currently my option are:
- don't use HPA at all and over-provision collectors with higher replica count.
- write my own HPA that will change replica count in OpenTelemetryCollector, which is probably to complicated.

May be im missing a better way off doing this, but right now I only see the way of achieving this by adding additional parameter (like replicasManagedByHPA or something like this) to the OpenTelemetryCollector spec, that reconcile loop will not trigger deployment update if the replicas has been changed and replicasManagedByHPA is true.

**Comment by pavolloffay** [comment]
There might be several ways how to solve this:

For instance jaeger operator creates HPA on behalf of the user https://github.com/jaegertracing/jaeger-operator/pull/856. 

he other approach might be something like described here https://github.com/operator-framework/operator-sdk/issues/5181: otel-operator would recognize that HPA is used and will not revert to the replicas defined in the CR.

**Comment by binjip978** [comment]
Jaeger approach looks good to me, will try to come with a PR.

**Comment by pavolloffay** [comment]
cc) @kearls
