### ISSUE TITLE
Add support for dotnet C# auto-instrumentation

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#756]
It seems that the dotnet instrumentation can be easily enabled by env. variables https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation#instrument-a-net-application-on-linux. 

Please upvote this issue 👍🏼 if you would like to see support for dotnet.

**Comment by anuraaga** [comment]
I guess we should wait for at least one published release :P https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases
