### ISSUE TITLE
Support k8s 1.19 and higher

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#757]
Currently from our readme: 

> Our promise is that we'll follow what's common practice in the Kubernetes world and support N-2 versions, based on the release date of the OpenTelemetry Operator.

https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager

I propose to change the policy and support k8s 1.19 and higher. There is no technical reason why the operator could not run on k8s 1.19 (it doesn't even import any betav1 APIs) and also our team at Red Hat is committed to provide resources for this.

There are a couple of ways we could make sure 1.19 is supported:
1. test on all k8s versions >= 1.19
2. test on N-2 k8s versions and 1.19 including
3. test on the latest k8s version (right now 1.23) and 1.19

I propose to take the 3 option.

* Amazon EKS still supports 1.19: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
* OpenShift 4.6 (based on 1.19): https://access.redhat.com/support/policy/updates/openshift
* Rancher supports 1.19: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-3/
* Tanzu seems to supports 1.19 : https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-D4AAD99E-9128-40CE-B89C-AD451DA8379D.html (the link might be wrong)

**Comment by jpkrohling** [comment]
Does it mean we'll start supporting N-4, or do we support N-2 plus 1.19? What should be the trigger to stop supporting 1.19?

**Comment by jpkrohling** [comment]
> We stop supporting 1.19 once it becomes a technical problem to support it, or there won't be able to fund supporting it.

I'd rather have a clear and predictable rule that we can announce and is easy to remember and reason about (Kubernetes follows the same N-2 pattern), and surprise our users by having the operator work just fine on older versions, than claiming support for a version, only to revoke it after we find a bug that would involve too much work to fix. We actually had this problem before, and it results in frustrated users.

If commercial offerings want to extend their support to older versions, that's fine. But I vote for keeping N-2 for the upstream project.

**Comment by pavolloffay** [comment]
> I'd rather have a clear and predictable rule that we can announce and is easy to remember and reason about (Kubernetes follows the same N-2 pattern), and surprise our users by having the operator work just fine on older versions, than claiming support for a version, only to revoke it after we find a bug that would involve too much work to fix. We actually had this problem before, and it results in frustrated users.

The proposal here is predictable as well, the supported k8s version will be documented in the readme during the release the same way like it is right now. The support for a particular k8s version won't be revoked after the operator is released.

**Comment by jpkrohling** [comment]
> The proposal here is predictable as well, the supported k8s version will be documented in the readme during the release the same way like it is right now

It's clear and documented, but not predictable: we cannot tell whether we are going to support 1.19 by the time we support 1.32. The N-2 rule is simple enough. It also creates the expectation that users should run on relatively recent Kubernetes.

**Comment by Aneurysm9** [comment]
The span of versions that any given operator release supports would be fixed at the time of release.  That gets to the predictability that @pavolloffay was talking about.  While it's true that we don't know at this point the widest that span of versions will be for any given future release, we should have reasonable ability to predict the release in which it will change when it becomes apparent that a change is necessary.  We can announce, for example, that in the next release we will increase the MSV to 1.X as a result of PR #Y when we know that PR #Y will require increasing the MSV.  Depending on what triggers that increase we may even be able to announce it a couple releases ahead of time.

While it is a good ideal to expect that users are running on relatively recent versions of Kubernetes, practice shows that this is not always the case and end-user upgrade timelines can be difficult to predict.  Even managed service providers are unlikely to support only N-2.  EKS, for instance, [supports N-5 through N-2](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) with N-5 ending support and N-1 coming into support this month.

**Comment by anuraaga** [comment]
+1 to Pavol's proposal - especially with auto instrumentation the operator is very useful in adding OTel based observability to a running system which could be running on an older version of k8s. Older systems tend to benefit more from a managed approach like an operator than newer ones even where there is less resistance to updating deployment scripts.

> We stop supporting 1.19 once it becomes a technical problem to support it

Notably this, as long as there is no real maintenance issue with running tests against 1.19 it seems safe to say it's supported, following the strategy of bumping the supported versions in a release as it becomes necessary as described.

**Comment by pavolloffay** [comment]
It seems there is a consensus between major contributors (except @jpkrohling) to go forward with this proposal (@VineethReddy02 approved the #734, please comment if you think otherwise).

How should we move forward if @jpkrohling is against it?

**Comment by jpkrohling** [comment]
> How should we move forward if @jpkrohling is against it?

Your proposal is accepted ;-) Thank you all for sharing your perspectives. I'm still of the opinion that we have limited resources here at upstream and that testing that wide range of versions will become a burden, but given that all other maintainers (and @Aneurysm9) are in favor of this proposal, I'm not going to stay in the way of it.

**Comment by pavolloffay** [comment]
Done in #734
