### ISSUE TITLE
Add support for configuring the initalDelaySeconds for liveness probe of the collector container

### ISSUE THREAD

**Issue by avadhut123pisal** [open-telemetry/opentelemetry-operator#760]
As per the current implementation, the liveness probe for the collector container is derived from the health check extension.

From health check extension value of the endpoint is used for configuring the liveness probe but there should be some way to specify the other attributes related to the liveness probe like initalDelaySeconds, periodSeconds, etc. 

It will help in the case when some operations are to be done before starting the collector process.

**Comment by pavolloffay** [comment]
Out of curiosity, for what use-case is this feature needed?

**Comment by avadhut123pisal** [comment]
Actually, in our case, we use some script as an entry point for the container, which after performing some operations starts the collector. So, when the health-check extension is configured, the operator uses it as a liveness probe which fails because even if the container is running but the collector is not stated yet.

**Comment by pavolloffay** [comment]
Thanks for sharing.

@avadhut123pisal would you like to take this one and propose a solution and submit a PR?

**Comment by avadhut123pisal** [comment]
> Thanks for sharing.
> 
> @avadhut123pisal would you like to take this one and propose a solution and submit a PR?

Yeah sure.

**Comment by avadhut123pisal** [comment]
The health-check extension is the optional component for the collector. If the health-check extension is not configured then there is no port or endpoint in the collector that can be used for configuring the liveness or readiness probe. In that case, the health-check extension will be like a mandatory component, if probes are needed to configure. 
@pavolloffay I would like to know your views on this.

**Comment by avadhut123pisal** [comment]
@pavolloffay we use the HC in collector config. 

Proposed solution:
1. We can accept the input of the Liveness & Readiness Probes as a part of the Collector Specs.
2. If the Liveness probe is not specified explicitly by the user, then it will be derived from the Health check config (existing implementation) otherwise the one which is provided by the user will be used. 
3. Same can be done for the readiness probe too.

**Comment by pureklkl** [comment]
@pavolloffay 
https://github.com/open-telemetry/opentelemetry-operator/blob/c7c4b5f97b346a57a1a6b07d30de40ba26a9c19c/pkg/collector/adapters/config_to_probe.go#L101

The HC does not configure the initial delay and interval of the probe. I have similar issue.

**Comment by pureklkl** [comment]
@pavolloffay 
@avadhut123pisal 
Just noticed this issue has been almost one year, is it still active? I need this feature for configuring the liveness delay for a customize image. 

I could make a pr for it if adding Liveness/Readiness probe to spec is acceptable.
