### ISSUE TITLE
Docker image 0.46.0 was not published

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#766]
https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fopentelemetry-operator

**Comment by pavolloffay** [comment]
https://github.com/open-telemetry/opentelemetry-operator/actions/runs/1962882696

**Comment by marciosoftfocus** [comment]
Thanks to report the issue, when I tried to install on my cluster the error below happened


`Warning  Failed       30m (x2 over 30m)   kubelet            Failed to pull image "ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.46.0": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.46.0": failed to resolve reference "ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.46.0": ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.46.0: not found`

**Comment by jpkrohling** [comment]
Didn't this happen as well for the previous version? Is the workflow not being triggered automatically?

**Comment by pavolloffay** [comment]
The workflow was triggered but the tagging is seems to be broken.

**Comment by pavolloffay** [comment]
The root cause seems to be that the operator image workflow was not triggered https://github.com/open-telemetry/opentelemetry-operator/blob/main/.github/workflows/publish-images.yaml#L7.
