### ISSUE TITLE
[controller-runtime] no kind is registered for the type v1alpha1.InstrumentationList

### ISSUE THREAD

**Issue by mat-rumian** [open-telemetry/opentelemetry-operator#772]
For [k8s-sigs.e2e-framework](https://github.com/kubernetes-sigs/e2e-framework) [ApiMachinery is not able to set type](https://github.com/kubernetes/apimachinery/blob/v0.23.4/pkg/runtime/scheme.go#L265) for probably all the OT-Operator K8s Objects.

Function used to list resources - https://github.com/kubernetes-sigs/e2e-framework/blob/v0.0.6/klient/k8s/resources/resources.go#L126-L141

Environment:
- sigs.k8s.io/e2e-framework v0.0.6
- k8s.io/api v0.23.4
- k8s.io/apimachinery v0.23.4
- github.com/open-telemetry/opentelemetry-operator v0.46.0

Error:
```
no kind is registered for the type v1alpha1.InstrumentationList in scheme "pkg/runtime/scheme.go:100"
```

**Comment by pavolloffay** [comment]
@mat-rumian where is this error coming from? 


The OTEL kinds are not part for the core k8s and need to be explicitly added: 
https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/collector/reconcile/suite_test.go#L83. Does this solve your issue?

**Comment by pmalek-sumo** [comment]
@pavolloffay it's coming from: https://github.com/kubernetes/apimachinery/blob/v0.23.4/pkg/runtime/scheme.go#L265 when trying to list `Instrumentation` (or rather `InstrumentationList`)

**Comment by pmalek-sumo** [comment]
BTW: can you help us understand then why is this working with `kubectl` but isn't working with apimachinery's runtime?

**Comment by pavolloffay** [comment]
> BTW: can you help us understand then why is this working with kubectl but isn't working with apimachinery's runtime?

The kubectl is working because OTEL CRDs are installed and kubectl gets them from the cluster.

The API machinery test suite does not install CRD/types automatically from the cluster (it actually bootstraps a clean cluster).

**Comment by pmalek-sumo** [comment]
Thanks @pavolloffay! Do you know how/through which mechanism does `kubectl` get those CRDs? Is this a standard or it "just" does it?
