### ISSUE TITLE
Collector CRD should support specifying a nodeSelector

### ISSUE THREAD

**Issue by jutley** [open-telemetry/opentelemetry-operator#779]
In environments where users want certain workloads to run on specific node pools, we can taint nodes and define our pods with nodeSelectors and tolerations. Currently the Collector CRD allows us to specify tolerations for a non-sidecar Collector, but not a nodeSelector. This means that we _may_ end up running our collector on the intended node pool, but it isn't guaranteed.

Adding support for this configuration would be a nice improvement.

**Comment by pavolloffay** [comment]
No objections, @jutley would you like to submit a PR to fix it?

**Comment by jutley** [comment]
Gave it a shot in #789. Seems straightforward enough, though I'm not sure if there are any subtleties I may have missed.
