### ISSUE TITLE
Create serving certs for headless services on OpenShift

### ISSUE THREAD

**Issue by rkukura** [open-telemetry/opentelemetry-operator#818]
When running on OpenShift, the opentelemetry-operator should include a `service.beta.openshift.io/serving-cert-secret-name` annotation in the headless services it creates for the collector. This will cause a certificate to be generated for the service and stored in a secret that can be mounted and used in the associated receiver TLS configuration. 

Without this feature in the operator, it is necessary to either manage serving certificates manually, or add the annotation manually after deploying the collector. Until the annotation is added, the collector cannot start successfully because the secret being mounted as a volume does not yet exist.

**Comment by rkukura** [comment]
@pavolloffay - Can you assign this to me? I expect to begin working on a PR today.

**Comment by pavolloffay** [comment]
It's yours, no need to assign a comment is enough.
