### ISSUE TITLE
Respect upstream Kubernetes (k8s) EOL policy

### ISSUE THREAD

**Issue by yuriolisa** [open-telemetry/opentelemetry-operator#820]
Although we've been supporting the K8S v1.19 and higher since the #734, I would like to suggest obeying the EOL of Kubernetes versions, which we can see in the link below: 

https://endoflife.date/kubernetes

If the idea is feasible, we should support 1.21.11 and higher.

**Comment by frzifus** [comment]
As far as I know we are holding it because of Openshift 4.6 which is still [supported until the end of october this year](https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_versions#openshift_release_history).

**Comment by pavolloffay** [comment]
The support for 1.19 was added specifically for vendors (Red Hat, AWS) that support older Kubernetes distributions regardless of the upstream k8s EOL policy - https://github.com/open-telemetry/opentelemetry-operator/issues/757. This ticket essentially reverts that agreement.

If there is no technical reasoning why a specific k8s version cannot be supported and there are resources to support old k8s versions then I am `-1` on this ticket.

**Comment by yuriolisa** [comment]
I see, however, that when I opened this ticket regarding the EOL, I thought that if we already have version compatibility tests on the Community Operators repo through different Openshift versions we could leave the tests on in supported k8s versions.
But on the other hand, I understand the requirement to support specific vendors' versions, then I'll close this issue.
