### ISSUE TITLE
DaemonSet deloyment with private container registry unstable (imagePullSecrets not configurable)

### ISSUE THREAD

**Issue by marcules** [open-telemetry/opentelemetry-operator#846]
Hi,

when I configure the `OpenTelemetryCollector` to run as daemonset only nodes, that already contain images from our private image registry come up - as the nodes where such images are not present can't access the configured otel-collector image.

This is not an issue in sidecar mode, as the configured deployments already contain an `imagePullSecrets` configuration, which the sidecar can use. The issue exists in daemonset, statefulset and deployment (simplest) mode when using a private registry.

<img width="1209" alt="SNAG-0081" src="https://user-images.githubusercontent.com/2453108/165949356-60e4d753-a826-43f1-bb4a-5eaa1fb4e85f.png">

<img width="1209" alt="SNAG-0082" src="https://user-images.githubusercontent.com/2453108/165949552-4f75fa3c-e2ff-4086-ac86-e289fee16665.png">

<img width="1209" alt="SNAG-0083" src="https://user-images.githubusercontent.com/2453108/165949655-235b8257-317f-4b2d-bcfb-303032f9a92e.png">

Can you add a configuration for `spec.containers.[*].imagePullPolicy` and `spec.imagePullSecrets` to the deployment, daemonset ad statefulset CRD? That would enable us to have a reliable way of deploying the otel-collector with our own images.

LG Marc

**Comment by pavolloffay** [comment]
I don't have objections to add `imagePullSecret` to the collector CR. 

@marcules are you interested in submitting a PR?

**Comment by jkroepke** [comment]
As I know, you can also [attach imagePullSecrets to service accounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) as alternative to define them on the Deamonset

**Comment by m1o1** [comment]
I think this would apply to the Deployment (as opposed to DaemonSet) as well. Just tried using a custom collector and couldn't figure out how to add `imagePullSecrets`. Going to try adding to the service account, but afaik that service account is managed by the controller so changes could be overwritten.

**Comment by m1o1** [comment]
I [opened a PR](https://github.com/open-telemetry/opentelemetry-operator/pull/954). I need to make sure I follow the contributing guidelines and clean it up, but if it looks like I'm on the right track, I'll fix it up.

**Comment by protopapa** [comment]
Hello, I would like to work on this.

**Comment by yuriolisa** [comment]
As mentioned by @pavolloffay, The CR has a config option to set a service account that can set the image pull secret.
