### ISSUE TITLE
Update Community OpenTelemetry Operator on OperatorHub to v0.51.0

### ISSUE THREAD

**Issue by jasaltvik** [open-telemetry/opentelemetry-operator#883]
Hi,

Sorry if this is already in the works, but it would be great if it was possible to update https://operatorhub.io/operator/opentelemetry-operator with the latest v0.51.0 release (I saw that v0.50.0 is also missing).

Really looking forward to using https://github.com/open-telemetry/opentelemetry-operator/pull/689 :100:

**Comment by pavolloffay** [comment]
@yuriolisa are you working on this?

**Comment by yuriolisa** [comment]
Hi @pavolloffay, I'll submit it tomorrow morning. Could you please assign it for me?

**Comment by yuriolisa** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1226

**Comment by yuriolisa** [comment]
https://github.com/k8s-operatorhub/community-operators/pull/1251
