### ISSUE TITLE
Improve release process by automatically submititng manifests to prod and community operators repositories

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-operator#885]
After a new operator version is released somebody has to submit two PRs with CSV and other manifest files to community and prod operators repositories. This is an easy-to-automate task and we should automate it through our release GHA.

 https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1226 and https://github.com/k8s-operatorhub/community-operators/pull/1251.
 

cc) @yuriolisa

**Comment by jaronoff97** [comment]
This is done automatically now! :D
