### ISSUE TITLE
support cross-namespace instrumentation references in annotations

### ISSUE THREAD

**Issue by tKe** [open-telemetry/opentelemetry-operator#886]
**Is your feature request related to a problem? Please describe.**
Currently, it is required to define an `Instrumentation` object in every namespace in which you wish to use the operator to auto-instrument pods. These many `Instrumentation`s may represent duplicate configurations.

**Describe the solution you'd like**
Being able to define an `Instrumentation` in one namespace and reference it in the annotations of pods in other namespaces would allow for better centralisation of `Instrumentation` configuration when required.

I.e.
```yaml
instrumentation.opentelemetry.io/inject-java: "tracing-components/my-instrumentation"
```

**Describe alternatives you've considered**
Alternatives to this would be using a helm chart or similar to approach to replicate a single configuration across multiple namespaces, or using another operator to replicate `Instrumentation` resources in a similar way to the many secret/configmap synchronisation solutions.

**Comment by ringerc** [comment]
It might make sense to do this how Istio does it for its policies.
