### ISSUE TITLE
How do you configure opentelemetry collectors to use a storageclass for pvcs it creates

### ISSUE THREAD

**Issue by jacobwalters** [open-telemetry/opentelemetry-operator#897]
I am creating an opentelemetry collector to scrape prometheus metrics in statefulset mode. I am seeing that the operator creates a pvc that the collector pod is going to use. It is creating the pvc with the storageclass "gp2". In our environment we have a custom storageclass. How do I configure the operator or collector to create the pvcs using a different storageclass than gp2.

**Comment by yuriolisa** [comment]
@jacobwalters , did you try using this:
**https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspecvolumeclaimtemplatesindexspec** ?

**Comment by VineethReddy02** [comment]
@jacobwalters Is this still an open question? Can you close the issue, if your question is answered? 
Thanks

**Comment by yuriolisa** [comment]
@jaronoff97, I believe we could close this issue, right?
