### ISSUE TITLE
Why is cert-manager required?

### ISSUE THREAD

**Issue by CatalinAdlerDF** [open-telemetry/opentelemetry-operator#937]
Hi,

Why is cert-manager even required?
Can it be made optional?

Thanks!

**Comment by pavolloffay** [comment]
It's not optional. It's required to secure connections to the webhooks.

**Comment by jpkrohling** [comment]
cert-manager it self is optional, provided that the TLS certs are made available in the right places. One example of that is when installing the operator via Operator Hub (OLM), which provisions the certs in the expected locations, compatible with cert-manager. You don't need cert-manager when running the operator in OpenShift (unless this has recently changed).

**Comment by jpkrohling** [comment]
Again, you don't need to: just provision the appropriate TLS certs in the right places.

**Comment by umarkhan17** [comment]
How to do this, I am trying to deploy opentelemetry operator without cert-manager(i cannot install cert-manager), please advice. how to achieve this without certmanager?

**Comment by umarkhan17** [comment]
I am getting this error, when i try to deploy collector:
Error from server (InternalError): error when creating "collector.yaml": Internal error occurred: failed calling webhook "mopentelemetrycollector.kb.io": Post "https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/mutate-opentelemetry-io-v1alpha1-opentelemetrycollector?timeout=10s": **x509: certificate signed by unknown authority**
