### ISSUE TITLE
Create a test for horizontal pod autoscaling

### ISSUE THREAD

**Issue by kevinearls** [open-telemetry/opentelemetry-operator#942]
Write a test for the changes for #801   This will most likely require changes to the default HPA settings so that it does not take a 5-10 minutes to downscale.  

See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ for reference.

**Comment by pavolloffay** [comment]
Do you mean e2e test?

**Comment by kevinearls** [comment]
@pavolloffay Yes

**Comment by yuriolisa** [comment]
@pavolloffay, I believe this issue can be closed.
