### ISSUE TITLE
Update HorizontalPodAutoscaler code from v1

### ISSUE THREAD

**Issue by kevinearls** [open-telemetry/opentelemetry-operator#943]
The current HPA code uses version v1 of the API.  We should upgrade to v2 or v2beta2 depending on what is supported in the versions of kubernetes that we need to support.

**Comment by pavolloffay** [comment]
What is the reasoning/use-case to migrate to v2beta2 or v2 on our end? Are we using any of the v2 features? 


from: https://kubernetes.io/docs/reference/using-api/deprecation-guide/

> Migrate manifests and API clients to use the autoscaling/v2 API version, available since v1.23.

We cannot use v2 right now because we are supporting k8s 1.19. 

> The autoscaling/v2beta1 API version of HorizontalPodAutoscaler will no longer be served in v1.25.


`v2beta2` could be intentionally used https://stackoverflow.com/a/62455298

**Comment by kevinearls** [comment]
The reason is to be able to add more features which will, among other things, permit us to change the scaledown time in order to run an e2e test (See #942) which does not run for an inordinate amount of time.

v1 is fairly old.  I was not able to find a release date, but I found references to v2beta2 from 2019.  Jaeger Operator uses it, and the code that added that was written in January 2020.  (See https://github.com/jaegertracing/jaeger-operator/pull/856)

**Comment by pavolloffay** [comment]
`v2beta2` was added in k8s 1.12 based on the link I shared above.

> The autoscaling/v2beta2 API version of HorizontalPodAutoscaler will no longer be served in v1.26.

from https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26

We should migrate to `v2` however the `v2` is supported on k8s 1.23 and above and we must support k8s 1.19 for now (RH requirement). Therefore I would suggest to choose the right autoscaler version at runtime:
* v2beta2 in 1.19-1.22
* v2 1.23 and above
