### ISSUE TITLE
[target-allocator] Target-level metadata labels is lost

### ISSUE THREAD

**Issue by CoderPoet** [open-telemetry/opentelemetry-operator#948]
When we use the target discovery of prometheus, we can only get the outermost metadata Labels, and lose the metadata Labels of the Targ-level

![Tc7tyfWAne](https://user-images.githubusercontent.com/19374680/175822404-c17aa358-67d8-4ee2-b5cb-ab30b340f5d7.jpg)

![nXVEwRXuwh](https://user-images.githubusercontent.com/19374680/175822411-15352183-b338-4599-bc03-d07025f5b9e6.jpg)

Expect to be able to get metadata to the Target-level Labels

![4xYSq4cbTF](https://user-images.githubusercontent.com/19374680/175822426-822ca742-7e23-4a6f-9657-d5f7297629e5.jpg)

**Comment by secustor** [comment]
This should be fixed with https://github.com/open-telemetry/opentelemetry-operator/pull/949
