### ISSUE TITLE
[target-allocator] The number of replicas of allocator is modified by the number of replicas of the allocator

### ISSUE THREAD

**Issue by CoderPoet** [open-telemetry/opentelemetry-operator#950]
When we set the `maxReplicas` parameter of the collector, the number of replicas of allocator is modified by the number of replicas of the allocator

It is expected to modify only the number of replicas of the collector

At present, when there are multiple replicas of the allocator, it will encounter target job allocation problems

**Comment by jaronoff97** [comment]
I believe this was closed by https://github.com/open-telemetry/opentelemetry-operator/pull/951 cc @pavolloffay

**Comment by pavolloffay** [comment]
Closing per @jaronoff97 comment
