### ISSUE TITLE
Update Instrumentation E2E Tests content

### ISSUE THREAD

**Issue by mat-rumian** [open-telemetry/opentelemetry-operator#956]
Currently Instrumentation e2e tests configuration content is random e.g. OTEL_EXPORTER_OTLP_ENDPOINT should always point to the default exporter port used in the supported instrumentation.

e.g. [instrumentatio-python](https://github.com/open-telemetry/opentelemetry-operator/blob/main/tests/e2e/instrumentation-python/00-install-instrumentation.yaml#L30) points to `OTLP gRPC` port but instrumentation is using [OTLP HTTP exporter](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/python/requirements.txt#L4) (4318)

**Comment by jaronoff97** [comment]
Closing this in favor of #552
