### ISSUE TITLE
[target-allocator] will assign the target to the old collector

### ISSUE THREAD

**Issue by CoderPoet** [open-telemetry/opentelemetry-operator#968]
When this log appears, there will be a problem of assigning the target to the old collector
`Collector pod watch event stopped no event`

![origin_img_v2_3914e607-960c-47c7-81fa-6ff8161c1b5g](https://user-images.githubusercontent.com/19374680/178220673-b5d5d917-2408-4b5a-916b-6a02494acc82.jpg)

**Comment by jaronoff97** [comment]
@CoderPoet i was unable to reproduce this just now, if you can repro this with the latest version please let me know and I will re-open this.
