### ISSUE TITLE
Integrate Cert-Manager installation

### ISSUE THREAD

**Issue by yuriolisa** [open-telemetry/opentelemetry-operator#988]
Would it be possible to integrate the `cert-manager` installation into the Otel Operator to avoid an extra-package installation as the first step?

**Comment by jpkrohling** [comment]
How integrated? I would vote against it, as it should be possible to specify dependencies in OLM if we ever have a hard dependency on cert-manager. At least until recently, we depended only on TLS certs to be placed in specific places, and this was fulfilled by both OpenShift and cert-manager. Has that recently changed?

**Comment by pavolloffay** [comment]
Operators should not install other operators, for that reason, there is OLM (and perhaps other package managers). 

Moving dependency management to the operator will expose another dimension of problems the operator would have to face.
