### ISSUE TITLE
Set environment variables without injection

### ISSUE THREAD

**Issue by bilbof** [open-telemetry/opentelemetry-operator#990]
Hey folks, it would be nice for the Instrumentation CRD to support adding OTEL environment variables to a Pod without injecting the init container / updating libraries and modifying env vars such as `NODE_OPTIONS`.

My use case is that I have many services written in Go, Rust, C++, etc. which aren't supported by the Instrumentation CRD but which I'd like to configure in the same way.

I could re-use the autoinstrumentation for another language like using an annotation `instrumentation.../language-python: "true"` on a Rust application PodSpec, but that feels a bit wrong, and I would expect this not to be supported.

Is there a way to set the generated OTEL environment variables on Pods which aren't using a supported language?

**Comment by pavolloffay** [comment]
This use-case has been discussed in the past, but I cannot find the ticket/PR. 

I think it makes sense to inject just the SDK config. It could be supported by:

```bash
instrumentation.opentelemetry.io/inject-sdk: "true"
```

It would inject only core SDK env vars like the exporter, sampler, propagation, resource attributes. https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/instrumentation/sdk.go#L100

**Comment by bilbof** [comment]
@pavolloffay I've added a PR for this at https://github.com/open-telemetry/opentelemetry-operator/pull/1000
