### ISSUE TITLE
Question: why is there v1.51.0 image in ghcr.io registry?

### ISSUE THREAD

**Issue by paulfantom** [open-telemetry/opentelemetry-operator#999]
We are using renovate to keep our dependencies up-to-date and recently we started pinning opentelemetry-operator image version and let renovate do its job. After doing so we got an automated PR from renovate which tries to update `ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator` image from version `v0.55.0` to `v1.51.0`. 

Executing `docker pull ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v1.51.0` locally proved that such image actually exists. 

My main question is if that image SHOULD exist in the first place considering there is no `v1.51.0` tag or release of the operator? And if it shouldn't exist could you delete it?

**Comment by pavolloffay** [comment]
That was an accidentally published image (pushed a wrong tag). We should probably remove it. 

@yurishkuro @bogdandrutu would it be possible to remove this version from the registry? I don't have access to do that.

**Comment by yurishkuro** [comment]
I don't know how to find it - github by default only shows 4-5 versions, and when you switch to All Versions view it shows them by uuids, not with labels.

**Comment by paulfantom** [comment]
I did some digging. Package tagged as `1.51.0` can be manipulated via GitHub API by using an id of `22436267`. As such it is possible to remove that package with the following command taken from [GitHub Docs](https://docs.github.com/en/rest/packages#delete-package-version-for-an-organization):
```
curl -XDELETE -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/orgs/open-telemetry/packages/container/opentelemetry-operator%2Fopentelemetry-operator/versions/22436267
```

You can double check me by retreiving the object with id `22436267` with the following command (also taken from [GitHub Docs](https://docs.github.com/en/rest/packages#get-a-package-version-for-an-organization)):
```
curl -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/orgs/open-telemetry/packages/container/opentelemetry-operator%2Fopentelemetry-operator/versions/22436267
```

Side note: the command has to run by a person with write access to the container registry and `GITHUB_TOKEN` must have `delete:packages` scope.

**Comment by pavolloffay** [comment]
@yurishkuro could you please remove the image?

**Comment by yurishkuro** [comment]
Deleted.
